// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Account enum constants
const (
	// AlternateContactType values
	AccountAlternateContactTypeBilling    = "BILLING"
	AccountAlternateContactTypeOperations = "OPERATIONS"
	AccountAlternateContactTypeSecurity   = "SECURITY"

	// AwsAccountState values
	AccountAwsAccountStatePendingActivation = "PENDING_ACTIVATION"
	AccountAwsAccountStateActive            = "ACTIVE"
	AccountAwsAccountStateSuspended         = "SUSPENDED"
	AccountAwsAccountStateClosed            = "CLOSED"

	// PrimaryEmailUpdateStatus values
	AccountPrimaryEmailUpdateStatusPending  = "PENDING"
	AccountPrimaryEmailUpdateStatusAccepted = "ACCEPTED"

	// RegionOptStatus values
	AccountRegionOptStatusEnabled          = "ENABLED"
	AccountRegionOptStatusEnabling         = "ENABLING"
	AccountRegionOptStatusDisabling        = "DISABLING"
	AccountRegionOptStatusDisabled         = "DISABLED"
	AccountRegionOptStatusEnabledByDefault = "ENABLED_BY_DEFAULT"

	// ValidationExceptionReason values
	AccountValidationExceptionReasonInvalidregionopttarget = "invalidRegionOptTarget"
	AccountValidationExceptionReasonFieldvalidationfailed  = "fieldValidationFailed"
)

var accountAlternateContactTypeValues = []string{
	"BILLING",
	"OPERATIONS",
	"SECURITY",
}

var accountAwsAccountStateValues = []string{
	"PENDING_ACTIVATION",
	"ACTIVE",
	"SUSPENDED",
	"CLOSED",
}

var accountPrimaryEmailUpdateStatusValues = []string{
	"PENDING",
	"ACCEPTED",
}

var accountRegionOptStatusValues = []string{
	"ENABLED",
	"ENABLING",
	"DISABLING",
	"DISABLED",
	"ENABLED_BY_DEFAULT",
}

var accountValidationExceptionReasonValues = []string{
	"invalidRegionOptTarget",
	"fieldValidationFailed",
}

func getAccountEnum(name string) []string {
	switch name {
	case "AlternateContactType":
		return accountAlternateContactTypeValues
	case "AwsAccountState":
		return accountAwsAccountStateValues
	case "PrimaryEmailUpdateStatus":
		return accountPrimaryEmailUpdateStatusValues
	case "RegionOptStatus":
		return accountRegionOptStatusValues
	case "ValidationExceptionReason":
		return accountValidationExceptionReasonValues
	}
	return nil
}

func getAccountEnumNames() []string {
	return []string{
		"AlternateContactType",
		"AwsAccountState",
		"PrimaryEmailUpdateStatus",
		"RegionOptStatus",
		"ValidationExceptionReason",
	}
}
