// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// BcmPricingCalculator enum constants
const (
	// BatchCreateBillScenarioCommitmentModificationErrorCode values
	BcmpricingcalculatorBatchCreateBillScenarioCommitmentModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchCreateBillScenarioCommitmentModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"
	BcmpricingcalculatorBatchCreateBillScenarioCommitmentModificationErrorCodeInvalidAccount      = "INVALID_ACCOUNT"

	// BatchCreateBillScenarioUsageModificationErrorCode values
	BcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeNotFound            = "NOT_FOUND"
	BcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BatchCreateWorkloadEstimateUsageCode values
	BcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeNotFound            = "NOT_FOUND"
	BcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BatchDeleteBillScenarioCommitmentModificationErrorCode values
	BcmpricingcalculatorBatchDeleteBillScenarioCommitmentModificationErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchDeleteBillScenarioCommitmentModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchDeleteBillScenarioCommitmentModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BatchDeleteBillScenarioUsageModificationErrorCode values
	BcmpricingcalculatorBatchDeleteBillScenarioUsageModificationErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchDeleteBillScenarioUsageModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchDeleteBillScenarioUsageModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BatchUpdateBillScenarioCommitmentModificationErrorCode values
	BcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeNotFound            = "NOT_FOUND"
	BcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BatchUpdateBillScenarioUsageModificationErrorCode values
	BcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeNotFound            = "NOT_FOUND"
	BcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"

	// BillEstimateStatus values
	BcmpricingcalculatorBillEstimateStatusInProgress = "IN_PROGRESS"
	BcmpricingcalculatorBillEstimateStatusComplete   = "COMPLETE"
	BcmpricingcalculatorBillEstimateStatusFailed     = "FAILED"

	// BillScenarioStatus values
	BcmpricingcalculatorBillScenarioStatusReady  = "READY"
	BcmpricingcalculatorBillScenarioStatusLocked = "LOCKED"
	BcmpricingcalculatorBillScenarioStatusFailed = "FAILED"
	BcmpricingcalculatorBillScenarioStatusStale  = "STALE"

	// CurrencyCode values
	BcmpricingcalculatorCurrencyCodeUsd = "USD"

	// GroupSharingPreferenceEnum values
	BcmpricingcalculatorGroupSharingPreferenceEnumOpen        = "OPEN"
	BcmpricingcalculatorGroupSharingPreferenceEnumPrioritized = "PRIORITIZED"
	BcmpricingcalculatorGroupSharingPreferenceEnumRestricted  = "RESTRICTED"

	// ListBillEstimateLineItemsFilterName values
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameUsageAccountId = "USAGE_ACCOUNT_ID"
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameServiceCode    = "SERVICE_CODE"
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameUsageType      = "USAGE_TYPE"
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameOperation      = "OPERATION"
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameLocation       = "LOCATION"
	BcmpricingcalculatorListBillEstimateLineItemsFilterNameLineItemType   = "LINE_ITEM_TYPE"

	// ListBillEstimatesFilterName values
	BcmpricingcalculatorListBillEstimatesFilterNameStatus = "STATUS"
	BcmpricingcalculatorListBillEstimatesFilterNameName   = "NAME"

	// ListBillScenariosFilterName values
	BcmpricingcalculatorListBillScenariosFilterNameStatus                 = "STATUS"
	BcmpricingcalculatorListBillScenariosFilterNameName                   = "NAME"
	BcmpricingcalculatorListBillScenariosFilterNameGroupSharingPreference = "GROUP_SHARING_PREFERENCE"
	BcmpricingcalculatorListBillScenariosFilterNameCostCategoryArn        = "COST_CATEGORY_ARN"

	// ListUsageFilterName values
	BcmpricingcalculatorListUsageFilterNameUsageAccountId           = "USAGE_ACCOUNT_ID"
	BcmpricingcalculatorListUsageFilterNameServiceCode              = "SERVICE_CODE"
	BcmpricingcalculatorListUsageFilterNameUsageType                = "USAGE_TYPE"
	BcmpricingcalculatorListUsageFilterNameOperation                = "OPERATION"
	BcmpricingcalculatorListUsageFilterNameLocation                 = "LOCATION"
	BcmpricingcalculatorListUsageFilterNameUsageGroup               = "USAGE_GROUP"
	BcmpricingcalculatorListUsageFilterNameHistoricalUsageAccountId = "HISTORICAL_USAGE_ACCOUNT_ID"
	BcmpricingcalculatorListUsageFilterNameHistoricalServiceCode    = "HISTORICAL_SERVICE_CODE"
	BcmpricingcalculatorListUsageFilterNameHistoricalUsageType      = "HISTORICAL_USAGE_TYPE"
	BcmpricingcalculatorListUsageFilterNameHistoricalOperation      = "HISTORICAL_OPERATION"
	BcmpricingcalculatorListUsageFilterNameHistoricalLocation       = "HISTORICAL_LOCATION"

	// ListWorkloadEstimatesFilterName values
	BcmpricingcalculatorListWorkloadEstimatesFilterNameStatus = "STATUS"
	BcmpricingcalculatorListWorkloadEstimatesFilterNameName   = "NAME"

	// MatchOption values
	BcmpricingcalculatorMatchOptionEquals     = "EQUALS"
	BcmpricingcalculatorMatchOptionStartsWith = "STARTS_WITH"
	BcmpricingcalculatorMatchOptionContains   = "CONTAINS"

	// PurchaseAgreementType values
	BcmpricingcalculatorPurchaseAgreementTypeSavingsPlans     = "SAVINGS_PLANS"
	BcmpricingcalculatorPurchaseAgreementTypeReservedInstance = "RESERVED_INSTANCE"

	// RateType values
	BcmpricingcalculatorRateTypeBeforeDiscounts              = "BEFORE_DISCOUNTS"
	BcmpricingcalculatorRateTypeAfterDiscounts               = "AFTER_DISCOUNTS"
	BcmpricingcalculatorRateTypeAfterDiscountsAndCommitments = "AFTER_DISCOUNTS_AND_COMMITMENTS"

	// ValidationExceptionReason values
	BcmpricingcalculatorValidationExceptionReasonUnknownoperation         = "unknownOperation"
	BcmpricingcalculatorValidationExceptionReasonCannotparse              = "cannotParse"
	BcmpricingcalculatorValidationExceptionReasonFieldvalidationfailed    = "fieldValidationFailed"
	BcmpricingcalculatorValidationExceptionReasonInvalidrequestfrommember = "invalidRequestFromMember"
	BcmpricingcalculatorValidationExceptionReasonDisallowedrate           = "disallowedRate"
	BcmpricingcalculatorValidationExceptionReasonOther                    = "other"

	// WorkloadEstimateCostStatus values
	BcmpricingcalculatorWorkloadEstimateCostStatusValid   = "VALID"
	BcmpricingcalculatorWorkloadEstimateCostStatusInvalid = "INVALID"
	BcmpricingcalculatorWorkloadEstimateCostStatusStale   = "STALE"

	// WorkloadEstimateRateType values
	BcmpricingcalculatorWorkloadEstimateRateTypeBeforeDiscounts              = "BEFORE_DISCOUNTS"
	BcmpricingcalculatorWorkloadEstimateRateTypeAfterDiscounts               = "AFTER_DISCOUNTS"
	BcmpricingcalculatorWorkloadEstimateRateTypeAfterDiscountsAndCommitments = "AFTER_DISCOUNTS_AND_COMMITMENTS"

	// WorkloadEstimateStatus values
	BcmpricingcalculatorWorkloadEstimateStatusUpdating     = "UPDATING"
	BcmpricingcalculatorWorkloadEstimateStatusValid        = "VALID"
	BcmpricingcalculatorWorkloadEstimateStatusInvalid      = "INVALID"
	BcmpricingcalculatorWorkloadEstimateStatusActionNeeded = "ACTION_NEEDED"

	// WorkloadEstimateUpdateUsageErrorCode values
	BcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeBadRequest          = "BAD_REQUEST"
	BcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeNotFound            = "NOT_FOUND"
	BcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeConflict            = "CONFLICT"
	BcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeInternalServerError = "INTERNAL_SERVER_ERROR"
)

var bcmpricingcalculatorBatchCreateBillScenarioCommitmentModificationErrorCodeValues = []string{
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
	"INVALID_ACCOUNT",
}

var bcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeValues = []string{
	"BAD_REQUEST",
	"NOT_FOUND",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeValues = []string{
	"BAD_REQUEST",
	"NOT_FOUND",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBatchDeleteBillScenarioCommitmentModificationErrorCodeValues = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBatchDeleteBillScenarioUsageModificationErrorCodeValues = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeValues = []string{
	"BAD_REQUEST",
	"NOT_FOUND",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeValues = []string{
	"BAD_REQUEST",
	"NOT_FOUND",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

var bcmpricingcalculatorBillEstimateStatusValues = []string{
	"IN_PROGRESS",
	"COMPLETE",
	"FAILED",
}

var bcmpricingcalculatorBillScenarioStatusValues = []string{
	"READY",
	"LOCKED",
	"FAILED",
	"STALE",
}

var bcmpricingcalculatorCurrencyCodeValues = []string{
	"USD",
}

var bcmpricingcalculatorGroupSharingPreferenceEnumValues = []string{
	"OPEN",
	"PRIORITIZED",
	"RESTRICTED",
}

var bcmpricingcalculatorListBillEstimateLineItemsFilterNameValues = []string{
	"USAGE_ACCOUNT_ID",
	"SERVICE_CODE",
	"USAGE_TYPE",
	"OPERATION",
	"LOCATION",
	"LINE_ITEM_TYPE",
}

var bcmpricingcalculatorListBillEstimatesFilterNameValues = []string{
	"STATUS",
	"NAME",
}

var bcmpricingcalculatorListBillScenariosFilterNameValues = []string{
	"STATUS",
	"NAME",
	"GROUP_SHARING_PREFERENCE",
	"COST_CATEGORY_ARN",
}

var bcmpricingcalculatorListUsageFilterNameValues = []string{
	"USAGE_ACCOUNT_ID",
	"SERVICE_CODE",
	"USAGE_TYPE",
	"OPERATION",
	"LOCATION",
	"USAGE_GROUP",
	"HISTORICAL_USAGE_ACCOUNT_ID",
	"HISTORICAL_SERVICE_CODE",
	"HISTORICAL_USAGE_TYPE",
	"HISTORICAL_OPERATION",
	"HISTORICAL_LOCATION",
}

var bcmpricingcalculatorListWorkloadEstimatesFilterNameValues = []string{
	"STATUS",
	"NAME",
}

var bcmpricingcalculatorMatchOptionValues = []string{
	"EQUALS",
	"STARTS_WITH",
	"CONTAINS",
}

var bcmpricingcalculatorPurchaseAgreementTypeValues = []string{
	"SAVINGS_PLANS",
	"RESERVED_INSTANCE",
}

var bcmpricingcalculatorRateTypeValues = []string{
	"BEFORE_DISCOUNTS",
	"AFTER_DISCOUNTS",
	"AFTER_DISCOUNTS_AND_COMMITMENTS",
}

var bcmpricingcalculatorValidationExceptionReasonValues = []string{
	"unknownOperation",
	"cannotParse",
	"fieldValidationFailed",
	"invalidRequestFromMember",
	"disallowedRate",
	"other",
}

var bcmpricingcalculatorWorkloadEstimateCostStatusValues = []string{
	"VALID",
	"INVALID",
	"STALE",
}

var bcmpricingcalculatorWorkloadEstimateRateTypeValues = []string{
	"BEFORE_DISCOUNTS",
	"AFTER_DISCOUNTS",
	"AFTER_DISCOUNTS_AND_COMMITMENTS",
}

var bcmpricingcalculatorWorkloadEstimateStatusValues = []string{
	"UPDATING",
	"VALID",
	"INVALID",
	"ACTION_NEEDED",
}

var bcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeValues = []string{
	"BAD_REQUEST",
	"NOT_FOUND",
	"CONFLICT",
	"INTERNAL_SERVER_ERROR",
}

func getBcmPricingCalculatorEnum(name string) []string {
	switch name {
	case "BatchCreateBillScenarioCommitmentModificationErrorCode":
		return bcmpricingcalculatorBatchCreateBillScenarioCommitmentModificationErrorCodeValues
	case "BatchCreateBillScenarioUsageModificationErrorCode":
		return bcmpricingcalculatorBatchCreateBillScenarioUsageModificationErrorCodeValues
	case "BatchCreateWorkloadEstimateUsageCode":
		return bcmpricingcalculatorBatchCreateWorkloadEstimateUsageCodeValues
	case "BatchDeleteBillScenarioCommitmentModificationErrorCode":
		return bcmpricingcalculatorBatchDeleteBillScenarioCommitmentModificationErrorCodeValues
	case "BatchDeleteBillScenarioUsageModificationErrorCode":
		return bcmpricingcalculatorBatchDeleteBillScenarioUsageModificationErrorCodeValues
	case "BatchUpdateBillScenarioCommitmentModificationErrorCode":
		return bcmpricingcalculatorBatchUpdateBillScenarioCommitmentModificationErrorCodeValues
	case "BatchUpdateBillScenarioUsageModificationErrorCode":
		return bcmpricingcalculatorBatchUpdateBillScenarioUsageModificationErrorCodeValues
	case "BillEstimateStatus":
		return bcmpricingcalculatorBillEstimateStatusValues
	case "BillScenarioStatus":
		return bcmpricingcalculatorBillScenarioStatusValues
	case "CurrencyCode":
		return bcmpricingcalculatorCurrencyCodeValues
	case "GroupSharingPreferenceEnum":
		return bcmpricingcalculatorGroupSharingPreferenceEnumValues
	case "ListBillEstimateLineItemsFilterName":
		return bcmpricingcalculatorListBillEstimateLineItemsFilterNameValues
	case "ListBillEstimatesFilterName":
		return bcmpricingcalculatorListBillEstimatesFilterNameValues
	case "ListBillScenariosFilterName":
		return bcmpricingcalculatorListBillScenariosFilterNameValues
	case "ListUsageFilterName":
		return bcmpricingcalculatorListUsageFilterNameValues
	case "ListWorkloadEstimatesFilterName":
		return bcmpricingcalculatorListWorkloadEstimatesFilterNameValues
	case "MatchOption":
		return bcmpricingcalculatorMatchOptionValues
	case "PurchaseAgreementType":
		return bcmpricingcalculatorPurchaseAgreementTypeValues
	case "RateType":
		return bcmpricingcalculatorRateTypeValues
	case "ValidationExceptionReason":
		return bcmpricingcalculatorValidationExceptionReasonValues
	case "WorkloadEstimateCostStatus":
		return bcmpricingcalculatorWorkloadEstimateCostStatusValues
	case "WorkloadEstimateRateType":
		return bcmpricingcalculatorWorkloadEstimateRateTypeValues
	case "WorkloadEstimateStatus":
		return bcmpricingcalculatorWorkloadEstimateStatusValues
	case "WorkloadEstimateUpdateUsageErrorCode":
		return bcmpricingcalculatorWorkloadEstimateUpdateUsageErrorCodeValues
	}
	return nil
}

func getBcmPricingCalculatorEnumNames() []string {
	return []string{
		"BatchCreateBillScenarioCommitmentModificationErrorCode",
		"BatchCreateBillScenarioUsageModificationErrorCode",
		"BatchCreateWorkloadEstimateUsageCode",
		"BatchDeleteBillScenarioCommitmentModificationErrorCode",
		"BatchDeleteBillScenarioUsageModificationErrorCode",
		"BatchUpdateBillScenarioCommitmentModificationErrorCode",
		"BatchUpdateBillScenarioUsageModificationErrorCode",
		"BillEstimateStatus",
		"BillScenarioStatus",
		"CurrencyCode",
		"GroupSharingPreferenceEnum",
		"ListBillEstimateLineItemsFilterName",
		"ListBillEstimatesFilterName",
		"ListBillScenariosFilterName",
		"ListUsageFilterName",
		"ListWorkloadEstimatesFilterName",
		"MatchOption",
		"PurchaseAgreementType",
		"RateType",
		"ValidationExceptionReason",
		"WorkloadEstimateCostStatus",
		"WorkloadEstimateRateType",
		"WorkloadEstimateStatus",
		"WorkloadEstimateUpdateUsageErrorCode",
	}
}
