// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// BedrockAgent enum constants
const (
	// ActionGroupSignature values
	BedrockagentActionGroupSignatureAmazonUserinput       = "AMAZON.UserInput"
	BedrockagentActionGroupSignatureAmazonCodeinterpreter = "AMAZON.CodeInterpreter"
	BedrockagentActionGroupSignatureAnthropicComputer     = "ANTHROPIC.Computer"
	BedrockagentActionGroupSignatureAnthropicBash         = "ANTHROPIC.Bash"
	BedrockagentActionGroupSignatureAnthropicTexteditor   = "ANTHROPIC.TextEditor"

	// ActionGroupState values
	BedrockagentActionGroupStateEnabled  = "ENABLED"
	BedrockagentActionGroupStateDisabled = "DISABLED"

	// AgentAliasStatus values
	BedrockagentAgentAliasStatusCreating    = "CREATING"
	BedrockagentAgentAliasStatusPrepared    = "PREPARED"
	BedrockagentAgentAliasStatusFailed      = "FAILED"
	BedrockagentAgentAliasStatusUpdating    = "UPDATING"
	BedrockagentAgentAliasStatusDeleting    = "DELETING"
	BedrockagentAgentAliasStatusDissociated = "DISSOCIATED"

	// AgentCollaboration values
	BedrockagentAgentCollaborationSupervisor       = "SUPERVISOR"
	BedrockagentAgentCollaborationSupervisorRouter = "SUPERVISOR_ROUTER"
	BedrockagentAgentCollaborationDisabled         = "DISABLED"

	// AgentStatus values
	BedrockagentAgentStatusCreating    = "CREATING"
	BedrockagentAgentStatusPreparing   = "PREPARING"
	BedrockagentAgentStatusPrepared    = "PREPARED"
	BedrockagentAgentStatusNotPrepared = "NOT_PREPARED"
	BedrockagentAgentStatusDeleting    = "DELETING"
	BedrockagentAgentStatusFailed      = "FAILED"
	BedrockagentAgentStatusVersioning  = "VERSIONING"
	BedrockagentAgentStatusUpdating    = "UPDATING"

	// AliasInvocationState values
	BedrockagentAliasInvocationStateAcceptInvocations = "ACCEPT_INVOCATIONS"
	BedrockagentAliasInvocationStateRejectInvocations = "REJECT_INVOCATIONS"

	// CachePointType values
	BedrockagentCachePointTypeDefault = "default"

	// ChunkingStrategy values
	BedrockagentChunkingStrategyFixedSize    = "FIXED_SIZE"
	BedrockagentChunkingStrategyNone         = "NONE"
	BedrockagentChunkingStrategyHierarchical = "HIERARCHICAL"
	BedrockagentChunkingStrategySemantic     = "SEMANTIC"

	// ConcurrencyType values
	BedrockagentConcurrencyTypeAutomatic = "Automatic"
	BedrockagentConcurrencyTypeManual    = "Manual"

	// ConfluenceAuthType values
	BedrockagentConfluenceAuthTypeBasic                   = "BASIC"
	BedrockagentConfluenceAuthTypeOauth2ClientCredentials = "OAUTH2_CLIENT_CREDENTIALS"

	// ConfluenceHostType values
	BedrockagentConfluenceHostTypeSaas = "SAAS"

	// ContentDataSourceType values
	BedrockagentContentDataSourceTypeCustom = "CUSTOM"
	BedrockagentContentDataSourceTypeS3     = "S3"

	// ContextEnrichmentType values
	BedrockagentContextEnrichmentTypeBedrockFoundationModel = "BEDROCK_FOUNDATION_MODEL"

	// ConversationRole values
	BedrockagentConversationRoleUser      = "user"
	BedrockagentConversationRoleAssistant = "assistant"

	// CrawlFilterConfigurationType values
	BedrockagentCrawlFilterConfigurationTypePattern = "PATTERN"

	// CreationMode values
	BedrockagentCreationModeDefault    = "DEFAULT"
	BedrockagentCreationModeOverridden = "OVERRIDDEN"

	// CustomControlMethod values
	BedrockagentCustomControlMethodReturnControl = "RETURN_CONTROL"

	// CustomSourceType values
	BedrockagentCustomSourceTypeInLine     = "IN_LINE"
	BedrockagentCustomSourceTypeS3Location = "S3_LOCATION"

	// DataDeletionPolicy values
	BedrockagentDataDeletionPolicyRetain = "RETAIN"
	BedrockagentDataDeletionPolicyDelete = "DELETE"

	// DataSourceStatus values
	BedrockagentDataSourceStatusAvailable          = "AVAILABLE"
	BedrockagentDataSourceStatusDeleting           = "DELETING"
	BedrockagentDataSourceStatusDeleteUnsuccessful = "DELETE_UNSUCCESSFUL"

	// DataSourceType values
	BedrockagentDataSourceTypeS3               = "S3"
	BedrockagentDataSourceTypeWeb              = "WEB"
	BedrockagentDataSourceTypeConfluence       = "CONFLUENCE"
	BedrockagentDataSourceTypeSalesforce       = "SALESFORCE"
	BedrockagentDataSourceTypeSharepoint       = "SHAREPOINT"
	BedrockagentDataSourceTypeCustom           = "CUSTOM"
	BedrockagentDataSourceTypeRedshiftMetadata = "REDSHIFT_METADATA"

	// DocumentStatus values
	BedrockagentDocumentStatusIndexed                  = "INDEXED"
	BedrockagentDocumentStatusPartiallyIndexed         = "PARTIALLY_INDEXED"
	BedrockagentDocumentStatusPending                  = "PENDING"
	BedrockagentDocumentStatusFailed                   = "FAILED"
	BedrockagentDocumentStatusMetadataPartiallyIndexed = "METADATA_PARTIALLY_INDEXED"
	BedrockagentDocumentStatusMetadataUpdateFailed     = "METADATA_UPDATE_FAILED"
	BedrockagentDocumentStatusIgnored                  = "IGNORED"
	BedrockagentDocumentStatusNotFound                 = "NOT_FOUND"
	BedrockagentDocumentStatusStarting                 = "STARTING"
	BedrockagentDocumentStatusInProgress               = "IN_PROGRESS"
	BedrockagentDocumentStatusDeleting                 = "DELETING"
	BedrockagentDocumentStatusDeleteInProgress         = "DELETE_IN_PROGRESS"

	// EmbeddingDataType values
	BedrockagentEmbeddingDataTypeFloat32 = "FLOAT32"
	BedrockagentEmbeddingDataTypeBinary  = "BINARY"

	// EnrichmentStrategyMethod values
	BedrockagentEnrichmentStrategyMethodChunkEntityExtraction = "CHUNK_ENTITY_EXTRACTION"

	// FlowConnectionType values
	BedrockagentFlowConnectionTypeData        = "Data"
	BedrockagentFlowConnectionTypeConditional = "Conditional"

	// FlowNodeIODataType values
	BedrockagentFlowNodeIODataTypeString  = "String"
	BedrockagentFlowNodeIODataTypeNumber  = "Number"
	BedrockagentFlowNodeIODataTypeBoolean = "Boolean"
	BedrockagentFlowNodeIODataTypeObject  = "Object"
	BedrockagentFlowNodeIODataTypeArray   = "Array"

	// FlowNodeInputCategory values
	BedrockagentFlowNodeInputCategoryLoopcondition          = "LoopCondition"
	BedrockagentFlowNodeInputCategoryReturnvaluetoloopstart = "ReturnValueToLoopStart"
	BedrockagentFlowNodeInputCategoryExitloop               = "ExitLoop"

	// FlowNodeType values
	BedrockagentFlowNodeTypeInput          = "Input"
	BedrockagentFlowNodeTypeOutput         = "Output"
	BedrockagentFlowNodeTypeKnowledgebase  = "KnowledgeBase"
	BedrockagentFlowNodeTypeCondition      = "Condition"
	BedrockagentFlowNodeTypeLex            = "Lex"
	BedrockagentFlowNodeTypePrompt         = "Prompt"
	BedrockagentFlowNodeTypeLambdafunction = "LambdaFunction"
	BedrockagentFlowNodeTypeStorage        = "Storage"
	BedrockagentFlowNodeTypeAgent          = "Agent"
	BedrockagentFlowNodeTypeRetrieval      = "Retrieval"
	BedrockagentFlowNodeTypeIterator       = "Iterator"
	BedrockagentFlowNodeTypeCollector      = "Collector"
	BedrockagentFlowNodeTypeInlinecode     = "InlineCode"
	BedrockagentFlowNodeTypeLoop           = "Loop"
	BedrockagentFlowNodeTypeLoopinput      = "LoopInput"
	BedrockagentFlowNodeTypeLoopcontroller = "LoopController"

	// FlowStatus values
	BedrockagentFlowStatusFailed      = "Failed"
	BedrockagentFlowStatusPrepared    = "Prepared"
	BedrockagentFlowStatusPreparing   = "Preparing"
	BedrockagentFlowStatusNotprepared = "NotPrepared"

	// FlowValidationSeverity values
	BedrockagentFlowValidationSeverityWarning = "Warning"
	BedrockagentFlowValidationSeverityError   = "Error"

	// FlowValidationType values
	BedrockagentFlowValidationTypeCyclicconnection                = "CyclicConnection"
	BedrockagentFlowValidationTypeDuplicateconnections            = "DuplicateConnections"
	BedrockagentFlowValidationTypeDuplicateconditionexpression    = "DuplicateConditionExpression"
	BedrockagentFlowValidationTypeUnreachablenode                 = "UnreachableNode"
	BedrockagentFlowValidationTypeUnknownconnectionsource         = "UnknownConnectionSource"
	BedrockagentFlowValidationTypeUnknownconnectionsourceoutput   = "UnknownConnectionSourceOutput"
	BedrockagentFlowValidationTypeUnknownconnectiontarget         = "UnknownConnectionTarget"
	BedrockagentFlowValidationTypeUnknownconnectiontargetinput    = "UnknownConnectionTargetInput"
	BedrockagentFlowValidationTypeUnknownconnectioncondition      = "UnknownConnectionCondition"
	BedrockagentFlowValidationTypeMalformedconditionexpression    = "MalformedConditionExpression"
	BedrockagentFlowValidationTypeMalformednodeinputexpression    = "MalformedNodeInputExpression"
	BedrockagentFlowValidationTypeMismatchednodeinputtype         = "MismatchedNodeInputType"
	BedrockagentFlowValidationTypeMismatchednodeoutputtype        = "MismatchedNodeOutputType"
	BedrockagentFlowValidationTypeIncompatibleconnectiondatatype  = "IncompatibleConnectionDataType"
	BedrockagentFlowValidationTypeMissingconnectionconfiguration  = "MissingConnectionConfiguration"
	BedrockagentFlowValidationTypeMissingdefaultcondition         = "MissingDefaultCondition"
	BedrockagentFlowValidationTypeMissingendingnodes              = "MissingEndingNodes"
	BedrockagentFlowValidationTypeMissingnodeconfiguration        = "MissingNodeConfiguration"
	BedrockagentFlowValidationTypeMissingnodeinput                = "MissingNodeInput"
	BedrockagentFlowValidationTypeMissingnodeoutput               = "MissingNodeOutput"
	BedrockagentFlowValidationTypeMissingstartingnodes            = "MissingStartingNodes"
	BedrockagentFlowValidationTypeMultiplenodeinputconnections    = "MultipleNodeInputConnections"
	BedrockagentFlowValidationTypeUnfulfillednodeinput            = "UnfulfilledNodeInput"
	BedrockagentFlowValidationTypeUnsatisfiedconnectionconditions = "UnsatisfiedConnectionConditions"
	BedrockagentFlowValidationTypeUnspecified                     = "Unspecified"
	BedrockagentFlowValidationTypeUnknownnodeinput                = "UnknownNodeInput"
	BedrockagentFlowValidationTypeUnknownnodeoutput               = "UnknownNodeOutput"
	BedrockagentFlowValidationTypeMissingloopinputnode            = "MissingLoopInputNode"
	BedrockagentFlowValidationTypeMissingloopcontrollernode       = "MissingLoopControllerNode"
	BedrockagentFlowValidationTypeMultipleloopinputnodes          = "MultipleLoopInputNodes"
	BedrockagentFlowValidationTypeMultipleloopcontrollernodes     = "MultipleLoopControllerNodes"
	BedrockagentFlowValidationTypeLoopincompatiblenodetype        = "LoopIncompatibleNodeType"
	BedrockagentFlowValidationTypeInvalidloopboundary             = "InvalidLoopBoundary"

	// IncludeExclude values
	BedrockagentIncludeExcludeInclude = "INCLUDE"
	BedrockagentIncludeExcludeExclude = "EXCLUDE"

	// IncompatibleLoopNodeType values
	BedrockagentIncompatibleLoopNodeTypeInput     = "Input"
	BedrockagentIncompatibleLoopNodeTypeCondition = "Condition"
	BedrockagentIncompatibleLoopNodeTypeIterator  = "Iterator"
	BedrockagentIncompatibleLoopNodeTypeCollector = "Collector"

	// IngestionJobFilterAttribute values
	BedrockagentIngestionJobFilterAttributeStatus = "STATUS"

	// IngestionJobFilterOperator values
	BedrockagentIngestionJobFilterOperatorEq = "EQ"

	// IngestionJobSortByAttribute values
	BedrockagentIngestionJobSortByAttributeStatus    = "STATUS"
	BedrockagentIngestionJobSortByAttributeStartedAt = "STARTED_AT"

	// IngestionJobStatus values
	BedrockagentIngestionJobStatusStarting   = "STARTING"
	BedrockagentIngestionJobStatusInProgress = "IN_PROGRESS"
	BedrockagentIngestionJobStatusComplete   = "COMPLETE"
	BedrockagentIngestionJobStatusFailed     = "FAILED"
	BedrockagentIngestionJobStatusStopping   = "STOPPING"
	BedrockagentIngestionJobStatusStopped    = "STOPPED"

	// InlineContentType values
	BedrockagentInlineContentTypeByte = "BYTE"
	BedrockagentInlineContentTypeText = "TEXT"

	// KnowledgeBaseState values
	BedrockagentKnowledgeBaseStateEnabled  = "ENABLED"
	BedrockagentKnowledgeBaseStateDisabled = "DISABLED"

	// KnowledgeBaseStatus values
	BedrockagentKnowledgeBaseStatusCreating           = "CREATING"
	BedrockagentKnowledgeBaseStatusActive             = "ACTIVE"
	BedrockagentKnowledgeBaseStatusDeleting           = "DELETING"
	BedrockagentKnowledgeBaseStatusUpdating           = "UPDATING"
	BedrockagentKnowledgeBaseStatusFailed             = "FAILED"
	BedrockagentKnowledgeBaseStatusDeleteUnsuccessful = "DELETE_UNSUCCESSFUL"

	// KnowledgeBaseStorageType values
	BedrockagentKnowledgeBaseStorageTypeOpensearchServerless     = "OPENSEARCH_SERVERLESS"
	BedrockagentKnowledgeBaseStorageTypePinecone                 = "PINECONE"
	BedrockagentKnowledgeBaseStorageTypeRedisEnterpriseCloud     = "REDIS_ENTERPRISE_CLOUD"
	BedrockagentKnowledgeBaseStorageTypeRds                      = "RDS"
	BedrockagentKnowledgeBaseStorageTypeMongoDbAtlas             = "MONGO_DB_ATLAS"
	BedrockagentKnowledgeBaseStorageTypeNeptuneAnalytics         = "NEPTUNE_ANALYTICS"
	BedrockagentKnowledgeBaseStorageTypeOpensearchManagedCluster = "OPENSEARCH_MANAGED_CLUSTER"
	BedrockagentKnowledgeBaseStorageTypeS3Vectors                = "S3_VECTORS"

	// KnowledgeBaseType values
	BedrockagentKnowledgeBaseTypeVector = "VECTOR"
	BedrockagentKnowledgeBaseTypeKendra = "KENDRA"
	BedrockagentKnowledgeBaseTypeSql    = "SQL"

	// MemoryType values
	BedrockagentMemoryTypeSessionSummary = "SESSION_SUMMARY"

	// MetadataSourceType values
	BedrockagentMetadataSourceTypeInLineAttribute = "IN_LINE_ATTRIBUTE"
	BedrockagentMetadataSourceTypeS3Location      = "S3_LOCATION"

	// MetadataValueType values
	BedrockagentMetadataValueTypeBoolean    = "BOOLEAN"
	BedrockagentMetadataValueTypeNumber     = "NUMBER"
	BedrockagentMetadataValueTypeString     = "STRING"
	BedrockagentMetadataValueTypeStringList = "STRING_LIST"

	// OrchestrationType values
	BedrockagentOrchestrationTypeDefault             = "DEFAULT"
	BedrockagentOrchestrationTypeCustomOrchestration = "CUSTOM_ORCHESTRATION"

	// ParsingModality values
	BedrockagentParsingModalityMultimodal = "MULTIMODAL"

	// ParsingStrategy values
	BedrockagentParsingStrategyBedrockFoundationModel = "BEDROCK_FOUNDATION_MODEL"
	BedrockagentParsingStrategyBedrockDataAutomation  = "BEDROCK_DATA_AUTOMATION"

	// PerformanceConfigLatency values
	BedrockagentPerformanceConfigLatencyStandard  = "standard"
	BedrockagentPerformanceConfigLatencyOptimized = "optimized"

	// PromptState values
	BedrockagentPromptStateEnabled  = "ENABLED"
	BedrockagentPromptStateDisabled = "DISABLED"

	// PromptTemplateType values
	BedrockagentPromptTemplateTypeText = "TEXT"
	BedrockagentPromptTemplateTypeChat = "CHAT"

	// PromptType values
	BedrockagentPromptTypePreProcessing                   = "PRE_PROCESSING"
	BedrockagentPromptTypeOrchestration                   = "ORCHESTRATION"
	BedrockagentPromptTypePostProcessing                  = "POST_PROCESSING"
	BedrockagentPromptTypeKnowledgeBaseResponseGeneration = "KNOWLEDGE_BASE_RESPONSE_GENERATION"
	BedrockagentPromptTypeMemorySummarization             = "MEMORY_SUMMARIZATION"

	// QueryEngineType values
	BedrockagentQueryEngineTypeRedshift = "REDSHIFT"

	// RedshiftProvisionedAuthType values
	BedrockagentRedshiftProvisionedAuthTypeIam              = "IAM"
	BedrockagentRedshiftProvisionedAuthTypeUsernamePassword = "USERNAME_PASSWORD"
	BedrockagentRedshiftProvisionedAuthTypeUsername         = "USERNAME"

	// RedshiftQueryEngineStorageType values
	BedrockagentRedshiftQueryEngineStorageTypeRedshift       = "REDSHIFT"
	BedrockagentRedshiftQueryEngineStorageTypeAwsDataCatalog = "AWS_DATA_CATALOG"

	// RedshiftQueryEngineType values
	BedrockagentRedshiftQueryEngineTypeServerless  = "SERVERLESS"
	BedrockagentRedshiftQueryEngineTypeProvisioned = "PROVISIONED"

	// RedshiftServerlessAuthType values
	BedrockagentRedshiftServerlessAuthTypeIam              = "IAM"
	BedrockagentRedshiftServerlessAuthTypeUsernamePassword = "USERNAME_PASSWORD"

	// RelayConversationHistory values
	BedrockagentRelayConversationHistoryToCollaborator = "TO_COLLABORATOR"
	BedrockagentRelayConversationHistoryDisabled       = "DISABLED"

	// RequireConfirmation values
	BedrockagentRequireConfirmationEnabled  = "ENABLED"
	BedrockagentRequireConfirmationDisabled = "DISABLED"

	// RerankingMetadataSelectionMode values
	BedrockagentRerankingMetadataSelectionModeSelective = "SELECTIVE"
	BedrockagentRerankingMetadataSelectionModeAll       = "ALL"

	// SalesforceAuthType values
	BedrockagentSalesforceAuthTypeOauth2ClientCredentials = "OAUTH2_CLIENT_CREDENTIALS"

	// SharePointAuthType values
	BedrockagentSharePointAuthTypeOauth2ClientCredentials                  = "OAUTH2_CLIENT_CREDENTIALS"
	BedrockagentSharePointAuthTypeOauth2SharepointAppOnlyClientCredentials = "OAUTH2_SHAREPOINT_APP_ONLY_CLIENT_CREDENTIALS"

	// SharePointHostType values
	BedrockagentSharePointHostTypeOnline = "ONLINE"

	// SortOrder values
	BedrockagentSortOrderAscending  = "ASCENDING"
	BedrockagentSortOrderDescending = "DESCENDING"

	// StepType values
	BedrockagentStepTypePostChunking = "POST_CHUNKING"

	// SupplementalDataStorageLocationType values
	BedrockagentSupplementalDataStorageLocationTypeS3 = "S3"

	// SupportedLanguages values
	BedrockagentSupportedLanguagesPython3 = "Python_3"

	// Type values
	BedrockagentTypeString  = "string"
	BedrockagentTypeNumber  = "number"
	BedrockagentTypeInteger = "integer"
	BedrockagentTypeBoolean = "boolean"
	BedrockagentTypeArray   = "array"

	// VectorSearchRerankingConfigurationType values
	BedrockagentVectorSearchRerankingConfigurationTypeBedrockRerankingModel = "BEDROCK_RERANKING_MODEL"

	// WebScopeType values
	BedrockagentWebScopeTypeHostOnly   = "HOST_ONLY"
	BedrockagentWebScopeTypeSubdomains = "SUBDOMAINS"
)

var bedrockagentActionGroupSignatureValues = []string{
	"AMAZON.UserInput",
	"AMAZON.CodeInterpreter",
	"ANTHROPIC.Computer",
	"ANTHROPIC.Bash",
	"ANTHROPIC.TextEditor",
}

var bedrockagentActionGroupStateValues = []string{
	"ENABLED",
	"DISABLED",
}

var bedrockagentAgentAliasStatusValues = []string{
	"CREATING",
	"PREPARED",
	"FAILED",
	"UPDATING",
	"DELETING",
	"DISSOCIATED",
}

var bedrockagentAgentCollaborationValues = []string{
	"SUPERVISOR",
	"SUPERVISOR_ROUTER",
	"DISABLED",
}

var bedrockagentAgentStatusValues = []string{
	"CREATING",
	"PREPARING",
	"PREPARED",
	"NOT_PREPARED",
	"DELETING",
	"FAILED",
	"VERSIONING",
	"UPDATING",
}

var bedrockagentAliasInvocationStateValues = []string{
	"ACCEPT_INVOCATIONS",
	"REJECT_INVOCATIONS",
}

var bedrockagentCachePointTypeValues = []string{
	"default",
}

var bedrockagentChunkingStrategyValues = []string{
	"FIXED_SIZE",
	"NONE",
	"HIERARCHICAL",
	"SEMANTIC",
}

var bedrockagentConcurrencyTypeValues = []string{
	"Automatic",
	"Manual",
}

var bedrockagentConfluenceAuthTypeValues = []string{
	"BASIC",
	"OAUTH2_CLIENT_CREDENTIALS",
}

var bedrockagentConfluenceHostTypeValues = []string{
	"SAAS",
}

var bedrockagentContentDataSourceTypeValues = []string{
	"CUSTOM",
	"S3",
}

var bedrockagentContextEnrichmentTypeValues = []string{
	"BEDROCK_FOUNDATION_MODEL",
}

var bedrockagentConversationRoleValues = []string{
	"user",
	"assistant",
}

var bedrockagentCrawlFilterConfigurationTypeValues = []string{
	"PATTERN",
}

var bedrockagentCreationModeValues = []string{
	"DEFAULT",
	"OVERRIDDEN",
}

var bedrockagentCustomControlMethodValues = []string{
	"RETURN_CONTROL",
}

var bedrockagentCustomSourceTypeValues = []string{
	"IN_LINE",
	"S3_LOCATION",
}

var bedrockagentDataDeletionPolicyValues = []string{
	"RETAIN",
	"DELETE",
}

var bedrockagentDataSourceStatusValues = []string{
	"AVAILABLE",
	"DELETING",
	"DELETE_UNSUCCESSFUL",
}

var bedrockagentDataSourceTypeValues = []string{
	"S3",
	"WEB",
	"CONFLUENCE",
	"SALESFORCE",
	"SHAREPOINT",
	"CUSTOM",
	"REDSHIFT_METADATA",
}

var bedrockagentDocumentStatusValues = []string{
	"INDEXED",
	"PARTIALLY_INDEXED",
	"PENDING",
	"FAILED",
	"METADATA_PARTIALLY_INDEXED",
	"METADATA_UPDATE_FAILED",
	"IGNORED",
	"NOT_FOUND",
	"STARTING",
	"IN_PROGRESS",
	"DELETING",
	"DELETE_IN_PROGRESS",
}

var bedrockagentEmbeddingDataTypeValues = []string{
	"FLOAT32",
	"BINARY",
}

var bedrockagentEnrichmentStrategyMethodValues = []string{
	"CHUNK_ENTITY_EXTRACTION",
}

var bedrockagentFlowConnectionTypeValues = []string{
	"Data",
	"Conditional",
}

var bedrockagentFlowNodeIODataTypeValues = []string{
	"String",
	"Number",
	"Boolean",
	"Object",
	"Array",
}

var bedrockagentFlowNodeInputCategoryValues = []string{
	"LoopCondition",
	"ReturnValueToLoopStart",
	"ExitLoop",
}

var bedrockagentFlowNodeTypeValues = []string{
	"Input",
	"Output",
	"KnowledgeBase",
	"Condition",
	"Lex",
	"Prompt",
	"LambdaFunction",
	"Storage",
	"Agent",
	"Retrieval",
	"Iterator",
	"Collector",
	"InlineCode",
	"Loop",
	"LoopInput",
	"LoopController",
}

var bedrockagentFlowStatusValues = []string{
	"Failed",
	"Prepared",
	"Preparing",
	"NotPrepared",
}

var bedrockagentFlowValidationSeverityValues = []string{
	"Warning",
	"Error",
}

var bedrockagentFlowValidationTypeValues = []string{
	"CyclicConnection",
	"DuplicateConnections",
	"DuplicateConditionExpression",
	"UnreachableNode",
	"UnknownConnectionSource",
	"UnknownConnectionSourceOutput",
	"UnknownConnectionTarget",
	"UnknownConnectionTargetInput",
	"UnknownConnectionCondition",
	"MalformedConditionExpression",
	"MalformedNodeInputExpression",
	"MismatchedNodeInputType",
	"MismatchedNodeOutputType",
	"IncompatibleConnectionDataType",
	"MissingConnectionConfiguration",
	"MissingDefaultCondition",
	"MissingEndingNodes",
	"MissingNodeConfiguration",
	"MissingNodeInput",
	"MissingNodeOutput",
	"MissingStartingNodes",
	"MultipleNodeInputConnections",
	"UnfulfilledNodeInput",
	"UnsatisfiedConnectionConditions",
	"Unspecified",
	"UnknownNodeInput",
	"UnknownNodeOutput",
	"MissingLoopInputNode",
	"MissingLoopControllerNode",
	"MultipleLoopInputNodes",
	"MultipleLoopControllerNodes",
	"LoopIncompatibleNodeType",
	"InvalidLoopBoundary",
}

var bedrockagentIncludeExcludeValues = []string{
	"INCLUDE",
	"EXCLUDE",
}

var bedrockagentIncompatibleLoopNodeTypeValues = []string{
	"Input",
	"Condition",
	"Iterator",
	"Collector",
}

var bedrockagentIngestionJobFilterAttributeValues = []string{
	"STATUS",
}

var bedrockagentIngestionJobFilterOperatorValues = []string{
	"EQ",
}

var bedrockagentIngestionJobSortByAttributeValues = []string{
	"STATUS",
	"STARTED_AT",
}

var bedrockagentIngestionJobStatusValues = []string{
	"STARTING",
	"IN_PROGRESS",
	"COMPLETE",
	"FAILED",
	"STOPPING",
	"STOPPED",
}

var bedrockagentInlineContentTypeValues = []string{
	"BYTE",
	"TEXT",
}

var bedrockagentKnowledgeBaseStateValues = []string{
	"ENABLED",
	"DISABLED",
}

var bedrockagentKnowledgeBaseStatusValues = []string{
	"CREATING",
	"ACTIVE",
	"DELETING",
	"UPDATING",
	"FAILED",
	"DELETE_UNSUCCESSFUL",
}

var bedrockagentKnowledgeBaseStorageTypeValues = []string{
	"OPENSEARCH_SERVERLESS",
	"PINECONE",
	"REDIS_ENTERPRISE_CLOUD",
	"RDS",
	"MONGO_DB_ATLAS",
	"NEPTUNE_ANALYTICS",
	"OPENSEARCH_MANAGED_CLUSTER",
	"S3_VECTORS",
}

var bedrockagentKnowledgeBaseTypeValues = []string{
	"VECTOR",
	"KENDRA",
	"SQL",
}

var bedrockagentMemoryTypeValues = []string{
	"SESSION_SUMMARY",
}

var bedrockagentMetadataSourceTypeValues = []string{
	"IN_LINE_ATTRIBUTE",
	"S3_LOCATION",
}

var bedrockagentMetadataValueTypeValues = []string{
	"BOOLEAN",
	"NUMBER",
	"STRING",
	"STRING_LIST",
}

var bedrockagentOrchestrationTypeValues = []string{
	"DEFAULT",
	"CUSTOM_ORCHESTRATION",
}

var bedrockagentParsingModalityValues = []string{
	"MULTIMODAL",
}

var bedrockagentParsingStrategyValues = []string{
	"BEDROCK_FOUNDATION_MODEL",
	"BEDROCK_DATA_AUTOMATION",
}

var bedrockagentPerformanceConfigLatencyValues = []string{
	"standard",
	"optimized",
}

var bedrockagentPromptStateValues = []string{
	"ENABLED",
	"DISABLED",
}

var bedrockagentPromptTemplateTypeValues = []string{
	"TEXT",
	"CHAT",
}

var bedrockagentPromptTypeValues = []string{
	"PRE_PROCESSING",
	"ORCHESTRATION",
	"POST_PROCESSING",
	"KNOWLEDGE_BASE_RESPONSE_GENERATION",
	"MEMORY_SUMMARIZATION",
}

var bedrockagentQueryEngineTypeValues = []string{
	"REDSHIFT",
}

var bedrockagentRedshiftProvisionedAuthTypeValues = []string{
	"IAM",
	"USERNAME_PASSWORD",
	"USERNAME",
}

var bedrockagentRedshiftQueryEngineStorageTypeValues = []string{
	"REDSHIFT",
	"AWS_DATA_CATALOG",
}

var bedrockagentRedshiftQueryEngineTypeValues = []string{
	"SERVERLESS",
	"PROVISIONED",
}

var bedrockagentRedshiftServerlessAuthTypeValues = []string{
	"IAM",
	"USERNAME_PASSWORD",
}

var bedrockagentRelayConversationHistoryValues = []string{
	"TO_COLLABORATOR",
	"DISABLED",
}

var bedrockagentRequireConfirmationValues = []string{
	"ENABLED",
	"DISABLED",
}

var bedrockagentRerankingMetadataSelectionModeValues = []string{
	"SELECTIVE",
	"ALL",
}

var bedrockagentSalesforceAuthTypeValues = []string{
	"OAUTH2_CLIENT_CREDENTIALS",
}

var bedrockagentSharePointAuthTypeValues = []string{
	"OAUTH2_CLIENT_CREDENTIALS",
	"OAUTH2_SHAREPOINT_APP_ONLY_CLIENT_CREDENTIALS",
}

var bedrockagentSharePointHostTypeValues = []string{
	"ONLINE",
}

var bedrockagentSortOrderValues = []string{
	"ASCENDING",
	"DESCENDING",
}

var bedrockagentStepTypeValues = []string{
	"POST_CHUNKING",
}

var bedrockagentSupplementalDataStorageLocationTypeValues = []string{
	"S3",
}

var bedrockagentSupportedLanguagesValues = []string{
	"Python_3",
}

var bedrockagentTypeValues = []string{
	"string",
	"number",
	"integer",
	"boolean",
	"array",
}

var bedrockagentVectorSearchRerankingConfigurationTypeValues = []string{
	"BEDROCK_RERANKING_MODEL",
}

var bedrockagentWebScopeTypeValues = []string{
	"HOST_ONLY",
	"SUBDOMAINS",
}

func getBedrockAgentEnum(name string) []string {
	switch name {
	case "ActionGroupSignature":
		return bedrockagentActionGroupSignatureValues
	case "ActionGroupState":
		return bedrockagentActionGroupStateValues
	case "AgentAliasStatus":
		return bedrockagentAgentAliasStatusValues
	case "AgentCollaboration":
		return bedrockagentAgentCollaborationValues
	case "AgentStatus":
		return bedrockagentAgentStatusValues
	case "AliasInvocationState":
		return bedrockagentAliasInvocationStateValues
	case "CachePointType":
		return bedrockagentCachePointTypeValues
	case "ChunkingStrategy":
		return bedrockagentChunkingStrategyValues
	case "ConcurrencyType":
		return bedrockagentConcurrencyTypeValues
	case "ConfluenceAuthType":
		return bedrockagentConfluenceAuthTypeValues
	case "ConfluenceHostType":
		return bedrockagentConfluenceHostTypeValues
	case "ContentDataSourceType":
		return bedrockagentContentDataSourceTypeValues
	case "ContextEnrichmentType":
		return bedrockagentContextEnrichmentTypeValues
	case "ConversationRole":
		return bedrockagentConversationRoleValues
	case "CrawlFilterConfigurationType":
		return bedrockagentCrawlFilterConfigurationTypeValues
	case "CreationMode":
		return bedrockagentCreationModeValues
	case "CustomControlMethod":
		return bedrockagentCustomControlMethodValues
	case "CustomSourceType":
		return bedrockagentCustomSourceTypeValues
	case "DataDeletionPolicy":
		return bedrockagentDataDeletionPolicyValues
	case "DataSourceStatus":
		return bedrockagentDataSourceStatusValues
	case "DataSourceType":
		return bedrockagentDataSourceTypeValues
	case "DocumentStatus":
		return bedrockagentDocumentStatusValues
	case "EmbeddingDataType":
		return bedrockagentEmbeddingDataTypeValues
	case "EnrichmentStrategyMethod":
		return bedrockagentEnrichmentStrategyMethodValues
	case "FlowConnectionType":
		return bedrockagentFlowConnectionTypeValues
	case "FlowNodeIODataType":
		return bedrockagentFlowNodeIODataTypeValues
	case "FlowNodeInputCategory":
		return bedrockagentFlowNodeInputCategoryValues
	case "FlowNodeType":
		return bedrockagentFlowNodeTypeValues
	case "FlowStatus":
		return bedrockagentFlowStatusValues
	case "FlowValidationSeverity":
		return bedrockagentFlowValidationSeverityValues
	case "FlowValidationType":
		return bedrockagentFlowValidationTypeValues
	case "IncludeExclude":
		return bedrockagentIncludeExcludeValues
	case "IncompatibleLoopNodeType":
		return bedrockagentIncompatibleLoopNodeTypeValues
	case "IngestionJobFilterAttribute":
		return bedrockagentIngestionJobFilterAttributeValues
	case "IngestionJobFilterOperator":
		return bedrockagentIngestionJobFilterOperatorValues
	case "IngestionJobSortByAttribute":
		return bedrockagentIngestionJobSortByAttributeValues
	case "IngestionJobStatus":
		return bedrockagentIngestionJobStatusValues
	case "InlineContentType":
		return bedrockagentInlineContentTypeValues
	case "KnowledgeBaseState":
		return bedrockagentKnowledgeBaseStateValues
	case "KnowledgeBaseStatus":
		return bedrockagentKnowledgeBaseStatusValues
	case "KnowledgeBaseStorageType":
		return bedrockagentKnowledgeBaseStorageTypeValues
	case "KnowledgeBaseType":
		return bedrockagentKnowledgeBaseTypeValues
	case "MemoryType":
		return bedrockagentMemoryTypeValues
	case "MetadataSourceType":
		return bedrockagentMetadataSourceTypeValues
	case "MetadataValueType":
		return bedrockagentMetadataValueTypeValues
	case "OrchestrationType":
		return bedrockagentOrchestrationTypeValues
	case "ParsingModality":
		return bedrockagentParsingModalityValues
	case "ParsingStrategy":
		return bedrockagentParsingStrategyValues
	case "PerformanceConfigLatency":
		return bedrockagentPerformanceConfigLatencyValues
	case "PromptState":
		return bedrockagentPromptStateValues
	case "PromptTemplateType":
		return bedrockagentPromptTemplateTypeValues
	case "PromptType":
		return bedrockagentPromptTypeValues
	case "QueryEngineType":
		return bedrockagentQueryEngineTypeValues
	case "RedshiftProvisionedAuthType":
		return bedrockagentRedshiftProvisionedAuthTypeValues
	case "RedshiftQueryEngineStorageType":
		return bedrockagentRedshiftQueryEngineStorageTypeValues
	case "RedshiftQueryEngineType":
		return bedrockagentRedshiftQueryEngineTypeValues
	case "RedshiftServerlessAuthType":
		return bedrockagentRedshiftServerlessAuthTypeValues
	case "RelayConversationHistory":
		return bedrockagentRelayConversationHistoryValues
	case "RequireConfirmation":
		return bedrockagentRequireConfirmationValues
	case "RerankingMetadataSelectionMode":
		return bedrockagentRerankingMetadataSelectionModeValues
	case "SalesforceAuthType":
		return bedrockagentSalesforceAuthTypeValues
	case "SharePointAuthType":
		return bedrockagentSharePointAuthTypeValues
	case "SharePointHostType":
		return bedrockagentSharePointHostTypeValues
	case "SortOrder":
		return bedrockagentSortOrderValues
	case "StepType":
		return bedrockagentStepTypeValues
	case "SupplementalDataStorageLocationType":
		return bedrockagentSupplementalDataStorageLocationTypeValues
	case "SupportedLanguages":
		return bedrockagentSupportedLanguagesValues
	case "Type":
		return bedrockagentTypeValues
	case "VectorSearchRerankingConfigurationType":
		return bedrockagentVectorSearchRerankingConfigurationTypeValues
	case "WebScopeType":
		return bedrockagentWebScopeTypeValues
	}
	return nil
}

func getBedrockAgentEnumNames() []string {
	return []string{
		"ActionGroupSignature",
		"ActionGroupState",
		"AgentAliasStatus",
		"AgentCollaboration",
		"AgentStatus",
		"AliasInvocationState",
		"CachePointType",
		"ChunkingStrategy",
		"ConcurrencyType",
		"ConfluenceAuthType",
		"ConfluenceHostType",
		"ContentDataSourceType",
		"ContextEnrichmentType",
		"ConversationRole",
		"CrawlFilterConfigurationType",
		"CreationMode",
		"CustomControlMethod",
		"CustomSourceType",
		"DataDeletionPolicy",
		"DataSourceStatus",
		"DataSourceType",
		"DocumentStatus",
		"EmbeddingDataType",
		"EnrichmentStrategyMethod",
		"FlowConnectionType",
		"FlowNodeIODataType",
		"FlowNodeInputCategory",
		"FlowNodeType",
		"FlowStatus",
		"FlowValidationSeverity",
		"FlowValidationType",
		"IncludeExclude",
		"IncompatibleLoopNodeType",
		"IngestionJobFilterAttribute",
		"IngestionJobFilterOperator",
		"IngestionJobSortByAttribute",
		"IngestionJobStatus",
		"InlineContentType",
		"KnowledgeBaseState",
		"KnowledgeBaseStatus",
		"KnowledgeBaseStorageType",
		"KnowledgeBaseType",
		"MemoryType",
		"MetadataSourceType",
		"MetadataValueType",
		"OrchestrationType",
		"ParsingModality",
		"ParsingStrategy",
		"PerformanceConfigLatency",
		"PromptState",
		"PromptTemplateType",
		"PromptType",
		"QueryEngineType",
		"RedshiftProvisionedAuthType",
		"RedshiftQueryEngineStorageType",
		"RedshiftQueryEngineType",
		"RedshiftServerlessAuthType",
		"RelayConversationHistory",
		"RequireConfirmation",
		"RerankingMetadataSelectionMode",
		"SalesforceAuthType",
		"SharePointAuthType",
		"SharePointHostType",
		"SortOrder",
		"StepType",
		"SupplementalDataStorageLocationType",
		"SupportedLanguages",
		"Type",
		"VectorSearchRerankingConfigurationType",
		"WebScopeType",
	}
}
