// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// ChimeSdkMessaging enum constants
const (
	// AllowNotifications values
	ChimesdkmessagingAllowNotificationsAll      = "ALL"
	ChimesdkmessagingAllowNotificationsNone     = "NONE"
	ChimesdkmessagingAllowNotificationsFiltered = "FILTERED"

	// ChannelMembershipType values
	ChimesdkmessagingChannelMembershipTypeDefault = "DEFAULT"
	ChimesdkmessagingChannelMembershipTypeHidden  = "HIDDEN"

	// ChannelMessagePersistenceType values
	ChimesdkmessagingChannelMessagePersistenceTypePersistent    = "PERSISTENT"
	ChimesdkmessagingChannelMessagePersistenceTypeNonPersistent = "NON_PERSISTENT"

	// ChannelMessageStatus values
	ChimesdkmessagingChannelMessageStatusSent    = "SENT"
	ChimesdkmessagingChannelMessageStatusPending = "PENDING"
	ChimesdkmessagingChannelMessageStatusFailed  = "FAILED"
	ChimesdkmessagingChannelMessageStatusDenied  = "DENIED"

	// ChannelMessageType values
	ChimesdkmessagingChannelMessageTypeStandard = "STANDARD"
	ChimesdkmessagingChannelMessageTypeControl  = "CONTROL"

	// ChannelMode values
	ChimesdkmessagingChannelModeUnrestricted = "UNRESTRICTED"
	ChimesdkmessagingChannelModeRestricted   = "RESTRICTED"

	// ChannelPrivacy values
	ChimesdkmessagingChannelPrivacyPublic  = "PUBLIC"
	ChimesdkmessagingChannelPrivacyPrivate = "PRIVATE"

	// ErrorCode values
	ChimesdkmessagingErrorCodeBadrequest                           = "BadRequest"
	ChimesdkmessagingErrorCodeConflict                             = "Conflict"
	ChimesdkmessagingErrorCodeForbidden                            = "Forbidden"
	ChimesdkmessagingErrorCodeNotfound                             = "NotFound"
	ChimesdkmessagingErrorCodePreconditionfailed                   = "PreconditionFailed"
	ChimesdkmessagingErrorCodeResourcelimitexceeded                = "ResourceLimitExceeded"
	ChimesdkmessagingErrorCodeServicefailure                       = "ServiceFailure"
	ChimesdkmessagingErrorCodeAccessdenied                         = "AccessDenied"
	ChimesdkmessagingErrorCodeServiceunavailable                   = "ServiceUnavailable"
	ChimesdkmessagingErrorCodeThrottled                            = "Throttled"
	ChimesdkmessagingErrorCodeThrottling                           = "Throttling"
	ChimesdkmessagingErrorCodeUnauthorized                         = "Unauthorized"
	ChimesdkmessagingErrorCodeUnprocessable                        = "Unprocessable"
	ChimesdkmessagingErrorCodeVoiceconnectorgroupassociationsexist = "VoiceConnectorGroupAssociationsExist"
	ChimesdkmessagingErrorCodePhonenumberassociationsexist         = "PhoneNumberAssociationsExist"

	// ExpirationCriterion values
	ChimesdkmessagingExpirationCriterionCreatedTimestamp     = "CREATED_TIMESTAMP"
	ChimesdkmessagingExpirationCriterionLastMessageTimestamp = "LAST_MESSAGE_TIMESTAMP"

	// FallbackAction values
	ChimesdkmessagingFallbackActionContinue = "CONTINUE"
	ChimesdkmessagingFallbackActionAbort    = "ABORT"

	// InvocationType values
	ChimesdkmessagingInvocationTypeAsync = "ASYNC"

	// MessagingDataType values
	ChimesdkmessagingMessagingDataTypeChannel        = "Channel"
	ChimesdkmessagingMessagingDataTypeChannelmessage = "ChannelMessage"

	// NetworkType values
	ChimesdkmessagingNetworkTypeIpv4Only  = "IPV4_ONLY"
	ChimesdkmessagingNetworkTypeDualStack = "DUAL_STACK"

	// PushNotificationType values
	ChimesdkmessagingPushNotificationTypeDefault = "DEFAULT"
	ChimesdkmessagingPushNotificationTypeVoip    = "VOIP"

	// SearchFieldKey values
	ChimesdkmessagingSearchFieldKeyMembers = "MEMBERS"

	// SearchFieldOperator values
	ChimesdkmessagingSearchFieldOperatorEquals   = "EQUALS"
	ChimesdkmessagingSearchFieldOperatorIncludes = "INCLUDES"

	// SortOrder values
	ChimesdkmessagingSortOrderAscending  = "ASCENDING"
	ChimesdkmessagingSortOrderDescending = "DESCENDING"
)

var chimesdkmessagingAllowNotificationsValues = []string{
	"ALL",
	"NONE",
	"FILTERED",
}

var chimesdkmessagingChannelMembershipTypeValues = []string{
	"DEFAULT",
	"HIDDEN",
}

var chimesdkmessagingChannelMessagePersistenceTypeValues = []string{
	"PERSISTENT",
	"NON_PERSISTENT",
}

var chimesdkmessagingChannelMessageStatusValues = []string{
	"SENT",
	"PENDING",
	"FAILED",
	"DENIED",
}

var chimesdkmessagingChannelMessageTypeValues = []string{
	"STANDARD",
	"CONTROL",
}

var chimesdkmessagingChannelModeValues = []string{
	"UNRESTRICTED",
	"RESTRICTED",
}

var chimesdkmessagingChannelPrivacyValues = []string{
	"PUBLIC",
	"PRIVATE",
}

var chimesdkmessagingErrorCodeValues = []string{
	"BadRequest",
	"Conflict",
	"Forbidden",
	"NotFound",
	"PreconditionFailed",
	"ResourceLimitExceeded",
	"ServiceFailure",
	"AccessDenied",
	"ServiceUnavailable",
	"Throttled",
	"Throttling",
	"Unauthorized",
	"Unprocessable",
	"VoiceConnectorGroupAssociationsExist",
	"PhoneNumberAssociationsExist",
}

var chimesdkmessagingExpirationCriterionValues = []string{
	"CREATED_TIMESTAMP",
	"LAST_MESSAGE_TIMESTAMP",
}

var chimesdkmessagingFallbackActionValues = []string{
	"CONTINUE",
	"ABORT",
}

var chimesdkmessagingInvocationTypeValues = []string{
	"ASYNC",
}

var chimesdkmessagingMessagingDataTypeValues = []string{
	"Channel",
	"ChannelMessage",
}

var chimesdkmessagingNetworkTypeValues = []string{
	"IPV4_ONLY",
	"DUAL_STACK",
}

var chimesdkmessagingPushNotificationTypeValues = []string{
	"DEFAULT",
	"VOIP",
}

var chimesdkmessagingSearchFieldKeyValues = []string{
	"MEMBERS",
}

var chimesdkmessagingSearchFieldOperatorValues = []string{
	"EQUALS",
	"INCLUDES",
}

var chimesdkmessagingSortOrderValues = []string{
	"ASCENDING",
	"DESCENDING",
}

func getChimeSdkMessagingEnum(name string) []string {
	switch name {
	case "AllowNotifications":
		return chimesdkmessagingAllowNotificationsValues
	case "ChannelMembershipType":
		return chimesdkmessagingChannelMembershipTypeValues
	case "ChannelMessagePersistenceType":
		return chimesdkmessagingChannelMessagePersistenceTypeValues
	case "ChannelMessageStatus":
		return chimesdkmessagingChannelMessageStatusValues
	case "ChannelMessageType":
		return chimesdkmessagingChannelMessageTypeValues
	case "ChannelMode":
		return chimesdkmessagingChannelModeValues
	case "ChannelPrivacy":
		return chimesdkmessagingChannelPrivacyValues
	case "ErrorCode":
		return chimesdkmessagingErrorCodeValues
	case "ExpirationCriterion":
		return chimesdkmessagingExpirationCriterionValues
	case "FallbackAction":
		return chimesdkmessagingFallbackActionValues
	case "InvocationType":
		return chimesdkmessagingInvocationTypeValues
	case "MessagingDataType":
		return chimesdkmessagingMessagingDataTypeValues
	case "NetworkType":
		return chimesdkmessagingNetworkTypeValues
	case "PushNotificationType":
		return chimesdkmessagingPushNotificationTypeValues
	case "SearchFieldKey":
		return chimesdkmessagingSearchFieldKeyValues
	case "SearchFieldOperator":
		return chimesdkmessagingSearchFieldOperatorValues
	case "SortOrder":
		return chimesdkmessagingSortOrderValues
	}
	return nil
}

func getChimeSdkMessagingEnumNames() []string {
	return []string{
		"AllowNotifications",
		"ChannelMembershipType",
		"ChannelMessagePersistenceType",
		"ChannelMessageStatus",
		"ChannelMessageType",
		"ChannelMode",
		"ChannelPrivacy",
		"ErrorCode",
		"ExpirationCriterion",
		"FallbackAction",
		"InvocationType",
		"MessagingDataType",
		"NetworkType",
		"PushNotificationType",
		"SearchFieldKey",
		"SearchFieldOperator",
		"SortOrder",
	}
}
