// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Cleanroomsml enum constants
const (
	// AccessBudgetType values
	CleanroomsmlAccessBudgetTypeCalendarDay   = "CALENDAR_DAY"
	CleanroomsmlAccessBudgetTypeCalendarMonth = "CALENDAR_MONTH"
	CleanroomsmlAccessBudgetTypeCalendarWeek  = "CALENDAR_WEEK"
	CleanroomsmlAccessBudgetTypeLifetime      = "LIFETIME"

	// AudienceExportJobStatus values
	CleanroomsmlAudienceExportJobStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlAudienceExportJobStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlAudienceExportJobStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlAudienceExportJobStatusActive           = "ACTIVE"

	// AudienceGenerationJobStatus values
	CleanroomsmlAudienceGenerationJobStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlAudienceGenerationJobStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlAudienceGenerationJobStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlAudienceGenerationJobStatusActive           = "ACTIVE"
	CleanroomsmlAudienceGenerationJobStatusDeletePending    = "DELETE_PENDING"
	CleanroomsmlAudienceGenerationJobStatusDeleteInProgress = "DELETE_IN_PROGRESS"
	CleanroomsmlAudienceGenerationJobStatusDeleteFailed     = "DELETE_FAILED"

	// AudienceModelStatus values
	CleanroomsmlAudienceModelStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlAudienceModelStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlAudienceModelStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlAudienceModelStatusActive           = "ACTIVE"
	CleanroomsmlAudienceModelStatusDeletePending    = "DELETE_PENDING"
	CleanroomsmlAudienceModelStatusDeleteInProgress = "DELETE_IN_PROGRESS"
	CleanroomsmlAudienceModelStatusDeleteFailed     = "DELETE_FAILED"

	// AudienceSizeType values
	CleanroomsmlAudienceSizeTypeAbsolute   = "ABSOLUTE"
	CleanroomsmlAudienceSizeTypePercentage = "PERCENTAGE"

	// AutoRefreshMode values
	CleanroomsmlAutoRefreshModeEnabled  = "ENABLED"
	CleanroomsmlAutoRefreshModeDisabled = "DISABLED"

	// ColumnType values
	CleanroomsmlColumnTypeUserId             = "USER_ID"
	CleanroomsmlColumnTypeItemId             = "ITEM_ID"
	CleanroomsmlColumnTypeTimestamp          = "TIMESTAMP"
	CleanroomsmlColumnTypeCategoricalFeature = "CATEGORICAL_FEATURE"
	CleanroomsmlColumnTypeNumericalFeature   = "NUMERICAL_FEATURE"

	// ConfiguredAudienceModelStatus values
	CleanroomsmlConfiguredAudienceModelStatusActive = "ACTIVE"

	// DatasetType values
	CleanroomsmlDatasetTypeInteractions = "INTERACTIONS"

	// EntityType values
	CleanroomsmlEntityTypeAllPersonallyIdentifiableInformation = "ALL_PERSONALLY_IDENTIFIABLE_INFORMATION"
	CleanroomsmlEntityTypeNumbers                              = "NUMBERS"
	CleanroomsmlEntityTypeCustom                               = "CUSTOM"

	// InferenceInstanceType values
	CleanroomsmlInferenceInstanceTypeMlR7i48xlarge  = "ml.r7i.48xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i16xlarge  = "ml.r6i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6iXlarge    = "ml.m6i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlM54xlarge    = "ml.m5.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlP2Xlarge     = "ml.p2.xlarge"
	CleanroomsmlInferenceInstanceTypeMlM416xlarge   = "ml.m4.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i16xlarge  = "ml.r7i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7iXlarge    = "ml.m7i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i12xlarge  = "ml.m6i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i8xlarge   = "ml.r7i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7iLarge     = "ml.r7i.large"
	CleanroomsmlInferenceInstanceTypeMlM7i12xlarge  = "ml.m7i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i24xlarge  = "ml.m6i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7i24xlarge  = "ml.m7i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i8xlarge   = "ml.r6i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6iLarge     = "ml.r6i.large"
	CleanroomsmlInferenceInstanceTypeMlG52xlarge    = "ml.g5.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlM5Large      = "ml.m5.large"
	CleanroomsmlInferenceInstanceTypeMlM7i48xlarge  = "ml.m7i.48xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i16xlarge  = "ml.m6i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlP216xlarge   = "ml.p2.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlG54xlarge    = "ml.g5.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7i16xlarge  = "ml.m7i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlC42xlarge    = "ml.c4.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlC52xlarge    = "ml.c5.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i32xlarge  = "ml.c6i.32xlarge"
	CleanroomsmlInferenceInstanceTypeMlC44xlarge    = "ml.c4.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlG58xlarge    = "ml.g5.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6iXlarge    = "ml.c6i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlC54xlarge    = "ml.c5.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dnXlarge   = "ml.g4dn.xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7iXlarge    = "ml.c7i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i12xlarge  = "ml.c6i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dn12xlarge = "ml.g4dn.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i12xlarge  = "ml.c7i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i24xlarge  = "ml.c6i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dn2xlarge  = "ml.g4dn.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i24xlarge  = "ml.c7i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i2xlarge   = "ml.c7i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlC48xlarge    = "ml.c4.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i2xlarge   = "ml.c6i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dn4xlarge  = "ml.g4dn.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i48xlarge  = "ml.c7i.48xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i4xlarge   = "ml.c7i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i16xlarge  = "ml.c6i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlC59xlarge    = "ml.c5.9xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dn16xlarge = "ml.g4dn.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i16xlarge  = "ml.c7i.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i4xlarge   = "ml.c6i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlC5Xlarge     = "ml.c5.xlarge"
	CleanroomsmlInferenceInstanceTypeMlC4Xlarge     = "ml.c4.xlarge"
	CleanroomsmlInferenceInstanceTypeMlG4dn8xlarge  = "ml.g4dn.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7i8xlarge   = "ml.c7i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlC7iLarge     = "ml.c7i.large"
	CleanroomsmlInferenceInstanceTypeMlG5Xlarge     = "ml.g5.xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6i8xlarge   = "ml.c6i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlC6iLarge     = "ml.c6i.large"
	CleanroomsmlInferenceInstanceTypeMlG512xlarge   = "ml.g5.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlG524xlarge   = "ml.g5.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7i2xlarge   = "ml.m7i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlC518xlarge   = "ml.c5.18xlarge"
	CleanroomsmlInferenceInstanceTypeMlG548xlarge   = "ml.g5.48xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i2xlarge   = "ml.m6i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlG516xlarge   = "ml.g5.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7i4xlarge   = "ml.m7i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i32xlarge  = "ml.r6i.32xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i4xlarge   = "ml.m6i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlM5Xlarge     = "ml.m5.xlarge"
	CleanroomsmlInferenceInstanceTypeMlM410xlarge   = "ml.m4.10xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6iXlarge    = "ml.r6i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlM512xlarge   = "ml.m5.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlM4Xlarge     = "ml.m4.xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i2xlarge   = "ml.r7i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7iXlarge    = "ml.r7i.xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i12xlarge  = "ml.r6i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlM524xlarge   = "ml.m5.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i12xlarge  = "ml.r7i.12xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7i8xlarge   = "ml.m7i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlM7iLarge     = "ml.m7i.large"
	CleanroomsmlInferenceInstanceTypeMlR6i24xlarge  = "ml.r6i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i2xlarge   = "ml.r6i.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlM42xlarge    = "ml.m4.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i24xlarge  = "ml.r7i.24xlarge"
	CleanroomsmlInferenceInstanceTypeMlR7i4xlarge   = "ml.r7i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i8xlarge   = "ml.m6i.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6iLarge     = "ml.m6i.large"
	CleanroomsmlInferenceInstanceTypeMlM52xlarge    = "ml.m5.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlP28xlarge    = "ml.p2.8xlarge"
	CleanroomsmlInferenceInstanceTypeMlR6i4xlarge   = "ml.r6i.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlM6i32xlarge  = "ml.m6i.32xlarge"
	CleanroomsmlInferenceInstanceTypeMlM44xlarge    = "ml.m4.4xlarge"
	CleanroomsmlInferenceInstanceTypeMlP316xlarge   = "ml.p3.16xlarge"
	CleanroomsmlInferenceInstanceTypeMlP32xlarge    = "ml.p3.2xlarge"
	CleanroomsmlInferenceInstanceTypeMlP38xlarge    = "ml.p3.8xlarge"

	// InstanceType values
	CleanroomsmlInstanceTypeMlM4Xlarge      = "ml.m4.xlarge"
	CleanroomsmlInstanceTypeMlM42xlarge     = "ml.m4.2xlarge"
	CleanroomsmlInstanceTypeMlM44xlarge     = "ml.m4.4xlarge"
	CleanroomsmlInstanceTypeMlM410xlarge    = "ml.m4.10xlarge"
	CleanroomsmlInstanceTypeMlM416xlarge    = "ml.m4.16xlarge"
	CleanroomsmlInstanceTypeMlG4dnXlarge    = "ml.g4dn.xlarge"
	CleanroomsmlInstanceTypeMlG4dn2xlarge   = "ml.g4dn.2xlarge"
	CleanroomsmlInstanceTypeMlG4dn4xlarge   = "ml.g4dn.4xlarge"
	CleanroomsmlInstanceTypeMlG4dn8xlarge   = "ml.g4dn.8xlarge"
	CleanroomsmlInstanceTypeMlG4dn12xlarge  = "ml.g4dn.12xlarge"
	CleanroomsmlInstanceTypeMlG4dn16xlarge  = "ml.g4dn.16xlarge"
	CleanroomsmlInstanceTypeMlM5Large       = "ml.m5.large"
	CleanroomsmlInstanceTypeMlM5Xlarge      = "ml.m5.xlarge"
	CleanroomsmlInstanceTypeMlM52xlarge     = "ml.m5.2xlarge"
	CleanroomsmlInstanceTypeMlM54xlarge     = "ml.m5.4xlarge"
	CleanroomsmlInstanceTypeMlM512xlarge    = "ml.m5.12xlarge"
	CleanroomsmlInstanceTypeMlM524xlarge    = "ml.m5.24xlarge"
	CleanroomsmlInstanceTypeMlC4Xlarge      = "ml.c4.xlarge"
	CleanroomsmlInstanceTypeMlC42xlarge     = "ml.c4.2xlarge"
	CleanroomsmlInstanceTypeMlC44xlarge     = "ml.c4.4xlarge"
	CleanroomsmlInstanceTypeMlC48xlarge     = "ml.c4.8xlarge"
	CleanroomsmlInstanceTypeMlP2Xlarge      = "ml.p2.xlarge"
	CleanroomsmlInstanceTypeMlP28xlarge     = "ml.p2.8xlarge"
	CleanroomsmlInstanceTypeMlP216xlarge    = "ml.p2.16xlarge"
	CleanroomsmlInstanceTypeMlP4d24xlarge   = "ml.p4d.24xlarge"
	CleanroomsmlInstanceTypeMlP4de24xlarge  = "ml.p4de.24xlarge"
	CleanroomsmlInstanceTypeMlP548xlarge    = "ml.p5.48xlarge"
	CleanroomsmlInstanceTypeMlC5Xlarge      = "ml.c5.xlarge"
	CleanroomsmlInstanceTypeMlC52xlarge     = "ml.c5.2xlarge"
	CleanroomsmlInstanceTypeMlC54xlarge     = "ml.c5.4xlarge"
	CleanroomsmlInstanceTypeMlC59xlarge     = "ml.c5.9xlarge"
	CleanroomsmlInstanceTypeMlC518xlarge    = "ml.c5.18xlarge"
	CleanroomsmlInstanceTypeMlC5nXlarge     = "ml.c5n.xlarge"
	CleanroomsmlInstanceTypeMlC5n2xlarge    = "ml.c5n.2xlarge"
	CleanroomsmlInstanceTypeMlC5n4xlarge    = "ml.c5n.4xlarge"
	CleanroomsmlInstanceTypeMlC5n9xlarge    = "ml.c5n.9xlarge"
	CleanroomsmlInstanceTypeMlC5n18xlarge   = "ml.c5n.18xlarge"
	CleanroomsmlInstanceTypeMlG5Xlarge      = "ml.g5.xlarge"
	CleanroomsmlInstanceTypeMlG52xlarge     = "ml.g5.2xlarge"
	CleanroomsmlInstanceTypeMlG54xlarge     = "ml.g5.4xlarge"
	CleanroomsmlInstanceTypeMlG58xlarge     = "ml.g5.8xlarge"
	CleanroomsmlInstanceTypeMlG516xlarge    = "ml.g5.16xlarge"
	CleanroomsmlInstanceTypeMlG512xlarge    = "ml.g5.12xlarge"
	CleanroomsmlInstanceTypeMlG524xlarge    = "ml.g5.24xlarge"
	CleanroomsmlInstanceTypeMlG548xlarge    = "ml.g5.48xlarge"
	CleanroomsmlInstanceTypeMlTrn12xlarge   = "ml.trn1.2xlarge"
	CleanroomsmlInstanceTypeMlTrn132xlarge  = "ml.trn1.32xlarge"
	CleanroomsmlInstanceTypeMlTrn1n32xlarge = "ml.trn1n.32xlarge"
	CleanroomsmlInstanceTypeMlM6iLarge      = "ml.m6i.large"
	CleanroomsmlInstanceTypeMlM6iXlarge     = "ml.m6i.xlarge"
	CleanroomsmlInstanceTypeMlM6i2xlarge    = "ml.m6i.2xlarge"
	CleanroomsmlInstanceTypeMlM6i4xlarge    = "ml.m6i.4xlarge"
	CleanroomsmlInstanceTypeMlM6i8xlarge    = "ml.m6i.8xlarge"
	CleanroomsmlInstanceTypeMlM6i12xlarge   = "ml.m6i.12xlarge"
	CleanroomsmlInstanceTypeMlM6i16xlarge   = "ml.m6i.16xlarge"
	CleanroomsmlInstanceTypeMlM6i24xlarge   = "ml.m6i.24xlarge"
	CleanroomsmlInstanceTypeMlM6i32xlarge   = "ml.m6i.32xlarge"
	CleanroomsmlInstanceTypeMlC6iXlarge     = "ml.c6i.xlarge"
	CleanroomsmlInstanceTypeMlC6i2xlarge    = "ml.c6i.2xlarge"
	CleanroomsmlInstanceTypeMlC6i8xlarge    = "ml.c6i.8xlarge"
	CleanroomsmlInstanceTypeMlC6i4xlarge    = "ml.c6i.4xlarge"
	CleanroomsmlInstanceTypeMlC6i12xlarge   = "ml.c6i.12xlarge"
	CleanroomsmlInstanceTypeMlC6i16xlarge   = "ml.c6i.16xlarge"
	CleanroomsmlInstanceTypeMlC6i24xlarge   = "ml.c6i.24xlarge"
	CleanroomsmlInstanceTypeMlC6i32xlarge   = "ml.c6i.32xlarge"
	CleanroomsmlInstanceTypeMlR5dLarge      = "ml.r5d.large"
	CleanroomsmlInstanceTypeMlR5dXlarge     = "ml.r5d.xlarge"
	CleanroomsmlInstanceTypeMlR5d2xlarge    = "ml.r5d.2xlarge"
	CleanroomsmlInstanceTypeMlR5d4xlarge    = "ml.r5d.4xlarge"
	CleanroomsmlInstanceTypeMlR5d8xlarge    = "ml.r5d.8xlarge"
	CleanroomsmlInstanceTypeMlR5d12xlarge   = "ml.r5d.12xlarge"
	CleanroomsmlInstanceTypeMlR5d16xlarge   = "ml.r5d.16xlarge"
	CleanroomsmlInstanceTypeMlR5d24xlarge   = "ml.r5d.24xlarge"
	CleanroomsmlInstanceTypeMlT3Medium      = "ml.t3.medium"
	CleanroomsmlInstanceTypeMlT3Large       = "ml.t3.large"
	CleanroomsmlInstanceTypeMlT3Xlarge      = "ml.t3.xlarge"
	CleanroomsmlInstanceTypeMlT32xlarge     = "ml.t3.2xlarge"
	CleanroomsmlInstanceTypeMlR5Large       = "ml.r5.large"
	CleanroomsmlInstanceTypeMlR5Xlarge      = "ml.r5.xlarge"
	CleanroomsmlInstanceTypeMlR52xlarge     = "ml.r5.2xlarge"
	CleanroomsmlInstanceTypeMlR54xlarge     = "ml.r5.4xlarge"
	CleanroomsmlInstanceTypeMlR58xlarge     = "ml.r5.8xlarge"
	CleanroomsmlInstanceTypeMlR512xlarge    = "ml.r5.12xlarge"
	CleanroomsmlInstanceTypeMlR516xlarge    = "ml.r5.16xlarge"
	CleanroomsmlInstanceTypeMlR524xlarge    = "ml.r5.24xlarge"
	CleanroomsmlInstanceTypeMlC7iLarge      = "ml.c7i.large"
	CleanroomsmlInstanceTypeMlC7iXlarge     = "ml.c7i.xlarge"
	CleanroomsmlInstanceTypeMlC7i2xlarge    = "ml.c7i.2xlarge"
	CleanroomsmlInstanceTypeMlC7i4xlarge    = "ml.c7i.4xlarge"
	CleanroomsmlInstanceTypeMlC7i8xlarge    = "ml.c7i.8xlarge"
	CleanroomsmlInstanceTypeMlC7i12xlarge   = "ml.c7i.12xlarge"
	CleanroomsmlInstanceTypeMlC7i16xlarge   = "ml.c7i.16xlarge"
	CleanroomsmlInstanceTypeMlC7i24xlarge   = "ml.c7i.24xlarge"
	CleanroomsmlInstanceTypeMlC7i48xlarge   = "ml.c7i.48xlarge"
	CleanroomsmlInstanceTypeMlM7iLarge      = "ml.m7i.large"
	CleanroomsmlInstanceTypeMlM7iXlarge     = "ml.m7i.xlarge"
	CleanroomsmlInstanceTypeMlM7i2xlarge    = "ml.m7i.2xlarge"
	CleanroomsmlInstanceTypeMlM7i4xlarge    = "ml.m7i.4xlarge"
	CleanroomsmlInstanceTypeMlM7i8xlarge    = "ml.m7i.8xlarge"
	CleanroomsmlInstanceTypeMlM7i12xlarge   = "ml.m7i.12xlarge"
	CleanroomsmlInstanceTypeMlM7i16xlarge   = "ml.m7i.16xlarge"
	CleanroomsmlInstanceTypeMlM7i24xlarge   = "ml.m7i.24xlarge"
	CleanroomsmlInstanceTypeMlM7i48xlarge   = "ml.m7i.48xlarge"
	CleanroomsmlInstanceTypeMlR7iLarge      = "ml.r7i.large"
	CleanroomsmlInstanceTypeMlR7iXlarge     = "ml.r7i.xlarge"
	CleanroomsmlInstanceTypeMlR7i2xlarge    = "ml.r7i.2xlarge"
	CleanroomsmlInstanceTypeMlR7i4xlarge    = "ml.r7i.4xlarge"
	CleanroomsmlInstanceTypeMlR7i8xlarge    = "ml.r7i.8xlarge"
	CleanroomsmlInstanceTypeMlR7i12xlarge   = "ml.r7i.12xlarge"
	CleanroomsmlInstanceTypeMlR7i16xlarge   = "ml.r7i.16xlarge"
	CleanroomsmlInstanceTypeMlR7i24xlarge   = "ml.r7i.24xlarge"
	CleanroomsmlInstanceTypeMlR7i48xlarge   = "ml.r7i.48xlarge"
	CleanroomsmlInstanceTypeMlG6Xlarge      = "ml.g6.xlarge"
	CleanroomsmlInstanceTypeMlG62xlarge     = "ml.g6.2xlarge"
	CleanroomsmlInstanceTypeMlG64xlarge     = "ml.g6.4xlarge"
	CleanroomsmlInstanceTypeMlG68xlarge     = "ml.g6.8xlarge"
	CleanroomsmlInstanceTypeMlG612xlarge    = "ml.g6.12xlarge"
	CleanroomsmlInstanceTypeMlG616xlarge    = "ml.g6.16xlarge"
	CleanroomsmlInstanceTypeMlG624xlarge    = "ml.g6.24xlarge"
	CleanroomsmlInstanceTypeMlG648xlarge    = "ml.g6.48xlarge"
	CleanroomsmlInstanceTypeMlG6eXlarge     = "ml.g6e.xlarge"
	CleanroomsmlInstanceTypeMlG6e2xlarge    = "ml.g6e.2xlarge"
	CleanroomsmlInstanceTypeMlG6e4xlarge    = "ml.g6e.4xlarge"
	CleanroomsmlInstanceTypeMlG6e8xlarge    = "ml.g6e.8xlarge"
	CleanroomsmlInstanceTypeMlG6e12xlarge   = "ml.g6e.12xlarge"
	CleanroomsmlInstanceTypeMlG6e16xlarge   = "ml.g6e.16xlarge"
	CleanroomsmlInstanceTypeMlG6e24xlarge   = "ml.g6e.24xlarge"
	CleanroomsmlInstanceTypeMlG6e48xlarge   = "ml.g6e.48xlarge"
	CleanroomsmlInstanceTypeMlP5en48xlarge  = "ml.p5en.48xlarge"
	CleanroomsmlInstanceTypeMlP32xlarge     = "ml.p3.2xlarge"
	CleanroomsmlInstanceTypeMlP38xlarge     = "ml.p3.8xlarge"
	CleanroomsmlInstanceTypeMlP316xlarge    = "ml.p3.16xlarge"
	CleanroomsmlInstanceTypeMlP3dn24xlarge  = "ml.p3dn.24xlarge"

	// LogType values
	CleanroomsmlLogTypeAll          = "ALL"
	CleanroomsmlLogTypeErrorSummary = "ERROR_SUMMARY"

	// LogsStatus values
	CleanroomsmlLogsStatusPublishSucceeded = "PUBLISH_SUCCEEDED"
	CleanroomsmlLogsStatusPublishFailed    = "PUBLISH_FAILED"

	// MLInputChannelStatus values
	CleanroomsmlMLInputChannelStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlMLInputChannelStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlMLInputChannelStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlMLInputChannelStatusActive           = "ACTIVE"
	CleanroomsmlMLInputChannelStatusDeletePending    = "DELETE_PENDING"
	CleanroomsmlMLInputChannelStatusDeleteInProgress = "DELETE_IN_PROGRESS"
	CleanroomsmlMLInputChannelStatusDeleteFailed     = "DELETE_FAILED"
	CleanroomsmlMLInputChannelStatusInactive         = "INACTIVE"

	// MembershipInferenceAttackVersion values
	CleanroomsmlMembershipInferenceAttackVersionDistanceToClosestRecordV1 = "DISTANCE_TO_CLOSEST_RECORD_V1"

	// MetricsStatus values
	CleanroomsmlMetricsStatusPublishSucceeded = "PUBLISH_SUCCEEDED"
	CleanroomsmlMetricsStatusPublishFailed    = "PUBLISH_FAILED"

	// NoiseLevelType values
	CleanroomsmlNoiseLevelTypeHigh   = "HIGH"
	CleanroomsmlNoiseLevelTypeMedium = "MEDIUM"
	CleanroomsmlNoiseLevelTypeLow    = "LOW"
	CleanroomsmlNoiseLevelTypeNone   = "NONE"

	// PolicyExistenceCondition values
	CleanroomsmlPolicyExistenceConditionPolicyMustExist    = "POLICY_MUST_EXIST"
	CleanroomsmlPolicyExistenceConditionPolicyMustNotExist = "POLICY_MUST_NOT_EXIST"

	// ResultFormat values
	CleanroomsmlResultFormatCsv     = "CSV"
	CleanroomsmlResultFormatParquet = "PARQUET"

	// S3DataDistributionType values
	CleanroomsmlS3DataDistributionTypeFullyreplicated = "FullyReplicated"
	CleanroomsmlS3DataDistributionTypeShardedbys3key  = "ShardedByS3Key"

	// SharedAudienceMetrics values
	CleanroomsmlSharedAudienceMetricsAll  = "ALL"
	CleanroomsmlSharedAudienceMetricsNone = "NONE"

	// SyntheticDataColumnType values
	CleanroomsmlSyntheticDataColumnTypeCategorical = "CATEGORICAL"
	CleanroomsmlSyntheticDataColumnTypeNumerical   = "NUMERICAL"

	// TagOnCreatePolicy values
	CleanroomsmlTagOnCreatePolicyFromParentResource = "FROM_PARENT_RESOURCE"
	CleanroomsmlTagOnCreatePolicyNone               = "NONE"

	// TrainedModelArtifactMaxSizeUnitType values
	CleanroomsmlTrainedModelArtifactMaxSizeUnitTypeGb = "GB"

	// TrainedModelExportFileType values
	CleanroomsmlTrainedModelExportFileTypeModel  = "MODEL"
	CleanroomsmlTrainedModelExportFileTypeOutput = "OUTPUT"

	// TrainedModelExportJobStatus values
	CleanroomsmlTrainedModelExportJobStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlTrainedModelExportJobStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlTrainedModelExportJobStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlTrainedModelExportJobStatusActive           = "ACTIVE"

	// TrainedModelExportsMaxSizeUnitType values
	CleanroomsmlTrainedModelExportsMaxSizeUnitTypeGb = "GB"

	// TrainedModelInferenceJobStatus values
	CleanroomsmlTrainedModelInferenceJobStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlTrainedModelInferenceJobStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlTrainedModelInferenceJobStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlTrainedModelInferenceJobStatusActive           = "ACTIVE"
	CleanroomsmlTrainedModelInferenceJobStatusCancelPending    = "CANCEL_PENDING"
	CleanroomsmlTrainedModelInferenceJobStatusCancelInProgress = "CANCEL_IN_PROGRESS"
	CleanroomsmlTrainedModelInferenceJobStatusCancelFailed     = "CANCEL_FAILED"
	CleanroomsmlTrainedModelInferenceJobStatusInactive         = "INACTIVE"

	// TrainedModelInferenceMaxOutputSizeUnitType values
	CleanroomsmlTrainedModelInferenceMaxOutputSizeUnitTypeGb = "GB"

	// TrainedModelStatus values
	CleanroomsmlTrainedModelStatusCreatePending    = "CREATE_PENDING"
	CleanroomsmlTrainedModelStatusCreateInProgress = "CREATE_IN_PROGRESS"
	CleanroomsmlTrainedModelStatusCreateFailed     = "CREATE_FAILED"
	CleanroomsmlTrainedModelStatusActive           = "ACTIVE"
	CleanroomsmlTrainedModelStatusDeletePending    = "DELETE_PENDING"
	CleanroomsmlTrainedModelStatusDeleteInProgress = "DELETE_IN_PROGRESS"
	CleanroomsmlTrainedModelStatusDeleteFailed     = "DELETE_FAILED"
	CleanroomsmlTrainedModelStatusInactive         = "INACTIVE"
	CleanroomsmlTrainedModelStatusCancelPending    = "CANCEL_PENDING"
	CleanroomsmlTrainedModelStatusCancelInProgress = "CANCEL_IN_PROGRESS"
	CleanroomsmlTrainedModelStatusCancelFailed     = "CANCEL_FAILED"

	// TrainingDatasetStatus values
	CleanroomsmlTrainingDatasetStatusActive = "ACTIVE"

	// TrainingInputMode values
	CleanroomsmlTrainingInputModeFile     = "File"
	CleanroomsmlTrainingInputModeFastfile = "FastFile"
	CleanroomsmlTrainingInputModePipe     = "Pipe"

	// WorkerComputeType values
	CleanroomsmlWorkerComputeTypeCr1x = "CR.1X"
	CleanroomsmlWorkerComputeTypeCr4x = "CR.4X"
)

var cleanroomsmlAccessBudgetTypeValues = []string{
	"CALENDAR_DAY",
	"CALENDAR_MONTH",
	"CALENDAR_WEEK",
	"LIFETIME",
}

var cleanroomsmlAudienceExportJobStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
}

var cleanroomsmlAudienceGenerationJobStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
	"DELETE_PENDING",
	"DELETE_IN_PROGRESS",
	"DELETE_FAILED",
}

var cleanroomsmlAudienceModelStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
	"DELETE_PENDING",
	"DELETE_IN_PROGRESS",
	"DELETE_FAILED",
}

var cleanroomsmlAudienceSizeTypeValues = []string{
	"ABSOLUTE",
	"PERCENTAGE",
}

var cleanroomsmlAutoRefreshModeValues = []string{
	"ENABLED",
	"DISABLED",
}

var cleanroomsmlColumnTypeValues = []string{
	"USER_ID",
	"ITEM_ID",
	"TIMESTAMP",
	"CATEGORICAL_FEATURE",
	"NUMERICAL_FEATURE",
}

var cleanroomsmlConfiguredAudienceModelStatusValues = []string{
	"ACTIVE",
}

var cleanroomsmlDatasetTypeValues = []string{
	"INTERACTIONS",
}

var cleanroomsmlEntityTypeValues = []string{
	"ALL_PERSONALLY_IDENTIFIABLE_INFORMATION",
	"NUMBERS",
	"CUSTOM",
}

var cleanroomsmlInferenceInstanceTypeValues = []string{
	"ml.r7i.48xlarge",
	"ml.r6i.16xlarge",
	"ml.m6i.xlarge",
	"ml.m5.4xlarge",
	"ml.p2.xlarge",
	"ml.m4.16xlarge",
	"ml.r7i.16xlarge",
	"ml.m7i.xlarge",
	"ml.m6i.12xlarge",
	"ml.r7i.8xlarge",
	"ml.r7i.large",
	"ml.m7i.12xlarge",
	"ml.m6i.24xlarge",
	"ml.m7i.24xlarge",
	"ml.r6i.8xlarge",
	"ml.r6i.large",
	"ml.g5.2xlarge",
	"ml.m5.large",
	"ml.m7i.48xlarge",
	"ml.m6i.16xlarge",
	"ml.p2.16xlarge",
	"ml.g5.4xlarge",
	"ml.m7i.16xlarge",
	"ml.c4.2xlarge",
	"ml.c5.2xlarge",
	"ml.c6i.32xlarge",
	"ml.c4.4xlarge",
	"ml.g5.8xlarge",
	"ml.c6i.xlarge",
	"ml.c5.4xlarge",
	"ml.g4dn.xlarge",
	"ml.c7i.xlarge",
	"ml.c6i.12xlarge",
	"ml.g4dn.12xlarge",
	"ml.c7i.12xlarge",
	"ml.c6i.24xlarge",
	"ml.g4dn.2xlarge",
	"ml.c7i.24xlarge",
	"ml.c7i.2xlarge",
	"ml.c4.8xlarge",
	"ml.c6i.2xlarge",
	"ml.g4dn.4xlarge",
	"ml.c7i.48xlarge",
	"ml.c7i.4xlarge",
	"ml.c6i.16xlarge",
	"ml.c5.9xlarge",
	"ml.g4dn.16xlarge",
	"ml.c7i.16xlarge",
	"ml.c6i.4xlarge",
	"ml.c5.xlarge",
	"ml.c4.xlarge",
	"ml.g4dn.8xlarge",
	"ml.c7i.8xlarge",
	"ml.c7i.large",
	"ml.g5.xlarge",
	"ml.c6i.8xlarge",
	"ml.c6i.large",
	"ml.g5.12xlarge",
	"ml.g5.24xlarge",
	"ml.m7i.2xlarge",
	"ml.c5.18xlarge",
	"ml.g5.48xlarge",
	"ml.m6i.2xlarge",
	"ml.g5.16xlarge",
	"ml.m7i.4xlarge",
	"ml.r6i.32xlarge",
	"ml.m6i.4xlarge",
	"ml.m5.xlarge",
	"ml.m4.10xlarge",
	"ml.r6i.xlarge",
	"ml.m5.12xlarge",
	"ml.m4.xlarge",
	"ml.r7i.2xlarge",
	"ml.r7i.xlarge",
	"ml.r6i.12xlarge",
	"ml.m5.24xlarge",
	"ml.r7i.12xlarge",
	"ml.m7i.8xlarge",
	"ml.m7i.large",
	"ml.r6i.24xlarge",
	"ml.r6i.2xlarge",
	"ml.m4.2xlarge",
	"ml.r7i.24xlarge",
	"ml.r7i.4xlarge",
	"ml.m6i.8xlarge",
	"ml.m6i.large",
	"ml.m5.2xlarge",
	"ml.p2.8xlarge",
	"ml.r6i.4xlarge",
	"ml.m6i.32xlarge",
	"ml.m4.4xlarge",
	"ml.p3.16xlarge",
	"ml.p3.2xlarge",
	"ml.p3.8xlarge",
}

var cleanroomsmlInstanceTypeValues = []string{
	"ml.m4.xlarge",
	"ml.m4.2xlarge",
	"ml.m4.4xlarge",
	"ml.m4.10xlarge",
	"ml.m4.16xlarge",
	"ml.g4dn.xlarge",
	"ml.g4dn.2xlarge",
	"ml.g4dn.4xlarge",
	"ml.g4dn.8xlarge",
	"ml.g4dn.12xlarge",
	"ml.g4dn.16xlarge",
	"ml.m5.large",
	"ml.m5.xlarge",
	"ml.m5.2xlarge",
	"ml.m5.4xlarge",
	"ml.m5.12xlarge",
	"ml.m5.24xlarge",
	"ml.c4.xlarge",
	"ml.c4.2xlarge",
	"ml.c4.4xlarge",
	"ml.c4.8xlarge",
	"ml.p2.xlarge",
	"ml.p2.8xlarge",
	"ml.p2.16xlarge",
	"ml.p4d.24xlarge",
	"ml.p4de.24xlarge",
	"ml.p5.48xlarge",
	"ml.c5.xlarge",
	"ml.c5.2xlarge",
	"ml.c5.4xlarge",
	"ml.c5.9xlarge",
	"ml.c5.18xlarge",
	"ml.c5n.xlarge",
	"ml.c5n.2xlarge",
	"ml.c5n.4xlarge",
	"ml.c5n.9xlarge",
	"ml.c5n.18xlarge",
	"ml.g5.xlarge",
	"ml.g5.2xlarge",
	"ml.g5.4xlarge",
	"ml.g5.8xlarge",
	"ml.g5.16xlarge",
	"ml.g5.12xlarge",
	"ml.g5.24xlarge",
	"ml.g5.48xlarge",
	"ml.trn1.2xlarge",
	"ml.trn1.32xlarge",
	"ml.trn1n.32xlarge",
	"ml.m6i.large",
	"ml.m6i.xlarge",
	"ml.m6i.2xlarge",
	"ml.m6i.4xlarge",
	"ml.m6i.8xlarge",
	"ml.m6i.12xlarge",
	"ml.m6i.16xlarge",
	"ml.m6i.24xlarge",
	"ml.m6i.32xlarge",
	"ml.c6i.xlarge",
	"ml.c6i.2xlarge",
	"ml.c6i.8xlarge",
	"ml.c6i.4xlarge",
	"ml.c6i.12xlarge",
	"ml.c6i.16xlarge",
	"ml.c6i.24xlarge",
	"ml.c6i.32xlarge",
	"ml.r5d.large",
	"ml.r5d.xlarge",
	"ml.r5d.2xlarge",
	"ml.r5d.4xlarge",
	"ml.r5d.8xlarge",
	"ml.r5d.12xlarge",
	"ml.r5d.16xlarge",
	"ml.r5d.24xlarge",
	"ml.t3.medium",
	"ml.t3.large",
	"ml.t3.xlarge",
	"ml.t3.2xlarge",
	"ml.r5.large",
	"ml.r5.xlarge",
	"ml.r5.2xlarge",
	"ml.r5.4xlarge",
	"ml.r5.8xlarge",
	"ml.r5.12xlarge",
	"ml.r5.16xlarge",
	"ml.r5.24xlarge",
	"ml.c7i.large",
	"ml.c7i.xlarge",
	"ml.c7i.2xlarge",
	"ml.c7i.4xlarge",
	"ml.c7i.8xlarge",
	"ml.c7i.12xlarge",
	"ml.c7i.16xlarge",
	"ml.c7i.24xlarge",
	"ml.c7i.48xlarge",
	"ml.m7i.large",
	"ml.m7i.xlarge",
	"ml.m7i.2xlarge",
	"ml.m7i.4xlarge",
	"ml.m7i.8xlarge",
	"ml.m7i.12xlarge",
	"ml.m7i.16xlarge",
	"ml.m7i.24xlarge",
	"ml.m7i.48xlarge",
	"ml.r7i.large",
	"ml.r7i.xlarge",
	"ml.r7i.2xlarge",
	"ml.r7i.4xlarge",
	"ml.r7i.8xlarge",
	"ml.r7i.12xlarge",
	"ml.r7i.16xlarge",
	"ml.r7i.24xlarge",
	"ml.r7i.48xlarge",
	"ml.g6.xlarge",
	"ml.g6.2xlarge",
	"ml.g6.4xlarge",
	"ml.g6.8xlarge",
	"ml.g6.12xlarge",
	"ml.g6.16xlarge",
	"ml.g6.24xlarge",
	"ml.g6.48xlarge",
	"ml.g6e.xlarge",
	"ml.g6e.2xlarge",
	"ml.g6e.4xlarge",
	"ml.g6e.8xlarge",
	"ml.g6e.12xlarge",
	"ml.g6e.16xlarge",
	"ml.g6e.24xlarge",
	"ml.g6e.48xlarge",
	"ml.p5en.48xlarge",
	"ml.p3.2xlarge",
	"ml.p3.8xlarge",
	"ml.p3.16xlarge",
	"ml.p3dn.24xlarge",
}

var cleanroomsmlLogTypeValues = []string{
	"ALL",
	"ERROR_SUMMARY",
}

var cleanroomsmlLogsStatusValues = []string{
	"PUBLISH_SUCCEEDED",
	"PUBLISH_FAILED",
}

var cleanroomsmlMLInputChannelStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
	"DELETE_PENDING",
	"DELETE_IN_PROGRESS",
	"DELETE_FAILED",
	"INACTIVE",
}

var cleanroomsmlMembershipInferenceAttackVersionValues = []string{
	"DISTANCE_TO_CLOSEST_RECORD_V1",
}

var cleanroomsmlMetricsStatusValues = []string{
	"PUBLISH_SUCCEEDED",
	"PUBLISH_FAILED",
}

var cleanroomsmlNoiseLevelTypeValues = []string{
	"HIGH",
	"MEDIUM",
	"LOW",
	"NONE",
}

var cleanroomsmlPolicyExistenceConditionValues = []string{
	"POLICY_MUST_EXIST",
	"POLICY_MUST_NOT_EXIST",
}

var cleanroomsmlResultFormatValues = []string{
	"CSV",
	"PARQUET",
}

var cleanroomsmlS3DataDistributionTypeValues = []string{
	"FullyReplicated",
	"ShardedByS3Key",
}

var cleanroomsmlSharedAudienceMetricsValues = []string{
	"ALL",
	"NONE",
}

var cleanroomsmlSyntheticDataColumnTypeValues = []string{
	"CATEGORICAL",
	"NUMERICAL",
}

var cleanroomsmlTagOnCreatePolicyValues = []string{
	"FROM_PARENT_RESOURCE",
	"NONE",
}

var cleanroomsmlTrainedModelArtifactMaxSizeUnitTypeValues = []string{
	"GB",
}

var cleanroomsmlTrainedModelExportFileTypeValues = []string{
	"MODEL",
	"OUTPUT",
}

var cleanroomsmlTrainedModelExportJobStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
}

var cleanroomsmlTrainedModelExportsMaxSizeUnitTypeValues = []string{
	"GB",
}

var cleanroomsmlTrainedModelInferenceJobStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
	"CANCEL_PENDING",
	"CANCEL_IN_PROGRESS",
	"CANCEL_FAILED",
	"INACTIVE",
}

var cleanroomsmlTrainedModelInferenceMaxOutputSizeUnitTypeValues = []string{
	"GB",
}

var cleanroomsmlTrainedModelStatusValues = []string{
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"ACTIVE",
	"DELETE_PENDING",
	"DELETE_IN_PROGRESS",
	"DELETE_FAILED",
	"INACTIVE",
	"CANCEL_PENDING",
	"CANCEL_IN_PROGRESS",
	"CANCEL_FAILED",
}

var cleanroomsmlTrainingDatasetStatusValues = []string{
	"ACTIVE",
}

var cleanroomsmlTrainingInputModeValues = []string{
	"File",
	"FastFile",
	"Pipe",
}

var cleanroomsmlWorkerComputeTypeValues = []string{
	"CR.1X",
	"CR.4X",
}

func getCleanroomsmlEnum(name string) []string {
	switch name {
	case "AccessBudgetType":
		return cleanroomsmlAccessBudgetTypeValues
	case "AudienceExportJobStatus":
		return cleanroomsmlAudienceExportJobStatusValues
	case "AudienceGenerationJobStatus":
		return cleanroomsmlAudienceGenerationJobStatusValues
	case "AudienceModelStatus":
		return cleanroomsmlAudienceModelStatusValues
	case "AudienceSizeType":
		return cleanroomsmlAudienceSizeTypeValues
	case "AutoRefreshMode":
		return cleanroomsmlAutoRefreshModeValues
	case "ColumnType":
		return cleanroomsmlColumnTypeValues
	case "ConfiguredAudienceModelStatus":
		return cleanroomsmlConfiguredAudienceModelStatusValues
	case "DatasetType":
		return cleanroomsmlDatasetTypeValues
	case "EntityType":
		return cleanroomsmlEntityTypeValues
	case "InferenceInstanceType":
		return cleanroomsmlInferenceInstanceTypeValues
	case "InstanceType":
		return cleanroomsmlInstanceTypeValues
	case "LogType":
		return cleanroomsmlLogTypeValues
	case "LogsStatus":
		return cleanroomsmlLogsStatusValues
	case "MLInputChannelStatus":
		return cleanroomsmlMLInputChannelStatusValues
	case "MembershipInferenceAttackVersion":
		return cleanroomsmlMembershipInferenceAttackVersionValues
	case "MetricsStatus":
		return cleanroomsmlMetricsStatusValues
	case "NoiseLevelType":
		return cleanroomsmlNoiseLevelTypeValues
	case "PolicyExistenceCondition":
		return cleanroomsmlPolicyExistenceConditionValues
	case "ResultFormat":
		return cleanroomsmlResultFormatValues
	case "S3DataDistributionType":
		return cleanroomsmlS3DataDistributionTypeValues
	case "SharedAudienceMetrics":
		return cleanroomsmlSharedAudienceMetricsValues
	case "SyntheticDataColumnType":
		return cleanroomsmlSyntheticDataColumnTypeValues
	case "TagOnCreatePolicy":
		return cleanroomsmlTagOnCreatePolicyValues
	case "TrainedModelArtifactMaxSizeUnitType":
		return cleanroomsmlTrainedModelArtifactMaxSizeUnitTypeValues
	case "TrainedModelExportFileType":
		return cleanroomsmlTrainedModelExportFileTypeValues
	case "TrainedModelExportJobStatus":
		return cleanroomsmlTrainedModelExportJobStatusValues
	case "TrainedModelExportsMaxSizeUnitType":
		return cleanroomsmlTrainedModelExportsMaxSizeUnitTypeValues
	case "TrainedModelInferenceJobStatus":
		return cleanroomsmlTrainedModelInferenceJobStatusValues
	case "TrainedModelInferenceMaxOutputSizeUnitType":
		return cleanroomsmlTrainedModelInferenceMaxOutputSizeUnitTypeValues
	case "TrainedModelStatus":
		return cleanroomsmlTrainedModelStatusValues
	case "TrainingDatasetStatus":
		return cleanroomsmlTrainingDatasetStatusValues
	case "TrainingInputMode":
		return cleanroomsmlTrainingInputModeValues
	case "WorkerComputeType":
		return cleanroomsmlWorkerComputeTypeValues
	}
	return nil
}

func getCleanroomsmlEnumNames() []string {
	return []string{
		"AccessBudgetType",
		"AudienceExportJobStatus",
		"AudienceGenerationJobStatus",
		"AudienceModelStatus",
		"AudienceSizeType",
		"AutoRefreshMode",
		"ColumnType",
		"ConfiguredAudienceModelStatus",
		"DatasetType",
		"EntityType",
		"InferenceInstanceType",
		"InstanceType",
		"LogType",
		"LogsStatus",
		"MLInputChannelStatus",
		"MembershipInferenceAttackVersion",
		"MetricsStatus",
		"NoiseLevelType",
		"PolicyExistenceCondition",
		"ResultFormat",
		"S3DataDistributionType",
		"SharedAudienceMetrics",
		"SyntheticDataColumnType",
		"TagOnCreatePolicy",
		"TrainedModelArtifactMaxSizeUnitType",
		"TrainedModelExportFileType",
		"TrainedModelExportJobStatus",
		"TrainedModelExportsMaxSizeUnitType",
		"TrainedModelInferenceJobStatus",
		"TrainedModelInferenceMaxOutputSizeUnitType",
		"TrainedModelStatus",
		"TrainingDatasetStatus",
		"TrainingInputMode",
		"WorkerComputeType",
	}
}
