// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Cloudcontrol enum constants
const (
	// HandlerErrorCode values
	CloudcontrolHandlerErrorCodeNotupdatable                 = "NotUpdatable"
	CloudcontrolHandlerErrorCodeInvalidrequest               = "InvalidRequest"
	CloudcontrolHandlerErrorCodeAccessdenied                 = "AccessDenied"
	CloudcontrolHandlerErrorCodeUnauthorizedtaggingoperation = "UnauthorizedTaggingOperation"
	CloudcontrolHandlerErrorCodeInvalidcredentials           = "InvalidCredentials"
	CloudcontrolHandlerErrorCodeAlreadyexists                = "AlreadyExists"
	CloudcontrolHandlerErrorCodeNotfound                     = "NotFound"
	CloudcontrolHandlerErrorCodeResourceconflict             = "ResourceConflict"
	CloudcontrolHandlerErrorCodeThrottling                   = "Throttling"
	CloudcontrolHandlerErrorCodeServicelimitexceeded         = "ServiceLimitExceeded"
	CloudcontrolHandlerErrorCodeNotstabilized                = "NotStabilized"
	CloudcontrolHandlerErrorCodeGeneralserviceexception      = "GeneralServiceException"
	CloudcontrolHandlerErrorCodeServiceinternalerror         = "ServiceInternalError"
	CloudcontrolHandlerErrorCodeServicetimeout               = "ServiceTimeout"
	CloudcontrolHandlerErrorCodeNetworkfailure               = "NetworkFailure"
	CloudcontrolHandlerErrorCodeInternalfailure              = "InternalFailure"

	// Operation values
	CloudcontrolOperationCreate = "CREATE"
	CloudcontrolOperationDelete = "DELETE"
	CloudcontrolOperationUpdate = "UPDATE"

	// OperationStatus values
	CloudcontrolOperationStatusPending          = "PENDING"
	CloudcontrolOperationStatusInProgress       = "IN_PROGRESS"
	CloudcontrolOperationStatusSuccess          = "SUCCESS"
	CloudcontrolOperationStatusFailed           = "FAILED"
	CloudcontrolOperationStatusCancelInProgress = "CANCEL_IN_PROGRESS"
	CloudcontrolOperationStatusCancelComplete   = "CANCEL_COMPLETE"
)

var cloudcontrolHandlerErrorCodeValues = []string{
	"NotUpdatable",
	"InvalidRequest",
	"AccessDenied",
	"UnauthorizedTaggingOperation",
	"InvalidCredentials",
	"AlreadyExists",
	"NotFound",
	"ResourceConflict",
	"Throttling",
	"ServiceLimitExceeded",
	"NotStabilized",
	"GeneralServiceException",
	"ServiceInternalError",
	"ServiceTimeout",
	"NetworkFailure",
	"InternalFailure",
}

var cloudcontrolOperationValues = []string{
	"CREATE",
	"DELETE",
	"UPDATE",
}

var cloudcontrolOperationStatusValues = []string{
	"PENDING",
	"IN_PROGRESS",
	"SUCCESS",
	"FAILED",
	"CANCEL_IN_PROGRESS",
	"CANCEL_COMPLETE",
}

func getCloudcontrolEnum(name string) []string {
	switch name {
	case "HandlerErrorCode":
		return cloudcontrolHandlerErrorCodeValues
	case "Operation":
		return cloudcontrolOperationValues
	case "OperationStatus":
		return cloudcontrolOperationStatusValues
	}
	return nil
}

func getCloudcontrolEnumNames() []string {
	return []string{
		"HandlerErrorCode",
		"Operation",
		"OperationStatus",
	}
}
