// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Codeconnections enum constants
const (
	// BlockerStatus values
	CodeconnectionsBlockerStatusActive   = "ACTIVE"
	CodeconnectionsBlockerStatusResolved = "RESOLVED"

	// BlockerType values
	CodeconnectionsBlockerTypeAutomated = "AUTOMATED"

	// ConnectionStatus values
	CodeconnectionsConnectionStatusPending   = "PENDING"
	CodeconnectionsConnectionStatusAvailable = "AVAILABLE"
	CodeconnectionsConnectionStatusError     = "ERROR"

	// ProviderType values
	CodeconnectionsProviderTypeBitbucket              = "Bitbucket"
	CodeconnectionsProviderTypeGithub                 = "GitHub"
	CodeconnectionsProviderTypeGithubenterpriseserver = "GitHubEnterpriseServer"
	CodeconnectionsProviderTypeGitlab                 = "GitLab"
	CodeconnectionsProviderTypeGitlabselfmanaged      = "GitLabSelfManaged"
	CodeconnectionsProviderTypeAzuredevops            = "AzureDevOps"

	// PublishDeploymentStatus values
	CodeconnectionsPublishDeploymentStatusEnabled  = "ENABLED"
	CodeconnectionsPublishDeploymentStatusDisabled = "DISABLED"

	// PullRequestComment values
	CodeconnectionsPullRequestCommentEnabled  = "ENABLED"
	CodeconnectionsPullRequestCommentDisabled = "DISABLED"

	// RepositorySyncStatus values
	CodeconnectionsRepositorySyncStatusFailed     = "FAILED"
	CodeconnectionsRepositorySyncStatusInitiated  = "INITIATED"
	CodeconnectionsRepositorySyncStatusInProgress = "IN_PROGRESS"
	CodeconnectionsRepositorySyncStatusSucceeded  = "SUCCEEDED"
	CodeconnectionsRepositorySyncStatusQueued     = "QUEUED"

	// ResourceSyncStatus values
	CodeconnectionsResourceSyncStatusFailed     = "FAILED"
	CodeconnectionsResourceSyncStatusInitiated  = "INITIATED"
	CodeconnectionsResourceSyncStatusInProgress = "IN_PROGRESS"
	CodeconnectionsResourceSyncStatusSucceeded  = "SUCCEEDED"

	// SyncConfigurationType values
	CodeconnectionsSyncConfigurationTypeCfnStackSync = "CFN_STACK_SYNC"

	// TriggerResourceUpdateOn values
	CodeconnectionsTriggerResourceUpdateOnAnyChange  = "ANY_CHANGE"
	CodeconnectionsTriggerResourceUpdateOnFileChange = "FILE_CHANGE"
)

var codeconnectionsBlockerStatusValues = []string{
	"ACTIVE",
	"RESOLVED",
}

var codeconnectionsBlockerTypeValues = []string{
	"AUTOMATED",
}

var codeconnectionsConnectionStatusValues = []string{
	"PENDING",
	"AVAILABLE",
	"ERROR",
}

var codeconnectionsProviderTypeValues = []string{
	"Bitbucket",
	"GitHub",
	"GitHubEnterpriseServer",
	"GitLab",
	"GitLabSelfManaged",
	"AzureDevOps",
}

var codeconnectionsPublishDeploymentStatusValues = []string{
	"ENABLED",
	"DISABLED",
}

var codeconnectionsPullRequestCommentValues = []string{
	"ENABLED",
	"DISABLED",
}

var codeconnectionsRepositorySyncStatusValues = []string{
	"FAILED",
	"INITIATED",
	"IN_PROGRESS",
	"SUCCEEDED",
	"QUEUED",
}

var codeconnectionsResourceSyncStatusValues = []string{
	"FAILED",
	"INITIATED",
	"IN_PROGRESS",
	"SUCCEEDED",
}

var codeconnectionsSyncConfigurationTypeValues = []string{
	"CFN_STACK_SYNC",
}

var codeconnectionsTriggerResourceUpdateOnValues = []string{
	"ANY_CHANGE",
	"FILE_CHANGE",
}

func getCodeconnectionsEnum(name string) []string {
	switch name {
	case "BlockerStatus":
		return codeconnectionsBlockerStatusValues
	case "BlockerType":
		return codeconnectionsBlockerTypeValues
	case "ConnectionStatus":
		return codeconnectionsConnectionStatusValues
	case "ProviderType":
		return codeconnectionsProviderTypeValues
	case "PublishDeploymentStatus":
		return codeconnectionsPublishDeploymentStatusValues
	case "PullRequestComment":
		return codeconnectionsPullRequestCommentValues
	case "RepositorySyncStatus":
		return codeconnectionsRepositorySyncStatusValues
	case "ResourceSyncStatus":
		return codeconnectionsResourceSyncStatusValues
	case "SyncConfigurationType":
		return codeconnectionsSyncConfigurationTypeValues
	case "TriggerResourceUpdateOn":
		return codeconnectionsTriggerResourceUpdateOnValues
	}
	return nil
}

func getCodeconnectionsEnumNames() []string {
	return []string{
		"BlockerStatus",
		"BlockerType",
		"ConnectionStatus",
		"ProviderType",
		"PublishDeploymentStatus",
		"PullRequestComment",
		"RepositorySyncStatus",
		"ResourceSyncStatus",
		"SyncConfigurationType",
		"TriggerResourceUpdateOn",
	}
}
