// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// CognitoSync enum constants
const (
	// BulkPublishStatus values
	CognitosyncBulkPublishStatusNotStarted = "NOT_STARTED"
	CognitosyncBulkPublishStatusInProgress = "IN_PROGRESS"
	CognitosyncBulkPublishStatusFailed     = "FAILED"
	CognitosyncBulkPublishStatusSucceeded  = "SUCCEEDED"

	// Operation values
	CognitosyncOperationReplace = "replace"
	CognitosyncOperationRemove  = "remove"

	// Platform values
	CognitosyncPlatformApns        = "APNS"
	CognitosyncPlatformApnsSandbox = "APNS_SANDBOX"
	CognitosyncPlatformGcm         = "GCM"
	CognitosyncPlatformAdm         = "ADM"

	// StreamingStatus values
	CognitosyncStreamingStatusEnabled  = "ENABLED"
	CognitosyncStreamingStatusDisabled = "DISABLED"
)

var cognitosyncBulkPublishStatusValues = []string{
	"NOT_STARTED",
	"IN_PROGRESS",
	"FAILED",
	"SUCCEEDED",
}

var cognitosyncOperationValues = []string{
	"replace",
	"remove",
}

var cognitosyncPlatformValues = []string{
	"APNS",
	"APNS_SANDBOX",
	"GCM",
	"ADM",
}

var cognitosyncStreamingStatusValues = []string{
	"ENABLED",
	"DISABLED",
}

func getCognitoSyncEnum(name string) []string {
	switch name {
	case "BulkPublishStatus":
		return cognitosyncBulkPublishStatusValues
	case "Operation":
		return cognitosyncOperationValues
	case "Platform":
		return cognitosyncPlatformValues
	case "StreamingStatus":
		return cognitosyncStreamingStatusValues
	}
	return nil
}

func getCognitoSyncEnumNames() []string {
	return []string{
		"BulkPublishStatus",
		"Operation",
		"Platform",
		"StreamingStatus",
	}
}
