// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Dynamodb enum constants
const (
	// BillingMode values
	DynamodbBillingModeProvisioned   = "PROVISIONED"
	DynamodbBillingModePayPerRequest = "PAY_PER_REQUEST"

	// StreamViewType values
	DynamodbStreamViewTypeNewImage        = "NEW_IMAGE"
	DynamodbStreamViewTypeOldImage        = "OLD_IMAGE"
	DynamodbStreamViewTypeNewAndOldImages = "NEW_AND_OLD_IMAGES"
	DynamodbStreamViewTypeKeysOnly        = "KEYS_ONLY"

	// TableClass values
	DynamodbTableClassStandard                 = "STANDARD"
	DynamodbTableClassStandardInfrequentAccess = "STANDARD_INFREQUENT_ACCESS"
)

var dynamodbBillingModeValues = []string{
	"PROVISIONED",
	"PAY_PER_REQUEST",
}

var dynamodbStreamViewTypeValues = []string{
	"NEW_IMAGE",
	"OLD_IMAGE",
	"NEW_AND_OLD_IMAGES",
	"KEYS_ONLY",
}

var dynamodbTableClassValues = []string{
	"STANDARD",
	"STANDARD_INFREQUENT_ACCESS",
}

func getDynamodbEnum(name string) []string {
	switch name {
	case "BillingMode":
		return dynamodbBillingModeValues
	case "StreamViewType":
		return dynamodbStreamViewTypeValues
	case "TableClass":
		return dynamodbTableClassValues
	}
	return nil
}

func getDynamodbEnumNames() []string {
	return []string{
		"BillingMode",
		"StreamViewType",
		"TableClass",
	}
}
