// Code generated by enumgen. DO NOT EDIT.

package enums

// Ec2 enum constants
const (
	// InstanceType values
	Ec2InstanceTypeA1Medium           = "a1.medium"
	Ec2InstanceTypeA1Large            = "a1.large"
	Ec2InstanceTypeA1Xlarge           = "a1.xlarge"
	Ec2InstanceTypeA12xlarge          = "a1.2xlarge"
	Ec2InstanceTypeA14xlarge          = "a1.4xlarge"
	Ec2InstanceTypeA1Metal            = "a1.metal"
	Ec2InstanceTypeC1Medium           = "c1.medium"
	Ec2InstanceTypeC1Xlarge           = "c1.xlarge"
	Ec2InstanceTypeC3Large            = "c3.large"
	Ec2InstanceTypeC3Xlarge           = "c3.xlarge"
	Ec2InstanceTypeC32xlarge          = "c3.2xlarge"
	Ec2InstanceTypeC34xlarge          = "c3.4xlarge"
	Ec2InstanceTypeC38xlarge          = "c3.8xlarge"
	Ec2InstanceTypeC4Large            = "c4.large"
	Ec2InstanceTypeC4Xlarge           = "c4.xlarge"
	Ec2InstanceTypeC42xlarge          = "c4.2xlarge"
	Ec2InstanceTypeC44xlarge          = "c4.4xlarge"
	Ec2InstanceTypeC48xlarge          = "c4.8xlarge"
	Ec2InstanceTypeC5Large            = "c5.large"
	Ec2InstanceTypeC5Xlarge           = "c5.xlarge"
	Ec2InstanceTypeC52xlarge          = "c5.2xlarge"
	Ec2InstanceTypeC54xlarge          = "c5.4xlarge"
	Ec2InstanceTypeC59xlarge          = "c5.9xlarge"
	Ec2InstanceTypeC512xlarge         = "c5.12xlarge"
	Ec2InstanceTypeC518xlarge         = "c5.18xlarge"
	Ec2InstanceTypeC524xlarge         = "c5.24xlarge"
	Ec2InstanceTypeC5Metal            = "c5.metal"
	Ec2InstanceTypeC5aLarge           = "c5a.large"
	Ec2InstanceTypeC5aXlarge          = "c5a.xlarge"
	Ec2InstanceTypeC5a2xlarge         = "c5a.2xlarge"
	Ec2InstanceTypeC5a4xlarge         = "c5a.4xlarge"
	Ec2InstanceTypeC5a8xlarge         = "c5a.8xlarge"
	Ec2InstanceTypeC5a12xlarge        = "c5a.12xlarge"
	Ec2InstanceTypeC5a16xlarge        = "c5a.16xlarge"
	Ec2InstanceTypeC5a24xlarge        = "c5a.24xlarge"
	Ec2InstanceTypeC5adLarge          = "c5ad.large"
	Ec2InstanceTypeC5adXlarge         = "c5ad.xlarge"
	Ec2InstanceTypeC5ad2xlarge        = "c5ad.2xlarge"
	Ec2InstanceTypeC5ad4xlarge        = "c5ad.4xlarge"
	Ec2InstanceTypeC5ad8xlarge        = "c5ad.8xlarge"
	Ec2InstanceTypeC5ad12xlarge       = "c5ad.12xlarge"
	Ec2InstanceTypeC5ad16xlarge       = "c5ad.16xlarge"
	Ec2InstanceTypeC5ad24xlarge       = "c5ad.24xlarge"
	Ec2InstanceTypeC5dLarge           = "c5d.large"
	Ec2InstanceTypeC5dXlarge          = "c5d.xlarge"
	Ec2InstanceTypeC5d2xlarge         = "c5d.2xlarge"
	Ec2InstanceTypeC5d4xlarge         = "c5d.4xlarge"
	Ec2InstanceTypeC5d9xlarge         = "c5d.9xlarge"
	Ec2InstanceTypeC5d12xlarge        = "c5d.12xlarge"
	Ec2InstanceTypeC5d18xlarge        = "c5d.18xlarge"
	Ec2InstanceTypeC5d24xlarge        = "c5d.24xlarge"
	Ec2InstanceTypeC5dMetal           = "c5d.metal"
	Ec2InstanceTypeC5nLarge           = "c5n.large"
	Ec2InstanceTypeC5nXlarge          = "c5n.xlarge"
	Ec2InstanceTypeC5n2xlarge         = "c5n.2xlarge"
	Ec2InstanceTypeC5n4xlarge         = "c5n.4xlarge"
	Ec2InstanceTypeC5n9xlarge         = "c5n.9xlarge"
	Ec2InstanceTypeC5n18xlarge        = "c5n.18xlarge"
	Ec2InstanceTypeC5nMetal           = "c5n.metal"
	Ec2InstanceTypeC6gMedium          = "c6g.medium"
	Ec2InstanceTypeC6gLarge           = "c6g.large"
	Ec2InstanceTypeC6gXlarge          = "c6g.xlarge"
	Ec2InstanceTypeC6g2xlarge         = "c6g.2xlarge"
	Ec2InstanceTypeC6g4xlarge         = "c6g.4xlarge"
	Ec2InstanceTypeC6g8xlarge         = "c6g.8xlarge"
	Ec2InstanceTypeC6g12xlarge        = "c6g.12xlarge"
	Ec2InstanceTypeC6g16xlarge        = "c6g.16xlarge"
	Ec2InstanceTypeC6gMetal           = "c6g.metal"
	Ec2InstanceTypeC6gdMedium         = "c6gd.medium"
	Ec2InstanceTypeC6gdLarge          = "c6gd.large"
	Ec2InstanceTypeC6gdXlarge         = "c6gd.xlarge"
	Ec2InstanceTypeC6gd2xlarge        = "c6gd.2xlarge"
	Ec2InstanceTypeC6gd4xlarge        = "c6gd.4xlarge"
	Ec2InstanceTypeC6gd8xlarge        = "c6gd.8xlarge"
	Ec2InstanceTypeC6gd12xlarge       = "c6gd.12xlarge"
	Ec2InstanceTypeC6gd16xlarge       = "c6gd.16xlarge"
	Ec2InstanceTypeC6gdMetal          = "c6gd.metal"
	Ec2InstanceTypeC6gnMedium         = "c6gn.medium"
	Ec2InstanceTypeC6gnLarge          = "c6gn.large"
	Ec2InstanceTypeC6gnXlarge         = "c6gn.xlarge"
	Ec2InstanceTypeC6gn2xlarge        = "c6gn.2xlarge"
	Ec2InstanceTypeC6gn4xlarge        = "c6gn.4xlarge"
	Ec2InstanceTypeC6gn8xlarge        = "c6gn.8xlarge"
	Ec2InstanceTypeC6gn12xlarge       = "c6gn.12xlarge"
	Ec2InstanceTypeC6gn16xlarge       = "c6gn.16xlarge"
	Ec2InstanceTypeC6iLarge           = "c6i.large"
	Ec2InstanceTypeC6iXlarge          = "c6i.xlarge"
	Ec2InstanceTypeC6i2xlarge         = "c6i.2xlarge"
	Ec2InstanceTypeC6i4xlarge         = "c6i.4xlarge"
	Ec2InstanceTypeC6i8xlarge         = "c6i.8xlarge"
	Ec2InstanceTypeC6i12xlarge        = "c6i.12xlarge"
	Ec2InstanceTypeC6i16xlarge        = "c6i.16xlarge"
	Ec2InstanceTypeC6i24xlarge        = "c6i.24xlarge"
	Ec2InstanceTypeC6i32xlarge        = "c6i.32xlarge"
	Ec2InstanceTypeC6iMetal           = "c6i.metal"
	Ec2InstanceTypeCc14xlarge         = "cc1.4xlarge"
	Ec2InstanceTypeCc28xlarge         = "cc2.8xlarge"
	Ec2InstanceTypeCg14xlarge         = "cg1.4xlarge"
	Ec2InstanceTypeCr18xlarge         = "cr1.8xlarge"
	Ec2InstanceTypeD2Xlarge           = "d2.xlarge"
	Ec2InstanceTypeD22xlarge          = "d2.2xlarge"
	Ec2InstanceTypeD24xlarge          = "d2.4xlarge"
	Ec2InstanceTypeD28xlarge          = "d2.8xlarge"
	Ec2InstanceTypeD3Xlarge           = "d3.xlarge"
	Ec2InstanceTypeD32xlarge          = "d3.2xlarge"
	Ec2InstanceTypeD34xlarge          = "d3.4xlarge"
	Ec2InstanceTypeD38xlarge          = "d3.8xlarge"
	Ec2InstanceTypeD3enXlarge         = "d3en.xlarge"
	Ec2InstanceTypeD3en2xlarge        = "d3en.2xlarge"
	Ec2InstanceTypeD3en4xlarge        = "d3en.4xlarge"
	Ec2InstanceTypeD3en6xlarge        = "d3en.6xlarge"
	Ec2InstanceTypeD3en8xlarge        = "d3en.8xlarge"
	Ec2InstanceTypeD3en12xlarge       = "d3en.12xlarge"
	Ec2InstanceTypeDl124xlarge        = "dl1.24xlarge"
	Ec2InstanceTypeF12xlarge          = "f1.2xlarge"
	Ec2InstanceTypeF14xlarge          = "f1.4xlarge"
	Ec2InstanceTypeF116xlarge         = "f1.16xlarge"
	Ec2InstanceTypeG22xlarge          = "g2.2xlarge"
	Ec2InstanceTypeG28xlarge          = "g2.8xlarge"
	Ec2InstanceTypeG34xlarge          = "g3.4xlarge"
	Ec2InstanceTypeG38xlarge          = "g3.8xlarge"
	Ec2InstanceTypeG316xlarge         = "g3.16xlarge"
	Ec2InstanceTypeG3sXlarge          = "g3s.xlarge"
	Ec2InstanceTypeG4adXlarge         = "g4ad.xlarge"
	Ec2InstanceTypeG4ad2xlarge        = "g4ad.2xlarge"
	Ec2InstanceTypeG4ad4xlarge        = "g4ad.4xlarge"
	Ec2InstanceTypeG4ad8xlarge        = "g4ad.8xlarge"
	Ec2InstanceTypeG4ad16xlarge       = "g4ad.16xlarge"
	Ec2InstanceTypeG4dnXlarge         = "g4dn.xlarge"
	Ec2InstanceTypeG4dn2xlarge        = "g4dn.2xlarge"
	Ec2InstanceTypeG4dn4xlarge        = "g4dn.4xlarge"
	Ec2InstanceTypeG4dn8xlarge        = "g4dn.8xlarge"
	Ec2InstanceTypeG4dn12xlarge       = "g4dn.12xlarge"
	Ec2InstanceTypeG4dn16xlarge       = "g4dn.16xlarge"
	Ec2InstanceTypeG4dnMetal          = "g4dn.metal"
	Ec2InstanceTypeG5Xlarge           = "g5.xlarge"
	Ec2InstanceTypeG52xlarge          = "g5.2xlarge"
	Ec2InstanceTypeG54xlarge          = "g5.4xlarge"
	Ec2InstanceTypeG58xlarge          = "g5.8xlarge"
	Ec2InstanceTypeG512xlarge         = "g5.12xlarge"
	Ec2InstanceTypeG516xlarge         = "g5.16xlarge"
	Ec2InstanceTypeG524xlarge         = "g5.24xlarge"
	Ec2InstanceTypeG548xlarge         = "g5.48xlarge"
	Ec2InstanceTypeG5gXlarge          = "g5g.xlarge"
	Ec2InstanceTypeG5g2xlarge         = "g5g.2xlarge"
	Ec2InstanceTypeG5g4xlarge         = "g5g.4xlarge"
	Ec2InstanceTypeG5g8xlarge         = "g5g.8xlarge"
	Ec2InstanceTypeG5g16xlarge        = "g5g.16xlarge"
	Ec2InstanceTypeG5gMetal           = "g5g.metal"
	Ec2InstanceTypeHi14xlarge         = "hi1.4xlarge"
	Ec2InstanceTypeHpc6a48xlarge      = "hpc6a.48xlarge"
	Ec2InstanceTypeHs18xlarge         = "hs1.8xlarge"
	Ec2InstanceTypeH12xlarge          = "h1.2xlarge"
	Ec2InstanceTypeH14xlarge          = "h1.4xlarge"
	Ec2InstanceTypeH18xlarge          = "h1.8xlarge"
	Ec2InstanceTypeH116xlarge         = "h1.16xlarge"
	Ec2InstanceTypeI2Xlarge           = "i2.xlarge"
	Ec2InstanceTypeI22xlarge          = "i2.2xlarge"
	Ec2InstanceTypeI24xlarge          = "i2.4xlarge"
	Ec2InstanceTypeI28xlarge          = "i2.8xlarge"
	Ec2InstanceTypeI3Large            = "i3.large"
	Ec2InstanceTypeI3Xlarge           = "i3.xlarge"
	Ec2InstanceTypeI32xlarge          = "i3.2xlarge"
	Ec2InstanceTypeI34xlarge          = "i3.4xlarge"
	Ec2InstanceTypeI38xlarge          = "i3.8xlarge"
	Ec2InstanceTypeI316xlarge         = "i3.16xlarge"
	Ec2InstanceTypeI3Metal            = "i3.metal"
	Ec2InstanceTypeI3enLarge          = "i3en.large"
	Ec2InstanceTypeI3enXlarge         = "i3en.xlarge"
	Ec2InstanceTypeI3en2xlarge        = "i3en.2xlarge"
	Ec2InstanceTypeI3en3xlarge        = "i3en.3xlarge"
	Ec2InstanceTypeI3en6xlarge        = "i3en.6xlarge"
	Ec2InstanceTypeI3en12xlarge       = "i3en.12xlarge"
	Ec2InstanceTypeI3en24xlarge       = "i3en.24xlarge"
	Ec2InstanceTypeI3enMetal          = "i3en.metal"
	Ec2InstanceTypeIm4gnLarge         = "im4gn.large"
	Ec2InstanceTypeIm4gnXlarge        = "im4gn.xlarge"
	Ec2InstanceTypeIm4gn2xlarge       = "im4gn.2xlarge"
	Ec2InstanceTypeIm4gn4xlarge       = "im4gn.4xlarge"
	Ec2InstanceTypeIm4gn8xlarge       = "im4gn.8xlarge"
	Ec2InstanceTypeIm4gn16xlarge      = "im4gn.16xlarge"
	Ec2InstanceTypeInf1Xlarge         = "inf1.xlarge"
	Ec2InstanceTypeInf12xlarge        = "inf1.2xlarge"
	Ec2InstanceTypeInf16xlarge        = "inf1.6xlarge"
	Ec2InstanceTypeInf124xlarge       = "inf1.24xlarge"
	Ec2InstanceTypeIs4genMedium       = "is4gen.medium"
	Ec2InstanceTypeIs4genLarge        = "is4gen.large"
	Ec2InstanceTypeIs4genXlarge       = "is4gen.xlarge"
	Ec2InstanceTypeIs4gen2xlarge      = "is4gen.2xlarge"
	Ec2InstanceTypeIs4gen4xlarge      = "is4gen.4xlarge"
	Ec2InstanceTypeIs4gen8xlarge      = "is4gen.8xlarge"
	Ec2InstanceTypeM1Small            = "m1.small"
	Ec2InstanceTypeM1Medium           = "m1.medium"
	Ec2InstanceTypeM1Large            = "m1.large"
	Ec2InstanceTypeM1Xlarge           = "m1.xlarge"
	Ec2InstanceTypeM2Xlarge           = "m2.xlarge"
	Ec2InstanceTypeM22xlarge          = "m2.2xlarge"
	Ec2InstanceTypeM24xlarge          = "m2.4xlarge"
	Ec2InstanceTypeM3Medium           = "m3.medium"
	Ec2InstanceTypeM3Large            = "m3.large"
	Ec2InstanceTypeM3Xlarge           = "m3.xlarge"
	Ec2InstanceTypeM32xlarge          = "m3.2xlarge"
	Ec2InstanceTypeM4Large            = "m4.large"
	Ec2InstanceTypeM4Xlarge           = "m4.xlarge"
	Ec2InstanceTypeM42xlarge          = "m4.2xlarge"
	Ec2InstanceTypeM44xlarge          = "m4.4xlarge"
	Ec2InstanceTypeM410xlarge         = "m4.10xlarge"
	Ec2InstanceTypeM416xlarge         = "m4.16xlarge"
	Ec2InstanceTypeM5Large            = "m5.large"
	Ec2InstanceTypeM5Xlarge           = "m5.xlarge"
	Ec2InstanceTypeM52xlarge          = "m5.2xlarge"
	Ec2InstanceTypeM54xlarge          = "m5.4xlarge"
	Ec2InstanceTypeM58xlarge          = "m5.8xlarge"
	Ec2InstanceTypeM512xlarge         = "m5.12xlarge"
	Ec2InstanceTypeM516xlarge         = "m5.16xlarge"
	Ec2InstanceTypeM524xlarge         = "m5.24xlarge"
	Ec2InstanceTypeM5Metal            = "m5.metal"
	Ec2InstanceTypeM5aLarge           = "m5a.large"
	Ec2InstanceTypeM5aXlarge          = "m5a.xlarge"
	Ec2InstanceTypeM5a2xlarge         = "m5a.2xlarge"
	Ec2InstanceTypeM5a4xlarge         = "m5a.4xlarge"
	Ec2InstanceTypeM5a8xlarge         = "m5a.8xlarge"
	Ec2InstanceTypeM5a12xlarge        = "m5a.12xlarge"
	Ec2InstanceTypeM5a16xlarge        = "m5a.16xlarge"
	Ec2InstanceTypeM5a24xlarge        = "m5a.24xlarge"
	Ec2InstanceTypeM5adLarge          = "m5ad.large"
	Ec2InstanceTypeM5adXlarge         = "m5ad.xlarge"
	Ec2InstanceTypeM5ad2xlarge        = "m5ad.2xlarge"
	Ec2InstanceTypeM5ad4xlarge        = "m5ad.4xlarge"
	Ec2InstanceTypeM5ad8xlarge        = "m5ad.8xlarge"
	Ec2InstanceTypeM5ad12xlarge       = "m5ad.12xlarge"
	Ec2InstanceTypeM5ad16xlarge       = "m5ad.16xlarge"
	Ec2InstanceTypeM5ad24xlarge       = "m5ad.24xlarge"
	Ec2InstanceTypeM5dLarge           = "m5d.large"
	Ec2InstanceTypeM5dXlarge          = "m5d.xlarge"
	Ec2InstanceTypeM5d2xlarge         = "m5d.2xlarge"
	Ec2InstanceTypeM5d4xlarge         = "m5d.4xlarge"
	Ec2InstanceTypeM5d8xlarge         = "m5d.8xlarge"
	Ec2InstanceTypeM5d12xlarge        = "m5d.12xlarge"
	Ec2InstanceTypeM5d16xlarge        = "m5d.16xlarge"
	Ec2InstanceTypeM5d24xlarge        = "m5d.24xlarge"
	Ec2InstanceTypeM5dMetal           = "m5d.metal"
	Ec2InstanceTypeM5dnLarge          = "m5dn.large"
	Ec2InstanceTypeM5dnXlarge         = "m5dn.xlarge"
	Ec2InstanceTypeM5dn2xlarge        = "m5dn.2xlarge"
	Ec2InstanceTypeM5dn4xlarge        = "m5dn.4xlarge"
	Ec2InstanceTypeM5dn8xlarge        = "m5dn.8xlarge"
	Ec2InstanceTypeM5dn12xlarge       = "m5dn.12xlarge"
	Ec2InstanceTypeM5dn16xlarge       = "m5dn.16xlarge"
	Ec2InstanceTypeM5dn24xlarge       = "m5dn.24xlarge"
	Ec2InstanceTypeM5dnMetal          = "m5dn.metal"
	Ec2InstanceTypeM5nLarge           = "m5n.large"
	Ec2InstanceTypeM5nXlarge          = "m5n.xlarge"
	Ec2InstanceTypeM5n2xlarge         = "m5n.2xlarge"
	Ec2InstanceTypeM5n4xlarge         = "m5n.4xlarge"
	Ec2InstanceTypeM5n8xlarge         = "m5n.8xlarge"
	Ec2InstanceTypeM5n12xlarge        = "m5n.12xlarge"
	Ec2InstanceTypeM5n16xlarge        = "m5n.16xlarge"
	Ec2InstanceTypeM5n24xlarge        = "m5n.24xlarge"
	Ec2InstanceTypeM5nMetal           = "m5n.metal"
	Ec2InstanceTypeM5znLarge          = "m5zn.large"
	Ec2InstanceTypeM5znXlarge         = "m5zn.xlarge"
	Ec2InstanceTypeM5zn2xlarge        = "m5zn.2xlarge"
	Ec2InstanceTypeM5zn3xlarge        = "m5zn.3xlarge"
	Ec2InstanceTypeM5zn6xlarge        = "m5zn.6xlarge"
	Ec2InstanceTypeM5zn12xlarge       = "m5zn.12xlarge"
	Ec2InstanceTypeM5znMetal          = "m5zn.metal"
	Ec2InstanceTypeM6aLarge           = "m6a.large"
	Ec2InstanceTypeM6aXlarge          = "m6a.xlarge"
	Ec2InstanceTypeM6a2xlarge         = "m6a.2xlarge"
	Ec2InstanceTypeM6a4xlarge         = "m6a.4xlarge"
	Ec2InstanceTypeM6a8xlarge         = "m6a.8xlarge"
	Ec2InstanceTypeM6a12xlarge        = "m6a.12xlarge"
	Ec2InstanceTypeM6a16xlarge        = "m6a.16xlarge"
	Ec2InstanceTypeM6a24xlarge        = "m6a.24xlarge"
	Ec2InstanceTypeM6a32xlarge        = "m6a.32xlarge"
	Ec2InstanceTypeM6a48xlarge        = "m6a.48xlarge"
	Ec2InstanceTypeM6gMetal           = "m6g.metal"
	Ec2InstanceTypeM6gMedium          = "m6g.medium"
	Ec2InstanceTypeM6gLarge           = "m6g.large"
	Ec2InstanceTypeM6gXlarge          = "m6g.xlarge"
	Ec2InstanceTypeM6g2xlarge         = "m6g.2xlarge"
	Ec2InstanceTypeM6g4xlarge         = "m6g.4xlarge"
	Ec2InstanceTypeM6g8xlarge         = "m6g.8xlarge"
	Ec2InstanceTypeM6g12xlarge        = "m6g.12xlarge"
	Ec2InstanceTypeM6g16xlarge        = "m6g.16xlarge"
	Ec2InstanceTypeM6gdMetal          = "m6gd.metal"
	Ec2InstanceTypeM6gdMedium         = "m6gd.medium"
	Ec2InstanceTypeM6gdLarge          = "m6gd.large"
	Ec2InstanceTypeM6gdXlarge         = "m6gd.xlarge"
	Ec2InstanceTypeM6gd2xlarge        = "m6gd.2xlarge"
	Ec2InstanceTypeM6gd4xlarge        = "m6gd.4xlarge"
	Ec2InstanceTypeM6gd8xlarge        = "m6gd.8xlarge"
	Ec2InstanceTypeM6gd12xlarge       = "m6gd.12xlarge"
	Ec2InstanceTypeM6gd16xlarge       = "m6gd.16xlarge"
	Ec2InstanceTypeM6iLarge           = "m6i.large"
	Ec2InstanceTypeM6iXlarge          = "m6i.xlarge"
	Ec2InstanceTypeM6i2xlarge         = "m6i.2xlarge"
	Ec2InstanceTypeM6i4xlarge         = "m6i.4xlarge"
	Ec2InstanceTypeM6i8xlarge         = "m6i.8xlarge"
	Ec2InstanceTypeM6i12xlarge        = "m6i.12xlarge"
	Ec2InstanceTypeM6i16xlarge        = "m6i.16xlarge"
	Ec2InstanceTypeM6i24xlarge        = "m6i.24xlarge"
	Ec2InstanceTypeM6i32xlarge        = "m6i.32xlarge"
	Ec2InstanceTypeM6iMetal           = "m6i.metal"
	Ec2InstanceTypeMac1Metal          = "mac1.metal"
	Ec2InstanceTypeP2Xlarge           = "p2.xlarge"
	Ec2InstanceTypeP28xlarge          = "p2.8xlarge"
	Ec2InstanceTypeP216xlarge         = "p2.16xlarge"
	Ec2InstanceTypeP32xlarge          = "p3.2xlarge"
	Ec2InstanceTypeP38xlarge          = "p3.8xlarge"
	Ec2InstanceTypeP316xlarge         = "p3.16xlarge"
	Ec2InstanceTypeP3dn24xlarge       = "p3dn.24xlarge"
	Ec2InstanceTypeP4d24xlarge        = "p4d.24xlarge"
	Ec2InstanceTypeR3Large            = "r3.large"
	Ec2InstanceTypeR3Xlarge           = "r3.xlarge"
	Ec2InstanceTypeR32xlarge          = "r3.2xlarge"
	Ec2InstanceTypeR34xlarge          = "r3.4xlarge"
	Ec2InstanceTypeR38xlarge          = "r3.8xlarge"
	Ec2InstanceTypeR4Large            = "r4.large"
	Ec2InstanceTypeR4Xlarge           = "r4.xlarge"
	Ec2InstanceTypeR42xlarge          = "r4.2xlarge"
	Ec2InstanceTypeR44xlarge          = "r4.4xlarge"
	Ec2InstanceTypeR48xlarge          = "r4.8xlarge"
	Ec2InstanceTypeR416xlarge         = "r4.16xlarge"
	Ec2InstanceTypeR5Large            = "r5.large"
	Ec2InstanceTypeR5Xlarge           = "r5.xlarge"
	Ec2InstanceTypeR52xlarge          = "r5.2xlarge"
	Ec2InstanceTypeR54xlarge          = "r5.4xlarge"
	Ec2InstanceTypeR58xlarge          = "r5.8xlarge"
	Ec2InstanceTypeR512xlarge         = "r5.12xlarge"
	Ec2InstanceTypeR516xlarge         = "r5.16xlarge"
	Ec2InstanceTypeR524xlarge         = "r5.24xlarge"
	Ec2InstanceTypeR5Metal            = "r5.metal"
	Ec2InstanceTypeR5aLarge           = "r5a.large"
	Ec2InstanceTypeR5aXlarge          = "r5a.xlarge"
	Ec2InstanceTypeR5a2xlarge         = "r5a.2xlarge"
	Ec2InstanceTypeR5a4xlarge         = "r5a.4xlarge"
	Ec2InstanceTypeR5a8xlarge         = "r5a.8xlarge"
	Ec2InstanceTypeR5a12xlarge        = "r5a.12xlarge"
	Ec2InstanceTypeR5a16xlarge        = "r5a.16xlarge"
	Ec2InstanceTypeR5a24xlarge        = "r5a.24xlarge"
	Ec2InstanceTypeR5adLarge          = "r5ad.large"
	Ec2InstanceTypeR5adXlarge         = "r5ad.xlarge"
	Ec2InstanceTypeR5ad2xlarge        = "r5ad.2xlarge"
	Ec2InstanceTypeR5ad4xlarge        = "r5ad.4xlarge"
	Ec2InstanceTypeR5ad8xlarge        = "r5ad.8xlarge"
	Ec2InstanceTypeR5ad12xlarge       = "r5ad.12xlarge"
	Ec2InstanceTypeR5ad16xlarge       = "r5ad.16xlarge"
	Ec2InstanceTypeR5ad24xlarge       = "r5ad.24xlarge"
	Ec2InstanceTypeR5bLarge           = "r5b.large"
	Ec2InstanceTypeR5bXlarge          = "r5b.xlarge"
	Ec2InstanceTypeR5b2xlarge         = "r5b.2xlarge"
	Ec2InstanceTypeR5b4xlarge         = "r5b.4xlarge"
	Ec2InstanceTypeR5b8xlarge         = "r5b.8xlarge"
	Ec2InstanceTypeR5b12xlarge        = "r5b.12xlarge"
	Ec2InstanceTypeR5b16xlarge        = "r5b.16xlarge"
	Ec2InstanceTypeR5b24xlarge        = "r5b.24xlarge"
	Ec2InstanceTypeR5bMetal           = "r5b.metal"
	Ec2InstanceTypeR5dLarge           = "r5d.large"
	Ec2InstanceTypeR5dXlarge          = "r5d.xlarge"
	Ec2InstanceTypeR5d2xlarge         = "r5d.2xlarge"
	Ec2InstanceTypeR5d4xlarge         = "r5d.4xlarge"
	Ec2InstanceTypeR5d8xlarge         = "r5d.8xlarge"
	Ec2InstanceTypeR5d12xlarge        = "r5d.12xlarge"
	Ec2InstanceTypeR5d16xlarge        = "r5d.16xlarge"
	Ec2InstanceTypeR5d24xlarge        = "r5d.24xlarge"
	Ec2InstanceTypeR5dMetal           = "r5d.metal"
	Ec2InstanceTypeR5dnLarge          = "r5dn.large"
	Ec2InstanceTypeR5dnXlarge         = "r5dn.xlarge"
	Ec2InstanceTypeR5dn2xlarge        = "r5dn.2xlarge"
	Ec2InstanceTypeR5dn4xlarge        = "r5dn.4xlarge"
	Ec2InstanceTypeR5dn8xlarge        = "r5dn.8xlarge"
	Ec2InstanceTypeR5dn12xlarge       = "r5dn.12xlarge"
	Ec2InstanceTypeR5dn16xlarge       = "r5dn.16xlarge"
	Ec2InstanceTypeR5dn24xlarge       = "r5dn.24xlarge"
	Ec2InstanceTypeR5dnMetal          = "r5dn.metal"
	Ec2InstanceTypeR5nLarge           = "r5n.large"
	Ec2InstanceTypeR5nXlarge          = "r5n.xlarge"
	Ec2InstanceTypeR5n2xlarge         = "r5n.2xlarge"
	Ec2InstanceTypeR5n4xlarge         = "r5n.4xlarge"
	Ec2InstanceTypeR5n8xlarge         = "r5n.8xlarge"
	Ec2InstanceTypeR5n12xlarge        = "r5n.12xlarge"
	Ec2InstanceTypeR5n16xlarge        = "r5n.16xlarge"
	Ec2InstanceTypeR5n24xlarge        = "r5n.24xlarge"
	Ec2InstanceTypeR5nMetal           = "r5n.metal"
	Ec2InstanceTypeR6gMedium          = "r6g.medium"
	Ec2InstanceTypeR6gLarge           = "r6g.large"
	Ec2InstanceTypeR6gXlarge          = "r6g.xlarge"
	Ec2InstanceTypeR6g2xlarge         = "r6g.2xlarge"
	Ec2InstanceTypeR6g4xlarge         = "r6g.4xlarge"
	Ec2InstanceTypeR6g8xlarge         = "r6g.8xlarge"
	Ec2InstanceTypeR6g12xlarge        = "r6g.12xlarge"
	Ec2InstanceTypeR6g16xlarge        = "r6g.16xlarge"
	Ec2InstanceTypeR6gMetal           = "r6g.metal"
	Ec2InstanceTypeR6gdMedium         = "r6gd.medium"
	Ec2InstanceTypeR6gdLarge          = "r6gd.large"
	Ec2InstanceTypeR6gdXlarge         = "r6gd.xlarge"
	Ec2InstanceTypeR6gd2xlarge        = "r6gd.2xlarge"
	Ec2InstanceTypeR6gd4xlarge        = "r6gd.4xlarge"
	Ec2InstanceTypeR6gd8xlarge        = "r6gd.8xlarge"
	Ec2InstanceTypeR6gd12xlarge       = "r6gd.12xlarge"
	Ec2InstanceTypeR6gd16xlarge       = "r6gd.16xlarge"
	Ec2InstanceTypeR6gdMetal          = "r6gd.metal"
	Ec2InstanceTypeR6iLarge           = "r6i.large"
	Ec2InstanceTypeR6iXlarge          = "r6i.xlarge"
	Ec2InstanceTypeR6i2xlarge         = "r6i.2xlarge"
	Ec2InstanceTypeR6i4xlarge         = "r6i.4xlarge"
	Ec2InstanceTypeR6i8xlarge         = "r6i.8xlarge"
	Ec2InstanceTypeR6i12xlarge        = "r6i.12xlarge"
	Ec2InstanceTypeR6i16xlarge        = "r6i.16xlarge"
	Ec2InstanceTypeR6i24xlarge        = "r6i.24xlarge"
	Ec2InstanceTypeR6i32xlarge        = "r6i.32xlarge"
	Ec2InstanceTypeR6iMetal           = "r6i.metal"
	Ec2InstanceTypeT1Micro            = "t1.micro"
	Ec2InstanceTypeT2Nano             = "t2.nano"
	Ec2InstanceTypeT2Micro            = "t2.micro"
	Ec2InstanceTypeT2Small            = "t2.small"
	Ec2InstanceTypeT2Medium           = "t2.medium"
	Ec2InstanceTypeT2Large            = "t2.large"
	Ec2InstanceTypeT2Xlarge           = "t2.xlarge"
	Ec2InstanceTypeT22xlarge          = "t2.2xlarge"
	Ec2InstanceTypeT3Nano             = "t3.nano"
	Ec2InstanceTypeT3Micro            = "t3.micro"
	Ec2InstanceTypeT3Small            = "t3.small"
	Ec2InstanceTypeT3Medium           = "t3.medium"
	Ec2InstanceTypeT3Large            = "t3.large"
	Ec2InstanceTypeT3Xlarge           = "t3.xlarge"
	Ec2InstanceTypeT32xlarge          = "t3.2xlarge"
	Ec2InstanceTypeT3aNano            = "t3a.nano"
	Ec2InstanceTypeT3aMicro           = "t3a.micro"
	Ec2InstanceTypeT3aSmall           = "t3a.small"
	Ec2InstanceTypeT3aMedium          = "t3a.medium"
	Ec2InstanceTypeT3aLarge           = "t3a.large"
	Ec2InstanceTypeT3aXlarge          = "t3a.xlarge"
	Ec2InstanceTypeT3a2xlarge         = "t3a.2xlarge"
	Ec2InstanceTypeT4gNano            = "t4g.nano"
	Ec2InstanceTypeT4gMicro           = "t4g.micro"
	Ec2InstanceTypeT4gSmall           = "t4g.small"
	Ec2InstanceTypeT4gMedium          = "t4g.medium"
	Ec2InstanceTypeT4gLarge           = "t4g.large"
	Ec2InstanceTypeT4gXlarge          = "t4g.xlarge"
	Ec2InstanceTypeT4g2xlarge         = "t4g.2xlarge"
	Ec2InstanceTypeU6tb156xlarge      = "u-6tb1.56xlarge"
	Ec2InstanceTypeU6tb1112xlarge     = "u-6tb1.112xlarge"
	Ec2InstanceTypeU9tb1112xlarge     = "u-9tb1.112xlarge"
	Ec2InstanceTypeU12tb1112xlarge    = "u-12tb1.112xlarge"
	Ec2InstanceTypeU6tb1Metal         = "u-6tb1.metal"
	Ec2InstanceTypeU9tb1Metal         = "u-9tb1.metal"
	Ec2InstanceTypeU12tb1Metal        = "u-12tb1.metal"
	Ec2InstanceTypeU18tb1Metal        = "u-18tb1.metal"
	Ec2InstanceTypeU24tb1Metal        = "u-24tb1.metal"
	Ec2InstanceTypeVt13xlarge         = "vt1.3xlarge"
	Ec2InstanceTypeVt16xlarge         = "vt1.6xlarge"
	Ec2InstanceTypeVt124xlarge        = "vt1.24xlarge"
	Ec2InstanceTypeX116xlarge         = "x1.16xlarge"
	Ec2InstanceTypeX132xlarge         = "x1.32xlarge"
	Ec2InstanceTypeX1eXlarge          = "x1e.xlarge"
	Ec2InstanceTypeX1e2xlarge         = "x1e.2xlarge"
	Ec2InstanceTypeX1e4xlarge         = "x1e.4xlarge"
	Ec2InstanceTypeX1e8xlarge         = "x1e.8xlarge"
	Ec2InstanceTypeX1e16xlarge        = "x1e.16xlarge"
	Ec2InstanceTypeX1e32xlarge        = "x1e.32xlarge"
	Ec2InstanceTypeX2iezn2xlarge      = "x2iezn.2xlarge"
	Ec2InstanceTypeX2iezn4xlarge      = "x2iezn.4xlarge"
	Ec2InstanceTypeX2iezn6xlarge      = "x2iezn.6xlarge"
	Ec2InstanceTypeX2iezn8xlarge      = "x2iezn.8xlarge"
	Ec2InstanceTypeX2iezn12xlarge     = "x2iezn.12xlarge"
	Ec2InstanceTypeX2ieznMetal        = "x2iezn.metal"
	Ec2InstanceTypeX2gdMedium         = "x2gd.medium"
	Ec2InstanceTypeX2gdLarge          = "x2gd.large"
	Ec2InstanceTypeX2gdXlarge         = "x2gd.xlarge"
	Ec2InstanceTypeX2gd2xlarge        = "x2gd.2xlarge"
	Ec2InstanceTypeX2gd4xlarge        = "x2gd.4xlarge"
	Ec2InstanceTypeX2gd8xlarge        = "x2gd.8xlarge"
	Ec2InstanceTypeX2gd12xlarge       = "x2gd.12xlarge"
	Ec2InstanceTypeX2gd16xlarge       = "x2gd.16xlarge"
	Ec2InstanceTypeX2gdMetal          = "x2gd.metal"
	Ec2InstanceTypeZ1dLarge           = "z1d.large"
	Ec2InstanceTypeZ1dXlarge          = "z1d.xlarge"
	Ec2InstanceTypeZ1d2xlarge         = "z1d.2xlarge"
	Ec2InstanceTypeZ1d3xlarge         = "z1d.3xlarge"
	Ec2InstanceTypeZ1d6xlarge         = "z1d.6xlarge"
	Ec2InstanceTypeZ1d12xlarge        = "z1d.12xlarge"
	Ec2InstanceTypeZ1dMetal           = "z1d.metal"
	Ec2InstanceTypeX2idn16xlarge      = "x2idn.16xlarge"
	Ec2InstanceTypeX2idn24xlarge      = "x2idn.24xlarge"
	Ec2InstanceTypeX2idn32xlarge      = "x2idn.32xlarge"
	Ec2InstanceTypeX2iednXlarge       = "x2iedn.xlarge"
	Ec2InstanceTypeX2iedn2xlarge      = "x2iedn.2xlarge"
	Ec2InstanceTypeX2iedn4xlarge      = "x2iedn.4xlarge"
	Ec2InstanceTypeX2iedn8xlarge      = "x2iedn.8xlarge"
	Ec2InstanceTypeX2iedn16xlarge     = "x2iedn.16xlarge"
	Ec2InstanceTypeX2iedn24xlarge     = "x2iedn.24xlarge"
	Ec2InstanceTypeX2iedn32xlarge     = "x2iedn.32xlarge"
	Ec2InstanceTypeC6aLarge           = "c6a.large"
	Ec2InstanceTypeC6aXlarge          = "c6a.xlarge"
	Ec2InstanceTypeC6a2xlarge         = "c6a.2xlarge"
	Ec2InstanceTypeC6a4xlarge         = "c6a.4xlarge"
	Ec2InstanceTypeC6a8xlarge         = "c6a.8xlarge"
	Ec2InstanceTypeC6a12xlarge        = "c6a.12xlarge"
	Ec2InstanceTypeC6a16xlarge        = "c6a.16xlarge"
	Ec2InstanceTypeC6a24xlarge        = "c6a.24xlarge"
	Ec2InstanceTypeC6a32xlarge        = "c6a.32xlarge"
	Ec2InstanceTypeC6a48xlarge        = "c6a.48xlarge"
	Ec2InstanceTypeC6aMetal           = "c6a.metal"
	Ec2InstanceTypeM6aMetal           = "m6a.metal"
	Ec2InstanceTypeI4iLarge           = "i4i.large"
	Ec2InstanceTypeI4iXlarge          = "i4i.xlarge"
	Ec2InstanceTypeI4i2xlarge         = "i4i.2xlarge"
	Ec2InstanceTypeI4i4xlarge         = "i4i.4xlarge"
	Ec2InstanceTypeI4i8xlarge         = "i4i.8xlarge"
	Ec2InstanceTypeI4i16xlarge        = "i4i.16xlarge"
	Ec2InstanceTypeI4i32xlarge        = "i4i.32xlarge"
	Ec2InstanceTypeI4iMetal           = "i4i.metal"
	Ec2InstanceTypeX2idnMetal         = "x2idn.metal"
	Ec2InstanceTypeX2iednMetal        = "x2iedn.metal"
	Ec2InstanceTypeC7gMedium          = "c7g.medium"
	Ec2InstanceTypeC7gLarge           = "c7g.large"
	Ec2InstanceTypeC7gXlarge          = "c7g.xlarge"
	Ec2InstanceTypeC7g2xlarge         = "c7g.2xlarge"
	Ec2InstanceTypeC7g4xlarge         = "c7g.4xlarge"
	Ec2InstanceTypeC7g8xlarge         = "c7g.8xlarge"
	Ec2InstanceTypeC7g12xlarge        = "c7g.12xlarge"
	Ec2InstanceTypeC7g16xlarge        = "c7g.16xlarge"
	Ec2InstanceTypeMac2Metal          = "mac2.metal"
	Ec2InstanceTypeC6idLarge          = "c6id.large"
	Ec2InstanceTypeC6idXlarge         = "c6id.xlarge"
	Ec2InstanceTypeC6id2xlarge        = "c6id.2xlarge"
	Ec2InstanceTypeC6id4xlarge        = "c6id.4xlarge"
	Ec2InstanceTypeC6id8xlarge        = "c6id.8xlarge"
	Ec2InstanceTypeC6id12xlarge       = "c6id.12xlarge"
	Ec2InstanceTypeC6id16xlarge       = "c6id.16xlarge"
	Ec2InstanceTypeC6id24xlarge       = "c6id.24xlarge"
	Ec2InstanceTypeC6id32xlarge       = "c6id.32xlarge"
	Ec2InstanceTypeC6idMetal          = "c6id.metal"
	Ec2InstanceTypeM6idLarge          = "m6id.large"
	Ec2InstanceTypeM6idXlarge         = "m6id.xlarge"
	Ec2InstanceTypeM6id2xlarge        = "m6id.2xlarge"
	Ec2InstanceTypeM6id4xlarge        = "m6id.4xlarge"
	Ec2InstanceTypeM6id8xlarge        = "m6id.8xlarge"
	Ec2InstanceTypeM6id12xlarge       = "m6id.12xlarge"
	Ec2InstanceTypeM6id16xlarge       = "m6id.16xlarge"
	Ec2InstanceTypeM6id24xlarge       = "m6id.24xlarge"
	Ec2InstanceTypeM6id32xlarge       = "m6id.32xlarge"
	Ec2InstanceTypeM6idMetal          = "m6id.metal"
	Ec2InstanceTypeR6idLarge          = "r6id.large"
	Ec2InstanceTypeR6idXlarge         = "r6id.xlarge"
	Ec2InstanceTypeR6id2xlarge        = "r6id.2xlarge"
	Ec2InstanceTypeR6id4xlarge        = "r6id.4xlarge"
	Ec2InstanceTypeR6id8xlarge        = "r6id.8xlarge"
	Ec2InstanceTypeR6id12xlarge       = "r6id.12xlarge"
	Ec2InstanceTypeR6id16xlarge       = "r6id.16xlarge"
	Ec2InstanceTypeR6id24xlarge       = "r6id.24xlarge"
	Ec2InstanceTypeR6id32xlarge       = "r6id.32xlarge"
	Ec2InstanceTypeR6idMetal          = "r6id.metal"
	Ec2InstanceTypeR6aLarge           = "r6a.large"
	Ec2InstanceTypeR6aXlarge          = "r6a.xlarge"
	Ec2InstanceTypeR6a2xlarge         = "r6a.2xlarge"
	Ec2InstanceTypeR6a4xlarge         = "r6a.4xlarge"
	Ec2InstanceTypeR6a8xlarge         = "r6a.8xlarge"
	Ec2InstanceTypeR6a12xlarge        = "r6a.12xlarge"
	Ec2InstanceTypeR6a16xlarge        = "r6a.16xlarge"
	Ec2InstanceTypeR6a24xlarge        = "r6a.24xlarge"
	Ec2InstanceTypeR6a32xlarge        = "r6a.32xlarge"
	Ec2InstanceTypeR6a48xlarge        = "r6a.48xlarge"
	Ec2InstanceTypeR6aMetal           = "r6a.metal"
	Ec2InstanceTypeP4de24xlarge       = "p4de.24xlarge"
	Ec2InstanceTypeU3tb156xlarge      = "u-3tb1.56xlarge"
	Ec2InstanceTypeU18tb1112xlarge    = "u-18tb1.112xlarge"
	Ec2InstanceTypeU24tb1112xlarge    = "u-24tb1.112xlarge"
	Ec2InstanceTypeTrn12xlarge        = "trn1.2xlarge"
	Ec2InstanceTypeTrn132xlarge       = "trn1.32xlarge"
	Ec2InstanceTypeHpc6id32xlarge     = "hpc6id.32xlarge"
	Ec2InstanceTypeC6inLarge          = "c6in.large"
	Ec2InstanceTypeC6inXlarge         = "c6in.xlarge"
	Ec2InstanceTypeC6in2xlarge        = "c6in.2xlarge"
	Ec2InstanceTypeC6in4xlarge        = "c6in.4xlarge"
	Ec2InstanceTypeC6in8xlarge        = "c6in.8xlarge"
	Ec2InstanceTypeC6in12xlarge       = "c6in.12xlarge"
	Ec2InstanceTypeC6in16xlarge       = "c6in.16xlarge"
	Ec2InstanceTypeC6in24xlarge       = "c6in.24xlarge"
	Ec2InstanceTypeC6in32xlarge       = "c6in.32xlarge"
	Ec2InstanceTypeM6inLarge          = "m6in.large"
	Ec2InstanceTypeM6inXlarge         = "m6in.xlarge"
	Ec2InstanceTypeM6in2xlarge        = "m6in.2xlarge"
	Ec2InstanceTypeM6in4xlarge        = "m6in.4xlarge"
	Ec2InstanceTypeM6in8xlarge        = "m6in.8xlarge"
	Ec2InstanceTypeM6in12xlarge       = "m6in.12xlarge"
	Ec2InstanceTypeM6in16xlarge       = "m6in.16xlarge"
	Ec2InstanceTypeM6in24xlarge       = "m6in.24xlarge"
	Ec2InstanceTypeM6in32xlarge       = "m6in.32xlarge"
	Ec2InstanceTypeM6idnLarge         = "m6idn.large"
	Ec2InstanceTypeM6idnXlarge        = "m6idn.xlarge"
	Ec2InstanceTypeM6idn2xlarge       = "m6idn.2xlarge"
	Ec2InstanceTypeM6idn4xlarge       = "m6idn.4xlarge"
	Ec2InstanceTypeM6idn8xlarge       = "m6idn.8xlarge"
	Ec2InstanceTypeM6idn12xlarge      = "m6idn.12xlarge"
	Ec2InstanceTypeM6idn16xlarge      = "m6idn.16xlarge"
	Ec2InstanceTypeM6idn24xlarge      = "m6idn.24xlarge"
	Ec2InstanceTypeM6idn32xlarge      = "m6idn.32xlarge"
	Ec2InstanceTypeR6inLarge          = "r6in.large"
	Ec2InstanceTypeR6inXlarge         = "r6in.xlarge"
	Ec2InstanceTypeR6in2xlarge        = "r6in.2xlarge"
	Ec2InstanceTypeR6in4xlarge        = "r6in.4xlarge"
	Ec2InstanceTypeR6in8xlarge        = "r6in.8xlarge"
	Ec2InstanceTypeR6in12xlarge       = "r6in.12xlarge"
	Ec2InstanceTypeR6in16xlarge       = "r6in.16xlarge"
	Ec2InstanceTypeR6in24xlarge       = "r6in.24xlarge"
	Ec2InstanceTypeR6in32xlarge       = "r6in.32xlarge"
	Ec2InstanceTypeR6idnLarge         = "r6idn.large"
	Ec2InstanceTypeR6idnXlarge        = "r6idn.xlarge"
	Ec2InstanceTypeR6idn2xlarge       = "r6idn.2xlarge"
	Ec2InstanceTypeR6idn4xlarge       = "r6idn.4xlarge"
	Ec2InstanceTypeR6idn8xlarge       = "r6idn.8xlarge"
	Ec2InstanceTypeR6idn12xlarge      = "r6idn.12xlarge"
	Ec2InstanceTypeR6idn16xlarge      = "r6idn.16xlarge"
	Ec2InstanceTypeR6idn24xlarge      = "r6idn.24xlarge"
	Ec2InstanceTypeR6idn32xlarge      = "r6idn.32xlarge"
	Ec2InstanceTypeC7gMetal           = "c7g.metal"
	Ec2InstanceTypeM7gMedium          = "m7g.medium"
	Ec2InstanceTypeM7gLarge           = "m7g.large"
	Ec2InstanceTypeM7gXlarge          = "m7g.xlarge"
	Ec2InstanceTypeM7g2xlarge         = "m7g.2xlarge"
	Ec2InstanceTypeM7g4xlarge         = "m7g.4xlarge"
	Ec2InstanceTypeM7g8xlarge         = "m7g.8xlarge"
	Ec2InstanceTypeM7g12xlarge        = "m7g.12xlarge"
	Ec2InstanceTypeM7g16xlarge        = "m7g.16xlarge"
	Ec2InstanceTypeM7gMetal           = "m7g.metal"
	Ec2InstanceTypeR7gMedium          = "r7g.medium"
	Ec2InstanceTypeR7gLarge           = "r7g.large"
	Ec2InstanceTypeR7gXlarge          = "r7g.xlarge"
	Ec2InstanceTypeR7g2xlarge         = "r7g.2xlarge"
	Ec2InstanceTypeR7g4xlarge         = "r7g.4xlarge"
	Ec2InstanceTypeR7g8xlarge         = "r7g.8xlarge"
	Ec2InstanceTypeR7g12xlarge        = "r7g.12xlarge"
	Ec2InstanceTypeR7g16xlarge        = "r7g.16xlarge"
	Ec2InstanceTypeR7gMetal           = "r7g.metal"
	Ec2InstanceTypeC6inMetal          = "c6in.metal"
	Ec2InstanceTypeM6inMetal          = "m6in.metal"
	Ec2InstanceTypeM6idnMetal         = "m6idn.metal"
	Ec2InstanceTypeR6inMetal          = "r6in.metal"
	Ec2InstanceTypeR6idnMetal         = "r6idn.metal"
	Ec2InstanceTypeInf2Xlarge         = "inf2.xlarge"
	Ec2InstanceTypeInf28xlarge        = "inf2.8xlarge"
	Ec2InstanceTypeInf224xlarge       = "inf2.24xlarge"
	Ec2InstanceTypeInf248xlarge       = "inf2.48xlarge"
	Ec2InstanceTypeTrn1n32xlarge      = "trn1n.32xlarge"
	Ec2InstanceTypeI4gLarge           = "i4g.large"
	Ec2InstanceTypeI4gXlarge          = "i4g.xlarge"
	Ec2InstanceTypeI4g2xlarge         = "i4g.2xlarge"
	Ec2InstanceTypeI4g4xlarge         = "i4g.4xlarge"
	Ec2InstanceTypeI4g8xlarge         = "i4g.8xlarge"
	Ec2InstanceTypeI4g16xlarge        = "i4g.16xlarge"
	Ec2InstanceTypeHpc7g4xlarge       = "hpc7g.4xlarge"
	Ec2InstanceTypeHpc7g8xlarge       = "hpc7g.8xlarge"
	Ec2InstanceTypeHpc7g16xlarge      = "hpc7g.16xlarge"
	Ec2InstanceTypeC7gnMedium         = "c7gn.medium"
	Ec2InstanceTypeC7gnLarge          = "c7gn.large"
	Ec2InstanceTypeC7gnXlarge         = "c7gn.xlarge"
	Ec2InstanceTypeC7gn2xlarge        = "c7gn.2xlarge"
	Ec2InstanceTypeC7gn4xlarge        = "c7gn.4xlarge"
	Ec2InstanceTypeC7gn8xlarge        = "c7gn.8xlarge"
	Ec2InstanceTypeC7gn12xlarge       = "c7gn.12xlarge"
	Ec2InstanceTypeC7gn16xlarge       = "c7gn.16xlarge"
	Ec2InstanceTypeP548xlarge         = "p5.48xlarge"
	Ec2InstanceTypeM7iLarge           = "m7i.large"
	Ec2InstanceTypeM7iXlarge          = "m7i.xlarge"
	Ec2InstanceTypeM7i2xlarge         = "m7i.2xlarge"
	Ec2InstanceTypeM7i4xlarge         = "m7i.4xlarge"
	Ec2InstanceTypeM7i8xlarge         = "m7i.8xlarge"
	Ec2InstanceTypeM7i12xlarge        = "m7i.12xlarge"
	Ec2InstanceTypeM7i16xlarge        = "m7i.16xlarge"
	Ec2InstanceTypeM7i24xlarge        = "m7i.24xlarge"
	Ec2InstanceTypeM7i48xlarge        = "m7i.48xlarge"
	Ec2InstanceTypeM7iFlexLarge       = "m7i-flex.large"
	Ec2InstanceTypeM7iFlexXlarge      = "m7i-flex.xlarge"
	Ec2InstanceTypeM7iFlex2xlarge     = "m7i-flex.2xlarge"
	Ec2InstanceTypeM7iFlex4xlarge     = "m7i-flex.4xlarge"
	Ec2InstanceTypeM7iFlex8xlarge     = "m7i-flex.8xlarge"
	Ec2InstanceTypeM7aMedium          = "m7a.medium"
	Ec2InstanceTypeM7aLarge           = "m7a.large"
	Ec2InstanceTypeM7aXlarge          = "m7a.xlarge"
	Ec2InstanceTypeM7a2xlarge         = "m7a.2xlarge"
	Ec2InstanceTypeM7a4xlarge         = "m7a.4xlarge"
	Ec2InstanceTypeM7a8xlarge         = "m7a.8xlarge"
	Ec2InstanceTypeM7a12xlarge        = "m7a.12xlarge"
	Ec2InstanceTypeM7a16xlarge        = "m7a.16xlarge"
	Ec2InstanceTypeM7a24xlarge        = "m7a.24xlarge"
	Ec2InstanceTypeM7a32xlarge        = "m7a.32xlarge"
	Ec2InstanceTypeM7a48xlarge        = "m7a.48xlarge"
	Ec2InstanceTypeM7aMetal48xl       = "m7a.metal-48xl"
	Ec2InstanceTypeHpc7a12xlarge      = "hpc7a.12xlarge"
	Ec2InstanceTypeHpc7a24xlarge      = "hpc7a.24xlarge"
	Ec2InstanceTypeHpc7a48xlarge      = "hpc7a.48xlarge"
	Ec2InstanceTypeHpc7a96xlarge      = "hpc7a.96xlarge"
	Ec2InstanceTypeC7gdMedium         = "c7gd.medium"
	Ec2InstanceTypeC7gdLarge          = "c7gd.large"
	Ec2InstanceTypeC7gdXlarge         = "c7gd.xlarge"
	Ec2InstanceTypeC7gd2xlarge        = "c7gd.2xlarge"
	Ec2InstanceTypeC7gd4xlarge        = "c7gd.4xlarge"
	Ec2InstanceTypeC7gd8xlarge        = "c7gd.8xlarge"
	Ec2InstanceTypeC7gd12xlarge       = "c7gd.12xlarge"
	Ec2InstanceTypeC7gd16xlarge       = "c7gd.16xlarge"
	Ec2InstanceTypeM7gdMedium         = "m7gd.medium"
	Ec2InstanceTypeM7gdLarge          = "m7gd.large"
	Ec2InstanceTypeM7gdXlarge         = "m7gd.xlarge"
	Ec2InstanceTypeM7gd2xlarge        = "m7gd.2xlarge"
	Ec2InstanceTypeM7gd4xlarge        = "m7gd.4xlarge"
	Ec2InstanceTypeM7gd8xlarge        = "m7gd.8xlarge"
	Ec2InstanceTypeM7gd12xlarge       = "m7gd.12xlarge"
	Ec2InstanceTypeM7gd16xlarge       = "m7gd.16xlarge"
	Ec2InstanceTypeR7gdMedium         = "r7gd.medium"
	Ec2InstanceTypeR7gdLarge          = "r7gd.large"
	Ec2InstanceTypeR7gdXlarge         = "r7gd.xlarge"
	Ec2InstanceTypeR7gd2xlarge        = "r7gd.2xlarge"
	Ec2InstanceTypeR7gd4xlarge        = "r7gd.4xlarge"
	Ec2InstanceTypeR7gd8xlarge        = "r7gd.8xlarge"
	Ec2InstanceTypeR7gd12xlarge       = "r7gd.12xlarge"
	Ec2InstanceTypeR7gd16xlarge       = "r7gd.16xlarge"
	Ec2InstanceTypeR7aMedium          = "r7a.medium"
	Ec2InstanceTypeR7aLarge           = "r7a.large"
	Ec2InstanceTypeR7aXlarge          = "r7a.xlarge"
	Ec2InstanceTypeR7a2xlarge         = "r7a.2xlarge"
	Ec2InstanceTypeR7a4xlarge         = "r7a.4xlarge"
	Ec2InstanceTypeR7a8xlarge         = "r7a.8xlarge"
	Ec2InstanceTypeR7a12xlarge        = "r7a.12xlarge"
	Ec2InstanceTypeR7a16xlarge        = "r7a.16xlarge"
	Ec2InstanceTypeR7a24xlarge        = "r7a.24xlarge"
	Ec2InstanceTypeR7a32xlarge        = "r7a.32xlarge"
	Ec2InstanceTypeR7a48xlarge        = "r7a.48xlarge"
	Ec2InstanceTypeC7iLarge           = "c7i.large"
	Ec2InstanceTypeC7iXlarge          = "c7i.xlarge"
	Ec2InstanceTypeC7i2xlarge         = "c7i.2xlarge"
	Ec2InstanceTypeC7i4xlarge         = "c7i.4xlarge"
	Ec2InstanceTypeC7i8xlarge         = "c7i.8xlarge"
	Ec2InstanceTypeC7i12xlarge        = "c7i.12xlarge"
	Ec2InstanceTypeC7i16xlarge        = "c7i.16xlarge"
	Ec2InstanceTypeC7i24xlarge        = "c7i.24xlarge"
	Ec2InstanceTypeC7i48xlarge        = "c7i.48xlarge"
	Ec2InstanceTypeMac2M2proMetal     = "mac2-m2pro.metal"
	Ec2InstanceTypeR7izLarge          = "r7iz.large"
	Ec2InstanceTypeR7izXlarge         = "r7iz.xlarge"
	Ec2InstanceTypeR7iz2xlarge        = "r7iz.2xlarge"
	Ec2InstanceTypeR7iz4xlarge        = "r7iz.4xlarge"
	Ec2InstanceTypeR7iz8xlarge        = "r7iz.8xlarge"
	Ec2InstanceTypeR7iz12xlarge       = "r7iz.12xlarge"
	Ec2InstanceTypeR7iz16xlarge       = "r7iz.16xlarge"
	Ec2InstanceTypeR7iz32xlarge       = "r7iz.32xlarge"
	Ec2InstanceTypeC7aMedium          = "c7a.medium"
	Ec2InstanceTypeC7aLarge           = "c7a.large"
	Ec2InstanceTypeC7aXlarge          = "c7a.xlarge"
	Ec2InstanceTypeC7a2xlarge         = "c7a.2xlarge"
	Ec2InstanceTypeC7a4xlarge         = "c7a.4xlarge"
	Ec2InstanceTypeC7a8xlarge         = "c7a.8xlarge"
	Ec2InstanceTypeC7a12xlarge        = "c7a.12xlarge"
	Ec2InstanceTypeC7a16xlarge        = "c7a.16xlarge"
	Ec2InstanceTypeC7a24xlarge        = "c7a.24xlarge"
	Ec2InstanceTypeC7a32xlarge        = "c7a.32xlarge"
	Ec2InstanceTypeC7a48xlarge        = "c7a.48xlarge"
	Ec2InstanceTypeC7aMetal48xl       = "c7a.metal-48xl"
	Ec2InstanceTypeR7aMetal48xl       = "r7a.metal-48xl"
	Ec2InstanceTypeR7iLarge           = "r7i.large"
	Ec2InstanceTypeR7iXlarge          = "r7i.xlarge"
	Ec2InstanceTypeR7i2xlarge         = "r7i.2xlarge"
	Ec2InstanceTypeR7i4xlarge         = "r7i.4xlarge"
	Ec2InstanceTypeR7i8xlarge         = "r7i.8xlarge"
	Ec2InstanceTypeR7i12xlarge        = "r7i.12xlarge"
	Ec2InstanceTypeR7i16xlarge        = "r7i.16xlarge"
	Ec2InstanceTypeR7i24xlarge        = "r7i.24xlarge"
	Ec2InstanceTypeR7i48xlarge        = "r7i.48xlarge"
	Ec2InstanceTypeDl2q24xlarge       = "dl2q.24xlarge"
	Ec2InstanceTypeMac2M2Metal        = "mac2-m2.metal"
	Ec2InstanceTypeI4i12xlarge        = "i4i.12xlarge"
	Ec2InstanceTypeI4i24xlarge        = "i4i.24xlarge"
	Ec2InstanceTypeC7iMetal24xl       = "c7i.metal-24xl"
	Ec2InstanceTypeC7iMetal48xl       = "c7i.metal-48xl"
	Ec2InstanceTypeM7iMetal24xl       = "m7i.metal-24xl"
	Ec2InstanceTypeM7iMetal48xl       = "m7i.metal-48xl"
	Ec2InstanceTypeR7iMetal24xl       = "r7i.metal-24xl"
	Ec2InstanceTypeR7iMetal48xl       = "r7i.metal-48xl"
	Ec2InstanceTypeR7izMetal16xl      = "r7iz.metal-16xl"
	Ec2InstanceTypeR7izMetal32xl      = "r7iz.metal-32xl"
	Ec2InstanceTypeC7gdMetal          = "c7gd.metal"
	Ec2InstanceTypeM7gdMetal          = "m7gd.metal"
	Ec2InstanceTypeR7gdMetal          = "r7gd.metal"
	Ec2InstanceTypeG6Xlarge           = "g6.xlarge"
	Ec2InstanceTypeG62xlarge          = "g6.2xlarge"
	Ec2InstanceTypeG64xlarge          = "g6.4xlarge"
	Ec2InstanceTypeG68xlarge          = "g6.8xlarge"
	Ec2InstanceTypeG612xlarge         = "g6.12xlarge"
	Ec2InstanceTypeG616xlarge         = "g6.16xlarge"
	Ec2InstanceTypeG624xlarge         = "g6.24xlarge"
	Ec2InstanceTypeG648xlarge         = "g6.48xlarge"
	Ec2InstanceTypeGr64xlarge         = "gr6.4xlarge"
	Ec2InstanceTypeGr68xlarge         = "gr6.8xlarge"
	Ec2InstanceTypeC7iFlexLarge       = "c7i-flex.large"
	Ec2InstanceTypeC7iFlexXlarge      = "c7i-flex.xlarge"
	Ec2InstanceTypeC7iFlex2xlarge     = "c7i-flex.2xlarge"
	Ec2InstanceTypeC7iFlex4xlarge     = "c7i-flex.4xlarge"
	Ec2InstanceTypeC7iFlex8xlarge     = "c7i-flex.8xlarge"
	Ec2InstanceTypeU7i12tb224xlarge   = "u7i-12tb.224xlarge"
	Ec2InstanceTypeU7in16tb224xlarge  = "u7in-16tb.224xlarge"
	Ec2InstanceTypeU7in24tb224xlarge  = "u7in-24tb.224xlarge"
	Ec2InstanceTypeU7in32tb224xlarge  = "u7in-32tb.224xlarge"
	Ec2InstanceTypeU7ib12tb224xlarge  = "u7ib-12tb.224xlarge"
	Ec2InstanceTypeC7gnMetal          = "c7gn.metal"
	Ec2InstanceTypeR8gMedium          = "r8g.medium"
	Ec2InstanceTypeR8gLarge           = "r8g.large"
	Ec2InstanceTypeR8gXlarge          = "r8g.xlarge"
	Ec2InstanceTypeR8g2xlarge         = "r8g.2xlarge"
	Ec2InstanceTypeR8g4xlarge         = "r8g.4xlarge"
	Ec2InstanceTypeR8g8xlarge         = "r8g.8xlarge"
	Ec2InstanceTypeR8g12xlarge        = "r8g.12xlarge"
	Ec2InstanceTypeR8g16xlarge        = "r8g.16xlarge"
	Ec2InstanceTypeR8g24xlarge        = "r8g.24xlarge"
	Ec2InstanceTypeR8g48xlarge        = "r8g.48xlarge"
	Ec2InstanceTypeR8gMetal24xl       = "r8g.metal-24xl"
	Ec2InstanceTypeR8gMetal48xl       = "r8g.metal-48xl"
	Ec2InstanceTypeMac2M1ultraMetal   = "mac2-m1ultra.metal"
	Ec2InstanceTypeG6eXlarge          = "g6e.xlarge"
	Ec2InstanceTypeG6e2xlarge         = "g6e.2xlarge"
	Ec2InstanceTypeG6e4xlarge         = "g6e.4xlarge"
	Ec2InstanceTypeG6e8xlarge         = "g6e.8xlarge"
	Ec2InstanceTypeG6e12xlarge        = "g6e.12xlarge"
	Ec2InstanceTypeG6e16xlarge        = "g6e.16xlarge"
	Ec2InstanceTypeG6e24xlarge        = "g6e.24xlarge"
	Ec2InstanceTypeG6e48xlarge        = "g6e.48xlarge"
	Ec2InstanceTypeC8gMedium          = "c8g.medium"
	Ec2InstanceTypeC8gLarge           = "c8g.large"
	Ec2InstanceTypeC8gXlarge          = "c8g.xlarge"
	Ec2InstanceTypeC8g2xlarge         = "c8g.2xlarge"
	Ec2InstanceTypeC8g4xlarge         = "c8g.4xlarge"
	Ec2InstanceTypeC8g8xlarge         = "c8g.8xlarge"
	Ec2InstanceTypeC8g12xlarge        = "c8g.12xlarge"
	Ec2InstanceTypeC8g16xlarge        = "c8g.16xlarge"
	Ec2InstanceTypeC8g24xlarge        = "c8g.24xlarge"
	Ec2InstanceTypeC8g48xlarge        = "c8g.48xlarge"
	Ec2InstanceTypeC8gMetal24xl       = "c8g.metal-24xl"
	Ec2InstanceTypeC8gMetal48xl       = "c8g.metal-48xl"
	Ec2InstanceTypeM8gMedium          = "m8g.medium"
	Ec2InstanceTypeM8gLarge           = "m8g.large"
	Ec2InstanceTypeM8gXlarge          = "m8g.xlarge"
	Ec2InstanceTypeM8g2xlarge         = "m8g.2xlarge"
	Ec2InstanceTypeM8g4xlarge         = "m8g.4xlarge"
	Ec2InstanceTypeM8g8xlarge         = "m8g.8xlarge"
	Ec2InstanceTypeM8g12xlarge        = "m8g.12xlarge"
	Ec2InstanceTypeM8g16xlarge        = "m8g.16xlarge"
	Ec2InstanceTypeM8g24xlarge        = "m8g.24xlarge"
	Ec2InstanceTypeM8g48xlarge        = "m8g.48xlarge"
	Ec2InstanceTypeM8gMetal24xl       = "m8g.metal-24xl"
	Ec2InstanceTypeM8gMetal48xl       = "m8g.metal-48xl"
	Ec2InstanceTypeX8gMedium          = "x8g.medium"
	Ec2InstanceTypeX8gLarge           = "x8g.large"
	Ec2InstanceTypeX8gXlarge          = "x8g.xlarge"
	Ec2InstanceTypeX8g2xlarge         = "x8g.2xlarge"
	Ec2InstanceTypeX8g4xlarge         = "x8g.4xlarge"
	Ec2InstanceTypeX8g8xlarge         = "x8g.8xlarge"
	Ec2InstanceTypeX8g12xlarge        = "x8g.12xlarge"
	Ec2InstanceTypeX8g16xlarge        = "x8g.16xlarge"
	Ec2InstanceTypeX8g24xlarge        = "x8g.24xlarge"
	Ec2InstanceTypeX8g48xlarge        = "x8g.48xlarge"
	Ec2InstanceTypeX8gMetal24xl       = "x8g.metal-24xl"
	Ec2InstanceTypeX8gMetal48xl       = "x8g.metal-48xl"
	Ec2InstanceTypeI7ieLarge          = "i7ie.large"
	Ec2InstanceTypeI7ieXlarge         = "i7ie.xlarge"
	Ec2InstanceTypeI7ie2xlarge        = "i7ie.2xlarge"
	Ec2InstanceTypeI7ie3xlarge        = "i7ie.3xlarge"
	Ec2InstanceTypeI7ie6xlarge        = "i7ie.6xlarge"
	Ec2InstanceTypeI7ie12xlarge       = "i7ie.12xlarge"
	Ec2InstanceTypeI7ie18xlarge       = "i7ie.18xlarge"
	Ec2InstanceTypeI7ie24xlarge       = "i7ie.24xlarge"
	Ec2InstanceTypeI7ie48xlarge       = "i7ie.48xlarge"
	Ec2InstanceTypeI8gLarge           = "i8g.large"
	Ec2InstanceTypeI8gXlarge          = "i8g.xlarge"
	Ec2InstanceTypeI8g2xlarge         = "i8g.2xlarge"
	Ec2InstanceTypeI8g4xlarge         = "i8g.4xlarge"
	Ec2InstanceTypeI8g8xlarge         = "i8g.8xlarge"
	Ec2InstanceTypeI8g12xlarge        = "i8g.12xlarge"
	Ec2InstanceTypeI8g16xlarge        = "i8g.16xlarge"
	Ec2InstanceTypeI8g24xlarge        = "i8g.24xlarge"
	Ec2InstanceTypeI8gMetal24xl       = "i8g.metal-24xl"
	Ec2InstanceTypeU7i6tb112xlarge    = "u7i-6tb.112xlarge"
	Ec2InstanceTypeU7i8tb112xlarge    = "u7i-8tb.112xlarge"
	Ec2InstanceTypeU7inh32tb480xlarge = "u7inh-32tb.480xlarge"
	Ec2InstanceTypeP5e48xlarge        = "p5e.48xlarge"
	Ec2InstanceTypeP5en48xlarge       = "p5en.48xlarge"
	Ec2InstanceTypeF212xlarge         = "f2.12xlarge"
	Ec2InstanceTypeF248xlarge         = "f2.48xlarge"
	Ec2InstanceTypeTrn248xlarge       = "trn2.48xlarge"
	Ec2InstanceTypeC7iFlex12xlarge    = "c7i-flex.12xlarge"
	Ec2InstanceTypeC7iFlex16xlarge    = "c7i-flex.16xlarge"
	Ec2InstanceTypeM7iFlex12xlarge    = "m7i-flex.12xlarge"
	Ec2InstanceTypeM7iFlex16xlarge    = "m7i-flex.16xlarge"
	Ec2InstanceTypeI7ieMetal24xl      = "i7ie.metal-24xl"
	Ec2InstanceTypeI7ieMetal48xl      = "i7ie.metal-48xl"
	Ec2InstanceTypeI8g48xlarge        = "i8g.48xlarge"
	Ec2InstanceTypeC8gdMedium         = "c8gd.medium"
	Ec2InstanceTypeC8gdLarge          = "c8gd.large"
	Ec2InstanceTypeC8gdXlarge         = "c8gd.xlarge"
	Ec2InstanceTypeC8gd2xlarge        = "c8gd.2xlarge"
	Ec2InstanceTypeC8gd4xlarge        = "c8gd.4xlarge"
	Ec2InstanceTypeC8gd8xlarge        = "c8gd.8xlarge"
	Ec2InstanceTypeC8gd12xlarge       = "c8gd.12xlarge"
	Ec2InstanceTypeC8gd16xlarge       = "c8gd.16xlarge"
	Ec2InstanceTypeC8gd24xlarge       = "c8gd.24xlarge"
	Ec2InstanceTypeC8gd48xlarge       = "c8gd.48xlarge"
	Ec2InstanceTypeC8gdMetal24xl      = "c8gd.metal-24xl"
	Ec2InstanceTypeC8gdMetal48xl      = "c8gd.metal-48xl"
	Ec2InstanceTypeI7iLarge           = "i7i.large"
	Ec2InstanceTypeI7iXlarge          = "i7i.xlarge"
	Ec2InstanceTypeI7i2xlarge         = "i7i.2xlarge"
	Ec2InstanceTypeI7i4xlarge         = "i7i.4xlarge"
	Ec2InstanceTypeI7i8xlarge         = "i7i.8xlarge"
	Ec2InstanceTypeI7i12xlarge        = "i7i.12xlarge"
	Ec2InstanceTypeI7i16xlarge        = "i7i.16xlarge"
	Ec2InstanceTypeI7i24xlarge        = "i7i.24xlarge"
	Ec2InstanceTypeI7i48xlarge        = "i7i.48xlarge"
	Ec2InstanceTypeI7iMetal24xl       = "i7i.metal-24xl"
	Ec2InstanceTypeI7iMetal48xl       = "i7i.metal-48xl"
	Ec2InstanceTypeP6B20048xlarge     = "p6-b200.48xlarge"
	Ec2InstanceTypeM8gdMedium         = "m8gd.medium"
	Ec2InstanceTypeM8gdLarge          = "m8gd.large"
	Ec2InstanceTypeM8gdXlarge         = "m8gd.xlarge"
	Ec2InstanceTypeM8gd2xlarge        = "m8gd.2xlarge"
	Ec2InstanceTypeM8gd4xlarge        = "m8gd.4xlarge"
	Ec2InstanceTypeM8gd8xlarge        = "m8gd.8xlarge"
	Ec2InstanceTypeM8gd12xlarge       = "m8gd.12xlarge"
	Ec2InstanceTypeM8gd16xlarge       = "m8gd.16xlarge"
	Ec2InstanceTypeM8gd24xlarge       = "m8gd.24xlarge"
	Ec2InstanceTypeM8gd48xlarge       = "m8gd.48xlarge"
	Ec2InstanceTypeM8gdMetal24xl      = "m8gd.metal-24xl"
	Ec2InstanceTypeM8gdMetal48xl      = "m8gd.metal-48xl"
	Ec2InstanceTypeR8gdMedium         = "r8gd.medium"
	Ec2InstanceTypeR8gdLarge          = "r8gd.large"
	Ec2InstanceTypeR8gdXlarge         = "r8gd.xlarge"
	Ec2InstanceTypeR8gd2xlarge        = "r8gd.2xlarge"
	Ec2InstanceTypeR8gd4xlarge        = "r8gd.4xlarge"
	Ec2InstanceTypeR8gd8xlarge        = "r8gd.8xlarge"
	Ec2InstanceTypeR8gd12xlarge       = "r8gd.12xlarge"
	Ec2InstanceTypeR8gd16xlarge       = "r8gd.16xlarge"
	Ec2InstanceTypeR8gd24xlarge       = "r8gd.24xlarge"
	Ec2InstanceTypeR8gd48xlarge       = "r8gd.48xlarge"
	Ec2InstanceTypeR8gdMetal24xl      = "r8gd.metal-24xl"
	Ec2InstanceTypeR8gdMetal48xl      = "r8gd.metal-48xl"
	Ec2InstanceTypeC8gnMedium         = "c8gn.medium"
	Ec2InstanceTypeC8gnLarge          = "c8gn.large"
	Ec2InstanceTypeC8gnXlarge         = "c8gn.xlarge"
	Ec2InstanceTypeC8gn2xlarge        = "c8gn.2xlarge"
	Ec2InstanceTypeC8gn4xlarge        = "c8gn.4xlarge"
	Ec2InstanceTypeC8gn8xlarge        = "c8gn.8xlarge"
	Ec2InstanceTypeC8gn12xlarge       = "c8gn.12xlarge"
	Ec2InstanceTypeC8gn16xlarge       = "c8gn.16xlarge"
	Ec2InstanceTypeC8gn24xlarge       = "c8gn.24xlarge"
	Ec2InstanceTypeC8gn48xlarge       = "c8gn.48xlarge"
	Ec2InstanceTypeC8gnMetal24xl      = "c8gn.metal-24xl"
	Ec2InstanceTypeC8gnMetal48xl      = "c8gn.metal-48xl"
	Ec2InstanceTypeF26xlarge          = "f2.6xlarge"
	Ec2InstanceTypeP6eGb20036xlarge   = "p6e-gb200.36xlarge"
	Ec2InstanceTypeG6fLarge           = "g6f.large"
	Ec2InstanceTypeG6fXlarge          = "g6f.xlarge"
	Ec2InstanceTypeG6f2xlarge         = "g6f.2xlarge"
	Ec2InstanceTypeG6f4xlarge         = "g6f.4xlarge"
	Ec2InstanceTypeGr6f4xlarge        = "gr6f.4xlarge"
	Ec2InstanceTypeP54xlarge          = "p5.4xlarge"
	Ec2InstanceTypeR8iLarge           = "r8i.large"
	Ec2InstanceTypeR8iXlarge          = "r8i.xlarge"
	Ec2InstanceTypeR8i2xlarge         = "r8i.2xlarge"
	Ec2InstanceTypeR8i4xlarge         = "r8i.4xlarge"
	Ec2InstanceTypeR8i8xlarge         = "r8i.8xlarge"
	Ec2InstanceTypeR8i12xlarge        = "r8i.12xlarge"
	Ec2InstanceTypeR8i16xlarge        = "r8i.16xlarge"
	Ec2InstanceTypeR8i24xlarge        = "r8i.24xlarge"
	Ec2InstanceTypeR8i32xlarge        = "r8i.32xlarge"
	Ec2InstanceTypeR8i48xlarge        = "r8i.48xlarge"
	Ec2InstanceTypeR8i96xlarge        = "r8i.96xlarge"
	Ec2InstanceTypeR8iMetal48xl       = "r8i.metal-48xl"
	Ec2InstanceTypeR8iMetal96xl       = "r8i.metal-96xl"
	Ec2InstanceTypeR8iFlexLarge       = "r8i-flex.large"
	Ec2InstanceTypeR8iFlexXlarge      = "r8i-flex.xlarge"
	Ec2InstanceTypeR8iFlex2xlarge     = "r8i-flex.2xlarge"
	Ec2InstanceTypeR8iFlex4xlarge     = "r8i-flex.4xlarge"
	Ec2InstanceTypeR8iFlex8xlarge     = "r8i-flex.8xlarge"
	Ec2InstanceTypeR8iFlex12xlarge    = "r8i-flex.12xlarge"
	Ec2InstanceTypeR8iFlex16xlarge    = "r8i-flex.16xlarge"
	Ec2InstanceTypeM8iLarge           = "m8i.large"
	Ec2InstanceTypeM8iXlarge          = "m8i.xlarge"
	Ec2InstanceTypeM8i2xlarge         = "m8i.2xlarge"
	Ec2InstanceTypeM8i4xlarge         = "m8i.4xlarge"
	Ec2InstanceTypeM8i8xlarge         = "m8i.8xlarge"
	Ec2InstanceTypeM8i12xlarge        = "m8i.12xlarge"
	Ec2InstanceTypeM8i16xlarge        = "m8i.16xlarge"
	Ec2InstanceTypeM8i24xlarge        = "m8i.24xlarge"
	Ec2InstanceTypeM8i32xlarge        = "m8i.32xlarge"
	Ec2InstanceTypeM8i48xlarge        = "m8i.48xlarge"
	Ec2InstanceTypeM8i96xlarge        = "m8i.96xlarge"
	Ec2InstanceTypeM8iMetal48xl       = "m8i.metal-48xl"
	Ec2InstanceTypeM8iMetal96xl       = "m8i.metal-96xl"
	Ec2InstanceTypeM8iFlexLarge       = "m8i-flex.large"
	Ec2InstanceTypeM8iFlexXlarge      = "m8i-flex.xlarge"
	Ec2InstanceTypeM8iFlex2xlarge     = "m8i-flex.2xlarge"
	Ec2InstanceTypeM8iFlex4xlarge     = "m8i-flex.4xlarge"
	Ec2InstanceTypeM8iFlex8xlarge     = "m8i-flex.8xlarge"
	Ec2InstanceTypeM8iFlex12xlarge    = "m8i-flex.12xlarge"
	Ec2InstanceTypeM8iFlex16xlarge    = "m8i-flex.16xlarge"
	Ec2InstanceTypeI8geLarge          = "i8ge.large"
	Ec2InstanceTypeI8geXlarge         = "i8ge.xlarge"
	Ec2InstanceTypeI8ge2xlarge        = "i8ge.2xlarge"
	Ec2InstanceTypeI8ge3xlarge        = "i8ge.3xlarge"
	Ec2InstanceTypeI8ge6xlarge        = "i8ge.6xlarge"
	Ec2InstanceTypeI8ge12xlarge       = "i8ge.12xlarge"
	Ec2InstanceTypeI8ge18xlarge       = "i8ge.18xlarge"
	Ec2InstanceTypeI8ge24xlarge       = "i8ge.24xlarge"
	Ec2InstanceTypeI8ge48xlarge       = "i8ge.48xlarge"
	Ec2InstanceTypeI8geMetal24xl      = "i8ge.metal-24xl"
	Ec2InstanceTypeI8geMetal48xl      = "i8ge.metal-48xl"
	Ec2InstanceTypeMacM4Metal         = "mac-m4.metal"
	Ec2InstanceTypeMacM4proMetal      = "mac-m4pro.metal"
	Ec2InstanceTypeR8gnMedium         = "r8gn.medium"
	Ec2InstanceTypeR8gnLarge          = "r8gn.large"
	Ec2InstanceTypeR8gnXlarge         = "r8gn.xlarge"
	Ec2InstanceTypeR8gn2xlarge        = "r8gn.2xlarge"
	Ec2InstanceTypeR8gn4xlarge        = "r8gn.4xlarge"
	Ec2InstanceTypeR8gn8xlarge        = "r8gn.8xlarge"
	Ec2InstanceTypeR8gn12xlarge       = "r8gn.12xlarge"
	Ec2InstanceTypeR8gn16xlarge       = "r8gn.16xlarge"
	Ec2InstanceTypeR8gn24xlarge       = "r8gn.24xlarge"
	Ec2InstanceTypeR8gn48xlarge       = "r8gn.48xlarge"
	Ec2InstanceTypeR8gnMetal24xl      = "r8gn.metal-24xl"
	Ec2InstanceTypeR8gnMetal48xl      = "r8gn.metal-48xl"
	Ec2InstanceTypeC8iLarge           = "c8i.large"
	Ec2InstanceTypeC8iXlarge          = "c8i.xlarge"
	Ec2InstanceTypeC8i2xlarge         = "c8i.2xlarge"
	Ec2InstanceTypeC8i4xlarge         = "c8i.4xlarge"
	Ec2InstanceTypeC8i8xlarge         = "c8i.8xlarge"
	Ec2InstanceTypeC8i12xlarge        = "c8i.12xlarge"
	Ec2InstanceTypeC8i16xlarge        = "c8i.16xlarge"
	Ec2InstanceTypeC8i24xlarge        = "c8i.24xlarge"
	Ec2InstanceTypeC8i32xlarge        = "c8i.32xlarge"
	Ec2InstanceTypeC8i48xlarge        = "c8i.48xlarge"
	Ec2InstanceTypeC8i96xlarge        = "c8i.96xlarge"
	Ec2InstanceTypeC8iMetal48xl       = "c8i.metal-48xl"
	Ec2InstanceTypeC8iMetal96xl       = "c8i.metal-96xl"
	Ec2InstanceTypeC8iFlexLarge       = "c8i-flex.large"
	Ec2InstanceTypeC8iFlexXlarge      = "c8i-flex.xlarge"
	Ec2InstanceTypeC8iFlex2xlarge     = "c8i-flex.2xlarge"
	Ec2InstanceTypeC8iFlex4xlarge     = "c8i-flex.4xlarge"
	Ec2InstanceTypeC8iFlex8xlarge     = "c8i-flex.8xlarge"
	Ec2InstanceTypeC8iFlex12xlarge    = "c8i-flex.12xlarge"
	Ec2InstanceTypeC8iFlex16xlarge    = "c8i-flex.16xlarge"
	Ec2InstanceTypeR8gbMedium         = "r8gb.medium"
	Ec2InstanceTypeR8gbLarge          = "r8gb.large"
	Ec2InstanceTypeR8gbXlarge         = "r8gb.xlarge"
	Ec2InstanceTypeR8gb2xlarge        = "r8gb.2xlarge"
	Ec2InstanceTypeR8gb4xlarge        = "r8gb.4xlarge"
	Ec2InstanceTypeR8gb8xlarge        = "r8gb.8xlarge"
	Ec2InstanceTypeR8gb12xlarge       = "r8gb.12xlarge"
	Ec2InstanceTypeR8gb16xlarge       = "r8gb.16xlarge"
	Ec2InstanceTypeR8gb24xlarge       = "r8gb.24xlarge"
	Ec2InstanceTypeR8gbMetal24xl      = "r8gb.metal-24xl"
	Ec2InstanceTypeM8aMedium          = "m8a.medium"
	Ec2InstanceTypeM8aLarge           = "m8a.large"
	Ec2InstanceTypeM8aXlarge          = "m8a.xlarge"
	Ec2InstanceTypeM8a2xlarge         = "m8a.2xlarge"
	Ec2InstanceTypeM8a4xlarge         = "m8a.4xlarge"
	Ec2InstanceTypeM8a8xlarge         = "m8a.8xlarge"
	Ec2InstanceTypeM8a12xlarge        = "m8a.12xlarge"
	Ec2InstanceTypeM8a16xlarge        = "m8a.16xlarge"
	Ec2InstanceTypeM8a24xlarge        = "m8a.24xlarge"
	Ec2InstanceTypeM8a48xlarge        = "m8a.48xlarge"
	Ec2InstanceTypeM8aMetal24xl       = "m8a.metal-24xl"
	Ec2InstanceTypeM8aMetal48xl       = "m8a.metal-48xl"
	Ec2InstanceTypeTrn23xlarge        = "trn2.3xlarge"
	Ec2InstanceTypeR8aMedium          = "r8a.medium"
	Ec2InstanceTypeR8aLarge           = "r8a.large"
	Ec2InstanceTypeR8aXlarge          = "r8a.xlarge"
	Ec2InstanceTypeR8a2xlarge         = "r8a.2xlarge"
	Ec2InstanceTypeR8a4xlarge         = "r8a.4xlarge"
	Ec2InstanceTypeR8a8xlarge         = "r8a.8xlarge"
	Ec2InstanceTypeR8a12xlarge        = "r8a.12xlarge"
	Ec2InstanceTypeR8a16xlarge        = "r8a.16xlarge"
	Ec2InstanceTypeR8a24xlarge        = "r8a.24xlarge"
	Ec2InstanceTypeR8a48xlarge        = "r8a.48xlarge"
	Ec2InstanceTypeR8aMetal24xl       = "r8a.metal-24xl"
	Ec2InstanceTypeR8aMetal48xl       = "r8a.metal-48xl"
	Ec2InstanceTypeP6B30048xlarge     = "p6-b300.48xlarge"
	Ec2InstanceTypeC8aMedium          = "c8a.medium"
	Ec2InstanceTypeC8aLarge           = "c8a.large"
	Ec2InstanceTypeC8aXlarge          = "c8a.xlarge"
	Ec2InstanceTypeC8a2xlarge         = "c8a.2xlarge"
	Ec2InstanceTypeC8a4xlarge         = "c8a.4xlarge"
	Ec2InstanceTypeC8a8xlarge         = "c8a.8xlarge"
	Ec2InstanceTypeC8a12xlarge        = "c8a.12xlarge"
	Ec2InstanceTypeC8a16xlarge        = "c8a.16xlarge"
	Ec2InstanceTypeC8a24xlarge        = "c8a.24xlarge"
	Ec2InstanceTypeC8a48xlarge        = "c8a.48xlarge"
	Ec2InstanceTypeC8aMetal24xl       = "c8a.metal-24xl"
	Ec2InstanceTypeC8aMetal48xl       = "c8a.metal-48xl"

	// VolumeType values
	Ec2VolumeTypeStandard = "standard"
	Ec2VolumeTypeIo1      = "io1"
	Ec2VolumeTypeIo2      = "io2"
	Ec2VolumeTypeGp2      = "gp2"
	Ec2VolumeTypeSc1      = "sc1"
	Ec2VolumeTypeSt1      = "st1"
	Ec2VolumeTypeGp3      = "gp3"
)

var ec2InstanceTypeValues = []string{
	"a1.medium",
	"a1.large",
	"a1.xlarge",
	"a1.2xlarge",
	"a1.4xlarge",
	"a1.metal",
	"c1.medium",
	"c1.xlarge",
	"c3.large",
	"c3.xlarge",
	"c3.2xlarge",
	"c3.4xlarge",
	"c3.8xlarge",
	"c4.large",
	"c4.xlarge",
	"c4.2xlarge",
	"c4.4xlarge",
	"c4.8xlarge",
	"c5.large",
	"c5.xlarge",
	"c5.2xlarge",
	"c5.4xlarge",
	"c5.9xlarge",
	"c5.12xlarge",
	"c5.18xlarge",
	"c5.24xlarge",
	"c5.metal",
	"c5a.large",
	"c5a.xlarge",
	"c5a.2xlarge",
	"c5a.4xlarge",
	"c5a.8xlarge",
	"c5a.12xlarge",
	"c5a.16xlarge",
	"c5a.24xlarge",
	"c5ad.large",
	"c5ad.xlarge",
	"c5ad.2xlarge",
	"c5ad.4xlarge",
	"c5ad.8xlarge",
	"c5ad.12xlarge",
	"c5ad.16xlarge",
	"c5ad.24xlarge",
	"c5d.large",
	"c5d.xlarge",
	"c5d.2xlarge",
	"c5d.4xlarge",
	"c5d.9xlarge",
	"c5d.12xlarge",
	"c5d.18xlarge",
	"c5d.24xlarge",
	"c5d.metal",
	"c5n.large",
	"c5n.xlarge",
	"c5n.2xlarge",
	"c5n.4xlarge",
	"c5n.9xlarge",
	"c5n.18xlarge",
	"c5n.metal",
	"c6g.medium",
	"c6g.large",
	"c6g.xlarge",
	"c6g.2xlarge",
	"c6g.4xlarge",
	"c6g.8xlarge",
	"c6g.12xlarge",
	"c6g.16xlarge",
	"c6g.metal",
	"c6gd.medium",
	"c6gd.large",
	"c6gd.xlarge",
	"c6gd.2xlarge",
	"c6gd.4xlarge",
	"c6gd.8xlarge",
	"c6gd.12xlarge",
	"c6gd.16xlarge",
	"c6gd.metal",
	"c6gn.medium",
	"c6gn.large",
	"c6gn.xlarge",
	"c6gn.2xlarge",
	"c6gn.4xlarge",
	"c6gn.8xlarge",
	"c6gn.12xlarge",
	"c6gn.16xlarge",
	"c6i.large",
	"c6i.xlarge",
	"c6i.2xlarge",
	"c6i.4xlarge",
	"c6i.8xlarge",
	"c6i.12xlarge",
	"c6i.16xlarge",
	"c6i.24xlarge",
	"c6i.32xlarge",
	"c6i.metal",
	"cc1.4xlarge",
	"cc2.8xlarge",
	"cg1.4xlarge",
	"cr1.8xlarge",
	"d2.xlarge",
	"d2.2xlarge",
	"d2.4xlarge",
	"d2.8xlarge",
	"d3.xlarge",
	"d3.2xlarge",
	"d3.4xlarge",
	"d3.8xlarge",
	"d3en.xlarge",
	"d3en.2xlarge",
	"d3en.4xlarge",
	"d3en.6xlarge",
	"d3en.8xlarge",
	"d3en.12xlarge",
	"dl1.24xlarge",
	"f1.2xlarge",
	"f1.4xlarge",
	"f1.16xlarge",
	"g2.2xlarge",
	"g2.8xlarge",
	"g3.4xlarge",
	"g3.8xlarge",
	"g3.16xlarge",
	"g3s.xlarge",
	"g4ad.xlarge",
	"g4ad.2xlarge",
	"g4ad.4xlarge",
	"g4ad.8xlarge",
	"g4ad.16xlarge",
	"g4dn.xlarge",
	"g4dn.2xlarge",
	"g4dn.4xlarge",
	"g4dn.8xlarge",
	"g4dn.12xlarge",
	"g4dn.16xlarge",
	"g4dn.metal",
	"g5.xlarge",
	"g5.2xlarge",
	"g5.4xlarge",
	"g5.8xlarge",
	"g5.12xlarge",
	"g5.16xlarge",
	"g5.24xlarge",
	"g5.48xlarge",
	"g5g.xlarge",
	"g5g.2xlarge",
	"g5g.4xlarge",
	"g5g.8xlarge",
	"g5g.16xlarge",
	"g5g.metal",
	"hi1.4xlarge",
	"hpc6a.48xlarge",
	"hs1.8xlarge",
	"h1.2xlarge",
	"h1.4xlarge",
	"h1.8xlarge",
	"h1.16xlarge",
	"i2.xlarge",
	"i2.2xlarge",
	"i2.4xlarge",
	"i2.8xlarge",
	"i3.large",
	"i3.xlarge",
	"i3.2xlarge",
	"i3.4xlarge",
	"i3.8xlarge",
	"i3.16xlarge",
	"i3.metal",
	"i3en.large",
	"i3en.xlarge",
	"i3en.2xlarge",
	"i3en.3xlarge",
	"i3en.6xlarge",
	"i3en.12xlarge",
	"i3en.24xlarge",
	"i3en.metal",
	"im4gn.large",
	"im4gn.xlarge",
	"im4gn.2xlarge",
	"im4gn.4xlarge",
	"im4gn.8xlarge",
	"im4gn.16xlarge",
	"inf1.xlarge",
	"inf1.2xlarge",
	"inf1.6xlarge",
	"inf1.24xlarge",
	"is4gen.medium",
	"is4gen.large",
	"is4gen.xlarge",
	"is4gen.2xlarge",
	"is4gen.4xlarge",
	"is4gen.8xlarge",
	"m1.small",
	"m1.medium",
	"m1.large",
	"m1.xlarge",
	"m2.xlarge",
	"m2.2xlarge",
	"m2.4xlarge",
	"m3.medium",
	"m3.large",
	"m3.xlarge",
	"m3.2xlarge",
	"m4.large",
	"m4.xlarge",
	"m4.2xlarge",
	"m4.4xlarge",
	"m4.10xlarge",
	"m4.16xlarge",
	"m5.large",
	"m5.xlarge",
	"m5.2xlarge",
	"m5.4xlarge",
	"m5.8xlarge",
	"m5.12xlarge",
	"m5.16xlarge",
	"m5.24xlarge",
	"m5.metal",
	"m5a.large",
	"m5a.xlarge",
	"m5a.2xlarge",
	"m5a.4xlarge",
	"m5a.8xlarge",
	"m5a.12xlarge",
	"m5a.16xlarge",
	"m5a.24xlarge",
	"m5ad.large",
	"m5ad.xlarge",
	"m5ad.2xlarge",
	"m5ad.4xlarge",
	"m5ad.8xlarge",
	"m5ad.12xlarge",
	"m5ad.16xlarge",
	"m5ad.24xlarge",
	"m5d.large",
	"m5d.xlarge",
	"m5d.2xlarge",
	"m5d.4xlarge",
	"m5d.8xlarge",
	"m5d.12xlarge",
	"m5d.16xlarge",
	"m5d.24xlarge",
	"m5d.metal",
	"m5dn.large",
	"m5dn.xlarge",
	"m5dn.2xlarge",
	"m5dn.4xlarge",
	"m5dn.8xlarge",
	"m5dn.12xlarge",
	"m5dn.16xlarge",
	"m5dn.24xlarge",
	"m5dn.metal",
	"m5n.large",
	"m5n.xlarge",
	"m5n.2xlarge",
	"m5n.4xlarge",
	"m5n.8xlarge",
	"m5n.12xlarge",
	"m5n.16xlarge",
	"m5n.24xlarge",
	"m5n.metal",
	"m5zn.large",
	"m5zn.xlarge",
	"m5zn.2xlarge",
	"m5zn.3xlarge",
	"m5zn.6xlarge",
	"m5zn.12xlarge",
	"m5zn.metal",
	"m6a.large",
	"m6a.xlarge",
	"m6a.2xlarge",
	"m6a.4xlarge",
	"m6a.8xlarge",
	"m6a.12xlarge",
	"m6a.16xlarge",
	"m6a.24xlarge",
	"m6a.32xlarge",
	"m6a.48xlarge",
	"m6g.metal",
	"m6g.medium",
	"m6g.large",
	"m6g.xlarge",
	"m6g.2xlarge",
	"m6g.4xlarge",
	"m6g.8xlarge",
	"m6g.12xlarge",
	"m6g.16xlarge",
	"m6gd.metal",
	"m6gd.medium",
	"m6gd.large",
	"m6gd.xlarge",
	"m6gd.2xlarge",
	"m6gd.4xlarge",
	"m6gd.8xlarge",
	"m6gd.12xlarge",
	"m6gd.16xlarge",
	"m6i.large",
	"m6i.xlarge",
	"m6i.2xlarge",
	"m6i.4xlarge",
	"m6i.8xlarge",
	"m6i.12xlarge",
	"m6i.16xlarge",
	"m6i.24xlarge",
	"m6i.32xlarge",
	"m6i.metal",
	"mac1.metal",
	"p2.xlarge",
	"p2.8xlarge",
	"p2.16xlarge",
	"p3.2xlarge",
	"p3.8xlarge",
	"p3.16xlarge",
	"p3dn.24xlarge",
	"p4d.24xlarge",
	"r3.large",
	"r3.xlarge",
	"r3.2xlarge",
	"r3.4xlarge",
	"r3.8xlarge",
	"r4.large",
	"r4.xlarge",
	"r4.2xlarge",
	"r4.4xlarge",
	"r4.8xlarge",
	"r4.16xlarge",
	"r5.large",
	"r5.xlarge",
	"r5.2xlarge",
	"r5.4xlarge",
	"r5.8xlarge",
	"r5.12xlarge",
	"r5.16xlarge",
	"r5.24xlarge",
	"r5.metal",
	"r5a.large",
	"r5a.xlarge",
	"r5a.2xlarge",
	"r5a.4xlarge",
	"r5a.8xlarge",
	"r5a.12xlarge",
	"r5a.16xlarge",
	"r5a.24xlarge",
	"r5ad.large",
	"r5ad.xlarge",
	"r5ad.2xlarge",
	"r5ad.4xlarge",
	"r5ad.8xlarge",
	"r5ad.12xlarge",
	"r5ad.16xlarge",
	"r5ad.24xlarge",
	"r5b.large",
	"r5b.xlarge",
	"r5b.2xlarge",
	"r5b.4xlarge",
	"r5b.8xlarge",
	"r5b.12xlarge",
	"r5b.16xlarge",
	"r5b.24xlarge",
	"r5b.metal",
	"r5d.large",
	"r5d.xlarge",
	"r5d.2xlarge",
	"r5d.4xlarge",
	"r5d.8xlarge",
	"r5d.12xlarge",
	"r5d.16xlarge",
	"r5d.24xlarge",
	"r5d.metal",
	"r5dn.large",
	"r5dn.xlarge",
	"r5dn.2xlarge",
	"r5dn.4xlarge",
	"r5dn.8xlarge",
	"r5dn.12xlarge",
	"r5dn.16xlarge",
	"r5dn.24xlarge",
	"r5dn.metal",
	"r5n.large",
	"r5n.xlarge",
	"r5n.2xlarge",
	"r5n.4xlarge",
	"r5n.8xlarge",
	"r5n.12xlarge",
	"r5n.16xlarge",
	"r5n.24xlarge",
	"r5n.metal",
	"r6g.medium",
	"r6g.large",
	"r6g.xlarge",
	"r6g.2xlarge",
	"r6g.4xlarge",
	"r6g.8xlarge",
	"r6g.12xlarge",
	"r6g.16xlarge",
	"r6g.metal",
	"r6gd.medium",
	"r6gd.large",
	"r6gd.xlarge",
	"r6gd.2xlarge",
	"r6gd.4xlarge",
	"r6gd.8xlarge",
	"r6gd.12xlarge",
	"r6gd.16xlarge",
	"r6gd.metal",
	"r6i.large",
	"r6i.xlarge",
	"r6i.2xlarge",
	"r6i.4xlarge",
	"r6i.8xlarge",
	"r6i.12xlarge",
	"r6i.16xlarge",
	"r6i.24xlarge",
	"r6i.32xlarge",
	"r6i.metal",
	"t1.micro",
	"t2.nano",
	"t2.micro",
	"t2.small",
	"t2.medium",
	"t2.large",
	"t2.xlarge",
	"t2.2xlarge",
	"t3.nano",
	"t3.micro",
	"t3.small",
	"t3.medium",
	"t3.large",
	"t3.xlarge",
	"t3.2xlarge",
	"t3a.nano",
	"t3a.micro",
	"t3a.small",
	"t3a.medium",
	"t3a.large",
	"t3a.xlarge",
	"t3a.2xlarge",
	"t4g.nano",
	"t4g.micro",
	"t4g.small",
	"t4g.medium",
	"t4g.large",
	"t4g.xlarge",
	"t4g.2xlarge",
	"u-6tb1.56xlarge",
	"u-6tb1.112xlarge",
	"u-9tb1.112xlarge",
	"u-12tb1.112xlarge",
	"u-6tb1.metal",
	"u-9tb1.metal",
	"u-12tb1.metal",
	"u-18tb1.metal",
	"u-24tb1.metal",
	"vt1.3xlarge",
	"vt1.6xlarge",
	"vt1.24xlarge",
	"x1.16xlarge",
	"x1.32xlarge",
	"x1e.xlarge",
	"x1e.2xlarge",
	"x1e.4xlarge",
	"x1e.8xlarge",
	"x1e.16xlarge",
	"x1e.32xlarge",
	"x2iezn.2xlarge",
	"x2iezn.4xlarge",
	"x2iezn.6xlarge",
	"x2iezn.8xlarge",
	"x2iezn.12xlarge",
	"x2iezn.metal",
	"x2gd.medium",
	"x2gd.large",
	"x2gd.xlarge",
	"x2gd.2xlarge",
	"x2gd.4xlarge",
	"x2gd.8xlarge",
	"x2gd.12xlarge",
	"x2gd.16xlarge",
	"x2gd.metal",
	"z1d.large",
	"z1d.xlarge",
	"z1d.2xlarge",
	"z1d.3xlarge",
	"z1d.6xlarge",
	"z1d.12xlarge",
	"z1d.metal",
	"x2idn.16xlarge",
	"x2idn.24xlarge",
	"x2idn.32xlarge",
	"x2iedn.xlarge",
	"x2iedn.2xlarge",
	"x2iedn.4xlarge",
	"x2iedn.8xlarge",
	"x2iedn.16xlarge",
	"x2iedn.24xlarge",
	"x2iedn.32xlarge",
	"c6a.large",
	"c6a.xlarge",
	"c6a.2xlarge",
	"c6a.4xlarge",
	"c6a.8xlarge",
	"c6a.12xlarge",
	"c6a.16xlarge",
	"c6a.24xlarge",
	"c6a.32xlarge",
	"c6a.48xlarge",
	"c6a.metal",
	"m6a.metal",
	"i4i.large",
	"i4i.xlarge",
	"i4i.2xlarge",
	"i4i.4xlarge",
	"i4i.8xlarge",
	"i4i.16xlarge",
	"i4i.32xlarge",
	"i4i.metal",
	"x2idn.metal",
	"x2iedn.metal",
	"c7g.medium",
	"c7g.large",
	"c7g.xlarge",
	"c7g.2xlarge",
	"c7g.4xlarge",
	"c7g.8xlarge",
	"c7g.12xlarge",
	"c7g.16xlarge",
	"mac2.metal",
	"c6id.large",
	"c6id.xlarge",
	"c6id.2xlarge",
	"c6id.4xlarge",
	"c6id.8xlarge",
	"c6id.12xlarge",
	"c6id.16xlarge",
	"c6id.24xlarge",
	"c6id.32xlarge",
	"c6id.metal",
	"m6id.large",
	"m6id.xlarge",
	"m6id.2xlarge",
	"m6id.4xlarge",
	"m6id.8xlarge",
	"m6id.12xlarge",
	"m6id.16xlarge",
	"m6id.24xlarge",
	"m6id.32xlarge",
	"m6id.metal",
	"r6id.large",
	"r6id.xlarge",
	"r6id.2xlarge",
	"r6id.4xlarge",
	"r6id.8xlarge",
	"r6id.12xlarge",
	"r6id.16xlarge",
	"r6id.24xlarge",
	"r6id.32xlarge",
	"r6id.metal",
	"r6a.large",
	"r6a.xlarge",
	"r6a.2xlarge",
	"r6a.4xlarge",
	"r6a.8xlarge",
	"r6a.12xlarge",
	"r6a.16xlarge",
	"r6a.24xlarge",
	"r6a.32xlarge",
	"r6a.48xlarge",
	"r6a.metal",
	"p4de.24xlarge",
	"u-3tb1.56xlarge",
	"u-18tb1.112xlarge",
	"u-24tb1.112xlarge",
	"trn1.2xlarge",
	"trn1.32xlarge",
	"hpc6id.32xlarge",
	"c6in.large",
	"c6in.xlarge",
	"c6in.2xlarge",
	"c6in.4xlarge",
	"c6in.8xlarge",
	"c6in.12xlarge",
	"c6in.16xlarge",
	"c6in.24xlarge",
	"c6in.32xlarge",
	"m6in.large",
	"m6in.xlarge",
	"m6in.2xlarge",
	"m6in.4xlarge",
	"m6in.8xlarge",
	"m6in.12xlarge",
	"m6in.16xlarge",
	"m6in.24xlarge",
	"m6in.32xlarge",
	"m6idn.large",
	"m6idn.xlarge",
	"m6idn.2xlarge",
	"m6idn.4xlarge",
	"m6idn.8xlarge",
	"m6idn.12xlarge",
	"m6idn.16xlarge",
	"m6idn.24xlarge",
	"m6idn.32xlarge",
	"r6in.large",
	"r6in.xlarge",
	"r6in.2xlarge",
	"r6in.4xlarge",
	"r6in.8xlarge",
	"r6in.12xlarge",
	"r6in.16xlarge",
	"r6in.24xlarge",
	"r6in.32xlarge",
	"r6idn.large",
	"r6idn.xlarge",
	"r6idn.2xlarge",
	"r6idn.4xlarge",
	"r6idn.8xlarge",
	"r6idn.12xlarge",
	"r6idn.16xlarge",
	"r6idn.24xlarge",
	"r6idn.32xlarge",
	"c7g.metal",
	"m7g.medium",
	"m7g.large",
	"m7g.xlarge",
	"m7g.2xlarge",
	"m7g.4xlarge",
	"m7g.8xlarge",
	"m7g.12xlarge",
	"m7g.16xlarge",
	"m7g.metal",
	"r7g.medium",
	"r7g.large",
	"r7g.xlarge",
	"r7g.2xlarge",
	"r7g.4xlarge",
	"r7g.8xlarge",
	"r7g.12xlarge",
	"r7g.16xlarge",
	"r7g.metal",
	"c6in.metal",
	"m6in.metal",
	"m6idn.metal",
	"r6in.metal",
	"r6idn.metal",
	"inf2.xlarge",
	"inf2.8xlarge",
	"inf2.24xlarge",
	"inf2.48xlarge",
	"trn1n.32xlarge",
	"i4g.large",
	"i4g.xlarge",
	"i4g.2xlarge",
	"i4g.4xlarge",
	"i4g.8xlarge",
	"i4g.16xlarge",
	"hpc7g.4xlarge",
	"hpc7g.8xlarge",
	"hpc7g.16xlarge",
	"c7gn.medium",
	"c7gn.large",
	"c7gn.xlarge",
	"c7gn.2xlarge",
	"c7gn.4xlarge",
	"c7gn.8xlarge",
	"c7gn.12xlarge",
	"c7gn.16xlarge",
	"p5.48xlarge",
	"m7i.large",
	"m7i.xlarge",
	"m7i.2xlarge",
	"m7i.4xlarge",
	"m7i.8xlarge",
	"m7i.12xlarge",
	"m7i.16xlarge",
	"m7i.24xlarge",
	"m7i.48xlarge",
	"m7i-flex.large",
	"m7i-flex.xlarge",
	"m7i-flex.2xlarge",
	"m7i-flex.4xlarge",
	"m7i-flex.8xlarge",
	"m7a.medium",
	"m7a.large",
	"m7a.xlarge",
	"m7a.2xlarge",
	"m7a.4xlarge",
	"m7a.8xlarge",
	"m7a.12xlarge",
	"m7a.16xlarge",
	"m7a.24xlarge",
	"m7a.32xlarge",
	"m7a.48xlarge",
	"m7a.metal-48xl",
	"hpc7a.12xlarge",
	"hpc7a.24xlarge",
	"hpc7a.48xlarge",
	"hpc7a.96xlarge",
	"c7gd.medium",
	"c7gd.large",
	"c7gd.xlarge",
	"c7gd.2xlarge",
	"c7gd.4xlarge",
	"c7gd.8xlarge",
	"c7gd.12xlarge",
	"c7gd.16xlarge",
	"m7gd.medium",
	"m7gd.large",
	"m7gd.xlarge",
	"m7gd.2xlarge",
	"m7gd.4xlarge",
	"m7gd.8xlarge",
	"m7gd.12xlarge",
	"m7gd.16xlarge",
	"r7gd.medium",
	"r7gd.large",
	"r7gd.xlarge",
	"r7gd.2xlarge",
	"r7gd.4xlarge",
	"r7gd.8xlarge",
	"r7gd.12xlarge",
	"r7gd.16xlarge",
	"r7a.medium",
	"r7a.large",
	"r7a.xlarge",
	"r7a.2xlarge",
	"r7a.4xlarge",
	"r7a.8xlarge",
	"r7a.12xlarge",
	"r7a.16xlarge",
	"r7a.24xlarge",
	"r7a.32xlarge",
	"r7a.48xlarge",
	"c7i.large",
	"c7i.xlarge",
	"c7i.2xlarge",
	"c7i.4xlarge",
	"c7i.8xlarge",
	"c7i.12xlarge",
	"c7i.16xlarge",
	"c7i.24xlarge",
	"c7i.48xlarge",
	"mac2-m2pro.metal",
	"r7iz.large",
	"r7iz.xlarge",
	"r7iz.2xlarge",
	"r7iz.4xlarge",
	"r7iz.8xlarge",
	"r7iz.12xlarge",
	"r7iz.16xlarge",
	"r7iz.32xlarge",
	"c7a.medium",
	"c7a.large",
	"c7a.xlarge",
	"c7a.2xlarge",
	"c7a.4xlarge",
	"c7a.8xlarge",
	"c7a.12xlarge",
	"c7a.16xlarge",
	"c7a.24xlarge",
	"c7a.32xlarge",
	"c7a.48xlarge",
	"c7a.metal-48xl",
	"r7a.metal-48xl",
	"r7i.large",
	"r7i.xlarge",
	"r7i.2xlarge",
	"r7i.4xlarge",
	"r7i.8xlarge",
	"r7i.12xlarge",
	"r7i.16xlarge",
	"r7i.24xlarge",
	"r7i.48xlarge",
	"dl2q.24xlarge",
	"mac2-m2.metal",
	"i4i.12xlarge",
	"i4i.24xlarge",
	"c7i.metal-24xl",
	"c7i.metal-48xl",
	"m7i.metal-24xl",
	"m7i.metal-48xl",
	"r7i.metal-24xl",
	"r7i.metal-48xl",
	"r7iz.metal-16xl",
	"r7iz.metal-32xl",
	"c7gd.metal",
	"m7gd.metal",
	"r7gd.metal",
	"g6.xlarge",
	"g6.2xlarge",
	"g6.4xlarge",
	"g6.8xlarge",
	"g6.12xlarge",
	"g6.16xlarge",
	"g6.24xlarge",
	"g6.48xlarge",
	"gr6.4xlarge",
	"gr6.8xlarge",
	"c7i-flex.large",
	"c7i-flex.xlarge",
	"c7i-flex.2xlarge",
	"c7i-flex.4xlarge",
	"c7i-flex.8xlarge",
	"u7i-12tb.224xlarge",
	"u7in-16tb.224xlarge",
	"u7in-24tb.224xlarge",
	"u7in-32tb.224xlarge",
	"u7ib-12tb.224xlarge",
	"c7gn.metal",
	"r8g.medium",
	"r8g.large",
	"r8g.xlarge",
	"r8g.2xlarge",
	"r8g.4xlarge",
	"r8g.8xlarge",
	"r8g.12xlarge",
	"r8g.16xlarge",
	"r8g.24xlarge",
	"r8g.48xlarge",
	"r8g.metal-24xl",
	"r8g.metal-48xl",
	"mac2-m1ultra.metal",
	"g6e.xlarge",
	"g6e.2xlarge",
	"g6e.4xlarge",
	"g6e.8xlarge",
	"g6e.12xlarge",
	"g6e.16xlarge",
	"g6e.24xlarge",
	"g6e.48xlarge",
	"c8g.medium",
	"c8g.large",
	"c8g.xlarge",
	"c8g.2xlarge",
	"c8g.4xlarge",
	"c8g.8xlarge",
	"c8g.12xlarge",
	"c8g.16xlarge",
	"c8g.24xlarge",
	"c8g.48xlarge",
	"c8g.metal-24xl",
	"c8g.metal-48xl",
	"m8g.medium",
	"m8g.large",
	"m8g.xlarge",
	"m8g.2xlarge",
	"m8g.4xlarge",
	"m8g.8xlarge",
	"m8g.12xlarge",
	"m8g.16xlarge",
	"m8g.24xlarge",
	"m8g.48xlarge",
	"m8g.metal-24xl",
	"m8g.metal-48xl",
	"x8g.medium",
	"x8g.large",
	"x8g.xlarge",
	"x8g.2xlarge",
	"x8g.4xlarge",
	"x8g.8xlarge",
	"x8g.12xlarge",
	"x8g.16xlarge",
	"x8g.24xlarge",
	"x8g.48xlarge",
	"x8g.metal-24xl",
	"x8g.metal-48xl",
	"i7ie.large",
	"i7ie.xlarge",
	"i7ie.2xlarge",
	"i7ie.3xlarge",
	"i7ie.6xlarge",
	"i7ie.12xlarge",
	"i7ie.18xlarge",
	"i7ie.24xlarge",
	"i7ie.48xlarge",
	"i8g.large",
	"i8g.xlarge",
	"i8g.2xlarge",
	"i8g.4xlarge",
	"i8g.8xlarge",
	"i8g.12xlarge",
	"i8g.16xlarge",
	"i8g.24xlarge",
	"i8g.metal-24xl",
	"u7i-6tb.112xlarge",
	"u7i-8tb.112xlarge",
	"u7inh-32tb.480xlarge",
	"p5e.48xlarge",
	"p5en.48xlarge",
	"f2.12xlarge",
	"f2.48xlarge",
	"trn2.48xlarge",
	"c7i-flex.12xlarge",
	"c7i-flex.16xlarge",
	"m7i-flex.12xlarge",
	"m7i-flex.16xlarge",
	"i7ie.metal-24xl",
	"i7ie.metal-48xl",
	"i8g.48xlarge",
	"c8gd.medium",
	"c8gd.large",
	"c8gd.xlarge",
	"c8gd.2xlarge",
	"c8gd.4xlarge",
	"c8gd.8xlarge",
	"c8gd.12xlarge",
	"c8gd.16xlarge",
	"c8gd.24xlarge",
	"c8gd.48xlarge",
	"c8gd.metal-24xl",
	"c8gd.metal-48xl",
	"i7i.large",
	"i7i.xlarge",
	"i7i.2xlarge",
	"i7i.4xlarge",
	"i7i.8xlarge",
	"i7i.12xlarge",
	"i7i.16xlarge",
	"i7i.24xlarge",
	"i7i.48xlarge",
	"i7i.metal-24xl",
	"i7i.metal-48xl",
	"p6-b200.48xlarge",
	"m8gd.medium",
	"m8gd.large",
	"m8gd.xlarge",
	"m8gd.2xlarge",
	"m8gd.4xlarge",
	"m8gd.8xlarge",
	"m8gd.12xlarge",
	"m8gd.16xlarge",
	"m8gd.24xlarge",
	"m8gd.48xlarge",
	"m8gd.metal-24xl",
	"m8gd.metal-48xl",
	"r8gd.medium",
	"r8gd.large",
	"r8gd.xlarge",
	"r8gd.2xlarge",
	"r8gd.4xlarge",
	"r8gd.8xlarge",
	"r8gd.12xlarge",
	"r8gd.16xlarge",
	"r8gd.24xlarge",
	"r8gd.48xlarge",
	"r8gd.metal-24xl",
	"r8gd.metal-48xl",
	"c8gn.medium",
	"c8gn.large",
	"c8gn.xlarge",
	"c8gn.2xlarge",
	"c8gn.4xlarge",
	"c8gn.8xlarge",
	"c8gn.12xlarge",
	"c8gn.16xlarge",
	"c8gn.24xlarge",
	"c8gn.48xlarge",
	"c8gn.metal-24xl",
	"c8gn.metal-48xl",
	"f2.6xlarge",
	"p6e-gb200.36xlarge",
	"g6f.large",
	"g6f.xlarge",
	"g6f.2xlarge",
	"g6f.4xlarge",
	"gr6f.4xlarge",
	"p5.4xlarge",
	"r8i.large",
	"r8i.xlarge",
	"r8i.2xlarge",
	"r8i.4xlarge",
	"r8i.8xlarge",
	"r8i.12xlarge",
	"r8i.16xlarge",
	"r8i.24xlarge",
	"r8i.32xlarge",
	"r8i.48xlarge",
	"r8i.96xlarge",
	"r8i.metal-48xl",
	"r8i.metal-96xl",
	"r8i-flex.large",
	"r8i-flex.xlarge",
	"r8i-flex.2xlarge",
	"r8i-flex.4xlarge",
	"r8i-flex.8xlarge",
	"r8i-flex.12xlarge",
	"r8i-flex.16xlarge",
	"m8i.large",
	"m8i.xlarge",
	"m8i.2xlarge",
	"m8i.4xlarge",
	"m8i.8xlarge",
	"m8i.12xlarge",
	"m8i.16xlarge",
	"m8i.24xlarge",
	"m8i.32xlarge",
	"m8i.48xlarge",
	"m8i.96xlarge",
	"m8i.metal-48xl",
	"m8i.metal-96xl",
	"m8i-flex.large",
	"m8i-flex.xlarge",
	"m8i-flex.2xlarge",
	"m8i-flex.4xlarge",
	"m8i-flex.8xlarge",
	"m8i-flex.12xlarge",
	"m8i-flex.16xlarge",
	"i8ge.large",
	"i8ge.xlarge",
	"i8ge.2xlarge",
	"i8ge.3xlarge",
	"i8ge.6xlarge",
	"i8ge.12xlarge",
	"i8ge.18xlarge",
	"i8ge.24xlarge",
	"i8ge.48xlarge",
	"i8ge.metal-24xl",
	"i8ge.metal-48xl",
	"mac-m4.metal",
	"mac-m4pro.metal",
	"r8gn.medium",
	"r8gn.large",
	"r8gn.xlarge",
	"r8gn.2xlarge",
	"r8gn.4xlarge",
	"r8gn.8xlarge",
	"r8gn.12xlarge",
	"r8gn.16xlarge",
	"r8gn.24xlarge",
	"r8gn.48xlarge",
	"r8gn.metal-24xl",
	"r8gn.metal-48xl",
	"c8i.large",
	"c8i.xlarge",
	"c8i.2xlarge",
	"c8i.4xlarge",
	"c8i.8xlarge",
	"c8i.12xlarge",
	"c8i.16xlarge",
	"c8i.24xlarge",
	"c8i.32xlarge",
	"c8i.48xlarge",
	"c8i.96xlarge",
	"c8i.metal-48xl",
	"c8i.metal-96xl",
	"c8i-flex.large",
	"c8i-flex.xlarge",
	"c8i-flex.2xlarge",
	"c8i-flex.4xlarge",
	"c8i-flex.8xlarge",
	"c8i-flex.12xlarge",
	"c8i-flex.16xlarge",
	"r8gb.medium",
	"r8gb.large",
	"r8gb.xlarge",
	"r8gb.2xlarge",
	"r8gb.4xlarge",
	"r8gb.8xlarge",
	"r8gb.12xlarge",
	"r8gb.16xlarge",
	"r8gb.24xlarge",
	"r8gb.metal-24xl",
	"m8a.medium",
	"m8a.large",
	"m8a.xlarge",
	"m8a.2xlarge",
	"m8a.4xlarge",
	"m8a.8xlarge",
	"m8a.12xlarge",
	"m8a.16xlarge",
	"m8a.24xlarge",
	"m8a.48xlarge",
	"m8a.metal-24xl",
	"m8a.metal-48xl",
	"trn2.3xlarge",
	"r8a.medium",
	"r8a.large",
	"r8a.xlarge",
	"r8a.2xlarge",
	"r8a.4xlarge",
	"r8a.8xlarge",
	"r8a.12xlarge",
	"r8a.16xlarge",
	"r8a.24xlarge",
	"r8a.48xlarge",
	"r8a.metal-24xl",
	"r8a.metal-48xl",
	"p6-b300.48xlarge",
	"c8a.medium",
	"c8a.large",
	"c8a.xlarge",
	"c8a.2xlarge",
	"c8a.4xlarge",
	"c8a.8xlarge",
	"c8a.12xlarge",
	"c8a.16xlarge",
	"c8a.24xlarge",
	"c8a.48xlarge",
	"c8a.metal-24xl",
	"c8a.metal-48xl",
}

var ec2VolumeTypeValues = []string{
	"standard",
	"io1",
	"io2",
	"gp2",
	"sc1",
	"st1",
	"gp3",
}

func getEc2Enum(name string) []string {
	switch name {
	case "InstanceType":
		return ec2InstanceTypeValues
	case "VolumeType":
		return ec2VolumeTypeValues
	}
	return nil
}

func getEc2EnumNames() []string {
	return []string{
		"InstanceType",
		"VolumeType",
	}
}
