// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Entityresolution enum constants
const (
	// AttributeMatchingModel values
	EntityresolutionAttributeMatchingModelOneToOne   = "ONE_TO_ONE"
	EntityresolutionAttributeMatchingModelManyToMany = "MANY_TO_MANY"

	// DeleteUniqueIdErrorType values
	EntityresolutionDeleteUniqueIdErrorTypeServiceError    = "SERVICE_ERROR"
	EntityresolutionDeleteUniqueIdErrorTypeValidationError = "VALIDATION_ERROR"

	// DeleteUniqueIdStatus values
	EntityresolutionDeleteUniqueIdStatusCompleted = "COMPLETED"
	EntityresolutionDeleteUniqueIdStatusAccepted  = "ACCEPTED"

	// IdMappingIncrementalRunType values
	EntityresolutionIdMappingIncrementalRunTypeOnDemand = "ON_DEMAND"

	// IdMappingType values
	EntityresolutionIdMappingTypeProvider  = "PROVIDER"
	EntityresolutionIdMappingTypeRuleBased = "RULE_BASED"

	// IdMappingWorkflowRuleDefinitionType values
	EntityresolutionIdMappingWorkflowRuleDefinitionTypeSource = "SOURCE"
	EntityresolutionIdMappingWorkflowRuleDefinitionTypeTarget = "TARGET"

	// IdNamespaceType values
	EntityresolutionIdNamespaceTypeSource = "SOURCE"
	EntityresolutionIdNamespaceTypeTarget = "TARGET"

	// IncrementalRunType values
	EntityresolutionIncrementalRunTypeImmediate = "IMMEDIATE"

	// JobStatus values
	EntityresolutionJobStatusRunning   = "RUNNING"
	EntityresolutionJobStatusSucceeded = "SUCCEEDED"
	EntityresolutionJobStatusFailed    = "FAILED"
	EntityresolutionJobStatusQueued    = "QUEUED"

	// JobType values
	EntityresolutionJobTypeBatch       = "BATCH"
	EntityresolutionJobTypeIncremental = "INCREMENTAL"
	EntityresolutionJobTypeDeleteOnly  = "DELETE_ONLY"

	// MatchPurpose values
	EntityresolutionMatchPurposeIdentifierGeneration = "IDENTIFIER_GENERATION"
	EntityresolutionMatchPurposeIndexing             = "INDEXING"

	// ProcessingType values
	EntityresolutionProcessingTypeConsistent       = "CONSISTENT"
	EntityresolutionProcessingTypeEventual         = "EVENTUAL"
	EntityresolutionProcessingTypeEventualNoLookup = "EVENTUAL_NO_LOOKUP"

	// RecordMatchingModel values
	EntityresolutionRecordMatchingModelOneSourceToOneTarget  = "ONE_SOURCE_TO_ONE_TARGET"
	EntityresolutionRecordMatchingModelManySourceToOneTarget = "MANY_SOURCE_TO_ONE_TARGET"

	// ResolutionType values
	EntityresolutionResolutionTypeRuleMatching = "RULE_MATCHING"
	EntityresolutionResolutionTypeMlMatching   = "ML_MATCHING"
	EntityresolutionResolutionTypeProvider     = "PROVIDER"

	// SchemaAttributeType values
	EntityresolutionSchemaAttributeTypeName              = "NAME"
	EntityresolutionSchemaAttributeTypeNameFirst         = "NAME_FIRST"
	EntityresolutionSchemaAttributeTypeNameMiddle        = "NAME_MIDDLE"
	EntityresolutionSchemaAttributeTypeNameLast          = "NAME_LAST"
	EntityresolutionSchemaAttributeTypeAddress           = "ADDRESS"
	EntityresolutionSchemaAttributeTypeAddressStreet1    = "ADDRESS_STREET1"
	EntityresolutionSchemaAttributeTypeAddressStreet2    = "ADDRESS_STREET2"
	EntityresolutionSchemaAttributeTypeAddressStreet3    = "ADDRESS_STREET3"
	EntityresolutionSchemaAttributeTypeAddressCity       = "ADDRESS_CITY"
	EntityresolutionSchemaAttributeTypeAddressState      = "ADDRESS_STATE"
	EntityresolutionSchemaAttributeTypeAddressCountry    = "ADDRESS_COUNTRY"
	EntityresolutionSchemaAttributeTypeAddressPostalcode = "ADDRESS_POSTALCODE"
	EntityresolutionSchemaAttributeTypePhone             = "PHONE"
	EntityresolutionSchemaAttributeTypePhoneNumber       = "PHONE_NUMBER"
	EntityresolutionSchemaAttributeTypePhoneCountrycode  = "PHONE_COUNTRYCODE"
	EntityresolutionSchemaAttributeTypeEmailAddress      = "EMAIL_ADDRESS"
	EntityresolutionSchemaAttributeTypeUniqueId          = "UNIQUE_ID"
	EntityresolutionSchemaAttributeTypeDate              = "DATE"
	EntityresolutionSchemaAttributeTypeString            = "STRING"
	EntityresolutionSchemaAttributeTypeProviderId        = "PROVIDER_ID"
	EntityresolutionSchemaAttributeTypeIpv4              = "IPV4"
	EntityresolutionSchemaAttributeTypeIpv6              = "IPV6"
	EntityresolutionSchemaAttributeTypeMaid              = "MAID"

	// ServiceType values
	EntityresolutionServiceTypeAssignment = "ASSIGNMENT"
	EntityresolutionServiceTypeIdMapping  = "ID_MAPPING"

	// StatementEffect values
	EntityresolutionStatementEffectAllow = "Allow"
	EntityresolutionStatementEffectDeny  = "Deny"
)

var entityresolutionAttributeMatchingModelValues = []string{
	"ONE_TO_ONE",
	"MANY_TO_MANY",
}

var entityresolutionDeleteUniqueIdErrorTypeValues = []string{
	"SERVICE_ERROR",
	"VALIDATION_ERROR",
}

var entityresolutionDeleteUniqueIdStatusValues = []string{
	"COMPLETED",
	"ACCEPTED",
}

var entityresolutionIdMappingIncrementalRunTypeValues = []string{
	"ON_DEMAND",
}

var entityresolutionIdMappingTypeValues = []string{
	"PROVIDER",
	"RULE_BASED",
}

var entityresolutionIdMappingWorkflowRuleDefinitionTypeValues = []string{
	"SOURCE",
	"TARGET",
}

var entityresolutionIdNamespaceTypeValues = []string{
	"SOURCE",
	"TARGET",
}

var entityresolutionIncrementalRunTypeValues = []string{
	"IMMEDIATE",
}

var entityresolutionJobStatusValues = []string{
	"RUNNING",
	"SUCCEEDED",
	"FAILED",
	"QUEUED",
}

var entityresolutionJobTypeValues = []string{
	"BATCH",
	"INCREMENTAL",
	"DELETE_ONLY",
}

var entityresolutionMatchPurposeValues = []string{
	"IDENTIFIER_GENERATION",
	"INDEXING",
}

var entityresolutionProcessingTypeValues = []string{
	"CONSISTENT",
	"EVENTUAL",
	"EVENTUAL_NO_LOOKUP",
}

var entityresolutionRecordMatchingModelValues = []string{
	"ONE_SOURCE_TO_ONE_TARGET",
	"MANY_SOURCE_TO_ONE_TARGET",
}

var entityresolutionResolutionTypeValues = []string{
	"RULE_MATCHING",
	"ML_MATCHING",
	"PROVIDER",
}

var entityresolutionSchemaAttributeTypeValues = []string{
	"NAME",
	"NAME_FIRST",
	"NAME_MIDDLE",
	"NAME_LAST",
	"ADDRESS",
	"ADDRESS_STREET1",
	"ADDRESS_STREET2",
	"ADDRESS_STREET3",
	"ADDRESS_CITY",
	"ADDRESS_STATE",
	"ADDRESS_COUNTRY",
	"ADDRESS_POSTALCODE",
	"PHONE",
	"PHONE_NUMBER",
	"PHONE_COUNTRYCODE",
	"EMAIL_ADDRESS",
	"UNIQUE_ID",
	"DATE",
	"STRING",
	"PROVIDER_ID",
	"IPV4",
	"IPV6",
	"MAID",
}

var entityresolutionServiceTypeValues = []string{
	"ASSIGNMENT",
	"ID_MAPPING",
}

var entityresolutionStatementEffectValues = []string{
	"Allow",
	"Deny",
}

func getEntityresolutionEnum(name string) []string {
	switch name {
	case "AttributeMatchingModel":
		return entityresolutionAttributeMatchingModelValues
	case "DeleteUniqueIdErrorType":
		return entityresolutionDeleteUniqueIdErrorTypeValues
	case "DeleteUniqueIdStatus":
		return entityresolutionDeleteUniqueIdStatusValues
	case "IdMappingIncrementalRunType":
		return entityresolutionIdMappingIncrementalRunTypeValues
	case "IdMappingType":
		return entityresolutionIdMappingTypeValues
	case "IdMappingWorkflowRuleDefinitionType":
		return entityresolutionIdMappingWorkflowRuleDefinitionTypeValues
	case "IdNamespaceType":
		return entityresolutionIdNamespaceTypeValues
	case "IncrementalRunType":
		return entityresolutionIncrementalRunTypeValues
	case "JobStatus":
		return entityresolutionJobStatusValues
	case "JobType":
		return entityresolutionJobTypeValues
	case "MatchPurpose":
		return entityresolutionMatchPurposeValues
	case "ProcessingType":
		return entityresolutionProcessingTypeValues
	case "RecordMatchingModel":
		return entityresolutionRecordMatchingModelValues
	case "ResolutionType":
		return entityresolutionResolutionTypeValues
	case "SchemaAttributeType":
		return entityresolutionSchemaAttributeTypeValues
	case "ServiceType":
		return entityresolutionServiceTypeValues
	case "StatementEffect":
		return entityresolutionStatementEffectValues
	}
	return nil
}

func getEntityresolutionEnumNames() []string {
	return []string{
		"AttributeMatchingModel",
		"DeleteUniqueIdErrorType",
		"DeleteUniqueIdStatus",
		"IdMappingIncrementalRunType",
		"IdMappingType",
		"IdMappingWorkflowRuleDefinitionType",
		"IdNamespaceType",
		"IncrementalRunType",
		"JobStatus",
		"JobType",
		"MatchPurpose",
		"ProcessingType",
		"RecordMatchingModel",
		"ResolutionType",
		"SchemaAttributeType",
		"ServiceType",
		"StatementEffect",
	}
}
