// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Forecast enum constants
const (
	// AttributeType values
	ForecastAttributeTypeString      = "string"
	ForecastAttributeTypeInteger     = "integer"
	ForecastAttributeTypeFloat       = "float"
	ForecastAttributeTypeTimestamp   = "timestamp"
	ForecastAttributeTypeGeolocation = "geolocation"

	// AutoMLOverrideStrategy values
	ForecastAutoMLOverrideStrategyLatencyoptimized  = "LatencyOptimized"
	ForecastAutoMLOverrideStrategyAccuracyoptimized = "AccuracyOptimized"

	// Condition values
	ForecastConditionEquals      = "EQUALS"
	ForecastConditionNotEquals   = "NOT_EQUALS"
	ForecastConditionLessThan    = "LESS_THAN"
	ForecastConditionGreaterThan = "GREATER_THAN"

	// DatasetType values
	ForecastDatasetTypeTargetTimeSeries  = "TARGET_TIME_SERIES"
	ForecastDatasetTypeRelatedTimeSeries = "RELATED_TIME_SERIES"
	ForecastDatasetTypeItemMetadata      = "ITEM_METADATA"

	// DayOfWeek values
	ForecastDayOfWeekMonday    = "MONDAY"
	ForecastDayOfWeekTuesday   = "TUESDAY"
	ForecastDayOfWeekWednesday = "WEDNESDAY"
	ForecastDayOfWeekThursday  = "THURSDAY"
	ForecastDayOfWeekFriday    = "FRIDAY"
	ForecastDayOfWeekSaturday  = "SATURDAY"
	ForecastDayOfWeekSunday    = "SUNDAY"

	// Domain values
	ForecastDomainRetail            = "RETAIL"
	ForecastDomainCustom            = "CUSTOM"
	ForecastDomainInventoryPlanning = "INVENTORY_PLANNING"
	ForecastDomainEc2Capacity       = "EC2_CAPACITY"
	ForecastDomainWorkForce         = "WORK_FORCE"
	ForecastDomainWebTraffic        = "WEB_TRAFFIC"
	ForecastDomainMetrics           = "METRICS"

	// EvaluationType values
	ForecastEvaluationTypeSummary  = "SUMMARY"
	ForecastEvaluationTypeComputed = "COMPUTED"

	// FeaturizationMethodName values
	ForecastFeaturizationMethodNameFilling = "filling"

	// FilterConditionString values
	ForecastFilterConditionStringIs    = "IS"
	ForecastFilterConditionStringIsNot = "IS_NOT"

	// ImportMode values
	ForecastImportModeFull        = "FULL"
	ForecastImportModeIncremental = "INCREMENTAL"

	// Month values
	ForecastMonthJanuary   = "JANUARY"
	ForecastMonthFebruary  = "FEBRUARY"
	ForecastMonthMarch     = "MARCH"
	ForecastMonthApril     = "APRIL"
	ForecastMonthMay       = "MAY"
	ForecastMonthJune      = "JUNE"
	ForecastMonthJuly      = "JULY"
	ForecastMonthAugust    = "AUGUST"
	ForecastMonthSeptember = "SEPTEMBER"
	ForecastMonthOctober   = "OCTOBER"
	ForecastMonthNovember  = "NOVEMBER"
	ForecastMonthDecember  = "DECEMBER"

	// Operation values
	ForecastOperationAdd      = "ADD"
	ForecastOperationSubtract = "SUBTRACT"
	ForecastOperationMultiply = "MULTIPLY"
	ForecastOperationDivide   = "DIVIDE"

	// OptimizationMetric values
	ForecastOptimizationMetricWape                        = "WAPE"
	ForecastOptimizationMetricRmse                        = "RMSE"
	ForecastOptimizationMetricAverageweightedquantileloss = "AverageWeightedQuantileLoss"
	ForecastOptimizationMetricMase                        = "MASE"
	ForecastOptimizationMetricMape                        = "MAPE"

	// ScalingType values
	ForecastScalingTypeAuto               = "Auto"
	ForecastScalingTypeLinear             = "Linear"
	ForecastScalingTypeLogarithmic        = "Logarithmic"
	ForecastScalingTypeReverselogarithmic = "ReverseLogarithmic"

	// State values
	ForecastStateActive  = "Active"
	ForecastStateDeleted = "Deleted"

	// TimePointGranularity values
	ForecastTimePointGranularityAll      = "ALL"
	ForecastTimePointGranularitySpecific = "SPECIFIC"

	// TimeSeriesGranularity values
	ForecastTimeSeriesGranularityAll      = "ALL"
	ForecastTimeSeriesGranularitySpecific = "SPECIFIC"
)

var forecastAttributeTypeValues = []string{
	"string",
	"integer",
	"float",
	"timestamp",
	"geolocation",
}

var forecastAutoMLOverrideStrategyValues = []string{
	"LatencyOptimized",
	"AccuracyOptimized",
}

var forecastConditionValues = []string{
	"EQUALS",
	"NOT_EQUALS",
	"LESS_THAN",
	"GREATER_THAN",
}

var forecastDatasetTypeValues = []string{
	"TARGET_TIME_SERIES",
	"RELATED_TIME_SERIES",
	"ITEM_METADATA",
}

var forecastDayOfWeekValues = []string{
	"MONDAY",
	"TUESDAY",
	"WEDNESDAY",
	"THURSDAY",
	"FRIDAY",
	"SATURDAY",
	"SUNDAY",
}

var forecastDomainValues = []string{
	"RETAIL",
	"CUSTOM",
	"INVENTORY_PLANNING",
	"EC2_CAPACITY",
	"WORK_FORCE",
	"WEB_TRAFFIC",
	"METRICS",
}

var forecastEvaluationTypeValues = []string{
	"SUMMARY",
	"COMPUTED",
}

var forecastFeaturizationMethodNameValues = []string{
	"filling",
}

var forecastFilterConditionStringValues = []string{
	"IS",
	"IS_NOT",
}

var forecastImportModeValues = []string{
	"FULL",
	"INCREMENTAL",
}

var forecastMonthValues = []string{
	"JANUARY",
	"FEBRUARY",
	"MARCH",
	"APRIL",
	"MAY",
	"JUNE",
	"JULY",
	"AUGUST",
	"SEPTEMBER",
	"OCTOBER",
	"NOVEMBER",
	"DECEMBER",
}

var forecastOperationValues = []string{
	"ADD",
	"SUBTRACT",
	"MULTIPLY",
	"DIVIDE",
}

var forecastOptimizationMetricValues = []string{
	"WAPE",
	"RMSE",
	"AverageWeightedQuantileLoss",
	"MASE",
	"MAPE",
}

var forecastScalingTypeValues = []string{
	"Auto",
	"Linear",
	"Logarithmic",
	"ReverseLogarithmic",
}

var forecastStateValues = []string{
	"Active",
	"Deleted",
}

var forecastTimePointGranularityValues = []string{
	"ALL",
	"SPECIFIC",
}

var forecastTimeSeriesGranularityValues = []string{
	"ALL",
	"SPECIFIC",
}

func getForecastEnum(name string) []string {
	switch name {
	case "AttributeType":
		return forecastAttributeTypeValues
	case "AutoMLOverrideStrategy":
		return forecastAutoMLOverrideStrategyValues
	case "Condition":
		return forecastConditionValues
	case "DatasetType":
		return forecastDatasetTypeValues
	case "DayOfWeek":
		return forecastDayOfWeekValues
	case "Domain":
		return forecastDomainValues
	case "EvaluationType":
		return forecastEvaluationTypeValues
	case "FeaturizationMethodName":
		return forecastFeaturizationMethodNameValues
	case "FilterConditionString":
		return forecastFilterConditionStringValues
	case "ImportMode":
		return forecastImportModeValues
	case "Month":
		return forecastMonthValues
	case "Operation":
		return forecastOperationValues
	case "OptimizationMetric":
		return forecastOptimizationMetricValues
	case "ScalingType":
		return forecastScalingTypeValues
	case "State":
		return forecastStateValues
	case "TimePointGranularity":
		return forecastTimePointGranularityValues
	case "TimeSeriesGranularity":
		return forecastTimeSeriesGranularityValues
	}
	return nil
}

func getForecastEnumNames() []string {
	return []string{
		"AttributeType",
		"AutoMLOverrideStrategy",
		"Condition",
		"DatasetType",
		"DayOfWeek",
		"Domain",
		"EvaluationType",
		"FeaturizationMethodName",
		"FilterConditionString",
		"ImportMode",
		"Month",
		"Operation",
		"OptimizationMetric",
		"ScalingType",
		"State",
		"TimePointGranularity",
		"TimeSeriesGranularity",
	}
}
