// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// GeoRoutes enum constants
const (
	// DayOfWeek values
	GeoroutesDayOfWeekMonday    = "Monday"
	GeoroutesDayOfWeekTuesday   = "Tuesday"
	GeoroutesDayOfWeekWednesday = "Wednesday"
	GeoroutesDayOfWeekThursday  = "Thursday"
	GeoroutesDayOfWeekFriday    = "Friday"
	GeoroutesDayOfWeekSaturday  = "Saturday"
	GeoroutesDayOfWeekSunday    = "Sunday"

	// GeometryFormat values
	GeoroutesGeometryFormatFlexiblepolyline = "FlexiblePolyline"
	GeoroutesGeometryFormatSimple           = "Simple"

	// IsolineEngineType values
	GeoroutesIsolineEngineTypeElectric           = "Electric"
	GeoroutesIsolineEngineTypeInternalcombustion = "InternalCombustion"
	GeoroutesIsolineEngineTypePluginhybrid       = "PluginHybrid"

	// IsolineHazardousCargoType values
	GeoroutesIsolineHazardousCargoTypeCombustible         = "Combustible"
	GeoroutesIsolineHazardousCargoTypeCorrosive           = "Corrosive"
	GeoroutesIsolineHazardousCargoTypeExplosive           = "Explosive"
	GeoroutesIsolineHazardousCargoTypeFlammable           = "Flammable"
	GeoroutesIsolineHazardousCargoTypeGas                 = "Gas"
	GeoroutesIsolineHazardousCargoTypeHarmfultowater      = "HarmfulToWater"
	GeoroutesIsolineHazardousCargoTypeOrganic             = "Organic"
	GeoroutesIsolineHazardousCargoTypeOther               = "Other"
	GeoroutesIsolineHazardousCargoTypePoison              = "Poison"
	GeoroutesIsolineHazardousCargoTypePoisonousinhalation = "PoisonousInhalation"
	GeoroutesIsolineHazardousCargoTypeRadioactive         = "Radioactive"

	// IsolineOptimizationObjective values
	GeoroutesIsolineOptimizationObjectiveAccuratecalculation = "AccurateCalculation"
	GeoroutesIsolineOptimizationObjectiveBalancedcalculation = "BalancedCalculation"
	GeoroutesIsolineOptimizationObjectiveFastcalculation     = "FastCalculation"

	// IsolineTravelMode values
	GeoroutesIsolineTravelModeCar        = "Car"
	GeoroutesIsolineTravelModePedestrian = "Pedestrian"
	GeoroutesIsolineTravelModeScooter    = "Scooter"
	GeoroutesIsolineTravelModeTruck      = "Truck"

	// IsolineTruckType values
	GeoroutesIsolineTruckTypeLighttruck    = "LightTruck"
	GeoroutesIsolineTruckTypeStraighttruck = "StraightTruck"
	GeoroutesIsolineTruckTypeTractor       = "Tractor"

	// IsolineZoneCategory values
	GeoroutesIsolineZoneCategoryCongestionpricing = "CongestionPricing"
	GeoroutesIsolineZoneCategoryEnvironmental     = "Environmental"
	GeoroutesIsolineZoneCategoryVignette          = "Vignette"

	// MatchingStrategy values
	GeoroutesMatchingStrategyMatchany                 = "MatchAny"
	GeoroutesMatchingStrategyMatchmostsignificantroad = "MatchMostSignificantRoad"

	// MeasurementSystem values
	GeoroutesMeasurementSystemMetric   = "Metric"
	GeoroutesMeasurementSystemImperial = "Imperial"

	// RoadSnapHazardousCargoType values
	GeoroutesRoadSnapHazardousCargoTypeCombustible         = "Combustible"
	GeoroutesRoadSnapHazardousCargoTypeCorrosive           = "Corrosive"
	GeoroutesRoadSnapHazardousCargoTypeExplosive           = "Explosive"
	GeoroutesRoadSnapHazardousCargoTypeFlammable           = "Flammable"
	GeoroutesRoadSnapHazardousCargoTypeGas                 = "Gas"
	GeoroutesRoadSnapHazardousCargoTypeHarmfultowater      = "HarmfulToWater"
	GeoroutesRoadSnapHazardousCargoTypeOrganic             = "Organic"
	GeoroutesRoadSnapHazardousCargoTypeOther               = "Other"
	GeoroutesRoadSnapHazardousCargoTypePoison              = "Poison"
	GeoroutesRoadSnapHazardousCargoTypePoisonousinhalation = "PoisonousInhalation"
	GeoroutesRoadSnapHazardousCargoTypeRadioactive         = "Radioactive"

	// RoadSnapNoticeCode values
	GeoroutesRoadSnapNoticeCodeTracepointsheadingignored       = "TracePointsHeadingIgnored"
	GeoroutesRoadSnapNoticeCodeTracepointsignored              = "TracePointsIgnored"
	GeoroutesRoadSnapNoticeCodeTracepointsmovedbylargedistance = "TracePointsMovedByLargeDistance"
	GeoroutesRoadSnapNoticeCodeTracepointsnotmatched           = "TracePointsNotMatched"
	GeoroutesRoadSnapNoticeCodeTracepointsoutofsequence        = "TracePointsOutOfSequence"
	GeoroutesRoadSnapNoticeCodeTracepointsspeedestimated       = "TracePointsSpeedEstimated"
	GeoroutesRoadSnapNoticeCodeTracepointsspeedignored         = "TracePointsSpeedIgnored"

	// RoadSnapTravelMode values
	GeoroutesRoadSnapTravelModeCar        = "Car"
	GeoroutesRoadSnapTravelModePedestrian = "Pedestrian"
	GeoroutesRoadSnapTravelModeScooter    = "Scooter"
	GeoroutesRoadSnapTravelModeTruck      = "Truck"

	// RouteDirection values
	GeoroutesRouteDirectionEast  = "East"
	GeoroutesRouteDirectionNorth = "North"
	GeoroutesRouteDirectionSouth = "South"
	GeoroutesRouteDirectionWest  = "West"

	// RouteEngineType values
	GeoroutesRouteEngineTypeElectric           = "Electric"
	GeoroutesRouteEngineTypeInternalcombustion = "InternalCombustion"
	GeoroutesRouteEngineTypePluginhybrid       = "PluginHybrid"

	// RouteFerryAfterTravelStepType values
	GeoroutesRouteFerryAfterTravelStepTypeDeboard = "Deboard"

	// RouteFerryBeforeTravelStepType values
	GeoroutesRouteFerryBeforeTravelStepTypeBoard = "Board"

	// RouteFerryNoticeCode values
	GeoroutesRouteFerryNoticeCodeAccuratepolylineunavailable              = "AccuratePolylineUnavailable"
	GeoroutesRouteFerryNoticeCodeNoschedule                               = "NoSchedule"
	GeoroutesRouteFerryNoticeCodeOther                                    = "Other"
	GeoroutesRouteFerryNoticeCodeViolatedavoidferry                       = "ViolatedAvoidFerry"
	GeoroutesRouteFerryNoticeCodeViolatedavoidrailferry                   = "ViolatedAvoidRailFerry"
	GeoroutesRouteFerryNoticeCodeSeasonalclosure                          = "SeasonalClosure"
	GeoroutesRouteFerryNoticeCodePotentialviolatedvehiclerestrictionusage = "PotentialViolatedVehicleRestrictionUsage"

	// RouteFerryTravelStepType values
	GeoroutesRouteFerryTravelStepTypeDepart   = "Depart"
	GeoroutesRouteFerryTravelStepTypeContinue = "Continue"
	GeoroutesRouteFerryTravelStepTypeArrive   = "Arrive"

	// RouteHazardousCargoType values
	GeoroutesRouteHazardousCargoTypeCombustible         = "Combustible"
	GeoroutesRouteHazardousCargoTypeCorrosive           = "Corrosive"
	GeoroutesRouteHazardousCargoTypeExplosive           = "Explosive"
	GeoroutesRouteHazardousCargoTypeFlammable           = "Flammable"
	GeoroutesRouteHazardousCargoTypeGas                 = "Gas"
	GeoroutesRouteHazardousCargoTypeHarmfultowater      = "HarmfulToWater"
	GeoroutesRouteHazardousCargoTypeOrganic             = "Organic"
	GeoroutesRouteHazardousCargoTypeOther               = "Other"
	GeoroutesRouteHazardousCargoTypePoison              = "Poison"
	GeoroutesRouteHazardousCargoTypePoisonousinhalation = "PoisonousInhalation"
	GeoroutesRouteHazardousCargoTypeRadioactive         = "Radioactive"

	// RouteLegAdditionalFeature values
	GeoroutesRouteLegAdditionalFeatureElevation              = "Elevation"
	GeoroutesRouteLegAdditionalFeatureIncidents              = "Incidents"
	GeoroutesRouteLegAdditionalFeaturePassthroughwaypoints   = "PassThroughWaypoints"
	GeoroutesRouteLegAdditionalFeatureSummary                = "Summary"
	GeoroutesRouteLegAdditionalFeatureTolls                  = "Tolls"
	GeoroutesRouteLegAdditionalFeatureTravelstepinstructions = "TravelStepInstructions"
	GeoroutesRouteLegAdditionalFeatureTruckroadtypes         = "TruckRoadTypes"
	GeoroutesRouteLegAdditionalFeatureTypicalduration        = "TypicalDuration"
	GeoroutesRouteLegAdditionalFeatureZones                  = "Zones"

	// RouteLegTravelMode values
	GeoroutesRouteLegTravelModeCar             = "Car"
	GeoroutesRouteLegTravelModeFerry           = "Ferry"
	GeoroutesRouteLegTravelModePedestrian      = "Pedestrian"
	GeoroutesRouteLegTravelModeScooter         = "Scooter"
	GeoroutesRouteLegTravelModeTruck           = "Truck"
	GeoroutesRouteLegTravelModeCarshuttletrain = "CarShuttleTrain"

	// RouteLegType values
	GeoroutesRouteLegTypeFerry      = "Ferry"
	GeoroutesRouteLegTypePedestrian = "Pedestrian"
	GeoroutesRouteLegTypeVehicle    = "Vehicle"

	// RouteMatrixErrorCode values
	GeoroutesRouteMatrixErrorCodeNomatch                = "NoMatch"
	GeoroutesRouteMatrixErrorCodeNomatchdestination     = "NoMatchDestination"
	GeoroutesRouteMatrixErrorCodeNomatchorigin          = "NoMatchOrigin"
	GeoroutesRouteMatrixErrorCodeNoroute                = "NoRoute"
	GeoroutesRouteMatrixErrorCodeOutofbounds            = "OutOfBounds"
	GeoroutesRouteMatrixErrorCodeOutofboundsdestination = "OutOfBoundsDestination"
	GeoroutesRouteMatrixErrorCodeOutofboundsorigin      = "OutOfBoundsOrigin"
	GeoroutesRouteMatrixErrorCodeOther                  = "Other"
	GeoroutesRouteMatrixErrorCodeViolation              = "Violation"

	// RouteMatrixHazardousCargoType values
	GeoroutesRouteMatrixHazardousCargoTypeCombustible         = "Combustible"
	GeoroutesRouteMatrixHazardousCargoTypeCorrosive           = "Corrosive"
	GeoroutesRouteMatrixHazardousCargoTypeExplosive           = "Explosive"
	GeoroutesRouteMatrixHazardousCargoTypeFlammable           = "Flammable"
	GeoroutesRouteMatrixHazardousCargoTypeGas                 = "Gas"
	GeoroutesRouteMatrixHazardousCargoTypeHarmfultowater      = "HarmfulToWater"
	GeoroutesRouteMatrixHazardousCargoTypeOrganic             = "Organic"
	GeoroutesRouteMatrixHazardousCargoTypeOther               = "Other"
	GeoroutesRouteMatrixHazardousCargoTypePoison              = "Poison"
	GeoroutesRouteMatrixHazardousCargoTypePoisonousinhalation = "PoisonousInhalation"
	GeoroutesRouteMatrixHazardousCargoTypeRadioactive         = "Radioactive"

	// RouteMatrixTravelMode values
	GeoroutesRouteMatrixTravelModeCar        = "Car"
	GeoroutesRouteMatrixTravelModePedestrian = "Pedestrian"
	GeoroutesRouteMatrixTravelModeScooter    = "Scooter"
	GeoroutesRouteMatrixTravelModeTruck      = "Truck"

	// RouteMatrixTruckType values
	GeoroutesRouteMatrixTruckTypeLighttruck    = "LightTruck"
	GeoroutesRouteMatrixTruckTypeStraighttruck = "StraightTruck"
	GeoroutesRouteMatrixTruckTypeTractor       = "Tractor"

	// RouteMatrixZoneCategory values
	GeoroutesRouteMatrixZoneCategoryCongestionpricing = "CongestionPricing"
	GeoroutesRouteMatrixZoneCategoryEnvironmental     = "Environmental"
	GeoroutesRouteMatrixZoneCategoryVignette          = "Vignette"

	// RouteNoticeImpact values
	GeoroutesRouteNoticeImpactHigh = "High"
	GeoroutesRouteNoticeImpactLow  = "Low"

	// RoutePedestrianNoticeCode values
	GeoroutesRoutePedestrianNoticeCodeAccuratepolylineunavailable = "AccuratePolylineUnavailable"
	GeoroutesRoutePedestrianNoticeCodeOther                       = "Other"
	GeoroutesRoutePedestrianNoticeCodeViolatedavoiddirtroad       = "ViolatedAvoidDirtRoad"
	GeoroutesRoutePedestrianNoticeCodeViolatedavoidtunnel         = "ViolatedAvoidTunnel"
	GeoroutesRoutePedestrianNoticeCodeViolatedpedestrianoption    = "ViolatedPedestrianOption"

	// RoutePedestrianTravelStepType values
	GeoroutesRoutePedestrianTravelStepTypeArrive          = "Arrive"
	GeoroutesRoutePedestrianTravelStepTypeContinue        = "Continue"
	GeoroutesRoutePedestrianTravelStepTypeDepart          = "Depart"
	GeoroutesRoutePedestrianTravelStepTypeKeep            = "Keep"
	GeoroutesRoutePedestrianTravelStepTypeRoundaboutenter = "RoundaboutEnter"
	GeoroutesRoutePedestrianTravelStepTypeRoundaboutexit  = "RoundaboutExit"
	GeoroutesRoutePedestrianTravelStepTypeRoundaboutpass  = "RoundaboutPass"
	GeoroutesRoutePedestrianTravelStepTypeTurn            = "Turn"
	GeoroutesRoutePedestrianTravelStepTypeExit            = "Exit"
	GeoroutesRoutePedestrianTravelStepTypeRamp            = "Ramp"
	GeoroutesRoutePedestrianTravelStepTypeUturn           = "UTurn"

	// RouteResponseNoticeCode values
	GeoroutesRouteResponseNoticeCodeMainlanguagenotfound             = "MainLanguageNotFound"
	GeoroutesRouteResponseNoticeCodeOther                            = "Other"
	GeoroutesRouteResponseNoticeCodeTraveltimeexceedsdriverworkhours = "TravelTimeExceedsDriverWorkHours"

	// RouteRoadType values
	GeoroutesRouteRoadTypeHighway = "Highway"
	GeoroutesRouteRoadTypeRural   = "Rural"
	GeoroutesRouteRoadTypeUrban   = "Urban"

	// RouteSideOfStreet values
	GeoroutesRouteSideOfStreetLeft  = "Left"
	GeoroutesRouteSideOfStreetRight = "Right"

	// RouteSpanAdditionalFeature values
	GeoroutesRouteSpanAdditionalFeatureBestcaseduration         = "BestCaseDuration"
	GeoroutesRouteSpanAdditionalFeatureCaraccess                = "CarAccess"
	GeoroutesRouteSpanAdditionalFeatureCountry                  = "Country"
	GeoroutesRouteSpanAdditionalFeatureDistance                 = "Distance"
	GeoroutesRouteSpanAdditionalFeatureDuration                 = "Duration"
	GeoroutesRouteSpanAdditionalFeatureDynamicspeed             = "DynamicSpeed"
	GeoroutesRouteSpanAdditionalFeatureFunctionalclassification = "FunctionalClassification"
	GeoroutesRouteSpanAdditionalFeatureGates                    = "Gates"
	GeoroutesRouteSpanAdditionalFeatureIncidents                = "Incidents"
	GeoroutesRouteSpanAdditionalFeatureNames                    = "Names"
	GeoroutesRouteSpanAdditionalFeatureNotices                  = "Notices"
	GeoroutesRouteSpanAdditionalFeaturePedestrianaccess         = "PedestrianAccess"
	GeoroutesRouteSpanAdditionalFeatureRailwaycrossings         = "RailwayCrossings"
	GeoroutesRouteSpanAdditionalFeatureRegion                   = "Region"
	GeoroutesRouteSpanAdditionalFeatureRoadattributes           = "RoadAttributes"
	GeoroutesRouteSpanAdditionalFeatureRoutenumbers             = "RouteNumbers"
	GeoroutesRouteSpanAdditionalFeatureScooteraccess            = "ScooterAccess"
	GeoroutesRouteSpanAdditionalFeatureSpeedlimit               = "SpeedLimit"
	GeoroutesRouteSpanAdditionalFeatureTollsystems              = "TollSystems"
	GeoroutesRouteSpanAdditionalFeatureTruckaccess              = "TruckAccess"
	GeoroutesRouteSpanAdditionalFeatureTruckroadtypes           = "TruckRoadTypes"
	GeoroutesRouteSpanAdditionalFeatureTypicalduration          = "TypicalDuration"
	GeoroutesRouteSpanAdditionalFeatureZones                    = "Zones"
	GeoroutesRouteSpanAdditionalFeatureConsumption              = "Consumption"

	// RouteSpanCarAccessAttribute values
	GeoroutesRouteSpanCarAccessAttributeAllowed          = "Allowed"
	GeoroutesRouteSpanCarAccessAttributeNothroughtraffic = "NoThroughTraffic"
	GeoroutesRouteSpanCarAccessAttributeTollroad         = "TollRoad"

	// RouteSpanGateAttribute values
	GeoroutesRouteSpanGateAttributeEmergency          = "Emergency"
	GeoroutesRouteSpanGateAttributeKeyaccess          = "KeyAccess"
	GeoroutesRouteSpanGateAttributePermissionrequired = "PermissionRequired"

	// RouteSpanPedestrianAccessAttribute values
	GeoroutesRouteSpanPedestrianAccessAttributeAllowed          = "Allowed"
	GeoroutesRouteSpanPedestrianAccessAttributeIndoors          = "Indoors"
	GeoroutesRouteSpanPedestrianAccessAttributeNothroughtraffic = "NoThroughTraffic"
	GeoroutesRouteSpanPedestrianAccessAttributePark             = "Park"
	GeoroutesRouteSpanPedestrianAccessAttributeStairs           = "Stairs"
	GeoroutesRouteSpanPedestrianAccessAttributeTollroad         = "TollRoad"

	// RouteSpanRailwayCrossingAttribute values
	GeoroutesRouteSpanRailwayCrossingAttributeProtected   = "Protected"
	GeoroutesRouteSpanRailwayCrossingAttributeUnprotected = "Unprotected"

	// RouteSpanRoadAttribute values
	GeoroutesRouteSpanRoadAttributeBridge                  = "Bridge"
	GeoroutesRouteSpanRoadAttributeBuiltuparea             = "BuiltUpArea"
	GeoroutesRouteSpanRoadAttributeControlledaccesshighway = "ControlledAccessHighway"
	GeoroutesRouteSpanRoadAttributeDirtroad                = "DirtRoad"
	GeoroutesRouteSpanRoadAttributeDividedroad             = "DividedRoad"
	GeoroutesRouteSpanRoadAttributeMotorway                = "Motorway"
	GeoroutesRouteSpanRoadAttributePrivateroad             = "PrivateRoad"
	GeoroutesRouteSpanRoadAttributeRamp                    = "Ramp"
	GeoroutesRouteSpanRoadAttributeRighthandtraffic        = "RightHandTraffic"
	GeoroutesRouteSpanRoadAttributeRoundabout              = "Roundabout"
	GeoroutesRouteSpanRoadAttributeTunnel                  = "Tunnel"
	GeoroutesRouteSpanRoadAttributeUnderconstruction       = "UnderConstruction"

	// RouteSpanScooterAccessAttribute values
	GeoroutesRouteSpanScooterAccessAttributeAllowed          = "Allowed"
	GeoroutesRouteSpanScooterAccessAttributeNothroughtraffic = "NoThroughTraffic"
	GeoroutesRouteSpanScooterAccessAttributeTollroad         = "TollRoad"

	// RouteSpanTruckAccessAttribute values
	GeoroutesRouteSpanTruckAccessAttributeAllowed          = "Allowed"
	GeoroutesRouteSpanTruckAccessAttributeNothroughtraffic = "NoThroughTraffic"
	GeoroutesRouteSpanTruckAccessAttributeTollroad         = "TollRoad"

	// RouteSteeringDirection values
	GeoroutesRouteSteeringDirectionLeft     = "Left"
	GeoroutesRouteSteeringDirectionRight    = "Right"
	GeoroutesRouteSteeringDirectionStraight = "Straight"

	// RouteTollPassValidityPeriodType values
	GeoroutesRouteTollPassValidityPeriodTypeAnnual         = "Annual"
	GeoroutesRouteTollPassValidityPeriodTypeDays           = "Days"
	GeoroutesRouteTollPassValidityPeriodTypeExtendedannual = "ExtendedAnnual"
	GeoroutesRouteTollPassValidityPeriodTypeMinutes        = "Minutes"
	GeoroutesRouteTollPassValidityPeriodTypeMonths         = "Months"

	// RouteTollPaymentMethod values
	GeoroutesRouteTollPaymentMethodBankcard         = "BankCard"
	GeoroutesRouteTollPaymentMethodCash             = "Cash"
	GeoroutesRouteTollPaymentMethodCashexact        = "CashExact"
	GeoroutesRouteTollPaymentMethodCreditcard       = "CreditCard"
	GeoroutesRouteTollPaymentMethodPasssubscription = "PassSubscription"
	GeoroutesRouteTollPaymentMethodTravelcard       = "TravelCard"
	GeoroutesRouteTollPaymentMethodTransponder      = "Transponder"
	GeoroutesRouteTollPaymentMethodVideotoll        = "VideoToll"

	// RouteTollVehicleCategory values
	GeoroutesRouteTollVehicleCategoryMinibus = "Minibus"

	// RouteTravelMode values
	GeoroutesRouteTravelModeCar        = "Car"
	GeoroutesRouteTravelModePedestrian = "Pedestrian"
	GeoroutesRouteTravelModeScooter    = "Scooter"
	GeoroutesRouteTravelModeTruck      = "Truck"

	// RouteTravelStepType values
	GeoroutesRouteTravelStepTypeDefault    = "Default"
	GeoroutesRouteTravelStepTypeTurnbyturn = "TurnByTurn"

	// RouteTruckType values
	GeoroutesRouteTruckTypeLighttruck    = "LightTruck"
	GeoroutesRouteTruckTypeStraighttruck = "StraightTruck"
	GeoroutesRouteTruckTypeTractor       = "Tractor"

	// RouteTurnIntensity values
	GeoroutesRouteTurnIntensitySharp   = "Sharp"
	GeoroutesRouteTurnIntensitySlight  = "Slight"
	GeoroutesRouteTurnIntensityTypical = "Typical"

	// RouteVehicleIncidentSeverity values
	GeoroutesRouteVehicleIncidentSeverityCritical = "Critical"
	GeoroutesRouteVehicleIncidentSeverityHigh     = "High"
	GeoroutesRouteVehicleIncidentSeverityMedium   = "Medium"
	GeoroutesRouteVehicleIncidentSeverityLow      = "Low"

	// RouteVehicleIncidentType values
	GeoroutesRouteVehicleIncidentTypeAccident        = "Accident"
	GeoroutesRouteVehicleIncidentTypeCongestion      = "Congestion"
	GeoroutesRouteVehicleIncidentTypeConstruction    = "Construction"
	GeoroutesRouteVehicleIncidentTypeDisabledvehicle = "DisabledVehicle"
	GeoroutesRouteVehicleIncidentTypeLanerestriction = "LaneRestriction"
	GeoroutesRouteVehicleIncidentTypeMasstransit     = "MassTransit"
	GeoroutesRouteVehicleIncidentTypeOther           = "Other"
	GeoroutesRouteVehicleIncidentTypePlannedevent    = "PlannedEvent"
	GeoroutesRouteVehicleIncidentTypeRoadclosure     = "RoadClosure"
	GeoroutesRouteVehicleIncidentTypeRoadhazard      = "RoadHazard"
	GeoroutesRouteVehicleIncidentTypeWeather         = "Weather"

	// RouteVehicleNoticeCode values
	GeoroutesRouteVehicleNoticeCodeAccuratepolylineunavailable              = "AccuratePolylineUnavailable"
	GeoroutesRouteVehicleNoticeCodeOther                                    = "Other"
	GeoroutesRouteVehicleNoticeCodePotentialviolatedavoidtollroadusage      = "PotentialViolatedAvoidTollRoadUsage"
	GeoroutesRouteVehicleNoticeCodePotentialviolatedcarpoolusage            = "PotentialViolatedCarpoolUsage"
	GeoroutesRouteVehicleNoticeCodePotentialviolatedturnrestrictionusage    = "PotentialViolatedTurnRestrictionUsage"
	GeoroutesRouteVehicleNoticeCodePotentialviolatedvehiclerestrictionusage = "PotentialViolatedVehicleRestrictionUsage"
	GeoroutesRouteVehicleNoticeCodePotentialviolatedzonerestrictionusage    = "PotentialViolatedZoneRestrictionUsage"
	GeoroutesRouteVehicleNoticeCodeSeasonalclosure                          = "SeasonalClosure"
	GeoroutesRouteVehicleNoticeCodeTollsdatatemporarilyunavailable          = "TollsDataTemporarilyUnavailable"
	GeoroutesRouteVehicleNoticeCodeTollsdataunavailable                     = "TollsDataUnavailable"
	GeoroutesRouteVehicleNoticeCodeTolltransponder                          = "TollTransponder"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidcontrolledaccesshighway     = "ViolatedAvoidControlledAccessHighway"
	GeoroutesRouteVehicleNoticeCodeViolatedavoiddifficultturns              = "ViolatedAvoidDifficultTurns"
	GeoroutesRouteVehicleNoticeCodeViolatedavoiddirtroad                    = "ViolatedAvoidDirtRoad"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidseasonalclosure             = "ViolatedAvoidSeasonalClosure"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidtollroad                    = "ViolatedAvoidTollRoad"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidtolltransponder             = "ViolatedAvoidTollTransponder"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidtruckroadtype               = "ViolatedAvoidTruckRoadType"
	GeoroutesRouteVehicleNoticeCodeViolatedavoidtunnel                      = "ViolatedAvoidTunnel"
	GeoroutesRouteVehicleNoticeCodeViolatedavoiduturns                      = "ViolatedAvoidUTurns"
	GeoroutesRouteVehicleNoticeCodeViolatedblockedroad                      = "ViolatedBlockedRoad"
	GeoroutesRouteVehicleNoticeCodeViolatedcarpool                          = "ViolatedCarpool"
	GeoroutesRouteVehicleNoticeCodeViolatedemergencygate                    = "ViolatedEmergencyGate"
	GeoroutesRouteVehicleNoticeCodeViolatedstartdirection                   = "ViolatedStartDirection"
	GeoroutesRouteVehicleNoticeCodeViolatedturnrestriction                  = "ViolatedTurnRestriction"
	GeoroutesRouteVehicleNoticeCodeViolatedvehiclerestriction               = "ViolatedVehicleRestriction"
	GeoroutesRouteVehicleNoticeCodeViolatedzonerestriction                  = "ViolatedZoneRestriction"

	// RouteVehicleTravelStepType values
	GeoroutesRouteVehicleTravelStepTypeArrive          = "Arrive"
	GeoroutesRouteVehicleTravelStepTypeContinue        = "Continue"
	GeoroutesRouteVehicleTravelStepTypeContinuehighway = "ContinueHighway"
	GeoroutesRouteVehicleTravelStepTypeDepart          = "Depart"
	GeoroutesRouteVehicleTravelStepTypeEnterhighway    = "EnterHighway"
	GeoroutesRouteVehicleTravelStepTypeExit            = "Exit"
	GeoroutesRouteVehicleTravelStepTypeKeep            = "Keep"
	GeoroutesRouteVehicleTravelStepTypeRamp            = "Ramp"
	GeoroutesRouteVehicleTravelStepTypeRoundaboutenter = "RoundaboutEnter"
	GeoroutesRouteVehicleTravelStepTypeRoundaboutexit  = "RoundaboutExit"
	GeoroutesRouteVehicleTravelStepTypeRoundaboutpass  = "RoundaboutPass"
	GeoroutesRouteVehicleTravelStepTypeTurn            = "Turn"
	GeoroutesRouteVehicleTravelStepTypeUturn           = "UTurn"

	// RouteWeightConstraintType values
	GeoroutesRouteWeightConstraintTypeCurrent = "Current"
	GeoroutesRouteWeightConstraintTypeGross   = "Gross"
	GeoroutesRouteWeightConstraintTypeUnknown = "Unknown"

	// RouteZoneCategory values
	GeoroutesRouteZoneCategoryCongestionpricing = "CongestionPricing"
	GeoroutesRouteZoneCategoryEnvironmental     = "Environmental"
	GeoroutesRouteZoneCategoryVignette          = "Vignette"

	// RoutingObjective values
	GeoroutesRoutingObjectiveFastestroute  = "FastestRoute"
	GeoroutesRoutingObjectiveShortestroute = "ShortestRoute"

	// SideOfStreetMatchingStrategy values
	GeoroutesSideOfStreetMatchingStrategyAnystreet         = "AnyStreet"
	GeoroutesSideOfStreetMatchingStrategyDividedstreetonly = "DividedStreetOnly"

	// TrafficUsage values
	GeoroutesTrafficUsageIgnoretrafficdata = "IgnoreTrafficData"
	GeoroutesTrafficUsageUsetrafficdata    = "UseTrafficData"

	// ValidationExceptionReason values
	GeoroutesValidationExceptionReasonUnknownoperation      = "UnknownOperation"
	GeoroutesValidationExceptionReasonMissing               = "Missing"
	GeoroutesValidationExceptionReasonCannotparse           = "CannotParse"
	GeoroutesValidationExceptionReasonFieldvalidationfailed = "FieldValidationFailed"
	GeoroutesValidationExceptionReasonOther                 = "Other"
	GeoroutesValidationExceptionReasonUnknownfield          = "UnknownField"

	// WaypointOptimizationClusteringAlgorithm values
	GeoroutesWaypointOptimizationClusteringAlgorithmDrivingdistance = "DrivingDistance"
	GeoroutesWaypointOptimizationClusteringAlgorithmTopologysegment = "TopologySegment"

	// WaypointOptimizationConstraint values
	GeoroutesWaypointOptimizationConstraintAccesshours     = "AccessHours"
	GeoroutesWaypointOptimizationConstraintAppointmenttime = "AppointmentTime"
	GeoroutesWaypointOptimizationConstraintBefore          = "Before"
	GeoroutesWaypointOptimizationConstraintHeading         = "Heading"
	GeoroutesWaypointOptimizationConstraintServiceduration = "ServiceDuration"
	GeoroutesWaypointOptimizationConstraintSideofstreet    = "SideOfStreet"

	// WaypointOptimizationHazardousCargoType values
	GeoroutesWaypointOptimizationHazardousCargoTypeCombustible         = "Combustible"
	GeoroutesWaypointOptimizationHazardousCargoTypeCorrosive           = "Corrosive"
	GeoroutesWaypointOptimizationHazardousCargoTypeExplosive           = "Explosive"
	GeoroutesWaypointOptimizationHazardousCargoTypeFlammable           = "Flammable"
	GeoroutesWaypointOptimizationHazardousCargoTypeGas                 = "Gas"
	GeoroutesWaypointOptimizationHazardousCargoTypeHarmfultowater      = "HarmfulToWater"
	GeoroutesWaypointOptimizationHazardousCargoTypeOrganic             = "Organic"
	GeoroutesWaypointOptimizationHazardousCargoTypeOther               = "Other"
	GeoroutesWaypointOptimizationHazardousCargoTypePoison              = "Poison"
	GeoroutesWaypointOptimizationHazardousCargoTypePoisonousinhalation = "PoisonousInhalation"
	GeoroutesWaypointOptimizationHazardousCargoTypeRadioactive         = "Radioactive"

	// WaypointOptimizationSequencingObjective values
	GeoroutesWaypointOptimizationSequencingObjectiveFastestroute  = "FastestRoute"
	GeoroutesWaypointOptimizationSequencingObjectiveShortestroute = "ShortestRoute"

	// WaypointOptimizationServiceTimeTreatment values
	GeoroutesWaypointOptimizationServiceTimeTreatmentRest = "Rest"
	GeoroutesWaypointOptimizationServiceTimeTreatmentWork = "Work"

	// WaypointOptimizationTravelMode values
	GeoroutesWaypointOptimizationTravelModeCar        = "Car"
	GeoroutesWaypointOptimizationTravelModePedestrian = "Pedestrian"
	GeoroutesWaypointOptimizationTravelModeScooter    = "Scooter"
	GeoroutesWaypointOptimizationTravelModeTruck      = "Truck"

	// WaypointOptimizationTruckType values
	GeoroutesWaypointOptimizationTruckTypeStraighttruck = "StraightTruck"
	GeoroutesWaypointOptimizationTruckTypeTractor       = "Tractor"
)

var georoutesDayOfWeekValues = []string{
	"Monday",
	"Tuesday",
	"Wednesday",
	"Thursday",
	"Friday",
	"Saturday",
	"Sunday",
}

var georoutesGeometryFormatValues = []string{
	"FlexiblePolyline",
	"Simple",
}

var georoutesIsolineEngineTypeValues = []string{
	"Electric",
	"InternalCombustion",
	"PluginHybrid",
}

var georoutesIsolineHazardousCargoTypeValues = []string{
	"Combustible",
	"Corrosive",
	"Explosive",
	"Flammable",
	"Gas",
	"HarmfulToWater",
	"Organic",
	"Other",
	"Poison",
	"PoisonousInhalation",
	"Radioactive",
}

var georoutesIsolineOptimizationObjectiveValues = []string{
	"AccurateCalculation",
	"BalancedCalculation",
	"FastCalculation",
}

var georoutesIsolineTravelModeValues = []string{
	"Car",
	"Pedestrian",
	"Scooter",
	"Truck",
}

var georoutesIsolineTruckTypeValues = []string{
	"LightTruck",
	"StraightTruck",
	"Tractor",
}

var georoutesIsolineZoneCategoryValues = []string{
	"CongestionPricing",
	"Environmental",
	"Vignette",
}

var georoutesMatchingStrategyValues = []string{
	"MatchAny",
	"MatchMostSignificantRoad",
}

var georoutesMeasurementSystemValues = []string{
	"Metric",
	"Imperial",
}

var georoutesRoadSnapHazardousCargoTypeValues = []string{
	"Combustible",
	"Corrosive",
	"Explosive",
	"Flammable",
	"Gas",
	"HarmfulToWater",
	"Organic",
	"Other",
	"Poison",
	"PoisonousInhalation",
	"Radioactive",
}

var georoutesRoadSnapNoticeCodeValues = []string{
	"TracePointsHeadingIgnored",
	"TracePointsIgnored",
	"TracePointsMovedByLargeDistance",
	"TracePointsNotMatched",
	"TracePointsOutOfSequence",
	"TracePointsSpeedEstimated",
	"TracePointsSpeedIgnored",
}

var georoutesRoadSnapTravelModeValues = []string{
	"Car",
	"Pedestrian",
	"Scooter",
	"Truck",
}

var georoutesRouteDirectionValues = []string{
	"East",
	"North",
	"South",
	"West",
}

var georoutesRouteEngineTypeValues = []string{
	"Electric",
	"InternalCombustion",
	"PluginHybrid",
}

var georoutesRouteFerryAfterTravelStepTypeValues = []string{
	"Deboard",
}

var georoutesRouteFerryBeforeTravelStepTypeValues = []string{
	"Board",
}

var georoutesRouteFerryNoticeCodeValues = []string{
	"AccuratePolylineUnavailable",
	"NoSchedule",
	"Other",
	"ViolatedAvoidFerry",
	"ViolatedAvoidRailFerry",
	"SeasonalClosure",
	"PotentialViolatedVehicleRestrictionUsage",
}

var georoutesRouteFerryTravelStepTypeValues = []string{
	"Depart",
	"Continue",
	"Arrive",
}

var georoutesRouteHazardousCargoTypeValues = []string{
	"Combustible",
	"Corrosive",
	"Explosive",
	"Flammable",
	"Gas",
	"HarmfulToWater",
	"Organic",
	"Other",
	"Poison",
	"PoisonousInhalation",
	"Radioactive",
}

var georoutesRouteLegAdditionalFeatureValues = []string{
	"Elevation",
	"Incidents",
	"PassThroughWaypoints",
	"Summary",
	"Tolls",
	"TravelStepInstructions",
	"TruckRoadTypes",
	"TypicalDuration",
	"Zones",
}

var georoutesRouteLegTravelModeValues = []string{
	"Car",
	"Ferry",
	"Pedestrian",
	"Scooter",
	"Truck",
	"CarShuttleTrain",
}

var georoutesRouteLegTypeValues = []string{
	"Ferry",
	"Pedestrian",
	"Vehicle",
}

var georoutesRouteMatrixErrorCodeValues = []string{
	"NoMatch",
	"NoMatchDestination",
	"NoMatchOrigin",
	"NoRoute",
	"OutOfBounds",
	"OutOfBoundsDestination",
	"OutOfBoundsOrigin",
	"Other",
	"Violation",
}

var georoutesRouteMatrixHazardousCargoTypeValues = []string{
	"Combustible",
	"Corrosive",
	"Explosive",
	"Flammable",
	"Gas",
	"HarmfulToWater",
	"Organic",
	"Other",
	"Poison",
	"PoisonousInhalation",
	"Radioactive",
}

var georoutesRouteMatrixTravelModeValues = []string{
	"Car",
	"Pedestrian",
	"Scooter",
	"Truck",
}

var georoutesRouteMatrixTruckTypeValues = []string{
	"LightTruck",
	"StraightTruck",
	"Tractor",
}

var georoutesRouteMatrixZoneCategoryValues = []string{
	"CongestionPricing",
	"Environmental",
	"Vignette",
}

var georoutesRouteNoticeImpactValues = []string{
	"High",
	"Low",
}

var georoutesRoutePedestrianNoticeCodeValues = []string{
	"AccuratePolylineUnavailable",
	"Other",
	"ViolatedAvoidDirtRoad",
	"ViolatedAvoidTunnel",
	"ViolatedPedestrianOption",
}

var georoutesRoutePedestrianTravelStepTypeValues = []string{
	"Arrive",
	"Continue",
	"Depart",
	"Keep",
	"RoundaboutEnter",
	"RoundaboutExit",
	"RoundaboutPass",
	"Turn",
	"Exit",
	"Ramp",
	"UTurn",
}

var georoutesRouteResponseNoticeCodeValues = []string{
	"MainLanguageNotFound",
	"Other",
	"TravelTimeExceedsDriverWorkHours",
}

var georoutesRouteRoadTypeValues = []string{
	"Highway",
	"Rural",
	"Urban",
}

var georoutesRouteSideOfStreetValues = []string{
	"Left",
	"Right",
}

var georoutesRouteSpanAdditionalFeatureValues = []string{
	"BestCaseDuration",
	"CarAccess",
	"Country",
	"Distance",
	"Duration",
	"DynamicSpeed",
	"FunctionalClassification",
	"Gates",
	"Incidents",
	"Names",
	"Notices",
	"PedestrianAccess",
	"RailwayCrossings",
	"Region",
	"RoadAttributes",
	"RouteNumbers",
	"ScooterAccess",
	"SpeedLimit",
	"TollSystems",
	"TruckAccess",
	"TruckRoadTypes",
	"TypicalDuration",
	"Zones",
	"Consumption",
}

var georoutesRouteSpanCarAccessAttributeValues = []string{
	"Allowed",
	"NoThroughTraffic",
	"TollRoad",
}

var georoutesRouteSpanGateAttributeValues = []string{
	"Emergency",
	"KeyAccess",
	"PermissionRequired",
}

var georoutesRouteSpanPedestrianAccessAttributeValues = []string{
	"Allowed",
	"Indoors",
	"NoThroughTraffic",
	"Park",
	"Stairs",
	"TollRoad",
}

var georoutesRouteSpanRailwayCrossingAttributeValues = []string{
	"Protected",
	"Unprotected",
}

var georoutesRouteSpanRoadAttributeValues = []string{
	"Bridge",
	"BuiltUpArea",
	"ControlledAccessHighway",
	"DirtRoad",
	"DividedRoad",
	"Motorway",
	"PrivateRoad",
	"Ramp",
	"RightHandTraffic",
	"Roundabout",
	"Tunnel",
	"UnderConstruction",
}

var georoutesRouteSpanScooterAccessAttributeValues = []string{
	"Allowed",
	"NoThroughTraffic",
	"TollRoad",
}

var georoutesRouteSpanTruckAccessAttributeValues = []string{
	"Allowed",
	"NoThroughTraffic",
	"TollRoad",
}

var georoutesRouteSteeringDirectionValues = []string{
	"Left",
	"Right",
	"Straight",
}

var georoutesRouteTollPassValidityPeriodTypeValues = []string{
	"Annual",
	"Days",
	"ExtendedAnnual",
	"Minutes",
	"Months",
}

var georoutesRouteTollPaymentMethodValues = []string{
	"BankCard",
	"Cash",
	"CashExact",
	"CreditCard",
	"PassSubscription",
	"TravelCard",
	"Transponder",
	"VideoToll",
}

var georoutesRouteTollVehicleCategoryValues = []string{
	"Minibus",
}

var georoutesRouteTravelModeValues = []string{
	"Car",
	"Pedestrian",
	"Scooter",
	"Truck",
}

var georoutesRouteTravelStepTypeValues = []string{
	"Default",
	"TurnByTurn",
}

var georoutesRouteTruckTypeValues = []string{
	"LightTruck",
	"StraightTruck",
	"Tractor",
}

var georoutesRouteTurnIntensityValues = []string{
	"Sharp",
	"Slight",
	"Typical",
}

var georoutesRouteVehicleIncidentSeverityValues = []string{
	"Critical",
	"High",
	"Medium",
	"Low",
}

var georoutesRouteVehicleIncidentTypeValues = []string{
	"Accident",
	"Congestion",
	"Construction",
	"DisabledVehicle",
	"LaneRestriction",
	"MassTransit",
	"Other",
	"PlannedEvent",
	"RoadClosure",
	"RoadHazard",
	"Weather",
}

var georoutesRouteVehicleNoticeCodeValues = []string{
	"AccuratePolylineUnavailable",
	"Other",
	"PotentialViolatedAvoidTollRoadUsage",
	"PotentialViolatedCarpoolUsage",
	"PotentialViolatedTurnRestrictionUsage",
	"PotentialViolatedVehicleRestrictionUsage",
	"PotentialViolatedZoneRestrictionUsage",
	"SeasonalClosure",
	"TollsDataTemporarilyUnavailable",
	"TollsDataUnavailable",
	"TollTransponder",
	"ViolatedAvoidControlledAccessHighway",
	"ViolatedAvoidDifficultTurns",
	"ViolatedAvoidDirtRoad",
	"ViolatedAvoidSeasonalClosure",
	"ViolatedAvoidTollRoad",
	"ViolatedAvoidTollTransponder",
	"ViolatedAvoidTruckRoadType",
	"ViolatedAvoidTunnel",
	"ViolatedAvoidUTurns",
	"ViolatedBlockedRoad",
	"ViolatedCarpool",
	"ViolatedEmergencyGate",
	"ViolatedStartDirection",
	"ViolatedTurnRestriction",
	"ViolatedVehicleRestriction",
	"ViolatedZoneRestriction",
}

var georoutesRouteVehicleTravelStepTypeValues = []string{
	"Arrive",
	"Continue",
	"ContinueHighway",
	"Depart",
	"EnterHighway",
	"Exit",
	"Keep",
	"Ramp",
	"RoundaboutEnter",
	"RoundaboutExit",
	"RoundaboutPass",
	"Turn",
	"UTurn",
}

var georoutesRouteWeightConstraintTypeValues = []string{
	"Current",
	"Gross",
	"Unknown",
}

var georoutesRouteZoneCategoryValues = []string{
	"CongestionPricing",
	"Environmental",
	"Vignette",
}

var georoutesRoutingObjectiveValues = []string{
	"FastestRoute",
	"ShortestRoute",
}

var georoutesSideOfStreetMatchingStrategyValues = []string{
	"AnyStreet",
	"DividedStreetOnly",
}

var georoutesTrafficUsageValues = []string{
	"IgnoreTrafficData",
	"UseTrafficData",
}

var georoutesValidationExceptionReasonValues = []string{
	"UnknownOperation",
	"Missing",
	"CannotParse",
	"FieldValidationFailed",
	"Other",
	"UnknownField",
}

var georoutesWaypointOptimizationClusteringAlgorithmValues = []string{
	"DrivingDistance",
	"TopologySegment",
}

var georoutesWaypointOptimizationConstraintValues = []string{
	"AccessHours",
	"AppointmentTime",
	"Before",
	"Heading",
	"ServiceDuration",
	"SideOfStreet",
}

var georoutesWaypointOptimizationHazardousCargoTypeValues = []string{
	"Combustible",
	"Corrosive",
	"Explosive",
	"Flammable",
	"Gas",
	"HarmfulToWater",
	"Organic",
	"Other",
	"Poison",
	"PoisonousInhalation",
	"Radioactive",
}

var georoutesWaypointOptimizationSequencingObjectiveValues = []string{
	"FastestRoute",
	"ShortestRoute",
}

var georoutesWaypointOptimizationServiceTimeTreatmentValues = []string{
	"Rest",
	"Work",
}

var georoutesWaypointOptimizationTravelModeValues = []string{
	"Car",
	"Pedestrian",
	"Scooter",
	"Truck",
}

var georoutesWaypointOptimizationTruckTypeValues = []string{
	"StraightTruck",
	"Tractor",
}

func getGeoRoutesEnum(name string) []string {
	switch name {
	case "DayOfWeek":
		return georoutesDayOfWeekValues
	case "GeometryFormat":
		return georoutesGeometryFormatValues
	case "IsolineEngineType":
		return georoutesIsolineEngineTypeValues
	case "IsolineHazardousCargoType":
		return georoutesIsolineHazardousCargoTypeValues
	case "IsolineOptimizationObjective":
		return georoutesIsolineOptimizationObjectiveValues
	case "IsolineTravelMode":
		return georoutesIsolineTravelModeValues
	case "IsolineTruckType":
		return georoutesIsolineTruckTypeValues
	case "IsolineZoneCategory":
		return georoutesIsolineZoneCategoryValues
	case "MatchingStrategy":
		return georoutesMatchingStrategyValues
	case "MeasurementSystem":
		return georoutesMeasurementSystemValues
	case "RoadSnapHazardousCargoType":
		return georoutesRoadSnapHazardousCargoTypeValues
	case "RoadSnapNoticeCode":
		return georoutesRoadSnapNoticeCodeValues
	case "RoadSnapTravelMode":
		return georoutesRoadSnapTravelModeValues
	case "RouteDirection":
		return georoutesRouteDirectionValues
	case "RouteEngineType":
		return georoutesRouteEngineTypeValues
	case "RouteFerryAfterTravelStepType":
		return georoutesRouteFerryAfterTravelStepTypeValues
	case "RouteFerryBeforeTravelStepType":
		return georoutesRouteFerryBeforeTravelStepTypeValues
	case "RouteFerryNoticeCode":
		return georoutesRouteFerryNoticeCodeValues
	case "RouteFerryTravelStepType":
		return georoutesRouteFerryTravelStepTypeValues
	case "RouteHazardousCargoType":
		return georoutesRouteHazardousCargoTypeValues
	case "RouteLegAdditionalFeature":
		return georoutesRouteLegAdditionalFeatureValues
	case "RouteLegTravelMode":
		return georoutesRouteLegTravelModeValues
	case "RouteLegType":
		return georoutesRouteLegTypeValues
	case "RouteMatrixErrorCode":
		return georoutesRouteMatrixErrorCodeValues
	case "RouteMatrixHazardousCargoType":
		return georoutesRouteMatrixHazardousCargoTypeValues
	case "RouteMatrixTravelMode":
		return georoutesRouteMatrixTravelModeValues
	case "RouteMatrixTruckType":
		return georoutesRouteMatrixTruckTypeValues
	case "RouteMatrixZoneCategory":
		return georoutesRouteMatrixZoneCategoryValues
	case "RouteNoticeImpact":
		return georoutesRouteNoticeImpactValues
	case "RoutePedestrianNoticeCode":
		return georoutesRoutePedestrianNoticeCodeValues
	case "RoutePedestrianTravelStepType":
		return georoutesRoutePedestrianTravelStepTypeValues
	case "RouteResponseNoticeCode":
		return georoutesRouteResponseNoticeCodeValues
	case "RouteRoadType":
		return georoutesRouteRoadTypeValues
	case "RouteSideOfStreet":
		return georoutesRouteSideOfStreetValues
	case "RouteSpanAdditionalFeature":
		return georoutesRouteSpanAdditionalFeatureValues
	case "RouteSpanCarAccessAttribute":
		return georoutesRouteSpanCarAccessAttributeValues
	case "RouteSpanGateAttribute":
		return georoutesRouteSpanGateAttributeValues
	case "RouteSpanPedestrianAccessAttribute":
		return georoutesRouteSpanPedestrianAccessAttributeValues
	case "RouteSpanRailwayCrossingAttribute":
		return georoutesRouteSpanRailwayCrossingAttributeValues
	case "RouteSpanRoadAttribute":
		return georoutesRouteSpanRoadAttributeValues
	case "RouteSpanScooterAccessAttribute":
		return georoutesRouteSpanScooterAccessAttributeValues
	case "RouteSpanTruckAccessAttribute":
		return georoutesRouteSpanTruckAccessAttributeValues
	case "RouteSteeringDirection":
		return georoutesRouteSteeringDirectionValues
	case "RouteTollPassValidityPeriodType":
		return georoutesRouteTollPassValidityPeriodTypeValues
	case "RouteTollPaymentMethod":
		return georoutesRouteTollPaymentMethodValues
	case "RouteTollVehicleCategory":
		return georoutesRouteTollVehicleCategoryValues
	case "RouteTravelMode":
		return georoutesRouteTravelModeValues
	case "RouteTravelStepType":
		return georoutesRouteTravelStepTypeValues
	case "RouteTruckType":
		return georoutesRouteTruckTypeValues
	case "RouteTurnIntensity":
		return georoutesRouteTurnIntensityValues
	case "RouteVehicleIncidentSeverity":
		return georoutesRouteVehicleIncidentSeverityValues
	case "RouteVehicleIncidentType":
		return georoutesRouteVehicleIncidentTypeValues
	case "RouteVehicleNoticeCode":
		return georoutesRouteVehicleNoticeCodeValues
	case "RouteVehicleTravelStepType":
		return georoutesRouteVehicleTravelStepTypeValues
	case "RouteWeightConstraintType":
		return georoutesRouteWeightConstraintTypeValues
	case "RouteZoneCategory":
		return georoutesRouteZoneCategoryValues
	case "RoutingObjective":
		return georoutesRoutingObjectiveValues
	case "SideOfStreetMatchingStrategy":
		return georoutesSideOfStreetMatchingStrategyValues
	case "TrafficUsage":
		return georoutesTrafficUsageValues
	case "ValidationExceptionReason":
		return georoutesValidationExceptionReasonValues
	case "WaypointOptimizationClusteringAlgorithm":
		return georoutesWaypointOptimizationClusteringAlgorithmValues
	case "WaypointOptimizationConstraint":
		return georoutesWaypointOptimizationConstraintValues
	case "WaypointOptimizationHazardousCargoType":
		return georoutesWaypointOptimizationHazardousCargoTypeValues
	case "WaypointOptimizationSequencingObjective":
		return georoutesWaypointOptimizationSequencingObjectiveValues
	case "WaypointOptimizationServiceTimeTreatment":
		return georoutesWaypointOptimizationServiceTimeTreatmentValues
	case "WaypointOptimizationTravelMode":
		return georoutesWaypointOptimizationTravelModeValues
	case "WaypointOptimizationTruckType":
		return georoutesWaypointOptimizationTruckTypeValues
	}
	return nil
}

func getGeoRoutesEnumNames() []string {
	return []string{
		"DayOfWeek",
		"GeometryFormat",
		"IsolineEngineType",
		"IsolineHazardousCargoType",
		"IsolineOptimizationObjective",
		"IsolineTravelMode",
		"IsolineTruckType",
		"IsolineZoneCategory",
		"MatchingStrategy",
		"MeasurementSystem",
		"RoadSnapHazardousCargoType",
		"RoadSnapNoticeCode",
		"RoadSnapTravelMode",
		"RouteDirection",
		"RouteEngineType",
		"RouteFerryAfterTravelStepType",
		"RouteFerryBeforeTravelStepType",
		"RouteFerryNoticeCode",
		"RouteFerryTravelStepType",
		"RouteHazardousCargoType",
		"RouteLegAdditionalFeature",
		"RouteLegTravelMode",
		"RouteLegType",
		"RouteMatrixErrorCode",
		"RouteMatrixHazardousCargoType",
		"RouteMatrixTravelMode",
		"RouteMatrixTruckType",
		"RouteMatrixZoneCategory",
		"RouteNoticeImpact",
		"RoutePedestrianNoticeCode",
		"RoutePedestrianTravelStepType",
		"RouteResponseNoticeCode",
		"RouteRoadType",
		"RouteSideOfStreet",
		"RouteSpanAdditionalFeature",
		"RouteSpanCarAccessAttribute",
		"RouteSpanGateAttribute",
		"RouteSpanPedestrianAccessAttribute",
		"RouteSpanRailwayCrossingAttribute",
		"RouteSpanRoadAttribute",
		"RouteSpanScooterAccessAttribute",
		"RouteSpanTruckAccessAttribute",
		"RouteSteeringDirection",
		"RouteTollPassValidityPeriodType",
		"RouteTollPaymentMethod",
		"RouteTollVehicleCategory",
		"RouteTravelMode",
		"RouteTravelStepType",
		"RouteTruckType",
		"RouteTurnIntensity",
		"RouteVehicleIncidentSeverity",
		"RouteVehicleIncidentType",
		"RouteVehicleNoticeCode",
		"RouteVehicleTravelStepType",
		"RouteWeightConstraintType",
		"RouteZoneCategory",
		"RoutingObjective",
		"SideOfStreetMatchingStrategy",
		"TrafficUsage",
		"ValidationExceptionReason",
		"WaypointOptimizationClusteringAlgorithm",
		"WaypointOptimizationConstraint",
		"WaypointOptimizationHazardousCargoType",
		"WaypointOptimizationSequencingObjective",
		"WaypointOptimizationServiceTimeTreatment",
		"WaypointOptimizationTravelMode",
		"WaypointOptimizationTruckType",
	}
}
