// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// IotJobsData enum constants
const (
	// JobExecutionStatus values
	IotjobsdataJobExecutionStatusQueued     = "QUEUED"
	IotjobsdataJobExecutionStatusInProgress = "IN_PROGRESS"
	IotjobsdataJobExecutionStatusSucceeded  = "SUCCEEDED"
	IotjobsdataJobExecutionStatusFailed     = "FAILED"
	IotjobsdataJobExecutionStatusTimedOut   = "TIMED_OUT"
	IotjobsdataJobExecutionStatusRejected   = "REJECTED"
	IotjobsdataJobExecutionStatusRemoved    = "REMOVED"
	IotjobsdataJobExecutionStatusCanceled   = "CANCELED"
)

var iotjobsdataJobExecutionStatusValues = []string{
	"QUEUED",
	"IN_PROGRESS",
	"SUCCEEDED",
	"FAILED",
	"TIMED_OUT",
	"REJECTED",
	"REMOVED",
	"CANCELED",
}

func getIotJobsDataEnum(name string) []string {
	switch name {
	case "JobExecutionStatus":
		return iotjobsdataJobExecutionStatusValues
	}
	return nil
}

func getIotJobsDataEnumNames() []string {
	return []string{
		"JobExecutionStatus",
	}
}
