// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Iottwinmaker enum constants
const (
	// ColumnType values
	IottwinmakerColumnTypeNode  = "NODE"
	IottwinmakerColumnTypeEdge  = "EDGE"
	IottwinmakerColumnTypeValue = "VALUE"

	// ComponentUpdateType values
	IottwinmakerComponentUpdateTypeCreate = "CREATE"
	IottwinmakerComponentUpdateTypeUpdate = "UPDATE"
	IottwinmakerComponentUpdateTypeDelete = "DELETE"

	// DestinationType values
	IottwinmakerDestinationTypeS3           = "s3"
	IottwinmakerDestinationTypeIotsitewise  = "iotsitewise"
	IottwinmakerDestinationTypeIottwinmaker = "iottwinmaker"

	// ErrorCode values
	IottwinmakerErrorCodeValidationError           = "VALIDATION_ERROR"
	IottwinmakerErrorCodeInternalFailure           = "INTERNAL_FAILURE"
	IottwinmakerErrorCodeSyncInitializingError     = "SYNC_INITIALIZING_ERROR"
	IottwinmakerErrorCodeSyncCreatingError         = "SYNC_CREATING_ERROR"
	IottwinmakerErrorCodeSyncProcessingError       = "SYNC_PROCESSING_ERROR"
	IottwinmakerErrorCodeSyncDeletingError         = "SYNC_DELETING_ERROR"
	IottwinmakerErrorCodeProcessingError           = "PROCESSING_ERROR"
	IottwinmakerErrorCodeCompositeComponentFailure = "COMPOSITE_COMPONENT_FAILURE"

	// GroupType values
	IottwinmakerGroupTypeTabular = "TABULAR"

	// InterpolationType values
	IottwinmakerInterpolationTypeLinear = "LINEAR"

	// MetadataTransferJobState values
	IottwinmakerMetadataTransferJobStateValidating = "VALIDATING"
	IottwinmakerMetadataTransferJobStatePending    = "PENDING"
	IottwinmakerMetadataTransferJobStateRunning    = "RUNNING"
	IottwinmakerMetadataTransferJobStateCancelling = "CANCELLING"
	IottwinmakerMetadataTransferJobStateError      = "ERROR"
	IottwinmakerMetadataTransferJobStateCompleted  = "COMPLETED"
	IottwinmakerMetadataTransferJobStateCancelled  = "CANCELLED"

	// Order values
	IottwinmakerOrderAscending  = "ASCENDING"
	IottwinmakerOrderDescending = "DESCENDING"

	// OrderByTime values
	IottwinmakerOrderByTimeAscending  = "ASCENDING"
	IottwinmakerOrderByTimeDescending = "DESCENDING"

	// ParentEntityUpdateType values
	IottwinmakerParentEntityUpdateTypeUpdate = "UPDATE"
	IottwinmakerParentEntityUpdateTypeDelete = "DELETE"

	// PricingMode values
	IottwinmakerPricingModeBasic        = "BASIC"
	IottwinmakerPricingModeStandard     = "STANDARD"
	IottwinmakerPricingModeTieredBundle = "TIERED_BUNDLE"

	// PricingTier values
	IottwinmakerPricingTierTier1 = "TIER_1"
	IottwinmakerPricingTierTier2 = "TIER_2"
	IottwinmakerPricingTierTier3 = "TIER_3"
	IottwinmakerPricingTierTier4 = "TIER_4"

	// PropertyGroupUpdateType values
	IottwinmakerPropertyGroupUpdateTypeUpdate = "UPDATE"
	IottwinmakerPropertyGroupUpdateTypeDelete = "DELETE"
	IottwinmakerPropertyGroupUpdateTypeCreate = "CREATE"

	// PropertyUpdateType values
	IottwinmakerPropertyUpdateTypeUpdate     = "UPDATE"
	IottwinmakerPropertyUpdateTypeDelete     = "DELETE"
	IottwinmakerPropertyUpdateTypeCreate     = "CREATE"
	IottwinmakerPropertyUpdateTypeResetValue = "RESET_VALUE"

	// SceneErrorCode values
	IottwinmakerSceneErrorCodeMatterportError = "MATTERPORT_ERROR"

	// Scope values
	IottwinmakerScopeEntity    = "ENTITY"
	IottwinmakerScopeWorkspace = "WORKSPACE"

	// SourceType values
	IottwinmakerSourceTypeS3           = "s3"
	IottwinmakerSourceTypeIotsitewise  = "iotsitewise"
	IottwinmakerSourceTypeIottwinmaker = "iottwinmaker"

	// State values
	IottwinmakerStateCreating = "CREATING"
	IottwinmakerStateUpdating = "UPDATING"
	IottwinmakerStateDeleting = "DELETING"
	IottwinmakerStateActive   = "ACTIVE"
	IottwinmakerStateError    = "ERROR"

	// SyncJobState values
	IottwinmakerSyncJobStateCreating     = "CREATING"
	IottwinmakerSyncJobStateInitializing = "INITIALIZING"
	IottwinmakerSyncJobStateActive       = "ACTIVE"
	IottwinmakerSyncJobStateDeleting     = "DELETING"
	IottwinmakerSyncJobStateError        = "ERROR"

	// SyncResourceState values
	IottwinmakerSyncResourceStateInitializing = "INITIALIZING"
	IottwinmakerSyncResourceStateProcessing   = "PROCESSING"
	IottwinmakerSyncResourceStateDeleted      = "DELETED"
	IottwinmakerSyncResourceStateInSync       = "IN_SYNC"
	IottwinmakerSyncResourceStateError        = "ERROR"

	// SyncResourceType values
	IottwinmakerSyncResourceTypeEntity        = "ENTITY"
	IottwinmakerSyncResourceTypeComponentType = "COMPONENT_TYPE"

	// Type values
	IottwinmakerTypeRelationship = "RELATIONSHIP"
	IottwinmakerTypeString       = "STRING"
	IottwinmakerTypeLong         = "LONG"
	IottwinmakerTypeBoolean      = "BOOLEAN"
	IottwinmakerTypeInteger      = "INTEGER"
	IottwinmakerTypeDouble       = "DOUBLE"
	IottwinmakerTypeList         = "LIST"
	IottwinmakerTypeMap          = "MAP"

	// UpdateReason values
	IottwinmakerUpdateReasonDefault           = "DEFAULT"
	IottwinmakerUpdateReasonPricingTierUpdate = "PRICING_TIER_UPDATE"
	IottwinmakerUpdateReasonEntityCountUpdate = "ENTITY_COUNT_UPDATE"
	IottwinmakerUpdateReasonPricingModeUpdate = "PRICING_MODE_UPDATE"
	IottwinmakerUpdateReasonOverwritten       = "OVERWRITTEN"
)

var iottwinmakerColumnTypeValues = []string{
	"NODE",
	"EDGE",
	"VALUE",
}

var iottwinmakerComponentUpdateTypeValues = []string{
	"CREATE",
	"UPDATE",
	"DELETE",
}

var iottwinmakerDestinationTypeValues = []string{
	"s3",
	"iotsitewise",
	"iottwinmaker",
}

var iottwinmakerErrorCodeValues = []string{
	"VALIDATION_ERROR",
	"INTERNAL_FAILURE",
	"SYNC_INITIALIZING_ERROR",
	"SYNC_CREATING_ERROR",
	"SYNC_PROCESSING_ERROR",
	"SYNC_DELETING_ERROR",
	"PROCESSING_ERROR",
	"COMPOSITE_COMPONENT_FAILURE",
}

var iottwinmakerGroupTypeValues = []string{
	"TABULAR",
}

var iottwinmakerInterpolationTypeValues = []string{
	"LINEAR",
}

var iottwinmakerMetadataTransferJobStateValues = []string{
	"VALIDATING",
	"PENDING",
	"RUNNING",
	"CANCELLING",
	"ERROR",
	"COMPLETED",
	"CANCELLED",
}

var iottwinmakerOrderValues = []string{
	"ASCENDING",
	"DESCENDING",
}

var iottwinmakerOrderByTimeValues = []string{
	"ASCENDING",
	"DESCENDING",
}

var iottwinmakerParentEntityUpdateTypeValues = []string{
	"UPDATE",
	"DELETE",
}

var iottwinmakerPricingModeValues = []string{
	"BASIC",
	"STANDARD",
	"TIERED_BUNDLE",
}

var iottwinmakerPricingTierValues = []string{
	"TIER_1",
	"TIER_2",
	"TIER_3",
	"TIER_4",
}

var iottwinmakerPropertyGroupUpdateTypeValues = []string{
	"UPDATE",
	"DELETE",
	"CREATE",
}

var iottwinmakerPropertyUpdateTypeValues = []string{
	"UPDATE",
	"DELETE",
	"CREATE",
	"RESET_VALUE",
}

var iottwinmakerSceneErrorCodeValues = []string{
	"MATTERPORT_ERROR",
}

var iottwinmakerScopeValues = []string{
	"ENTITY",
	"WORKSPACE",
}

var iottwinmakerSourceTypeValues = []string{
	"s3",
	"iotsitewise",
	"iottwinmaker",
}

var iottwinmakerStateValues = []string{
	"CREATING",
	"UPDATING",
	"DELETING",
	"ACTIVE",
	"ERROR",
}

var iottwinmakerSyncJobStateValues = []string{
	"CREATING",
	"INITIALIZING",
	"ACTIVE",
	"DELETING",
	"ERROR",
}

var iottwinmakerSyncResourceStateValues = []string{
	"INITIALIZING",
	"PROCESSING",
	"DELETED",
	"IN_SYNC",
	"ERROR",
}

var iottwinmakerSyncResourceTypeValues = []string{
	"ENTITY",
	"COMPONENT_TYPE",
}

var iottwinmakerTypeValues = []string{
	"RELATIONSHIP",
	"STRING",
	"LONG",
	"BOOLEAN",
	"INTEGER",
	"DOUBLE",
	"LIST",
	"MAP",
}

var iottwinmakerUpdateReasonValues = []string{
	"DEFAULT",
	"PRICING_TIER_UPDATE",
	"ENTITY_COUNT_UPDATE",
	"PRICING_MODE_UPDATE",
	"OVERWRITTEN",
}

func getIottwinmakerEnum(name string) []string {
	switch name {
	case "ColumnType":
		return iottwinmakerColumnTypeValues
	case "ComponentUpdateType":
		return iottwinmakerComponentUpdateTypeValues
	case "DestinationType":
		return iottwinmakerDestinationTypeValues
	case "ErrorCode":
		return iottwinmakerErrorCodeValues
	case "GroupType":
		return iottwinmakerGroupTypeValues
	case "InterpolationType":
		return iottwinmakerInterpolationTypeValues
	case "MetadataTransferJobState":
		return iottwinmakerMetadataTransferJobStateValues
	case "Order":
		return iottwinmakerOrderValues
	case "OrderByTime":
		return iottwinmakerOrderByTimeValues
	case "ParentEntityUpdateType":
		return iottwinmakerParentEntityUpdateTypeValues
	case "PricingMode":
		return iottwinmakerPricingModeValues
	case "PricingTier":
		return iottwinmakerPricingTierValues
	case "PropertyGroupUpdateType":
		return iottwinmakerPropertyGroupUpdateTypeValues
	case "PropertyUpdateType":
		return iottwinmakerPropertyUpdateTypeValues
	case "SceneErrorCode":
		return iottwinmakerSceneErrorCodeValues
	case "Scope":
		return iottwinmakerScopeValues
	case "SourceType":
		return iottwinmakerSourceTypeValues
	case "State":
		return iottwinmakerStateValues
	case "SyncJobState":
		return iottwinmakerSyncJobStateValues
	case "SyncResourceState":
		return iottwinmakerSyncResourceStateValues
	case "SyncResourceType":
		return iottwinmakerSyncResourceTypeValues
	case "Type":
		return iottwinmakerTypeValues
	case "UpdateReason":
		return iottwinmakerUpdateReasonValues
	}
	return nil
}

func getIottwinmakerEnumNames() []string {
	return []string{
		"ColumnType",
		"ComponentUpdateType",
		"DestinationType",
		"ErrorCode",
		"GroupType",
		"InterpolationType",
		"MetadataTransferJobState",
		"Order",
		"OrderByTime",
		"ParentEntityUpdateType",
		"PricingMode",
		"PricingTier",
		"PropertyGroupUpdateType",
		"PropertyUpdateType",
		"SceneErrorCode",
		"Scope",
		"SourceType",
		"State",
		"SyncJobState",
		"SyncResourceState",
		"SyncResourceType",
		"Type",
		"UpdateReason",
	}
}
