// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Iotwireless enum constants
const (
	// AggregationPeriod values
	IotwirelessAggregationPeriodOnehour = "OneHour"
	IotwirelessAggregationPeriodOneday  = "OneDay"
	IotwirelessAggregationPeriodOneweek = "OneWeek"

	// ApplicationConfigType values
	IotwirelessApplicationConfigTypeSemtechgeolocation = "SemtechGeolocation"

	// BatteryLevel values
	IotwirelessBatteryLevelNormal   = "normal"
	IotwirelessBatteryLevelLow      = "low"
	IotwirelessBatteryLevelCritical = "critical"

	// ConnectionStatus values
	IotwirelessConnectionStatusConnected    = "Connected"
	IotwirelessConnectionStatusDisconnected = "Disconnected"

	// DeviceProfileType values
	IotwirelessDeviceProfileTypeSidewalk = "Sidewalk"
	IotwirelessDeviceProfileTypeLorawan  = "LoRaWAN"

	// DeviceState values
	IotwirelessDeviceStateProvisioned           = "Provisioned"
	IotwirelessDeviceStateRegisterednotseen     = "RegisteredNotSeen"
	IotwirelessDeviceStateRegisteredreachable   = "RegisteredReachable"
	IotwirelessDeviceStateRegisteredunreachable = "RegisteredUnreachable"

	// DimensionName values
	IotwirelessDimensionNameDeviceid  = "DeviceId"
	IotwirelessDimensionNameGatewayid = "GatewayId"

	// DlClass values
	IotwirelessDlClassClassb = "ClassB"
	IotwirelessDlClassClassc = "ClassC"

	// DownlinkMode values
	IotwirelessDownlinkModeSequential         = "SEQUENTIAL"
	IotwirelessDownlinkModeConcurrent         = "CONCURRENT"
	IotwirelessDownlinkModeUsingUplinkGateway = "USING_UPLINK_GATEWAY"

	// Event values
	IotwirelessEventDiscovered  = "discovered"
	IotwirelessEventLost        = "lost"
	IotwirelessEventAck         = "ack"
	IotwirelessEventNack        = "nack"
	IotwirelessEventPassthrough = "passthrough"

	// EventNotificationPartnerType values
	IotwirelessEventNotificationPartnerTypeSidewalk = "Sidewalk"

	// EventNotificationResourceType values
	IotwirelessEventNotificationResourceTypeSidewalkaccount = "SidewalkAccount"
	IotwirelessEventNotificationResourceTypeWirelessdevice  = "WirelessDevice"
	IotwirelessEventNotificationResourceTypeWirelessgateway = "WirelessGateway"

	// EventNotificationTopicStatus values
	IotwirelessEventNotificationTopicStatusEnabled  = "Enabled"
	IotwirelessEventNotificationTopicStatusDisabled = "Disabled"

	// ExpressionType values
	IotwirelessExpressionTypeRulename  = "RuleName"
	IotwirelessExpressionTypeMqtttopic = "MqttTopic"

	// FuotaDeviceStatus values
	IotwirelessFuotaDeviceStatusInitial                        = "Initial"
	IotwirelessFuotaDeviceStatusPackageNotSupported            = "Package_Not_Supported"
	IotwirelessFuotaDeviceStatusFragalgoUnsupported            = "FragAlgo_unsupported"
	IotwirelessFuotaDeviceStatusNotEnoughMemory                = "Not_enough_memory"
	IotwirelessFuotaDeviceStatusFragindexUnsupported           = "FragIndex_unsupported"
	IotwirelessFuotaDeviceStatusWrongDescriptor                = "Wrong_descriptor"
	IotwirelessFuotaDeviceStatusSessioncntReplay               = "SessionCnt_replay"
	IotwirelessFuotaDeviceStatusMissingfrag                    = "MissingFrag"
	IotwirelessFuotaDeviceStatusMemoryerror                    = "MemoryError"
	IotwirelessFuotaDeviceStatusMicerror                       = "MICError"
	IotwirelessFuotaDeviceStatusSuccessful                     = "Successful"
	IotwirelessFuotaDeviceStatusDeviceExistInConflictFuotaTask = "Device_exist_in_conflict_fuota_task"

	// FuotaTaskEvent values
	IotwirelessFuotaTaskEventFuota = "Fuota"

	// FuotaTaskStatus values
	IotwirelessFuotaTaskStatusPending             = "Pending"
	IotwirelessFuotaTaskStatusFuotasessionWaiting = "FuotaSession_Waiting"
	IotwirelessFuotaTaskStatusInFuotasession      = "In_FuotaSession"
	IotwirelessFuotaTaskStatusFuotadone           = "FuotaDone"
	IotwirelessFuotaTaskStatusDeleteWaiting       = "Delete_Waiting"

	// FuotaTaskType values
	IotwirelessFuotaTaskTypeLorawan = "LoRaWAN"

	// IdentifierType values
	IotwirelessIdentifierTypePartneraccountid  = "PartnerAccountId"
	IotwirelessIdentifierTypeDeveui            = "DevEui"
	IotwirelessIdentifierTypeGatewayeui        = "GatewayEui"
	IotwirelessIdentifierTypeWirelessdeviceid  = "WirelessDeviceId"
	IotwirelessIdentifierTypeWirelessgatewayid = "WirelessGatewayId"

	// ImportTaskStatus values
	IotwirelessImportTaskStatusInitializing = "INITIALIZING"
	IotwirelessImportTaskStatusInitialized  = "INITIALIZED"
	IotwirelessImportTaskStatusPending      = "PENDING"
	IotwirelessImportTaskStatusComplete     = "COMPLETE"
	IotwirelessImportTaskStatusFailed       = "FAILED"
	IotwirelessImportTaskStatusDeleting     = "DELETING"

	// LogLevel values
	IotwirelessLogLevelInfo     = "INFO"
	IotwirelessLogLevelError    = "ERROR"
	IotwirelessLogLevelDisabled = "DISABLED"

	// MessageType values
	IotwirelessMessageTypeCustomCommandIdNotify = "CUSTOM_COMMAND_ID_NOTIFY"
	IotwirelessMessageTypeCustomCommandIdGet    = "CUSTOM_COMMAND_ID_GET"
	IotwirelessMessageTypeCustomCommandIdSet    = "CUSTOM_COMMAND_ID_SET"
	IotwirelessMessageTypeCustomCommandIdResp   = "CUSTOM_COMMAND_ID_RESP"

	// MetricName values
	IotwirelessMetricNameDevicerssi                     = "DeviceRSSI"
	IotwirelessMetricNameDevicesnr                      = "DeviceSNR"
	IotwirelessMetricNameDeviceroamingrssi              = "DeviceRoamingRSSI"
	IotwirelessMetricNameDeviceroamingsnr               = "DeviceRoamingSNR"
	IotwirelessMetricNameDeviceuplinkcount              = "DeviceUplinkCount"
	IotwirelessMetricNameDevicedownlinkcount            = "DeviceDownlinkCount"
	IotwirelessMetricNameDeviceuplinklostcount          = "DeviceUplinkLostCount"
	IotwirelessMetricNameDeviceuplinklostrate           = "DeviceUplinkLostRate"
	IotwirelessMetricNameDevicejoinrequestcount         = "DeviceJoinRequestCount"
	IotwirelessMetricNameDevicejoinacceptcount          = "DeviceJoinAcceptCount"
	IotwirelessMetricNameDeviceroaminguplinkcount       = "DeviceRoamingUplinkCount"
	IotwirelessMetricNameDeviceroamingdownlinkcount     = "DeviceRoamingDownlinkCount"
	IotwirelessMetricNameGatewayuptime                  = "GatewayUpTime"
	IotwirelessMetricNameGatewaydowntime                = "GatewayDownTime"
	IotwirelessMetricNameGatewayrssi                    = "GatewayRSSI"
	IotwirelessMetricNameGatewaysnr                     = "GatewaySNR"
	IotwirelessMetricNameGatewayuplinkcount             = "GatewayUplinkCount"
	IotwirelessMetricNameGatewaydownlinkcount           = "GatewayDownlinkCount"
	IotwirelessMetricNameGatewayjoinrequestcount        = "GatewayJoinRequestCount"
	IotwirelessMetricNameGatewayjoinacceptcount         = "GatewayJoinAcceptCount"
	IotwirelessMetricNameAwsaccountuplinkcount          = "AwsAccountUplinkCount"
	IotwirelessMetricNameAwsaccountdownlinkcount        = "AwsAccountDownlinkCount"
	IotwirelessMetricNameAwsaccountuplinklostcount      = "AwsAccountUplinkLostCount"
	IotwirelessMetricNameAwsaccountuplinklostrate       = "AwsAccountUplinkLostRate"
	IotwirelessMetricNameAwsaccountjoinrequestcount     = "AwsAccountJoinRequestCount"
	IotwirelessMetricNameAwsaccountjoinacceptcount      = "AwsAccountJoinAcceptCount"
	IotwirelessMetricNameAwsaccountroaminguplinkcount   = "AwsAccountRoamingUplinkCount"
	IotwirelessMetricNameAwsaccountroamingdownlinkcount = "AwsAccountRoamingDownlinkCount"
	IotwirelessMetricNameAwsaccountdevicecount          = "AwsAccountDeviceCount"
	IotwirelessMetricNameAwsaccountgatewaycount         = "AwsAccountGatewayCount"
	IotwirelessMetricNameAwsaccountactivedevicecount    = "AwsAccountActiveDeviceCount"
	IotwirelessMetricNameAwsaccountactivegatewaycount   = "AwsAccountActiveGatewayCount"

	// MetricQueryStatus values
	IotwirelessMetricQueryStatusSucceeded = "Succeeded"
	IotwirelessMetricQueryStatusFailed    = "Failed"

	// MulticastFrameInfo values
	IotwirelessMulticastFrameInfoEnabled  = "ENABLED"
	IotwirelessMulticastFrameInfoDisabled = "DISABLED"

	// OnboardStatus values
	IotwirelessOnboardStatusInitialized = "INITIALIZED"
	IotwirelessOnboardStatusPending     = "PENDING"
	IotwirelessOnboardStatusOnboarded   = "ONBOARDED"
	IotwirelessOnboardStatusFailed      = "FAILED"

	// PartnerType values
	IotwirelessPartnerTypeSidewalk = "Sidewalk"

	// PositionConfigurationFec values
	IotwirelessPositionConfigurationFecRose = "ROSE"
	IotwirelessPositionConfigurationFecNone = "NONE"

	// PositionConfigurationStatus values
	IotwirelessPositionConfigurationStatusEnabled  = "Enabled"
	IotwirelessPositionConfigurationStatusDisabled = "Disabled"

	// PositionResourceType values
	IotwirelessPositionResourceTypeWirelessdevice  = "WirelessDevice"
	IotwirelessPositionResourceTypeWirelessgateway = "WirelessGateway"

	// PositionSolverProvider values
	IotwirelessPositionSolverProviderSemtech = "Semtech"

	// PositionSolverType values
	IotwirelessPositionSolverTypeGnss = "GNSS"

	// PositioningConfigStatus values
	IotwirelessPositioningConfigStatusEnabled  = "Enabled"
	IotwirelessPositioningConfigStatusDisabled = "Disabled"

	// SigningAlg values
	IotwirelessSigningAlgEd25519 = "Ed25519"
	IotwirelessSigningAlgP256r1  = "P256r1"

	// SummaryMetricConfigurationStatus values
	IotwirelessSummaryMetricConfigurationStatusEnabled  = "Enabled"
	IotwirelessSummaryMetricConfigurationStatusDisabled = "Disabled"

	// SupportedRfRegion values
	IotwirelessSupportedRfRegionEu868  = "EU868"
	IotwirelessSupportedRfRegionUs915  = "US915"
	IotwirelessSupportedRfRegionAu915  = "AU915"
	IotwirelessSupportedRfRegionAs9231 = "AS923-1"
	IotwirelessSupportedRfRegionAs9232 = "AS923-2"
	IotwirelessSupportedRfRegionAs9233 = "AS923-3"
	IotwirelessSupportedRfRegionAs9234 = "AS923-4"
	IotwirelessSupportedRfRegionEu433  = "EU433"
	IotwirelessSupportedRfRegionCn470  = "CN470"
	IotwirelessSupportedRfRegionCn779  = "CN779"
	IotwirelessSupportedRfRegionRu864  = "RU864"
	IotwirelessSupportedRfRegionKr920  = "KR920"
	IotwirelessSupportedRfRegionIn865  = "IN865"

	// WirelessDeviceEvent values
	IotwirelessWirelessDeviceEventJoin         = "Join"
	IotwirelessWirelessDeviceEventRejoin       = "Rejoin"
	IotwirelessWirelessDeviceEventUplinkData   = "Uplink_Data"
	IotwirelessWirelessDeviceEventDownlinkData = "Downlink_Data"
	IotwirelessWirelessDeviceEventRegistration = "Registration"

	// WirelessDeviceFrameInfo values
	IotwirelessWirelessDeviceFrameInfoEnabled  = "ENABLED"
	IotwirelessWirelessDeviceFrameInfoDisabled = "DISABLED"

	// WirelessDeviceIdType values
	IotwirelessWirelessDeviceIdTypeWirelessdeviceid        = "WirelessDeviceId"
	IotwirelessWirelessDeviceIdTypeDeveui                  = "DevEui"
	IotwirelessWirelessDeviceIdTypeThingname               = "ThingName"
	IotwirelessWirelessDeviceIdTypeSidewalkmanufacturingsn = "SidewalkManufacturingSn"

	// WirelessDeviceSidewalkStatus values
	IotwirelessWirelessDeviceSidewalkStatusProvisioned = "PROVISIONED"
	IotwirelessWirelessDeviceSidewalkStatusRegistered  = "REGISTERED"
	IotwirelessWirelessDeviceSidewalkStatusActivated   = "ACTIVATED"
	IotwirelessWirelessDeviceSidewalkStatusUnknown     = "UNKNOWN"

	// WirelessDeviceType values
	IotwirelessWirelessDeviceTypeSidewalk = "Sidewalk"
	IotwirelessWirelessDeviceTypeLorawan  = "LoRaWAN"

	// WirelessGatewayEvent values
	IotwirelessWirelessGatewayEventCupsRequest = "CUPS_Request"
	IotwirelessWirelessGatewayEventCertificate = "Certificate"

	// WirelessGatewayIdType values
	IotwirelessWirelessGatewayIdTypeGatewayeui        = "GatewayEui"
	IotwirelessWirelessGatewayIdTypeWirelessgatewayid = "WirelessGatewayId"
	IotwirelessWirelessGatewayIdTypeThingname         = "ThingName"

	// WirelessGatewayServiceType values
	IotwirelessWirelessGatewayServiceTypeCups = "CUPS"
	IotwirelessWirelessGatewayServiceTypeLns  = "LNS"

	// WirelessGatewayTaskDefinitionType values
	IotwirelessWirelessGatewayTaskDefinitionTypeUpdate = "UPDATE"

	// WirelessGatewayTaskStatus values
	IotwirelessWirelessGatewayTaskStatusPending     = "PENDING"
	IotwirelessWirelessGatewayTaskStatusInProgress  = "IN_PROGRESS"
	IotwirelessWirelessGatewayTaskStatusFirstRetry  = "FIRST_RETRY"
	IotwirelessWirelessGatewayTaskStatusSecondRetry = "SECOND_RETRY"
	IotwirelessWirelessGatewayTaskStatusCompleted   = "COMPLETED"
	IotwirelessWirelessGatewayTaskStatusFailed      = "FAILED"

	// WirelessGatewayType values
	IotwirelessWirelessGatewayTypeLorawan = "LoRaWAN"
)

var iotwirelessAggregationPeriodValues = []string{
	"OneHour",
	"OneDay",
	"OneWeek",
}

var iotwirelessApplicationConfigTypeValues = []string{
	"SemtechGeolocation",
}

var iotwirelessBatteryLevelValues = []string{
	"normal",
	"low",
	"critical",
}

var iotwirelessConnectionStatusValues = []string{
	"Connected",
	"Disconnected",
}

var iotwirelessDeviceProfileTypeValues = []string{
	"Sidewalk",
	"LoRaWAN",
}

var iotwirelessDeviceStateValues = []string{
	"Provisioned",
	"RegisteredNotSeen",
	"RegisteredReachable",
	"RegisteredUnreachable",
}

var iotwirelessDimensionNameValues = []string{
	"DeviceId",
	"GatewayId",
}

var iotwirelessDlClassValues = []string{
	"ClassB",
	"ClassC",
}

var iotwirelessDownlinkModeValues = []string{
	"SEQUENTIAL",
	"CONCURRENT",
	"USING_UPLINK_GATEWAY",
}

var iotwirelessEventValues = []string{
	"discovered",
	"lost",
	"ack",
	"nack",
	"passthrough",
}

var iotwirelessEventNotificationPartnerTypeValues = []string{
	"Sidewalk",
}

var iotwirelessEventNotificationResourceTypeValues = []string{
	"SidewalkAccount",
	"WirelessDevice",
	"WirelessGateway",
}

var iotwirelessEventNotificationTopicStatusValues = []string{
	"Enabled",
	"Disabled",
}

var iotwirelessExpressionTypeValues = []string{
	"RuleName",
	"MqttTopic",
}

var iotwirelessFuotaDeviceStatusValues = []string{
	"Initial",
	"Package_Not_Supported",
	"FragAlgo_unsupported",
	"Not_enough_memory",
	"FragIndex_unsupported",
	"Wrong_descriptor",
	"SessionCnt_replay",
	"MissingFrag",
	"MemoryError",
	"MICError",
	"Successful",
	"Device_exist_in_conflict_fuota_task",
}

var iotwirelessFuotaTaskEventValues = []string{
	"Fuota",
}

var iotwirelessFuotaTaskStatusValues = []string{
	"Pending",
	"FuotaSession_Waiting",
	"In_FuotaSession",
	"FuotaDone",
	"Delete_Waiting",
}

var iotwirelessFuotaTaskTypeValues = []string{
	"LoRaWAN",
}

var iotwirelessIdentifierTypeValues = []string{
	"PartnerAccountId",
	"DevEui",
	"GatewayEui",
	"WirelessDeviceId",
	"WirelessGatewayId",
}

var iotwirelessImportTaskStatusValues = []string{
	"INITIALIZING",
	"INITIALIZED",
	"PENDING",
	"COMPLETE",
	"FAILED",
	"DELETING",
}

var iotwirelessLogLevelValues = []string{
	"INFO",
	"ERROR",
	"DISABLED",
}

var iotwirelessMessageTypeValues = []string{
	"CUSTOM_COMMAND_ID_NOTIFY",
	"CUSTOM_COMMAND_ID_GET",
	"CUSTOM_COMMAND_ID_SET",
	"CUSTOM_COMMAND_ID_RESP",
}

var iotwirelessMetricNameValues = []string{
	"DeviceRSSI",
	"DeviceSNR",
	"DeviceRoamingRSSI",
	"DeviceRoamingSNR",
	"DeviceUplinkCount",
	"DeviceDownlinkCount",
	"DeviceUplinkLostCount",
	"DeviceUplinkLostRate",
	"DeviceJoinRequestCount",
	"DeviceJoinAcceptCount",
	"DeviceRoamingUplinkCount",
	"DeviceRoamingDownlinkCount",
	"GatewayUpTime",
	"GatewayDownTime",
	"GatewayRSSI",
	"GatewaySNR",
	"GatewayUplinkCount",
	"GatewayDownlinkCount",
	"GatewayJoinRequestCount",
	"GatewayJoinAcceptCount",
	"AwsAccountUplinkCount",
	"AwsAccountDownlinkCount",
	"AwsAccountUplinkLostCount",
	"AwsAccountUplinkLostRate",
	"AwsAccountJoinRequestCount",
	"AwsAccountJoinAcceptCount",
	"AwsAccountRoamingUplinkCount",
	"AwsAccountRoamingDownlinkCount",
	"AwsAccountDeviceCount",
	"AwsAccountGatewayCount",
	"AwsAccountActiveDeviceCount",
	"AwsAccountActiveGatewayCount",
}

var iotwirelessMetricQueryStatusValues = []string{
	"Succeeded",
	"Failed",
}

var iotwirelessMulticastFrameInfoValues = []string{
	"ENABLED",
	"DISABLED",
}

var iotwirelessOnboardStatusValues = []string{
	"INITIALIZED",
	"PENDING",
	"ONBOARDED",
	"FAILED",
}

var iotwirelessPartnerTypeValues = []string{
	"Sidewalk",
}

var iotwirelessPositionConfigurationFecValues = []string{
	"ROSE",
	"NONE",
}

var iotwirelessPositionConfigurationStatusValues = []string{
	"Enabled",
	"Disabled",
}

var iotwirelessPositionResourceTypeValues = []string{
	"WirelessDevice",
	"WirelessGateway",
}

var iotwirelessPositionSolverProviderValues = []string{
	"Semtech",
}

var iotwirelessPositionSolverTypeValues = []string{
	"GNSS",
}

var iotwirelessPositioningConfigStatusValues = []string{
	"Enabled",
	"Disabled",
}

var iotwirelessSigningAlgValues = []string{
	"Ed25519",
	"P256r1",
}

var iotwirelessSummaryMetricConfigurationStatusValues = []string{
	"Enabled",
	"Disabled",
}

var iotwirelessSupportedRfRegionValues = []string{
	"EU868",
	"US915",
	"AU915",
	"AS923-1",
	"AS923-2",
	"AS923-3",
	"AS923-4",
	"EU433",
	"CN470",
	"CN779",
	"RU864",
	"KR920",
	"IN865",
}

var iotwirelessWirelessDeviceEventValues = []string{
	"Join",
	"Rejoin",
	"Uplink_Data",
	"Downlink_Data",
	"Registration",
}

var iotwirelessWirelessDeviceFrameInfoValues = []string{
	"ENABLED",
	"DISABLED",
}

var iotwirelessWirelessDeviceIdTypeValues = []string{
	"WirelessDeviceId",
	"DevEui",
	"ThingName",
	"SidewalkManufacturingSn",
}

var iotwirelessWirelessDeviceSidewalkStatusValues = []string{
	"PROVISIONED",
	"REGISTERED",
	"ACTIVATED",
	"UNKNOWN",
}

var iotwirelessWirelessDeviceTypeValues = []string{
	"Sidewalk",
	"LoRaWAN",
}

var iotwirelessWirelessGatewayEventValues = []string{
	"CUPS_Request",
	"Certificate",
}

var iotwirelessWirelessGatewayIdTypeValues = []string{
	"GatewayEui",
	"WirelessGatewayId",
	"ThingName",
}

var iotwirelessWirelessGatewayServiceTypeValues = []string{
	"CUPS",
	"LNS",
}

var iotwirelessWirelessGatewayTaskDefinitionTypeValues = []string{
	"UPDATE",
}

var iotwirelessWirelessGatewayTaskStatusValues = []string{
	"PENDING",
	"IN_PROGRESS",
	"FIRST_RETRY",
	"SECOND_RETRY",
	"COMPLETED",
	"FAILED",
}

var iotwirelessWirelessGatewayTypeValues = []string{
	"LoRaWAN",
}

func getIotwirelessEnum(name string) []string {
	switch name {
	case "AggregationPeriod":
		return iotwirelessAggregationPeriodValues
	case "ApplicationConfigType":
		return iotwirelessApplicationConfigTypeValues
	case "BatteryLevel":
		return iotwirelessBatteryLevelValues
	case "ConnectionStatus":
		return iotwirelessConnectionStatusValues
	case "DeviceProfileType":
		return iotwirelessDeviceProfileTypeValues
	case "DeviceState":
		return iotwirelessDeviceStateValues
	case "DimensionName":
		return iotwirelessDimensionNameValues
	case "DlClass":
		return iotwirelessDlClassValues
	case "DownlinkMode":
		return iotwirelessDownlinkModeValues
	case "Event":
		return iotwirelessEventValues
	case "EventNotificationPartnerType":
		return iotwirelessEventNotificationPartnerTypeValues
	case "EventNotificationResourceType":
		return iotwirelessEventNotificationResourceTypeValues
	case "EventNotificationTopicStatus":
		return iotwirelessEventNotificationTopicStatusValues
	case "ExpressionType":
		return iotwirelessExpressionTypeValues
	case "FuotaDeviceStatus":
		return iotwirelessFuotaDeviceStatusValues
	case "FuotaTaskEvent":
		return iotwirelessFuotaTaskEventValues
	case "FuotaTaskStatus":
		return iotwirelessFuotaTaskStatusValues
	case "FuotaTaskType":
		return iotwirelessFuotaTaskTypeValues
	case "IdentifierType":
		return iotwirelessIdentifierTypeValues
	case "ImportTaskStatus":
		return iotwirelessImportTaskStatusValues
	case "LogLevel":
		return iotwirelessLogLevelValues
	case "MessageType":
		return iotwirelessMessageTypeValues
	case "MetricName":
		return iotwirelessMetricNameValues
	case "MetricQueryStatus":
		return iotwirelessMetricQueryStatusValues
	case "MulticastFrameInfo":
		return iotwirelessMulticastFrameInfoValues
	case "OnboardStatus":
		return iotwirelessOnboardStatusValues
	case "PartnerType":
		return iotwirelessPartnerTypeValues
	case "PositionConfigurationFec":
		return iotwirelessPositionConfigurationFecValues
	case "PositionConfigurationStatus":
		return iotwirelessPositionConfigurationStatusValues
	case "PositionResourceType":
		return iotwirelessPositionResourceTypeValues
	case "PositionSolverProvider":
		return iotwirelessPositionSolverProviderValues
	case "PositionSolverType":
		return iotwirelessPositionSolverTypeValues
	case "PositioningConfigStatus":
		return iotwirelessPositioningConfigStatusValues
	case "SigningAlg":
		return iotwirelessSigningAlgValues
	case "SummaryMetricConfigurationStatus":
		return iotwirelessSummaryMetricConfigurationStatusValues
	case "SupportedRfRegion":
		return iotwirelessSupportedRfRegionValues
	case "WirelessDeviceEvent":
		return iotwirelessWirelessDeviceEventValues
	case "WirelessDeviceFrameInfo":
		return iotwirelessWirelessDeviceFrameInfoValues
	case "WirelessDeviceIdType":
		return iotwirelessWirelessDeviceIdTypeValues
	case "WirelessDeviceSidewalkStatus":
		return iotwirelessWirelessDeviceSidewalkStatusValues
	case "WirelessDeviceType":
		return iotwirelessWirelessDeviceTypeValues
	case "WirelessGatewayEvent":
		return iotwirelessWirelessGatewayEventValues
	case "WirelessGatewayIdType":
		return iotwirelessWirelessGatewayIdTypeValues
	case "WirelessGatewayServiceType":
		return iotwirelessWirelessGatewayServiceTypeValues
	case "WirelessGatewayTaskDefinitionType":
		return iotwirelessWirelessGatewayTaskDefinitionTypeValues
	case "WirelessGatewayTaskStatus":
		return iotwirelessWirelessGatewayTaskStatusValues
	case "WirelessGatewayType":
		return iotwirelessWirelessGatewayTypeValues
	}
	return nil
}

func getIotwirelessEnumNames() []string {
	return []string{
		"AggregationPeriod",
		"ApplicationConfigType",
		"BatteryLevel",
		"ConnectionStatus",
		"DeviceProfileType",
		"DeviceState",
		"DimensionName",
		"DlClass",
		"DownlinkMode",
		"Event",
		"EventNotificationPartnerType",
		"EventNotificationResourceType",
		"EventNotificationTopicStatus",
		"ExpressionType",
		"FuotaDeviceStatus",
		"FuotaTaskEvent",
		"FuotaTaskStatus",
		"FuotaTaskType",
		"IdentifierType",
		"ImportTaskStatus",
		"LogLevel",
		"MessageType",
		"MetricName",
		"MetricQueryStatus",
		"MulticastFrameInfo",
		"OnboardStatus",
		"PartnerType",
		"PositionConfigurationFec",
		"PositionConfigurationStatus",
		"PositionResourceType",
		"PositionSolverProvider",
		"PositionSolverType",
		"PositioningConfigStatus",
		"SigningAlg",
		"SummaryMetricConfigurationStatus",
		"SupportedRfRegion",
		"WirelessDeviceEvent",
		"WirelessDeviceFrameInfo",
		"WirelessDeviceIdType",
		"WirelessDeviceSidewalkStatus",
		"WirelessDeviceType",
		"WirelessGatewayEvent",
		"WirelessGatewayIdType",
		"WirelessGatewayServiceType",
		"WirelessGatewayTaskDefinitionType",
		"WirelessGatewayTaskStatus",
		"WirelessGatewayType",
	}
}
