// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// M2 enum constants
const (
	// ApplicationDeploymentLifecycle values
	M2ApplicationDeploymentLifecycleDeploying = "Deploying"
	M2ApplicationDeploymentLifecycleDeployed  = "Deployed"

	// ApplicationLifecycle values
	M2ApplicationLifecycleCreating                = "Creating"
	M2ApplicationLifecycleCreated                 = "Created"
	M2ApplicationLifecycleAvailable               = "Available"
	M2ApplicationLifecycleReady                   = "Ready"
	M2ApplicationLifecycleStarting                = "Starting"
	M2ApplicationLifecycleRunning                 = "Running"
	M2ApplicationLifecycleStopping                = "Stopping"
	M2ApplicationLifecycleStopped                 = "Stopped"
	M2ApplicationLifecycleFailed                  = "Failed"
	M2ApplicationLifecycleDeleting                = "Deleting"
	M2ApplicationLifecycleDeletingFromEnvironment = "Deleting From Environment"

	// ApplicationVersionLifecycle values
	M2ApplicationVersionLifecycleCreating  = "Creating"
	M2ApplicationVersionLifecycleAvailable = "Available"
	M2ApplicationVersionLifecycleFailed    = "Failed"

	// BatchJobExecutionStatus values
	M2BatchJobExecutionStatusSubmitting           = "Submitting"
	M2BatchJobExecutionStatusHolding              = "Holding"
	M2BatchJobExecutionStatusDispatching          = "Dispatching"
	M2BatchJobExecutionStatusRunning              = "Running"
	M2BatchJobExecutionStatusCancelling           = "Cancelling"
	M2BatchJobExecutionStatusCancelled            = "Cancelled"
	M2BatchJobExecutionStatusSucceeded            = "Succeeded"
	M2BatchJobExecutionStatusFailed               = "Failed"
	M2BatchJobExecutionStatusPurged               = "Purged"
	M2BatchJobExecutionStatusSucceededWithWarning = "Succeeded With Warning"

	// BatchJobType values
	M2BatchJobTypeVse  = "VSE"
	M2BatchJobTypeJes2 = "JES2"
	M2BatchJobTypeJes3 = "JES3"

	// DataSetTaskLifecycle values
	M2DataSetTaskLifecycleCreating  = "Creating"
	M2DataSetTaskLifecycleRunning   = "Running"
	M2DataSetTaskLifecycleCompleted = "Completed"
	M2DataSetTaskLifecycleFailed    = "Failed"

	// DeploymentLifecycle values
	M2DeploymentLifecycleDeploying          = "Deploying"
	M2DeploymentLifecycleSucceeded          = "Succeeded"
	M2DeploymentLifecycleFailed             = "Failed"
	M2DeploymentLifecycleUpdatingDeployment = "Updating Deployment"

	// EngineType values
	M2EngineTypeMicrofocus = "microfocus"
	M2EngineTypeBluage     = "bluage"

	// EnvironmentLifecycle values
	M2EnvironmentLifecycleCreating  = "Creating"
	M2EnvironmentLifecycleAvailable = "Available"
	M2EnvironmentLifecycleUpdating  = "Updating"
	M2EnvironmentLifecycleDeleting  = "Deleting"
	M2EnvironmentLifecycleFailed    = "Failed"
	M2EnvironmentLifecycleUnhealthy = "UnHealthy"

	// NetworkType values
	M2NetworkTypeIpv4 = "ipv4"
	M2NetworkTypeDual = "dual"

	// ValidationExceptionReason values
	M2ValidationExceptionReasonUnknownoperation         = "unknownOperation"
	M2ValidationExceptionReasonCannotparse              = "cannotParse"
	M2ValidationExceptionReasonFeaturenotavailable      = "featureNotAvailable"
	M2ValidationExceptionReasonUnsupportedengineversion = "unsupportedEngineVersion"
	M2ValidationExceptionReasonFieldvalidationfailed    = "fieldValidationFailed"
	M2ValidationExceptionReasonOther                    = "other"
)

var m2ApplicationDeploymentLifecycleValues = []string{
	"Deploying",
	"Deployed",
}

var m2ApplicationLifecycleValues = []string{
	"Creating",
	"Created",
	"Available",
	"Ready",
	"Starting",
	"Running",
	"Stopping",
	"Stopped",
	"Failed",
	"Deleting",
	"Deleting From Environment",
}

var m2ApplicationVersionLifecycleValues = []string{
	"Creating",
	"Available",
	"Failed",
}

var m2BatchJobExecutionStatusValues = []string{
	"Submitting",
	"Holding",
	"Dispatching",
	"Running",
	"Cancelling",
	"Cancelled",
	"Succeeded",
	"Failed",
	"Purged",
	"Succeeded With Warning",
}

var m2BatchJobTypeValues = []string{
	"VSE",
	"JES2",
	"JES3",
}

var m2DataSetTaskLifecycleValues = []string{
	"Creating",
	"Running",
	"Completed",
	"Failed",
}

var m2DeploymentLifecycleValues = []string{
	"Deploying",
	"Succeeded",
	"Failed",
	"Updating Deployment",
}

var m2EngineTypeValues = []string{
	"microfocus",
	"bluage",
}

var m2EnvironmentLifecycleValues = []string{
	"Creating",
	"Available",
	"Updating",
	"Deleting",
	"Failed",
	"UnHealthy",
}

var m2NetworkTypeValues = []string{
	"ipv4",
	"dual",
}

var m2ValidationExceptionReasonValues = []string{
	"unknownOperation",
	"cannotParse",
	"featureNotAvailable",
	"unsupportedEngineVersion",
	"fieldValidationFailed",
	"other",
}

func getM2Enum(name string) []string {
	switch name {
	case "ApplicationDeploymentLifecycle":
		return m2ApplicationDeploymentLifecycleValues
	case "ApplicationLifecycle":
		return m2ApplicationLifecycleValues
	case "ApplicationVersionLifecycle":
		return m2ApplicationVersionLifecycleValues
	case "BatchJobExecutionStatus":
		return m2BatchJobExecutionStatusValues
	case "BatchJobType":
		return m2BatchJobTypeValues
	case "DataSetTaskLifecycle":
		return m2DataSetTaskLifecycleValues
	case "DeploymentLifecycle":
		return m2DeploymentLifecycleValues
	case "EngineType":
		return m2EngineTypeValues
	case "EnvironmentLifecycle":
		return m2EnvironmentLifecycleValues
	case "NetworkType":
		return m2NetworkTypeValues
	case "ValidationExceptionReason":
		return m2ValidationExceptionReasonValues
	}
	return nil
}

func getM2EnumNames() []string {
	return []string{
		"ApplicationDeploymentLifecycle",
		"ApplicationLifecycle",
		"ApplicationVersionLifecycle",
		"BatchJobExecutionStatus",
		"BatchJobType",
		"DataSetTaskLifecycle",
		"DeploymentLifecycle",
		"EngineType",
		"EnvironmentLifecycle",
		"NetworkType",
		"ValidationExceptionReason",
	}
}
