// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Mq enum constants
const (
	// AuthenticationStrategy values
	MqAuthenticationStrategySimple        = "SIMPLE"
	MqAuthenticationStrategyLdap          = "LDAP"
	MqAuthenticationStrategyConfigManaged = "CONFIG_MANAGED"

	// BrokerState values
	MqBrokerStateCreationInProgress     = "CREATION_IN_PROGRESS"
	MqBrokerStateCreationFailed         = "CREATION_FAILED"
	MqBrokerStateDeletionInProgress     = "DELETION_IN_PROGRESS"
	MqBrokerStateRunning                = "RUNNING"
	MqBrokerStateRebootInProgress       = "REBOOT_IN_PROGRESS"
	MqBrokerStateCriticalActionRequired = "CRITICAL_ACTION_REQUIRED"
	MqBrokerStateReplica                = "REPLICA"

	// BrokerStorageType values
	MqBrokerStorageTypeEbs = "EBS"
	MqBrokerStorageTypeEfs = "EFS"

	// ChangeType values
	MqChangeTypeCreate = "CREATE"
	MqChangeTypeUpdate = "UPDATE"
	MqChangeTypeDelete = "DELETE"

	// DataReplicationMode values
	MqDataReplicationModeNone = "NONE"
	MqDataReplicationModeCrdr = "CRDR"

	// DayOfWeek values
	MqDayOfWeekMonday    = "MONDAY"
	MqDayOfWeekTuesday   = "TUESDAY"
	MqDayOfWeekWednesday = "WEDNESDAY"
	MqDayOfWeekThursday  = "THURSDAY"
	MqDayOfWeekFriday    = "FRIDAY"
	MqDayOfWeekSaturday  = "SATURDAY"
	MqDayOfWeekSunday    = "SUNDAY"

	// DeploymentMode values
	MqDeploymentModeSingleInstance       = "SINGLE_INSTANCE"
	MqDeploymentModeActiveStandbyMultiAz = "ACTIVE_STANDBY_MULTI_AZ"
	MqDeploymentModeClusterMultiAz       = "CLUSTER_MULTI_AZ"

	// EngineType values
	MqEngineTypeActivemq = "ACTIVEMQ"
	MqEngineTypeRabbitmq = "RABBITMQ"

	// PromoteMode values
	MqPromoteModeSwitchover = "SWITCHOVER"
	MqPromoteModeFailover   = "FAILOVER"

	// SanitizationWarningReason values
	MqSanitizationWarningReasonDisallowedElementRemoved     = "DISALLOWED_ELEMENT_REMOVED"
	MqSanitizationWarningReasonDisallowedAttributeRemoved   = "DISALLOWED_ATTRIBUTE_REMOVED"
	MqSanitizationWarningReasonInvalidAttributeValueRemoved = "INVALID_ATTRIBUTE_VALUE_REMOVED"
)

var mqAuthenticationStrategyValues = []string{
	"SIMPLE",
	"LDAP",
	"CONFIG_MANAGED",
}

var mqBrokerStateValues = []string{
	"CREATION_IN_PROGRESS",
	"CREATION_FAILED",
	"DELETION_IN_PROGRESS",
	"RUNNING",
	"REBOOT_IN_PROGRESS",
	"CRITICAL_ACTION_REQUIRED",
	"REPLICA",
}

var mqBrokerStorageTypeValues = []string{
	"EBS",
	"EFS",
}

var mqChangeTypeValues = []string{
	"CREATE",
	"UPDATE",
	"DELETE",
}

var mqDataReplicationModeValues = []string{
	"NONE",
	"CRDR",
}

var mqDayOfWeekValues = []string{
	"MONDAY",
	"TUESDAY",
	"WEDNESDAY",
	"THURSDAY",
	"FRIDAY",
	"SATURDAY",
	"SUNDAY",
}

var mqDeploymentModeValues = []string{
	"SINGLE_INSTANCE",
	"ACTIVE_STANDBY_MULTI_AZ",
	"CLUSTER_MULTI_AZ",
}

var mqEngineTypeValues = []string{
	"ACTIVEMQ",
	"RABBITMQ",
}

var mqPromoteModeValues = []string{
	"SWITCHOVER",
	"FAILOVER",
}

var mqSanitizationWarningReasonValues = []string{
	"DISALLOWED_ELEMENT_REMOVED",
	"DISALLOWED_ATTRIBUTE_REMOVED",
	"INVALID_ATTRIBUTE_VALUE_REMOVED",
}

func getMqEnum(name string) []string {
	switch name {
	case "AuthenticationStrategy":
		return mqAuthenticationStrategyValues
	case "BrokerState":
		return mqBrokerStateValues
	case "BrokerStorageType":
		return mqBrokerStorageTypeValues
	case "ChangeType":
		return mqChangeTypeValues
	case "DataReplicationMode":
		return mqDataReplicationModeValues
	case "DayOfWeek":
		return mqDayOfWeekValues
	case "DeploymentMode":
		return mqDeploymentModeValues
	case "EngineType":
		return mqEngineTypeValues
	case "PromoteMode":
		return mqPromoteModeValues
	case "SanitizationWarningReason":
		return mqSanitizationWarningReasonValues
	}
	return nil
}

func getMqEnumNames() []string {
	return []string{
		"AuthenticationStrategy",
		"BrokerState",
		"BrokerStorageType",
		"ChangeType",
		"DataReplicationMode",
		"DayOfWeek",
		"DeploymentMode",
		"EngineType",
		"PromoteMode",
		"SanitizationWarningReason",
	}
}
