// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Neptunedata enum constants
const (
	// Action values
	NeptunedataActionInitiatedatabasereset = "initiateDatabaseReset"
	NeptunedataActionPerformdatabasereset  = "performDatabaseReset"

	// Encoding values
	NeptunedataEncodingGzip = "gzip"

	// Format values
	NeptunedataFormatCsv        = "csv"
	NeptunedataFormatOpencypher = "opencypher"
	NeptunedataFormatNtriples   = "ntriples"
	NeptunedataFormatNquads     = "nquads"
	NeptunedataFormatRdfxml     = "rdfxml"
	NeptunedataFormatTurtle     = "turtle"

	// GraphSummaryType values
	NeptunedataGraphSummaryTypeBasic    = "basic"
	NeptunedataGraphSummaryTypeDetailed = "detailed"

	// IteratorType values
	NeptunedataIteratorTypeAtSequenceNumber    = "AT_SEQUENCE_NUMBER"
	NeptunedataIteratorTypeAfterSequenceNumber = "AFTER_SEQUENCE_NUMBER"
	NeptunedataIteratorTypeTrimHorizon         = "TRIM_HORIZON"
	NeptunedataIteratorTypeLatest              = "LATEST"

	// Mode values
	NeptunedataModeResume = "RESUME"
	NeptunedataModeNew    = "NEW"
	NeptunedataModeAuto   = "AUTO"

	// OpenCypherExplainMode values
	NeptunedataOpenCypherExplainModeStatic  = "static"
	NeptunedataOpenCypherExplainModeDynamic = "dynamic"
	NeptunedataOpenCypherExplainModeDetails = "details"

	// Parallelism values
	NeptunedataParallelismLow           = "LOW"
	NeptunedataParallelismMedium        = "MEDIUM"
	NeptunedataParallelismHigh          = "HIGH"
	NeptunedataParallelismOversubscribe = "OVERSUBSCRIBE"

	// S3BucketRegion values
	NeptunedataS3BucketRegionUsEast1      = "us-east-1"
	NeptunedataS3BucketRegionUsEast2      = "us-east-2"
	NeptunedataS3BucketRegionUsWest1      = "us-west-1"
	NeptunedataS3BucketRegionUsWest2      = "us-west-2"
	NeptunedataS3BucketRegionCaCentral1   = "ca-central-1"
	NeptunedataS3BucketRegionSaEast1      = "sa-east-1"
	NeptunedataS3BucketRegionEuNorth1     = "eu-north-1"
	NeptunedataS3BucketRegionEuWest1      = "eu-west-1"
	NeptunedataS3BucketRegionEuWest2      = "eu-west-2"
	NeptunedataS3BucketRegionEuWest3      = "eu-west-3"
	NeptunedataS3BucketRegionEuCentral1   = "eu-central-1"
	NeptunedataS3BucketRegionMeSouth1     = "me-south-1"
	NeptunedataS3BucketRegionAfSouth1     = "af-south-1"
	NeptunedataS3BucketRegionApEast1      = "ap-east-1"
	NeptunedataS3BucketRegionApNortheast1 = "ap-northeast-1"
	NeptunedataS3BucketRegionApNortheast2 = "ap-northeast-2"
	NeptunedataS3BucketRegionApSoutheast1 = "ap-southeast-1"
	NeptunedataS3BucketRegionApSoutheast2 = "ap-southeast-2"
	NeptunedataS3BucketRegionApSouth1     = "ap-south-1"
	NeptunedataS3BucketRegionCnNorth1     = "cn-north-1"
	NeptunedataS3BucketRegionCnNorthwest1 = "cn-northwest-1"
	NeptunedataS3BucketRegionUsGovWest1   = "us-gov-west-1"
	NeptunedataS3BucketRegionUsGovEast1   = "us-gov-east-1"
	NeptunedataS3BucketRegionCaWest1      = "ca-west-1"
	NeptunedataS3BucketRegionEuSouth2     = "eu-south-2"
	NeptunedataS3BucketRegionIlCentral1   = "il-central-1"
	NeptunedataS3BucketRegionMeCentral1   = "me-central-1"
	NeptunedataS3BucketRegionApNortheast3 = "ap-northeast-3"
	NeptunedataS3BucketRegionApSoutheast3 = "ap-southeast-3"
	NeptunedataS3BucketRegionApSoutheast4 = "ap-southeast-4"
	NeptunedataS3BucketRegionApSoutheast5 = "ap-southeast-5"
	NeptunedataS3BucketRegionApSoutheast7 = "ap-southeast-7"
	NeptunedataS3BucketRegionMxCentral1   = "mx-central-1"
	NeptunedataS3BucketRegionApEast2      = "ap-east-2"
	NeptunedataS3BucketRegionApSouth2     = "ap-south-2"
	NeptunedataS3BucketRegionEuCentral2   = "eu-central-2"

	// StatisticsAutoGenerationMode values
	NeptunedataStatisticsAutoGenerationModeDisableautocompute = "disableAutoCompute"
	NeptunedataStatisticsAutoGenerationModeEnableautocompute  = "enableAutoCompute"
	NeptunedataStatisticsAutoGenerationModeRefresh            = "refresh"
)

var neptunedataActionValues = []string{
	"initiateDatabaseReset",
	"performDatabaseReset",
}

var neptunedataEncodingValues = []string{
	"gzip",
}

var neptunedataFormatValues = []string{
	"csv",
	"opencypher",
	"ntriples",
	"nquads",
	"rdfxml",
	"turtle",
}

var neptunedataGraphSummaryTypeValues = []string{
	"basic",
	"detailed",
}

var neptunedataIteratorTypeValues = []string{
	"AT_SEQUENCE_NUMBER",
	"AFTER_SEQUENCE_NUMBER",
	"TRIM_HORIZON",
	"LATEST",
}

var neptunedataModeValues = []string{
	"RESUME",
	"NEW",
	"AUTO",
}

var neptunedataOpenCypherExplainModeValues = []string{
	"static",
	"dynamic",
	"details",
}

var neptunedataParallelismValues = []string{
	"LOW",
	"MEDIUM",
	"HIGH",
	"OVERSUBSCRIBE",
}

var neptunedataS3BucketRegionValues = []string{
	"us-east-1",
	"us-east-2",
	"us-west-1",
	"us-west-2",
	"ca-central-1",
	"sa-east-1",
	"eu-north-1",
	"eu-west-1",
	"eu-west-2",
	"eu-west-3",
	"eu-central-1",
	"me-south-1",
	"af-south-1",
	"ap-east-1",
	"ap-northeast-1",
	"ap-northeast-2",
	"ap-southeast-1",
	"ap-southeast-2",
	"ap-south-1",
	"cn-north-1",
	"cn-northwest-1",
	"us-gov-west-1",
	"us-gov-east-1",
	"ca-west-1",
	"eu-south-2",
	"il-central-1",
	"me-central-1",
	"ap-northeast-3",
	"ap-southeast-3",
	"ap-southeast-4",
	"ap-southeast-5",
	"ap-southeast-7",
	"mx-central-1",
	"ap-east-2",
	"ap-south-2",
	"eu-central-2",
}

var neptunedataStatisticsAutoGenerationModeValues = []string{
	"disableAutoCompute",
	"enableAutoCompute",
	"refresh",
}

func getNeptunedataEnum(name string) []string {
	switch name {
	case "Action":
		return neptunedataActionValues
	case "Encoding":
		return neptunedataEncodingValues
	case "Format":
		return neptunedataFormatValues
	case "GraphSummaryType":
		return neptunedataGraphSummaryTypeValues
	case "IteratorType":
		return neptunedataIteratorTypeValues
	case "Mode":
		return neptunedataModeValues
	case "OpenCypherExplainMode":
		return neptunedataOpenCypherExplainModeValues
	case "Parallelism":
		return neptunedataParallelismValues
	case "S3BucketRegion":
		return neptunedataS3BucketRegionValues
	case "StatisticsAutoGenerationMode":
		return neptunedataStatisticsAutoGenerationModeValues
	}
	return nil
}

func getNeptunedataEnumNames() []string {
	return []string{
		"Action",
		"Encoding",
		"Format",
		"GraphSummaryType",
		"IteratorType",
		"Mode",
		"OpenCypherExplainMode",
		"Parallelism",
		"S3BucketRegion",
		"StatisticsAutoGenerationMode",
	}
}
