// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Oam enum constants
const (
	// ResourceType values
	OamResourceTypeAwsCloudwatchMetric                        = "AWS::CloudWatch::Metric"
	OamResourceTypeAwsLogsLoggroup                            = "AWS::Logs::LogGroup"
	OamResourceTypeAwsXrayTrace                               = "AWS::XRay::Trace"
	OamResourceTypeAwsApplicationinsightsApplication          = "AWS::ApplicationInsights::Application"
	OamResourceTypeAwsInternetmonitorMonitor                  = "AWS::InternetMonitor::Monitor"
	OamResourceTypeAwsApplicationsignalsService               = "AWS::ApplicationSignals::Service"
	OamResourceTypeAwsApplicationsignalsServicelevelobjective = "AWS::ApplicationSignals::ServiceLevelObjective"
)

var oamResourceTypeValues = []string{
	"AWS::CloudWatch::Metric",
	"AWS::Logs::LogGroup",
	"AWS::XRay::Trace",
	"AWS::ApplicationInsights::Application",
	"AWS::InternetMonitor::Monitor",
	"AWS::ApplicationSignals::Service",
	"AWS::ApplicationSignals::ServiceLevelObjective",
}

func getOamEnum(name string) []string {
	switch name {
	case "ResourceType":
		return oamResourceTypeValues
	}
	return nil
}

func getOamEnumNames() []string {
	return []string{
		"ResourceType",
	}
}
