// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Route53domains enum constants
const (
	// ContactType values
	Route53domainsContactTypePerson      = "PERSON"
	Route53domainsContactTypeCompany     = "COMPANY"
	Route53domainsContactTypeAssociation = "ASSOCIATION"
	Route53domainsContactTypePublicBody  = "PUBLIC_BODY"
	Route53domainsContactTypeReseller    = "RESELLER"

	// CountryCode values
	Route53domainsCountryCodeAc = "AC"
	Route53domainsCountryCodeAd = "AD"
	Route53domainsCountryCodeAe = "AE"
	Route53domainsCountryCodeAf = "AF"
	Route53domainsCountryCodeAg = "AG"
	Route53domainsCountryCodeAi = "AI"
	Route53domainsCountryCodeAl = "AL"
	Route53domainsCountryCodeAm = "AM"
	Route53domainsCountryCodeAn = "AN"
	Route53domainsCountryCodeAo = "AO"
	Route53domainsCountryCodeAq = "AQ"
	Route53domainsCountryCodeAr = "AR"
	Route53domainsCountryCodeAs = "AS"
	Route53domainsCountryCodeAt = "AT"
	Route53domainsCountryCodeAu = "AU"
	Route53domainsCountryCodeAw = "AW"
	Route53domainsCountryCodeAx = "AX"
	Route53domainsCountryCodeAz = "AZ"
	Route53domainsCountryCodeBa = "BA"
	Route53domainsCountryCodeBb = "BB"
	Route53domainsCountryCodeBd = "BD"
	Route53domainsCountryCodeBe = "BE"
	Route53domainsCountryCodeBf = "BF"
	Route53domainsCountryCodeBg = "BG"
	Route53domainsCountryCodeBh = "BH"
	Route53domainsCountryCodeBi = "BI"
	Route53domainsCountryCodeBj = "BJ"
	Route53domainsCountryCodeBl = "BL"
	Route53domainsCountryCodeBm = "BM"
	Route53domainsCountryCodeBn = "BN"
	Route53domainsCountryCodeBo = "BO"
	Route53domainsCountryCodeBq = "BQ"
	Route53domainsCountryCodeBr = "BR"
	Route53domainsCountryCodeBs = "BS"
	Route53domainsCountryCodeBt = "BT"
	Route53domainsCountryCodeBv = "BV"
	Route53domainsCountryCodeBw = "BW"
	Route53domainsCountryCodeBy = "BY"
	Route53domainsCountryCodeBz = "BZ"
	Route53domainsCountryCodeCa = "CA"
	Route53domainsCountryCodeCc = "CC"
	Route53domainsCountryCodeCd = "CD"
	Route53domainsCountryCodeCf = "CF"
	Route53domainsCountryCodeCg = "CG"
	Route53domainsCountryCodeCh = "CH"
	Route53domainsCountryCodeCi = "CI"
	Route53domainsCountryCodeCk = "CK"
	Route53domainsCountryCodeCl = "CL"
	Route53domainsCountryCodeCm = "CM"
	Route53domainsCountryCodeCn = "CN"
	Route53domainsCountryCodeCo = "CO"
	Route53domainsCountryCodeCr = "CR"
	Route53domainsCountryCodeCu = "CU"
	Route53domainsCountryCodeCv = "CV"
	Route53domainsCountryCodeCw = "CW"
	Route53domainsCountryCodeCx = "CX"
	Route53domainsCountryCodeCy = "CY"
	Route53domainsCountryCodeCz = "CZ"
	Route53domainsCountryCodeDe = "DE"
	Route53domainsCountryCodeDj = "DJ"
	Route53domainsCountryCodeDk = "DK"
	Route53domainsCountryCodeDm = "DM"
	Route53domainsCountryCodeDo = "DO"
	Route53domainsCountryCodeDz = "DZ"
	Route53domainsCountryCodeEc = "EC"
	Route53domainsCountryCodeEe = "EE"
	Route53domainsCountryCodeEg = "EG"
	Route53domainsCountryCodeEh = "EH"
	Route53domainsCountryCodeEr = "ER"
	Route53domainsCountryCodeEs = "ES"
	Route53domainsCountryCodeEt = "ET"
	Route53domainsCountryCodeFi = "FI"
	Route53domainsCountryCodeFj = "FJ"
	Route53domainsCountryCodeFk = "FK"
	Route53domainsCountryCodeFm = "FM"
	Route53domainsCountryCodeFo = "FO"
	Route53domainsCountryCodeFr = "FR"
	Route53domainsCountryCodeGa = "GA"
	Route53domainsCountryCodeGb = "GB"
	Route53domainsCountryCodeGd = "GD"
	Route53domainsCountryCodeGe = "GE"
	Route53domainsCountryCodeGf = "GF"
	Route53domainsCountryCodeGg = "GG"
	Route53domainsCountryCodeGh = "GH"
	Route53domainsCountryCodeGi = "GI"
	Route53domainsCountryCodeGl = "GL"
	Route53domainsCountryCodeGm = "GM"
	Route53domainsCountryCodeGn = "GN"
	Route53domainsCountryCodeGp = "GP"
	Route53domainsCountryCodeGq = "GQ"
	Route53domainsCountryCodeGr = "GR"
	Route53domainsCountryCodeGs = "GS"
	Route53domainsCountryCodeGt = "GT"
	Route53domainsCountryCodeGu = "GU"
	Route53domainsCountryCodeGw = "GW"
	Route53domainsCountryCodeGy = "GY"
	Route53domainsCountryCodeHk = "HK"
	Route53domainsCountryCodeHm = "HM"
	Route53domainsCountryCodeHn = "HN"
	Route53domainsCountryCodeHr = "HR"
	Route53domainsCountryCodeHt = "HT"
	Route53domainsCountryCodeHu = "HU"
	Route53domainsCountryCodeId = "ID"
	Route53domainsCountryCodeIe = "IE"
	Route53domainsCountryCodeIl = "IL"
	Route53domainsCountryCodeIm = "IM"
	Route53domainsCountryCodeIn = "IN"
	Route53domainsCountryCodeIo = "IO"
	Route53domainsCountryCodeIq = "IQ"
	Route53domainsCountryCodeIr = "IR"
	Route53domainsCountryCodeIs = "IS"
	Route53domainsCountryCodeIt = "IT"
	Route53domainsCountryCodeJe = "JE"
	Route53domainsCountryCodeJm = "JM"
	Route53domainsCountryCodeJo = "JO"
	Route53domainsCountryCodeJp = "JP"
	Route53domainsCountryCodeKe = "KE"
	Route53domainsCountryCodeKg = "KG"
	Route53domainsCountryCodeKh = "KH"
	Route53domainsCountryCodeKi = "KI"
	Route53domainsCountryCodeKm = "KM"
	Route53domainsCountryCodeKn = "KN"
	Route53domainsCountryCodeKp = "KP"
	Route53domainsCountryCodeKr = "KR"
	Route53domainsCountryCodeKw = "KW"
	Route53domainsCountryCodeKy = "KY"
	Route53domainsCountryCodeKz = "KZ"
	Route53domainsCountryCodeLa = "LA"
	Route53domainsCountryCodeLb = "LB"
	Route53domainsCountryCodeLc = "LC"
	Route53domainsCountryCodeLi = "LI"
	Route53domainsCountryCodeLk = "LK"
	Route53domainsCountryCodeLr = "LR"
	Route53domainsCountryCodeLs = "LS"
	Route53domainsCountryCodeLt = "LT"
	Route53domainsCountryCodeLu = "LU"
	Route53domainsCountryCodeLv = "LV"
	Route53domainsCountryCodeLy = "LY"
	Route53domainsCountryCodeMa = "MA"
	Route53domainsCountryCodeMc = "MC"
	Route53domainsCountryCodeMd = "MD"
	Route53domainsCountryCodeMe = "ME"
	Route53domainsCountryCodeMf = "MF"
	Route53domainsCountryCodeMg = "MG"
	Route53domainsCountryCodeMh = "MH"
	Route53domainsCountryCodeMk = "MK"
	Route53domainsCountryCodeMl = "ML"
	Route53domainsCountryCodeMm = "MM"
	Route53domainsCountryCodeMn = "MN"
	Route53domainsCountryCodeMo = "MO"
	Route53domainsCountryCodeMp = "MP"
	Route53domainsCountryCodeMq = "MQ"
	Route53domainsCountryCodeMr = "MR"
	Route53domainsCountryCodeMs = "MS"
	Route53domainsCountryCodeMt = "MT"
	Route53domainsCountryCodeMu = "MU"
	Route53domainsCountryCodeMv = "MV"
	Route53domainsCountryCodeMw = "MW"
	Route53domainsCountryCodeMx = "MX"
	Route53domainsCountryCodeMy = "MY"
	Route53domainsCountryCodeMz = "MZ"
	Route53domainsCountryCodeNa = "NA"
	Route53domainsCountryCodeNc = "NC"
	Route53domainsCountryCodeNe = "NE"
	Route53domainsCountryCodeNf = "NF"
	Route53domainsCountryCodeNg = "NG"
	Route53domainsCountryCodeNi = "NI"
	Route53domainsCountryCodeNl = "NL"
	Route53domainsCountryCodeNo = "NO"
	Route53domainsCountryCodeNp = "NP"
	Route53domainsCountryCodeNr = "NR"
	Route53domainsCountryCodeNu = "NU"
	Route53domainsCountryCodeNz = "NZ"
	Route53domainsCountryCodeOm = "OM"
	Route53domainsCountryCodePa = "PA"
	Route53domainsCountryCodePe = "PE"
	Route53domainsCountryCodePf = "PF"
	Route53domainsCountryCodePg = "PG"
	Route53domainsCountryCodePh = "PH"
	Route53domainsCountryCodePk = "PK"
	Route53domainsCountryCodePl = "PL"
	Route53domainsCountryCodePm = "PM"
	Route53domainsCountryCodePn = "PN"
	Route53domainsCountryCodePr = "PR"
	Route53domainsCountryCodePs = "PS"
	Route53domainsCountryCodePt = "PT"
	Route53domainsCountryCodePw = "PW"
	Route53domainsCountryCodePy = "PY"
	Route53domainsCountryCodeQa = "QA"
	Route53domainsCountryCodeRe = "RE"
	Route53domainsCountryCodeRo = "RO"
	Route53domainsCountryCodeRs = "RS"
	Route53domainsCountryCodeRu = "RU"
	Route53domainsCountryCodeRw = "RW"
	Route53domainsCountryCodeSa = "SA"
	Route53domainsCountryCodeSb = "SB"
	Route53domainsCountryCodeSc = "SC"
	Route53domainsCountryCodeSd = "SD"
	Route53domainsCountryCodeSe = "SE"
	Route53domainsCountryCodeSg = "SG"
	Route53domainsCountryCodeSh = "SH"
	Route53domainsCountryCodeSi = "SI"
	Route53domainsCountryCodeSj = "SJ"
	Route53domainsCountryCodeSk = "SK"
	Route53domainsCountryCodeSl = "SL"
	Route53domainsCountryCodeSm = "SM"
	Route53domainsCountryCodeSn = "SN"
	Route53domainsCountryCodeSo = "SO"
	Route53domainsCountryCodeSr = "SR"
	Route53domainsCountryCodeSs = "SS"
	Route53domainsCountryCodeSt = "ST"
	Route53domainsCountryCodeSv = "SV"
	Route53domainsCountryCodeSx = "SX"
	Route53domainsCountryCodeSy = "SY"
	Route53domainsCountryCodeSz = "SZ"
	Route53domainsCountryCodeTc = "TC"
	Route53domainsCountryCodeTd = "TD"
	Route53domainsCountryCodeTf = "TF"
	Route53domainsCountryCodeTg = "TG"
	Route53domainsCountryCodeTh = "TH"
	Route53domainsCountryCodeTj = "TJ"
	Route53domainsCountryCodeTk = "TK"
	Route53domainsCountryCodeTl = "TL"
	Route53domainsCountryCodeTm = "TM"
	Route53domainsCountryCodeTn = "TN"
	Route53domainsCountryCodeTo = "TO"
	Route53domainsCountryCodeTp = "TP"
	Route53domainsCountryCodeTr = "TR"
	Route53domainsCountryCodeTt = "TT"
	Route53domainsCountryCodeTv = "TV"
	Route53domainsCountryCodeTw = "TW"
	Route53domainsCountryCodeTz = "TZ"
	Route53domainsCountryCodeUa = "UA"
	Route53domainsCountryCodeUg = "UG"
	Route53domainsCountryCodeUs = "US"
	Route53domainsCountryCodeUy = "UY"
	Route53domainsCountryCodeUz = "UZ"
	Route53domainsCountryCodeVa = "VA"
	Route53domainsCountryCodeVc = "VC"
	Route53domainsCountryCodeVe = "VE"
	Route53domainsCountryCodeVg = "VG"
	Route53domainsCountryCodeVi = "VI"
	Route53domainsCountryCodeVn = "VN"
	Route53domainsCountryCodeVu = "VU"
	Route53domainsCountryCodeWf = "WF"
	Route53domainsCountryCodeWs = "WS"
	Route53domainsCountryCodeYe = "YE"
	Route53domainsCountryCodeYt = "YT"
	Route53domainsCountryCodeZa = "ZA"
	Route53domainsCountryCodeZm = "ZM"
	Route53domainsCountryCodeZw = "ZW"

	// DomainAvailability values
	Route53domainsDomainAvailabilityAvailable             = "AVAILABLE"
	Route53domainsDomainAvailabilityAvailableReserved     = "AVAILABLE_RESERVED"
	Route53domainsDomainAvailabilityAvailablePreorder     = "AVAILABLE_PREORDER"
	Route53domainsDomainAvailabilityUnavailable           = "UNAVAILABLE"
	Route53domainsDomainAvailabilityUnavailablePremium    = "UNAVAILABLE_PREMIUM"
	Route53domainsDomainAvailabilityUnavailableRestricted = "UNAVAILABLE_RESTRICTED"
	Route53domainsDomainAvailabilityReserved              = "RESERVED"
	Route53domainsDomainAvailabilityDontKnow              = "DONT_KNOW"
	Route53domainsDomainAvailabilityInvalidNameForTld     = "INVALID_NAME_FOR_TLD"
	Route53domainsDomainAvailabilityPending               = "PENDING"

	// ExtraParamName values
	Route53domainsExtraParamNameDunsNumber                    = "DUNS_NUMBER"
	Route53domainsExtraParamNameBrandNumber                   = "BRAND_NUMBER"
	Route53domainsExtraParamNameBirthDepartment               = "BIRTH_DEPARTMENT"
	Route53domainsExtraParamNameBirthDateInYyyyMmDd           = "BIRTH_DATE_IN_YYYY_MM_DD"
	Route53domainsExtraParamNameBirthCountry                  = "BIRTH_COUNTRY"
	Route53domainsExtraParamNameBirthCity                     = "BIRTH_CITY"
	Route53domainsExtraParamNameDocumentNumber                = "DOCUMENT_NUMBER"
	Route53domainsExtraParamNameAuIdNumber                    = "AU_ID_NUMBER"
	Route53domainsExtraParamNameAuIdType                      = "AU_ID_TYPE"
	Route53domainsExtraParamNameCaLegalType                   = "CA_LEGAL_TYPE"
	Route53domainsExtraParamNameCaBusinessEntityType          = "CA_BUSINESS_ENTITY_TYPE"
	Route53domainsExtraParamNameCaLegalRepresentative         = "CA_LEGAL_REPRESENTATIVE"
	Route53domainsExtraParamNameCaLegalRepresentativeCapacity = "CA_LEGAL_REPRESENTATIVE_CAPACITY"
	Route53domainsExtraParamNameEsIdentification              = "ES_IDENTIFICATION"
	Route53domainsExtraParamNameEsIdentificationType          = "ES_IDENTIFICATION_TYPE"
	Route53domainsExtraParamNameEsLegalForm                   = "ES_LEGAL_FORM"
	Route53domainsExtraParamNameFiBusinessNumber              = "FI_BUSINESS_NUMBER"
	Route53domainsExtraParamNameFiIdNumber                    = "FI_ID_NUMBER"
	Route53domainsExtraParamNameFiNationality                 = "FI_NATIONALITY"
	Route53domainsExtraParamNameFiOrganizationType            = "FI_ORGANIZATION_TYPE"
	Route53domainsExtraParamNameItNationality                 = "IT_NATIONALITY"
	Route53domainsExtraParamNameItPin                         = "IT_PIN"
	Route53domainsExtraParamNameItRegistrantEntityType        = "IT_REGISTRANT_ENTITY_TYPE"
	Route53domainsExtraParamNameRuPassportData                = "RU_PASSPORT_DATA"
	Route53domainsExtraParamNameSeIdNumber                    = "SE_ID_NUMBER"
	Route53domainsExtraParamNameSgIdNumber                    = "SG_ID_NUMBER"
	Route53domainsExtraParamNameVatNumber                     = "VAT_NUMBER"
	Route53domainsExtraParamNameUkContactType                 = "UK_CONTACT_TYPE"
	Route53domainsExtraParamNameUkCompanyNumber               = "UK_COMPANY_NUMBER"
	Route53domainsExtraParamNameEuCountryOfCitizenship        = "EU_COUNTRY_OF_CITIZENSHIP"
	Route53domainsExtraParamNameAuPriorityToken               = "AU_PRIORITY_TOKEN"
	Route53domainsExtraParamNameAuEligibilityType             = "AU_ELIGIBILITY_TYPE"
	Route53domainsExtraParamNameAuPolicyReason                = "AU_POLICY_REASON"
	Route53domainsExtraParamNameAuRegistrantName              = "AU_REGISTRANT_NAME"

	// ListDomainsAttributeName values
	Route53domainsListDomainsAttributeNameDomainname = "DomainName"
	Route53domainsListDomainsAttributeNameExpiry     = "Expiry"

	// ListOperationsSortAttributeName values
	Route53domainsListOperationsSortAttributeNameSubmitteddate = "SubmittedDate"

	// OperationStatus values
	Route53domainsOperationStatusSubmitted  = "SUBMITTED"
	Route53domainsOperationStatusInProgress = "IN_PROGRESS"
	Route53domainsOperationStatusError      = "ERROR"
	Route53domainsOperationStatusSuccessful = "SUCCESSFUL"
	Route53domainsOperationStatusFailed     = "FAILED"

	// OperationType values
	Route53domainsOperationTypeRegisterDomain            = "REGISTER_DOMAIN"
	Route53domainsOperationTypeDeleteDomain              = "DELETE_DOMAIN"
	Route53domainsOperationTypeTransferInDomain          = "TRANSFER_IN_DOMAIN"
	Route53domainsOperationTypeUpdateDomainContact       = "UPDATE_DOMAIN_CONTACT"
	Route53domainsOperationTypeUpdateNameserver          = "UPDATE_NAMESERVER"
	Route53domainsOperationTypeChangePrivacyProtection   = "CHANGE_PRIVACY_PROTECTION"
	Route53domainsOperationTypeDomainLock                = "DOMAIN_LOCK"
	Route53domainsOperationTypeEnableAutorenew           = "ENABLE_AUTORENEW"
	Route53domainsOperationTypeDisableAutorenew          = "DISABLE_AUTORENEW"
	Route53domainsOperationTypeAddDnssec                 = "ADD_DNSSEC"
	Route53domainsOperationTypeRemoveDnssec              = "REMOVE_DNSSEC"
	Route53domainsOperationTypeExpireDomain              = "EXPIRE_DOMAIN"
	Route53domainsOperationTypeTransferOutDomain         = "TRANSFER_OUT_DOMAIN"
	Route53domainsOperationTypeChangeDomainOwner         = "CHANGE_DOMAIN_OWNER"
	Route53domainsOperationTypeRenewDomain               = "RENEW_DOMAIN"
	Route53domainsOperationTypePushDomain                = "PUSH_DOMAIN"
	Route53domainsOperationTypeInternalTransferOutDomain = "INTERNAL_TRANSFER_OUT_DOMAIN"
	Route53domainsOperationTypeInternalTransferInDomain  = "INTERNAL_TRANSFER_IN_DOMAIN"
	Route53domainsOperationTypeReleaseToGandi            = "RELEASE_TO_GANDI"
	Route53domainsOperationTypeTransferOnRenew           = "TRANSFER_ON_RENEW"
	Route53domainsOperationTypeRestoreDomain             = "RESTORE_DOMAIN"

	// Operator values
	Route53domainsOperatorLe         = "LE"
	Route53domainsOperatorGe         = "GE"
	Route53domainsOperatorBeginsWith = "BEGINS_WITH"

	// ReachabilityStatus values
	Route53domainsReachabilityStatusPending = "PENDING"
	Route53domainsReachabilityStatusDone    = "DONE"
	Route53domainsReachabilityStatusExpired = "EXPIRED"

	// SortOrder values
	Route53domainsSortOrderAsc  = "ASC"
	Route53domainsSortOrderDesc = "DESC"

	// StatusFlag values
	Route53domainsStatusFlagPendingAcceptance          = "PENDING_ACCEPTANCE"
	Route53domainsStatusFlagPendingCustomerAction      = "PENDING_CUSTOMER_ACTION"
	Route53domainsStatusFlagPendingAuthorization       = "PENDING_AUTHORIZATION"
	Route53domainsStatusFlagPendingPaymentVerification = "PENDING_PAYMENT_VERIFICATION"
	Route53domainsStatusFlagPendingSupportCase         = "PENDING_SUPPORT_CASE"

	// Transferable values
	Route53domainsTransferableTransferable           = "TRANSFERABLE"
	Route53domainsTransferableUntransferable         = "UNTRANSFERABLE"
	Route53domainsTransferableDontKnow               = "DONT_KNOW"
	Route53domainsTransferableDomainInOwnAccount     = "DOMAIN_IN_OWN_ACCOUNT"
	Route53domainsTransferableDomainInAnotherAccount = "DOMAIN_IN_ANOTHER_ACCOUNT"
	Route53domainsTransferablePremiumDomain          = "PREMIUM_DOMAIN"
)

var route53domainsContactTypeValues = []string{
	"PERSON",
	"COMPANY",
	"ASSOCIATION",
	"PUBLIC_BODY",
	"RESELLER",
}

var route53domainsCountryCodeValues = []string{
	"AC",
	"AD",
	"AE",
	"AF",
	"AG",
	"AI",
	"AL",
	"AM",
	"AN",
	"AO",
	"AQ",
	"AR",
	"AS",
	"AT",
	"AU",
	"AW",
	"AX",
	"AZ",
	"BA",
	"BB",
	"BD",
	"BE",
	"BF",
	"BG",
	"BH",
	"BI",
	"BJ",
	"BL",
	"BM",
	"BN",
	"BO",
	"BQ",
	"BR",
	"BS",
	"BT",
	"BV",
	"BW",
	"BY",
	"BZ",
	"CA",
	"CC",
	"CD",
	"CF",
	"CG",
	"CH",
	"CI",
	"CK",
	"CL",
	"CM",
	"CN",
	"CO",
	"CR",
	"CU",
	"CV",
	"CW",
	"CX",
	"CY",
	"CZ",
	"DE",
	"DJ",
	"DK",
	"DM",
	"DO",
	"DZ",
	"EC",
	"EE",
	"EG",
	"EH",
	"ER",
	"ES",
	"ET",
	"FI",
	"FJ",
	"FK",
	"FM",
	"FO",
	"FR",
	"GA",
	"GB",
	"GD",
	"GE",
	"GF",
	"GG",
	"GH",
	"GI",
	"GL",
	"GM",
	"GN",
	"GP",
	"GQ",
	"GR",
	"GS",
	"GT",
	"GU",
	"GW",
	"GY",
	"HK",
	"HM",
	"HN",
	"HR",
	"HT",
	"HU",
	"ID",
	"IE",
	"IL",
	"IM",
	"IN",
	"IO",
	"IQ",
	"IR",
	"IS",
	"IT",
	"JE",
	"JM",
	"JO",
	"JP",
	"KE",
	"KG",
	"KH",
	"KI",
	"KM",
	"KN",
	"KP",
	"KR",
	"KW",
	"KY",
	"KZ",
	"LA",
	"LB",
	"LC",
	"LI",
	"LK",
	"LR",
	"LS",
	"LT",
	"LU",
	"LV",
	"LY",
	"MA",
	"MC",
	"MD",
	"ME",
	"MF",
	"MG",
	"MH",
	"MK",
	"ML",
	"MM",
	"MN",
	"MO",
	"MP",
	"MQ",
	"MR",
	"MS",
	"MT",
	"MU",
	"MV",
	"MW",
	"MX",
	"MY",
	"MZ",
	"NA",
	"NC",
	"NE",
	"NF",
	"NG",
	"NI",
	"NL",
	"NO",
	"NP",
	"NR",
	"NU",
	"NZ",
	"OM",
	"PA",
	"PE",
	"PF",
	"PG",
	"PH",
	"PK",
	"PL",
	"PM",
	"PN",
	"PR",
	"PS",
	"PT",
	"PW",
	"PY",
	"QA",
	"RE",
	"RO",
	"RS",
	"RU",
	"RW",
	"SA",
	"SB",
	"SC",
	"SD",
	"SE",
	"SG",
	"SH",
	"SI",
	"SJ",
	"SK",
	"SL",
	"SM",
	"SN",
	"SO",
	"SR",
	"SS",
	"ST",
	"SV",
	"SX",
	"SY",
	"SZ",
	"TC",
	"TD",
	"TF",
	"TG",
	"TH",
	"TJ",
	"TK",
	"TL",
	"TM",
	"TN",
	"TO",
	"TP",
	"TR",
	"TT",
	"TV",
	"TW",
	"TZ",
	"UA",
	"UG",
	"US",
	"UY",
	"UZ",
	"VA",
	"VC",
	"VE",
	"VG",
	"VI",
	"VN",
	"VU",
	"WF",
	"WS",
	"YE",
	"YT",
	"ZA",
	"ZM",
	"ZW",
}

var route53domainsDomainAvailabilityValues = []string{
	"AVAILABLE",
	"AVAILABLE_RESERVED",
	"AVAILABLE_PREORDER",
	"UNAVAILABLE",
	"UNAVAILABLE_PREMIUM",
	"UNAVAILABLE_RESTRICTED",
	"RESERVED",
	"DONT_KNOW",
	"INVALID_NAME_FOR_TLD",
	"PENDING",
}

var route53domainsExtraParamNameValues = []string{
	"DUNS_NUMBER",
	"BRAND_NUMBER",
	"BIRTH_DEPARTMENT",
	"BIRTH_DATE_IN_YYYY_MM_DD",
	"BIRTH_COUNTRY",
	"BIRTH_CITY",
	"DOCUMENT_NUMBER",
	"AU_ID_NUMBER",
	"AU_ID_TYPE",
	"CA_LEGAL_TYPE",
	"CA_BUSINESS_ENTITY_TYPE",
	"CA_LEGAL_REPRESENTATIVE",
	"CA_LEGAL_REPRESENTATIVE_CAPACITY",
	"ES_IDENTIFICATION",
	"ES_IDENTIFICATION_TYPE",
	"ES_LEGAL_FORM",
	"FI_BUSINESS_NUMBER",
	"FI_ID_NUMBER",
	"FI_NATIONALITY",
	"FI_ORGANIZATION_TYPE",
	"IT_NATIONALITY",
	"IT_PIN",
	"IT_REGISTRANT_ENTITY_TYPE",
	"RU_PASSPORT_DATA",
	"SE_ID_NUMBER",
	"SG_ID_NUMBER",
	"VAT_NUMBER",
	"UK_CONTACT_TYPE",
	"UK_COMPANY_NUMBER",
	"EU_COUNTRY_OF_CITIZENSHIP",
	"AU_PRIORITY_TOKEN",
	"AU_ELIGIBILITY_TYPE",
	"AU_POLICY_REASON",
	"AU_REGISTRANT_NAME",
}

var route53domainsListDomainsAttributeNameValues = []string{
	"DomainName",
	"Expiry",
}

var route53domainsListOperationsSortAttributeNameValues = []string{
	"SubmittedDate",
}

var route53domainsOperationStatusValues = []string{
	"SUBMITTED",
	"IN_PROGRESS",
	"ERROR",
	"SUCCESSFUL",
	"FAILED",
}

var route53domainsOperationTypeValues = []string{
	"REGISTER_DOMAIN",
	"DELETE_DOMAIN",
	"TRANSFER_IN_DOMAIN",
	"UPDATE_DOMAIN_CONTACT",
	"UPDATE_NAMESERVER",
	"CHANGE_PRIVACY_PROTECTION",
	"DOMAIN_LOCK",
	"ENABLE_AUTORENEW",
	"DISABLE_AUTORENEW",
	"ADD_DNSSEC",
	"REMOVE_DNSSEC",
	"EXPIRE_DOMAIN",
	"TRANSFER_OUT_DOMAIN",
	"CHANGE_DOMAIN_OWNER",
	"RENEW_DOMAIN",
	"PUSH_DOMAIN",
	"INTERNAL_TRANSFER_OUT_DOMAIN",
	"INTERNAL_TRANSFER_IN_DOMAIN",
	"RELEASE_TO_GANDI",
	"TRANSFER_ON_RENEW",
	"RESTORE_DOMAIN",
}

var route53domainsOperatorValues = []string{
	"LE",
	"GE",
	"BEGINS_WITH",
}

var route53domainsReachabilityStatusValues = []string{
	"PENDING",
	"DONE",
	"EXPIRED",
}

var route53domainsSortOrderValues = []string{
	"ASC",
	"DESC",
}

var route53domainsStatusFlagValues = []string{
	"PENDING_ACCEPTANCE",
	"PENDING_CUSTOMER_ACTION",
	"PENDING_AUTHORIZATION",
	"PENDING_PAYMENT_VERIFICATION",
	"PENDING_SUPPORT_CASE",
}

var route53domainsTransferableValues = []string{
	"TRANSFERABLE",
	"UNTRANSFERABLE",
	"DONT_KNOW",
	"DOMAIN_IN_OWN_ACCOUNT",
	"DOMAIN_IN_ANOTHER_ACCOUNT",
	"PREMIUM_DOMAIN",
}

func getRoute53domainsEnum(name string) []string {
	switch name {
	case "ContactType":
		return route53domainsContactTypeValues
	case "CountryCode":
		return route53domainsCountryCodeValues
	case "DomainAvailability":
		return route53domainsDomainAvailabilityValues
	case "ExtraParamName":
		return route53domainsExtraParamNameValues
	case "ListDomainsAttributeName":
		return route53domainsListDomainsAttributeNameValues
	case "ListOperationsSortAttributeName":
		return route53domainsListOperationsSortAttributeNameValues
	case "OperationStatus":
		return route53domainsOperationStatusValues
	case "OperationType":
		return route53domainsOperationTypeValues
	case "Operator":
		return route53domainsOperatorValues
	case "ReachabilityStatus":
		return route53domainsReachabilityStatusValues
	case "SortOrder":
		return route53domainsSortOrderValues
	case "StatusFlag":
		return route53domainsStatusFlagValues
	case "Transferable":
		return route53domainsTransferableValues
	}
	return nil
}

func getRoute53domainsEnumNames() []string {
	return []string{
		"ContactType",
		"CountryCode",
		"DomainAvailability",
		"ExtraParamName",
		"ListDomainsAttributeName",
		"ListOperationsSortAttributeName",
		"OperationStatus",
		"OperationType",
		"Operator",
		"ReachabilityStatus",
		"SortOrder",
		"StatusFlag",
		"Transferable",
	}
}
