// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Synthetics enum constants
const (
	// BrowserType values
	SyntheticsBrowserTypeChrome  = "CHROME"
	SyntheticsBrowserTypeFirefox = "FIREFOX"

	// CanaryRunState values
	SyntheticsCanaryRunStateRunning = "RUNNING"
	SyntheticsCanaryRunStatePassed  = "PASSED"
	SyntheticsCanaryRunStateFailed  = "FAILED"

	// CanaryRunStateReasonCode values
	SyntheticsCanaryRunStateReasonCodeCanaryFailure    = "CANARY_FAILURE"
	SyntheticsCanaryRunStateReasonCodeExecutionFailure = "EXECUTION_FAILURE"

	// CanaryRunTestResult values
	SyntheticsCanaryRunTestResultPassed  = "PASSED"
	SyntheticsCanaryRunTestResultFailed  = "FAILED"
	SyntheticsCanaryRunTestResultUnknown = "UNKNOWN"

	// CanaryState values
	SyntheticsCanaryStateCreating = "CREATING"
	SyntheticsCanaryStateReady    = "READY"
	SyntheticsCanaryStateStarting = "STARTING"
	SyntheticsCanaryStateRunning  = "RUNNING"
	SyntheticsCanaryStateUpdating = "UPDATING"
	SyntheticsCanaryStateStopping = "STOPPING"
	SyntheticsCanaryStateStopped  = "STOPPED"
	SyntheticsCanaryStateError    = "ERROR"
	SyntheticsCanaryStateDeleting = "DELETING"

	// CanaryStateReasonCode values
	SyntheticsCanaryStateReasonCodeInvalidPermissions   = "INVALID_PERMISSIONS"
	SyntheticsCanaryStateReasonCodeCreatePending        = "CREATE_PENDING"
	SyntheticsCanaryStateReasonCodeCreateInProgress     = "CREATE_IN_PROGRESS"
	SyntheticsCanaryStateReasonCodeCreateFailed         = "CREATE_FAILED"
	SyntheticsCanaryStateReasonCodeUpdatePending        = "UPDATE_PENDING"
	SyntheticsCanaryStateReasonCodeUpdateInProgress     = "UPDATE_IN_PROGRESS"
	SyntheticsCanaryStateReasonCodeUpdateComplete       = "UPDATE_COMPLETE"
	SyntheticsCanaryStateReasonCodeRollbackComplete     = "ROLLBACK_COMPLETE"
	SyntheticsCanaryStateReasonCodeRollbackFailed       = "ROLLBACK_FAILED"
	SyntheticsCanaryStateReasonCodeDeleteInProgress     = "DELETE_IN_PROGRESS"
	SyntheticsCanaryStateReasonCodeDeleteFailed         = "DELETE_FAILED"
	SyntheticsCanaryStateReasonCodeSyncDeleteInProgress = "SYNC_DELETE_IN_PROGRESS"

	// DependencyType values
	SyntheticsDependencyTypeLambdalayer = "LambdaLayer"

	// EncryptionMode values
	SyntheticsEncryptionModeSseS3  = "SSE_S3"
	SyntheticsEncryptionModeSseKms = "SSE_KMS"

	// ProvisionedResourceCleanupSetting values
	SyntheticsProvisionedResourceCleanupSettingAutomatic = "AUTOMATIC"
	SyntheticsProvisionedResourceCleanupSettingOff       = "OFF"

	// ResourceToTag values
	SyntheticsResourceToTagLambdaFunction = "lambda-function"

	// RunType values
	SyntheticsRunTypeCanaryRun = "CANARY_RUN"
	SyntheticsRunTypeDryRun    = "DRY_RUN"
)

var syntheticsBrowserTypeValues = []string{
	"CHROME",
	"FIREFOX",
}

var syntheticsCanaryRunStateValues = []string{
	"RUNNING",
	"PASSED",
	"FAILED",
}

var syntheticsCanaryRunStateReasonCodeValues = []string{
	"CANARY_FAILURE",
	"EXECUTION_FAILURE",
}

var syntheticsCanaryRunTestResultValues = []string{
	"PASSED",
	"FAILED",
	"UNKNOWN",
}

var syntheticsCanaryStateValues = []string{
	"CREATING",
	"READY",
	"STARTING",
	"RUNNING",
	"UPDATING",
	"STOPPING",
	"STOPPED",
	"ERROR",
	"DELETING",
}

var syntheticsCanaryStateReasonCodeValues = []string{
	"INVALID_PERMISSIONS",
	"CREATE_PENDING",
	"CREATE_IN_PROGRESS",
	"CREATE_FAILED",
	"UPDATE_PENDING",
	"UPDATE_IN_PROGRESS",
	"UPDATE_COMPLETE",
	"ROLLBACK_COMPLETE",
	"ROLLBACK_FAILED",
	"DELETE_IN_PROGRESS",
	"DELETE_FAILED",
	"SYNC_DELETE_IN_PROGRESS",
}

var syntheticsDependencyTypeValues = []string{
	"LambdaLayer",
}

var syntheticsEncryptionModeValues = []string{
	"SSE_S3",
	"SSE_KMS",
}

var syntheticsProvisionedResourceCleanupSettingValues = []string{
	"AUTOMATIC",
	"OFF",
}

var syntheticsResourceToTagValues = []string{
	"lambda-function",
}

var syntheticsRunTypeValues = []string{
	"CANARY_RUN",
	"DRY_RUN",
}

func getSyntheticsEnum(name string) []string {
	switch name {
	case "BrowserType":
		return syntheticsBrowserTypeValues
	case "CanaryRunState":
		return syntheticsCanaryRunStateValues
	case "CanaryRunStateReasonCode":
		return syntheticsCanaryRunStateReasonCodeValues
	case "CanaryRunTestResult":
		return syntheticsCanaryRunTestResultValues
	case "CanaryState":
		return syntheticsCanaryStateValues
	case "CanaryStateReasonCode":
		return syntheticsCanaryStateReasonCodeValues
	case "DependencyType":
		return syntheticsDependencyTypeValues
	case "EncryptionMode":
		return syntheticsEncryptionModeValues
	case "ProvisionedResourceCleanupSetting":
		return syntheticsProvisionedResourceCleanupSettingValues
	case "ResourceToTag":
		return syntheticsResourceToTagValues
	case "RunType":
		return syntheticsRunTypeValues
	}
	return nil
}

func getSyntheticsEnumNames() []string {
	return []string{
		"BrowserType",
		"CanaryRunState",
		"CanaryRunStateReasonCode",
		"CanaryRunTestResult",
		"CanaryState",
		"CanaryStateReasonCode",
		"DependencyType",
		"EncryptionMode",
		"ProvisionedResourceCleanupSetting",
		"ResourceToTag",
		"RunType",
	}
}
