// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// WafRegional enum constants
const (
	// ChangeAction values
	WafregionalChangeActionInsert = "INSERT"
	WafregionalChangeActionDelete = "DELETE"

	// ChangeTokenStatus values
	WafregionalChangeTokenStatusProvisioned = "PROVISIONED"
	WafregionalChangeTokenStatusPending     = "PENDING"
	WafregionalChangeTokenStatusInsync      = "INSYNC"

	// ComparisonOperator values
	WafregionalComparisonOperatorEq = "EQ"
	WafregionalComparisonOperatorNe = "NE"
	WafregionalComparisonOperatorLe = "LE"
	WafregionalComparisonOperatorLt = "LT"
	WafregionalComparisonOperatorGe = "GE"
	WafregionalComparisonOperatorGt = "GT"

	// GeoMatchConstraintType values
	WafregionalGeoMatchConstraintTypeCountry = "Country"

	// GeoMatchConstraintValue values
	WafregionalGeoMatchConstraintValueAf = "AF"
	WafregionalGeoMatchConstraintValueAx = "AX"
	WafregionalGeoMatchConstraintValueAl = "AL"
	WafregionalGeoMatchConstraintValueDz = "DZ"
	WafregionalGeoMatchConstraintValueAs = "AS"
	WafregionalGeoMatchConstraintValueAd = "AD"
	WafregionalGeoMatchConstraintValueAo = "AO"
	WafregionalGeoMatchConstraintValueAi = "AI"
	WafregionalGeoMatchConstraintValueAq = "AQ"
	WafregionalGeoMatchConstraintValueAg = "AG"
	WafregionalGeoMatchConstraintValueAr = "AR"
	WafregionalGeoMatchConstraintValueAm = "AM"
	WafregionalGeoMatchConstraintValueAw = "AW"
	WafregionalGeoMatchConstraintValueAu = "AU"
	WafregionalGeoMatchConstraintValueAt = "AT"
	WafregionalGeoMatchConstraintValueAz = "AZ"
	WafregionalGeoMatchConstraintValueBs = "BS"
	WafregionalGeoMatchConstraintValueBh = "BH"
	WafregionalGeoMatchConstraintValueBd = "BD"
	WafregionalGeoMatchConstraintValueBb = "BB"
	WafregionalGeoMatchConstraintValueBy = "BY"
	WafregionalGeoMatchConstraintValueBe = "BE"
	WafregionalGeoMatchConstraintValueBz = "BZ"
	WafregionalGeoMatchConstraintValueBj = "BJ"
	WafregionalGeoMatchConstraintValueBm = "BM"
	WafregionalGeoMatchConstraintValueBt = "BT"
	WafregionalGeoMatchConstraintValueBo = "BO"
	WafregionalGeoMatchConstraintValueBq = "BQ"
	WafregionalGeoMatchConstraintValueBa = "BA"
	WafregionalGeoMatchConstraintValueBw = "BW"
	WafregionalGeoMatchConstraintValueBv = "BV"
	WafregionalGeoMatchConstraintValueBr = "BR"
	WafregionalGeoMatchConstraintValueIo = "IO"
	WafregionalGeoMatchConstraintValueBn = "BN"
	WafregionalGeoMatchConstraintValueBg = "BG"
	WafregionalGeoMatchConstraintValueBf = "BF"
	WafregionalGeoMatchConstraintValueBi = "BI"
	WafregionalGeoMatchConstraintValueKh = "KH"
	WafregionalGeoMatchConstraintValueCm = "CM"
	WafregionalGeoMatchConstraintValueCa = "CA"
	WafregionalGeoMatchConstraintValueCv = "CV"
	WafregionalGeoMatchConstraintValueKy = "KY"
	WafregionalGeoMatchConstraintValueCf = "CF"
	WafregionalGeoMatchConstraintValueTd = "TD"
	WafregionalGeoMatchConstraintValueCl = "CL"
	WafregionalGeoMatchConstraintValueCn = "CN"
	WafregionalGeoMatchConstraintValueCx = "CX"
	WafregionalGeoMatchConstraintValueCc = "CC"
	WafregionalGeoMatchConstraintValueCo = "CO"
	WafregionalGeoMatchConstraintValueKm = "KM"
	WafregionalGeoMatchConstraintValueCg = "CG"
	WafregionalGeoMatchConstraintValueCd = "CD"
	WafregionalGeoMatchConstraintValueCk = "CK"
	WafregionalGeoMatchConstraintValueCr = "CR"
	WafregionalGeoMatchConstraintValueCi = "CI"
	WafregionalGeoMatchConstraintValueHr = "HR"
	WafregionalGeoMatchConstraintValueCu = "CU"
	WafregionalGeoMatchConstraintValueCw = "CW"
	WafregionalGeoMatchConstraintValueCy = "CY"
	WafregionalGeoMatchConstraintValueCz = "CZ"
	WafregionalGeoMatchConstraintValueDk = "DK"
	WafregionalGeoMatchConstraintValueDj = "DJ"
	WafregionalGeoMatchConstraintValueDm = "DM"
	WafregionalGeoMatchConstraintValueDo = "DO"
	WafregionalGeoMatchConstraintValueEc = "EC"
	WafregionalGeoMatchConstraintValueEg = "EG"
	WafregionalGeoMatchConstraintValueSv = "SV"
	WafregionalGeoMatchConstraintValueGq = "GQ"
	WafregionalGeoMatchConstraintValueEr = "ER"
	WafregionalGeoMatchConstraintValueEe = "EE"
	WafregionalGeoMatchConstraintValueEt = "ET"
	WafregionalGeoMatchConstraintValueFk = "FK"
	WafregionalGeoMatchConstraintValueFo = "FO"
	WafregionalGeoMatchConstraintValueFj = "FJ"
	WafregionalGeoMatchConstraintValueFi = "FI"
	WafregionalGeoMatchConstraintValueFr = "FR"
	WafregionalGeoMatchConstraintValueGf = "GF"
	WafregionalGeoMatchConstraintValuePf = "PF"
	WafregionalGeoMatchConstraintValueTf = "TF"
	WafregionalGeoMatchConstraintValueGa = "GA"
	WafregionalGeoMatchConstraintValueGm = "GM"
	WafregionalGeoMatchConstraintValueGe = "GE"
	WafregionalGeoMatchConstraintValueDe = "DE"
	WafregionalGeoMatchConstraintValueGh = "GH"
	WafregionalGeoMatchConstraintValueGi = "GI"
	WafregionalGeoMatchConstraintValueGr = "GR"
	WafregionalGeoMatchConstraintValueGl = "GL"
	WafregionalGeoMatchConstraintValueGd = "GD"
	WafregionalGeoMatchConstraintValueGp = "GP"
	WafregionalGeoMatchConstraintValueGu = "GU"
	WafregionalGeoMatchConstraintValueGt = "GT"
	WafregionalGeoMatchConstraintValueGg = "GG"
	WafregionalGeoMatchConstraintValueGn = "GN"
	WafregionalGeoMatchConstraintValueGw = "GW"
	WafregionalGeoMatchConstraintValueGy = "GY"
	WafregionalGeoMatchConstraintValueHt = "HT"
	WafregionalGeoMatchConstraintValueHm = "HM"
	WafregionalGeoMatchConstraintValueVa = "VA"
	WafregionalGeoMatchConstraintValueHn = "HN"
	WafregionalGeoMatchConstraintValueHk = "HK"
	WafregionalGeoMatchConstraintValueHu = "HU"
	WafregionalGeoMatchConstraintValueIs = "IS"
	WafregionalGeoMatchConstraintValueIn = "IN"
	WafregionalGeoMatchConstraintValueId = "ID"
	WafregionalGeoMatchConstraintValueIr = "IR"
	WafregionalGeoMatchConstraintValueIq = "IQ"
	WafregionalGeoMatchConstraintValueIe = "IE"
	WafregionalGeoMatchConstraintValueIm = "IM"
	WafregionalGeoMatchConstraintValueIl = "IL"
	WafregionalGeoMatchConstraintValueIt = "IT"
	WafregionalGeoMatchConstraintValueJm = "JM"
	WafregionalGeoMatchConstraintValueJp = "JP"
	WafregionalGeoMatchConstraintValueJe = "JE"
	WafregionalGeoMatchConstraintValueJo = "JO"
	WafregionalGeoMatchConstraintValueKz = "KZ"
	WafregionalGeoMatchConstraintValueKe = "KE"
	WafregionalGeoMatchConstraintValueKi = "KI"
	WafregionalGeoMatchConstraintValueKp = "KP"
	WafregionalGeoMatchConstraintValueKr = "KR"
	WafregionalGeoMatchConstraintValueKw = "KW"
	WafregionalGeoMatchConstraintValueKg = "KG"
	WafregionalGeoMatchConstraintValueLa = "LA"
	WafregionalGeoMatchConstraintValueLv = "LV"
	WafregionalGeoMatchConstraintValueLb = "LB"
	WafregionalGeoMatchConstraintValueLs = "LS"
	WafregionalGeoMatchConstraintValueLr = "LR"
	WafregionalGeoMatchConstraintValueLy = "LY"
	WafregionalGeoMatchConstraintValueLi = "LI"
	WafregionalGeoMatchConstraintValueLt = "LT"
	WafregionalGeoMatchConstraintValueLu = "LU"
	WafregionalGeoMatchConstraintValueMo = "MO"
	WafregionalGeoMatchConstraintValueMk = "MK"
	WafregionalGeoMatchConstraintValueMg = "MG"
	WafregionalGeoMatchConstraintValueMw = "MW"
	WafregionalGeoMatchConstraintValueMy = "MY"
	WafregionalGeoMatchConstraintValueMv = "MV"
	WafregionalGeoMatchConstraintValueMl = "ML"
	WafregionalGeoMatchConstraintValueMt = "MT"
	WafregionalGeoMatchConstraintValueMh = "MH"
	WafregionalGeoMatchConstraintValueMq = "MQ"
	WafregionalGeoMatchConstraintValueMr = "MR"
	WafregionalGeoMatchConstraintValueMu = "MU"
	WafregionalGeoMatchConstraintValueYt = "YT"
	WafregionalGeoMatchConstraintValueMx = "MX"
	WafregionalGeoMatchConstraintValueFm = "FM"
	WafregionalGeoMatchConstraintValueMd = "MD"
	WafregionalGeoMatchConstraintValueMc = "MC"
	WafregionalGeoMatchConstraintValueMn = "MN"
	WafregionalGeoMatchConstraintValueMe = "ME"
	WafregionalGeoMatchConstraintValueMs = "MS"
	WafregionalGeoMatchConstraintValueMa = "MA"
	WafregionalGeoMatchConstraintValueMz = "MZ"
	WafregionalGeoMatchConstraintValueMm = "MM"
	WafregionalGeoMatchConstraintValueNa = "NA"
	WafregionalGeoMatchConstraintValueNr = "NR"
	WafregionalGeoMatchConstraintValueNp = "NP"
	WafregionalGeoMatchConstraintValueNl = "NL"
	WafregionalGeoMatchConstraintValueNc = "NC"
	WafregionalGeoMatchConstraintValueNz = "NZ"
	WafregionalGeoMatchConstraintValueNi = "NI"
	WafregionalGeoMatchConstraintValueNe = "NE"
	WafregionalGeoMatchConstraintValueNg = "NG"
	WafregionalGeoMatchConstraintValueNu = "NU"
	WafregionalGeoMatchConstraintValueNf = "NF"
	WafregionalGeoMatchConstraintValueMp = "MP"
	WafregionalGeoMatchConstraintValueNo = "NO"
	WafregionalGeoMatchConstraintValueOm = "OM"
	WafregionalGeoMatchConstraintValuePk = "PK"
	WafregionalGeoMatchConstraintValuePw = "PW"
	WafregionalGeoMatchConstraintValuePs = "PS"
	WafregionalGeoMatchConstraintValuePa = "PA"
	WafregionalGeoMatchConstraintValuePg = "PG"
	WafregionalGeoMatchConstraintValuePy = "PY"
	WafregionalGeoMatchConstraintValuePe = "PE"
	WafregionalGeoMatchConstraintValuePh = "PH"
	WafregionalGeoMatchConstraintValuePn = "PN"
	WafregionalGeoMatchConstraintValuePl = "PL"
	WafregionalGeoMatchConstraintValuePt = "PT"
	WafregionalGeoMatchConstraintValuePr = "PR"
	WafregionalGeoMatchConstraintValueQa = "QA"
	WafregionalGeoMatchConstraintValueRe = "RE"
	WafregionalGeoMatchConstraintValueRo = "RO"
	WafregionalGeoMatchConstraintValueRu = "RU"
	WafregionalGeoMatchConstraintValueRw = "RW"
	WafregionalGeoMatchConstraintValueBl = "BL"
	WafregionalGeoMatchConstraintValueSh = "SH"
	WafregionalGeoMatchConstraintValueKn = "KN"
	WafregionalGeoMatchConstraintValueLc = "LC"
	WafregionalGeoMatchConstraintValueMf = "MF"
	WafregionalGeoMatchConstraintValuePm = "PM"
	WafregionalGeoMatchConstraintValueVc = "VC"
	WafregionalGeoMatchConstraintValueWs = "WS"
	WafregionalGeoMatchConstraintValueSm = "SM"
	WafregionalGeoMatchConstraintValueSt = "ST"
	WafregionalGeoMatchConstraintValueSa = "SA"
	WafregionalGeoMatchConstraintValueSn = "SN"
	WafregionalGeoMatchConstraintValueRs = "RS"
	WafregionalGeoMatchConstraintValueSc = "SC"
	WafregionalGeoMatchConstraintValueSl = "SL"
	WafregionalGeoMatchConstraintValueSg = "SG"
	WafregionalGeoMatchConstraintValueSx = "SX"
	WafregionalGeoMatchConstraintValueSk = "SK"
	WafregionalGeoMatchConstraintValueSi = "SI"
	WafregionalGeoMatchConstraintValueSb = "SB"
	WafregionalGeoMatchConstraintValueSo = "SO"
	WafregionalGeoMatchConstraintValueZa = "ZA"
	WafregionalGeoMatchConstraintValueGs = "GS"
	WafregionalGeoMatchConstraintValueSs = "SS"
	WafregionalGeoMatchConstraintValueEs = "ES"
	WafregionalGeoMatchConstraintValueLk = "LK"
	WafregionalGeoMatchConstraintValueSd = "SD"
	WafregionalGeoMatchConstraintValueSr = "SR"
	WafregionalGeoMatchConstraintValueSj = "SJ"
	WafregionalGeoMatchConstraintValueSz = "SZ"
	WafregionalGeoMatchConstraintValueSe = "SE"
	WafregionalGeoMatchConstraintValueCh = "CH"
	WafregionalGeoMatchConstraintValueSy = "SY"
	WafregionalGeoMatchConstraintValueTw = "TW"
	WafregionalGeoMatchConstraintValueTj = "TJ"
	WafregionalGeoMatchConstraintValueTz = "TZ"
	WafregionalGeoMatchConstraintValueTh = "TH"
	WafregionalGeoMatchConstraintValueTl = "TL"
	WafregionalGeoMatchConstraintValueTg = "TG"
	WafregionalGeoMatchConstraintValueTk = "TK"
	WafregionalGeoMatchConstraintValueTo = "TO"
	WafregionalGeoMatchConstraintValueTt = "TT"
	WafregionalGeoMatchConstraintValueTn = "TN"
	WafregionalGeoMatchConstraintValueTr = "TR"
	WafregionalGeoMatchConstraintValueTm = "TM"
	WafregionalGeoMatchConstraintValueTc = "TC"
	WafregionalGeoMatchConstraintValueTv = "TV"
	WafregionalGeoMatchConstraintValueUg = "UG"
	WafregionalGeoMatchConstraintValueUa = "UA"
	WafregionalGeoMatchConstraintValueAe = "AE"
	WafregionalGeoMatchConstraintValueGb = "GB"
	WafregionalGeoMatchConstraintValueUs = "US"
	WafregionalGeoMatchConstraintValueUm = "UM"
	WafregionalGeoMatchConstraintValueUy = "UY"
	WafregionalGeoMatchConstraintValueUz = "UZ"
	WafregionalGeoMatchConstraintValueVu = "VU"
	WafregionalGeoMatchConstraintValueVe = "VE"
	WafregionalGeoMatchConstraintValueVn = "VN"
	WafregionalGeoMatchConstraintValueVg = "VG"
	WafregionalGeoMatchConstraintValueVi = "VI"
	WafregionalGeoMatchConstraintValueWf = "WF"
	WafregionalGeoMatchConstraintValueEh = "EH"
	WafregionalGeoMatchConstraintValueYe = "YE"
	WafregionalGeoMatchConstraintValueZm = "ZM"
	WafregionalGeoMatchConstraintValueZw = "ZW"

	// IPSetDescriptorType values
	WafregionalIPSetDescriptorTypeIpv4 = "IPV4"
	WafregionalIPSetDescriptorTypeIpv6 = "IPV6"

	// MatchFieldType values
	WafregionalMatchFieldTypeUri            = "URI"
	WafregionalMatchFieldTypeQueryString    = "QUERY_STRING"
	WafregionalMatchFieldTypeHeader         = "HEADER"
	WafregionalMatchFieldTypeMethod         = "METHOD"
	WafregionalMatchFieldTypeBody           = "BODY"
	WafregionalMatchFieldTypeSingleQueryArg = "SINGLE_QUERY_ARG"
	WafregionalMatchFieldTypeAllQueryArgs   = "ALL_QUERY_ARGS"

	// MigrationErrorType values
	WafregionalMigrationErrorTypeEntityNotSupported    = "ENTITY_NOT_SUPPORTED"
	WafregionalMigrationErrorTypeEntityNotFound        = "ENTITY_NOT_FOUND"
	WafregionalMigrationErrorTypeS3BucketNoPermission  = "S3_BUCKET_NO_PERMISSION"
	WafregionalMigrationErrorTypeS3BucketNotAccessible = "S3_BUCKET_NOT_ACCESSIBLE"
	WafregionalMigrationErrorTypeS3BucketNotFound      = "S3_BUCKET_NOT_FOUND"
	WafregionalMigrationErrorTypeS3BucketInvalidRegion = "S3_BUCKET_INVALID_REGION"
	WafregionalMigrationErrorTypeS3InternalError       = "S3_INTERNAL_ERROR"

	// ParameterExceptionField values
	WafregionalParameterExceptionFieldChangeAction                     = "CHANGE_ACTION"
	WafregionalParameterExceptionFieldWafAction                        = "WAF_ACTION"
	WafregionalParameterExceptionFieldWafOverrideAction                = "WAF_OVERRIDE_ACTION"
	WafregionalParameterExceptionFieldPredicateType                    = "PREDICATE_TYPE"
	WafregionalParameterExceptionFieldIpsetType                        = "IPSET_TYPE"
	WafregionalParameterExceptionFieldByteMatchFieldType               = "BYTE_MATCH_FIELD_TYPE"
	WafregionalParameterExceptionFieldSqlInjectionMatchFieldType       = "SQL_INJECTION_MATCH_FIELD_TYPE"
	WafregionalParameterExceptionFieldByteMatchTextTransformation      = "BYTE_MATCH_TEXT_TRANSFORMATION"
	WafregionalParameterExceptionFieldByteMatchPositionalConstraint    = "BYTE_MATCH_POSITIONAL_CONSTRAINT"
	WafregionalParameterExceptionFieldSizeConstraintComparisonOperator = "SIZE_CONSTRAINT_COMPARISON_OPERATOR"
	WafregionalParameterExceptionFieldGeoMatchLocationType             = "GEO_MATCH_LOCATION_TYPE"
	WafregionalParameterExceptionFieldGeoMatchLocationValue            = "GEO_MATCH_LOCATION_VALUE"
	WafregionalParameterExceptionFieldRateKey                          = "RATE_KEY"
	WafregionalParameterExceptionFieldRuleType                         = "RULE_TYPE"
	WafregionalParameterExceptionFieldNextMarker                       = "NEXT_MARKER"
	WafregionalParameterExceptionFieldResourceArn                      = "RESOURCE_ARN"
	WafregionalParameterExceptionFieldTags                             = "TAGS"
	WafregionalParameterExceptionFieldTagKeys                          = "TAG_KEYS"

	// ParameterExceptionReason values
	WafregionalParameterExceptionReasonInvalidOption      = "INVALID_OPTION"
	WafregionalParameterExceptionReasonIllegalCombination = "ILLEGAL_COMBINATION"
	WafregionalParameterExceptionReasonIllegalArgument    = "ILLEGAL_ARGUMENT"
	WafregionalParameterExceptionReasonInvalidTagKey      = "INVALID_TAG_KEY"

	// PositionalConstraint values
	WafregionalPositionalConstraintExactly      = "EXACTLY"
	WafregionalPositionalConstraintStartsWith   = "STARTS_WITH"
	WafregionalPositionalConstraintEndsWith     = "ENDS_WITH"
	WafregionalPositionalConstraintContains     = "CONTAINS"
	WafregionalPositionalConstraintContainsWord = "CONTAINS_WORD"

	// PredicateType values
	WafregionalPredicateTypeIpmatch           = "IPMatch"
	WafregionalPredicateTypeBytematch         = "ByteMatch"
	WafregionalPredicateTypeSqlinjectionmatch = "SqlInjectionMatch"
	WafregionalPredicateTypeGeomatch          = "GeoMatch"
	WafregionalPredicateTypeSizeconstraint    = "SizeConstraint"
	WafregionalPredicateTypeXssmatch          = "XssMatch"
	WafregionalPredicateTypeRegexmatch        = "RegexMatch"

	// RateKey values
	WafregionalRateKeyIp = "IP"

	// ResourceType values
	WafregionalResourceTypeApplicationLoadBalancer = "APPLICATION_LOAD_BALANCER"
	WafregionalResourceTypeApiGateway              = "API_GATEWAY"

	// TextTransformation values
	WafregionalTextTransformationNone               = "NONE"
	WafregionalTextTransformationCompressWhiteSpace = "COMPRESS_WHITE_SPACE"
	WafregionalTextTransformationHtmlEntityDecode   = "HTML_ENTITY_DECODE"
	WafregionalTextTransformationLowercase          = "LOWERCASE"
	WafregionalTextTransformationCmdLine            = "CMD_LINE"
	WafregionalTextTransformationUrlDecode          = "URL_DECODE"

	// WafActionType values
	WafregionalWafActionTypeBlock = "BLOCK"
	WafregionalWafActionTypeAllow = "ALLOW"
	WafregionalWafActionTypeCount = "COUNT"

	// WafOverrideActionType values
	WafregionalWafOverrideActionTypeNone  = "NONE"
	WafregionalWafOverrideActionTypeCount = "COUNT"

	// WafRuleType values
	WafregionalWafRuleTypeRegular   = "REGULAR"
	WafregionalWafRuleTypeRateBased = "RATE_BASED"
	WafregionalWafRuleTypeGroup     = "GROUP"
)

var wafregionalChangeActionValues = []string{
	"INSERT",
	"DELETE",
}

var wafregionalChangeTokenStatusValues = []string{
	"PROVISIONED",
	"PENDING",
	"INSYNC",
}

var wafregionalComparisonOperatorValues = []string{
	"EQ",
	"NE",
	"LE",
	"LT",
	"GE",
	"GT",
}

var wafregionalGeoMatchConstraintTypeValues = []string{
	"Country",
}

var wafregionalGeoMatchConstraintValueValues = []string{
	"AF",
	"AX",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BQ",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"KH",
	"CM",
	"CA",
	"CV",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CG",
	"CD",
	"CK",
	"CR",
	"CI",
	"HR",
	"CU",
	"CW",
	"CY",
	"CZ",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KP",
	"KR",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MK",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"MP",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RE",
	"RO",
	"RU",
	"RW",
	"BL",
	"SH",
	"KN",
	"LC",
	"MF",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SX",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"SS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SZ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TR",
	"TM",
	"TC",
	"TV",
	"UG",
	"UA",
	"AE",
	"GB",
	"US",
	"UM",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"ZM",
	"ZW",
}

var wafregionalIPSetDescriptorTypeValues = []string{
	"IPV4",
	"IPV6",
}

var wafregionalMatchFieldTypeValues = []string{
	"URI",
	"QUERY_STRING",
	"HEADER",
	"METHOD",
	"BODY",
	"SINGLE_QUERY_ARG",
	"ALL_QUERY_ARGS",
}

var wafregionalMigrationErrorTypeValues = []string{
	"ENTITY_NOT_SUPPORTED",
	"ENTITY_NOT_FOUND",
	"S3_BUCKET_NO_PERMISSION",
	"S3_BUCKET_NOT_ACCESSIBLE",
	"S3_BUCKET_NOT_FOUND",
	"S3_BUCKET_INVALID_REGION",
	"S3_INTERNAL_ERROR",
}

var wafregionalParameterExceptionFieldValues = []string{
	"CHANGE_ACTION",
	"WAF_ACTION",
	"WAF_OVERRIDE_ACTION",
	"PREDICATE_TYPE",
	"IPSET_TYPE",
	"BYTE_MATCH_FIELD_TYPE",
	"SQL_INJECTION_MATCH_FIELD_TYPE",
	"BYTE_MATCH_TEXT_TRANSFORMATION",
	"BYTE_MATCH_POSITIONAL_CONSTRAINT",
	"SIZE_CONSTRAINT_COMPARISON_OPERATOR",
	"GEO_MATCH_LOCATION_TYPE",
	"GEO_MATCH_LOCATION_VALUE",
	"RATE_KEY",
	"RULE_TYPE",
	"NEXT_MARKER",
	"RESOURCE_ARN",
	"TAGS",
	"TAG_KEYS",
}

var wafregionalParameterExceptionReasonValues = []string{
	"INVALID_OPTION",
	"ILLEGAL_COMBINATION",
	"ILLEGAL_ARGUMENT",
	"INVALID_TAG_KEY",
}

var wafregionalPositionalConstraintValues = []string{
	"EXACTLY",
	"STARTS_WITH",
	"ENDS_WITH",
	"CONTAINS",
	"CONTAINS_WORD",
}

var wafregionalPredicateTypeValues = []string{
	"IPMatch",
	"ByteMatch",
	"SqlInjectionMatch",
	"GeoMatch",
	"SizeConstraint",
	"XssMatch",
	"RegexMatch",
}

var wafregionalRateKeyValues = []string{
	"IP",
}

var wafregionalResourceTypeValues = []string{
	"APPLICATION_LOAD_BALANCER",
	"API_GATEWAY",
}

var wafregionalTextTransformationValues = []string{
	"NONE",
	"COMPRESS_WHITE_SPACE",
	"HTML_ENTITY_DECODE",
	"LOWERCASE",
	"CMD_LINE",
	"URL_DECODE",
}

var wafregionalWafActionTypeValues = []string{
	"BLOCK",
	"ALLOW",
	"COUNT",
}

var wafregionalWafOverrideActionTypeValues = []string{
	"NONE",
	"COUNT",
}

var wafregionalWafRuleTypeValues = []string{
	"REGULAR",
	"RATE_BASED",
	"GROUP",
}

func getWafRegionalEnum(name string) []string {
	switch name {
	case "ChangeAction":
		return wafregionalChangeActionValues
	case "ChangeTokenStatus":
		return wafregionalChangeTokenStatusValues
	case "ComparisonOperator":
		return wafregionalComparisonOperatorValues
	case "GeoMatchConstraintType":
		return wafregionalGeoMatchConstraintTypeValues
	case "GeoMatchConstraintValue":
		return wafregionalGeoMatchConstraintValueValues
	case "IPSetDescriptorType":
		return wafregionalIPSetDescriptorTypeValues
	case "MatchFieldType":
		return wafregionalMatchFieldTypeValues
	case "MigrationErrorType":
		return wafregionalMigrationErrorTypeValues
	case "ParameterExceptionField":
		return wafregionalParameterExceptionFieldValues
	case "ParameterExceptionReason":
		return wafregionalParameterExceptionReasonValues
	case "PositionalConstraint":
		return wafregionalPositionalConstraintValues
	case "PredicateType":
		return wafregionalPredicateTypeValues
	case "RateKey":
		return wafregionalRateKeyValues
	case "ResourceType":
		return wafregionalResourceTypeValues
	case "TextTransformation":
		return wafregionalTextTransformationValues
	case "WafActionType":
		return wafregionalWafActionTypeValues
	case "WafOverrideActionType":
		return wafregionalWafOverrideActionTypeValues
	case "WafRuleType":
		return wafregionalWafRuleTypeValues
	}
	return nil
}

func getWafRegionalEnumNames() []string {
	return []string{
		"ChangeAction",
		"ChangeTokenStatus",
		"ComparisonOperator",
		"GeoMatchConstraintType",
		"GeoMatchConstraintValue",
		"IPSetDescriptorType",
		"MatchFieldType",
		"MigrationErrorType",
		"ParameterExceptionField",
		"ParameterExceptionReason",
		"PositionalConstraint",
		"PredicateType",
		"RateKey",
		"ResourceType",
		"TextTransformation",
		"WafActionType",
		"WafOverrideActionType",
		"WafRuleType",
	}
}
