// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Waf enum constants
const (
	// ChangeAction values
	WafChangeActionInsert = "INSERT"
	WafChangeActionDelete = "DELETE"

	// ChangeTokenStatus values
	WafChangeTokenStatusProvisioned = "PROVISIONED"
	WafChangeTokenStatusPending     = "PENDING"
	WafChangeTokenStatusInsync      = "INSYNC"

	// ComparisonOperator values
	WafComparisonOperatorEq = "EQ"
	WafComparisonOperatorNe = "NE"
	WafComparisonOperatorLe = "LE"
	WafComparisonOperatorLt = "LT"
	WafComparisonOperatorGe = "GE"
	WafComparisonOperatorGt = "GT"

	// GeoMatchConstraintType values
	WafGeoMatchConstraintTypeCountry = "Country"

	// GeoMatchConstraintValue values
	WafGeoMatchConstraintValueAf = "AF"
	WafGeoMatchConstraintValueAx = "AX"
	WafGeoMatchConstraintValueAl = "AL"
	WafGeoMatchConstraintValueDz = "DZ"
	WafGeoMatchConstraintValueAs = "AS"
	WafGeoMatchConstraintValueAd = "AD"
	WafGeoMatchConstraintValueAo = "AO"
	WafGeoMatchConstraintValueAi = "AI"
	WafGeoMatchConstraintValueAq = "AQ"
	WafGeoMatchConstraintValueAg = "AG"
	WafGeoMatchConstraintValueAr = "AR"
	WafGeoMatchConstraintValueAm = "AM"
	WafGeoMatchConstraintValueAw = "AW"
	WafGeoMatchConstraintValueAu = "AU"
	WafGeoMatchConstraintValueAt = "AT"
	WafGeoMatchConstraintValueAz = "AZ"
	WafGeoMatchConstraintValueBs = "BS"
	WafGeoMatchConstraintValueBh = "BH"
	WafGeoMatchConstraintValueBd = "BD"
	WafGeoMatchConstraintValueBb = "BB"
	WafGeoMatchConstraintValueBy = "BY"
	WafGeoMatchConstraintValueBe = "BE"
	WafGeoMatchConstraintValueBz = "BZ"
	WafGeoMatchConstraintValueBj = "BJ"
	WafGeoMatchConstraintValueBm = "BM"
	WafGeoMatchConstraintValueBt = "BT"
	WafGeoMatchConstraintValueBo = "BO"
	WafGeoMatchConstraintValueBq = "BQ"
	WafGeoMatchConstraintValueBa = "BA"
	WafGeoMatchConstraintValueBw = "BW"
	WafGeoMatchConstraintValueBv = "BV"
	WafGeoMatchConstraintValueBr = "BR"
	WafGeoMatchConstraintValueIo = "IO"
	WafGeoMatchConstraintValueBn = "BN"
	WafGeoMatchConstraintValueBg = "BG"
	WafGeoMatchConstraintValueBf = "BF"
	WafGeoMatchConstraintValueBi = "BI"
	WafGeoMatchConstraintValueKh = "KH"
	WafGeoMatchConstraintValueCm = "CM"
	WafGeoMatchConstraintValueCa = "CA"
	WafGeoMatchConstraintValueCv = "CV"
	WafGeoMatchConstraintValueKy = "KY"
	WafGeoMatchConstraintValueCf = "CF"
	WafGeoMatchConstraintValueTd = "TD"
	WafGeoMatchConstraintValueCl = "CL"
	WafGeoMatchConstraintValueCn = "CN"
	WafGeoMatchConstraintValueCx = "CX"
	WafGeoMatchConstraintValueCc = "CC"
	WafGeoMatchConstraintValueCo = "CO"
	WafGeoMatchConstraintValueKm = "KM"
	WafGeoMatchConstraintValueCg = "CG"
	WafGeoMatchConstraintValueCd = "CD"
	WafGeoMatchConstraintValueCk = "CK"
	WafGeoMatchConstraintValueCr = "CR"
	WafGeoMatchConstraintValueCi = "CI"
	WafGeoMatchConstraintValueHr = "HR"
	WafGeoMatchConstraintValueCu = "CU"
	WafGeoMatchConstraintValueCw = "CW"
	WafGeoMatchConstraintValueCy = "CY"
	WafGeoMatchConstraintValueCz = "CZ"
	WafGeoMatchConstraintValueDk = "DK"
	WafGeoMatchConstraintValueDj = "DJ"
	WafGeoMatchConstraintValueDm = "DM"
	WafGeoMatchConstraintValueDo = "DO"
	WafGeoMatchConstraintValueEc = "EC"
	WafGeoMatchConstraintValueEg = "EG"
	WafGeoMatchConstraintValueSv = "SV"
	WafGeoMatchConstraintValueGq = "GQ"
	WafGeoMatchConstraintValueEr = "ER"
	WafGeoMatchConstraintValueEe = "EE"
	WafGeoMatchConstraintValueEt = "ET"
	WafGeoMatchConstraintValueFk = "FK"
	WafGeoMatchConstraintValueFo = "FO"
	WafGeoMatchConstraintValueFj = "FJ"
	WafGeoMatchConstraintValueFi = "FI"
	WafGeoMatchConstraintValueFr = "FR"
	WafGeoMatchConstraintValueGf = "GF"
	WafGeoMatchConstraintValuePf = "PF"
	WafGeoMatchConstraintValueTf = "TF"
	WafGeoMatchConstraintValueGa = "GA"
	WafGeoMatchConstraintValueGm = "GM"
	WafGeoMatchConstraintValueGe = "GE"
	WafGeoMatchConstraintValueDe = "DE"
	WafGeoMatchConstraintValueGh = "GH"
	WafGeoMatchConstraintValueGi = "GI"
	WafGeoMatchConstraintValueGr = "GR"
	WafGeoMatchConstraintValueGl = "GL"
	WafGeoMatchConstraintValueGd = "GD"
	WafGeoMatchConstraintValueGp = "GP"
	WafGeoMatchConstraintValueGu = "GU"
	WafGeoMatchConstraintValueGt = "GT"
	WafGeoMatchConstraintValueGg = "GG"
	WafGeoMatchConstraintValueGn = "GN"
	WafGeoMatchConstraintValueGw = "GW"
	WafGeoMatchConstraintValueGy = "GY"
	WafGeoMatchConstraintValueHt = "HT"
	WafGeoMatchConstraintValueHm = "HM"
	WafGeoMatchConstraintValueVa = "VA"
	WafGeoMatchConstraintValueHn = "HN"
	WafGeoMatchConstraintValueHk = "HK"
	WafGeoMatchConstraintValueHu = "HU"
	WafGeoMatchConstraintValueIs = "IS"
	WafGeoMatchConstraintValueIn = "IN"
	WafGeoMatchConstraintValueId = "ID"
	WafGeoMatchConstraintValueIr = "IR"
	WafGeoMatchConstraintValueIq = "IQ"
	WafGeoMatchConstraintValueIe = "IE"
	WafGeoMatchConstraintValueIm = "IM"
	WafGeoMatchConstraintValueIl = "IL"
	WafGeoMatchConstraintValueIt = "IT"
	WafGeoMatchConstraintValueJm = "JM"
	WafGeoMatchConstraintValueJp = "JP"
	WafGeoMatchConstraintValueJe = "JE"
	WafGeoMatchConstraintValueJo = "JO"
	WafGeoMatchConstraintValueKz = "KZ"
	WafGeoMatchConstraintValueKe = "KE"
	WafGeoMatchConstraintValueKi = "KI"
	WafGeoMatchConstraintValueKp = "KP"
	WafGeoMatchConstraintValueKr = "KR"
	WafGeoMatchConstraintValueKw = "KW"
	WafGeoMatchConstraintValueKg = "KG"
	WafGeoMatchConstraintValueLa = "LA"
	WafGeoMatchConstraintValueLv = "LV"
	WafGeoMatchConstraintValueLb = "LB"
	WafGeoMatchConstraintValueLs = "LS"
	WafGeoMatchConstraintValueLr = "LR"
	WafGeoMatchConstraintValueLy = "LY"
	WafGeoMatchConstraintValueLi = "LI"
	WafGeoMatchConstraintValueLt = "LT"
	WafGeoMatchConstraintValueLu = "LU"
	WafGeoMatchConstraintValueMo = "MO"
	WafGeoMatchConstraintValueMk = "MK"
	WafGeoMatchConstraintValueMg = "MG"
	WafGeoMatchConstraintValueMw = "MW"
	WafGeoMatchConstraintValueMy = "MY"
	WafGeoMatchConstraintValueMv = "MV"
	WafGeoMatchConstraintValueMl = "ML"
	WafGeoMatchConstraintValueMt = "MT"
	WafGeoMatchConstraintValueMh = "MH"
	WafGeoMatchConstraintValueMq = "MQ"
	WafGeoMatchConstraintValueMr = "MR"
	WafGeoMatchConstraintValueMu = "MU"
	WafGeoMatchConstraintValueYt = "YT"
	WafGeoMatchConstraintValueMx = "MX"
	WafGeoMatchConstraintValueFm = "FM"
	WafGeoMatchConstraintValueMd = "MD"
	WafGeoMatchConstraintValueMc = "MC"
	WafGeoMatchConstraintValueMn = "MN"
	WafGeoMatchConstraintValueMe = "ME"
	WafGeoMatchConstraintValueMs = "MS"
	WafGeoMatchConstraintValueMa = "MA"
	WafGeoMatchConstraintValueMz = "MZ"
	WafGeoMatchConstraintValueMm = "MM"
	WafGeoMatchConstraintValueNa = "NA"
	WafGeoMatchConstraintValueNr = "NR"
	WafGeoMatchConstraintValueNp = "NP"
	WafGeoMatchConstraintValueNl = "NL"
	WafGeoMatchConstraintValueNc = "NC"
	WafGeoMatchConstraintValueNz = "NZ"
	WafGeoMatchConstraintValueNi = "NI"
	WafGeoMatchConstraintValueNe = "NE"
	WafGeoMatchConstraintValueNg = "NG"
	WafGeoMatchConstraintValueNu = "NU"
	WafGeoMatchConstraintValueNf = "NF"
	WafGeoMatchConstraintValueMp = "MP"
	WafGeoMatchConstraintValueNo = "NO"
	WafGeoMatchConstraintValueOm = "OM"
	WafGeoMatchConstraintValuePk = "PK"
	WafGeoMatchConstraintValuePw = "PW"
	WafGeoMatchConstraintValuePs = "PS"
	WafGeoMatchConstraintValuePa = "PA"
	WafGeoMatchConstraintValuePg = "PG"
	WafGeoMatchConstraintValuePy = "PY"
	WafGeoMatchConstraintValuePe = "PE"
	WafGeoMatchConstraintValuePh = "PH"
	WafGeoMatchConstraintValuePn = "PN"
	WafGeoMatchConstraintValuePl = "PL"
	WafGeoMatchConstraintValuePt = "PT"
	WafGeoMatchConstraintValuePr = "PR"
	WafGeoMatchConstraintValueQa = "QA"
	WafGeoMatchConstraintValueRe = "RE"
	WafGeoMatchConstraintValueRo = "RO"
	WafGeoMatchConstraintValueRu = "RU"
	WafGeoMatchConstraintValueRw = "RW"
	WafGeoMatchConstraintValueBl = "BL"
	WafGeoMatchConstraintValueSh = "SH"
	WafGeoMatchConstraintValueKn = "KN"
	WafGeoMatchConstraintValueLc = "LC"
	WafGeoMatchConstraintValueMf = "MF"
	WafGeoMatchConstraintValuePm = "PM"
	WafGeoMatchConstraintValueVc = "VC"
	WafGeoMatchConstraintValueWs = "WS"
	WafGeoMatchConstraintValueSm = "SM"
	WafGeoMatchConstraintValueSt = "ST"
	WafGeoMatchConstraintValueSa = "SA"
	WafGeoMatchConstraintValueSn = "SN"
	WafGeoMatchConstraintValueRs = "RS"
	WafGeoMatchConstraintValueSc = "SC"
	WafGeoMatchConstraintValueSl = "SL"
	WafGeoMatchConstraintValueSg = "SG"
	WafGeoMatchConstraintValueSx = "SX"
	WafGeoMatchConstraintValueSk = "SK"
	WafGeoMatchConstraintValueSi = "SI"
	WafGeoMatchConstraintValueSb = "SB"
	WafGeoMatchConstraintValueSo = "SO"
	WafGeoMatchConstraintValueZa = "ZA"
	WafGeoMatchConstraintValueGs = "GS"
	WafGeoMatchConstraintValueSs = "SS"
	WafGeoMatchConstraintValueEs = "ES"
	WafGeoMatchConstraintValueLk = "LK"
	WafGeoMatchConstraintValueSd = "SD"
	WafGeoMatchConstraintValueSr = "SR"
	WafGeoMatchConstraintValueSj = "SJ"
	WafGeoMatchConstraintValueSz = "SZ"
	WafGeoMatchConstraintValueSe = "SE"
	WafGeoMatchConstraintValueCh = "CH"
	WafGeoMatchConstraintValueSy = "SY"
	WafGeoMatchConstraintValueTw = "TW"
	WafGeoMatchConstraintValueTj = "TJ"
	WafGeoMatchConstraintValueTz = "TZ"
	WafGeoMatchConstraintValueTh = "TH"
	WafGeoMatchConstraintValueTl = "TL"
	WafGeoMatchConstraintValueTg = "TG"
	WafGeoMatchConstraintValueTk = "TK"
	WafGeoMatchConstraintValueTo = "TO"
	WafGeoMatchConstraintValueTt = "TT"
	WafGeoMatchConstraintValueTn = "TN"
	WafGeoMatchConstraintValueTr = "TR"
	WafGeoMatchConstraintValueTm = "TM"
	WafGeoMatchConstraintValueTc = "TC"
	WafGeoMatchConstraintValueTv = "TV"
	WafGeoMatchConstraintValueUg = "UG"
	WafGeoMatchConstraintValueUa = "UA"
	WafGeoMatchConstraintValueAe = "AE"
	WafGeoMatchConstraintValueGb = "GB"
	WafGeoMatchConstraintValueUs = "US"
	WafGeoMatchConstraintValueUm = "UM"
	WafGeoMatchConstraintValueUy = "UY"
	WafGeoMatchConstraintValueUz = "UZ"
	WafGeoMatchConstraintValueVu = "VU"
	WafGeoMatchConstraintValueVe = "VE"
	WafGeoMatchConstraintValueVn = "VN"
	WafGeoMatchConstraintValueVg = "VG"
	WafGeoMatchConstraintValueVi = "VI"
	WafGeoMatchConstraintValueWf = "WF"
	WafGeoMatchConstraintValueEh = "EH"
	WafGeoMatchConstraintValueYe = "YE"
	WafGeoMatchConstraintValueZm = "ZM"
	WafGeoMatchConstraintValueZw = "ZW"

	// IPSetDescriptorType values
	WafIPSetDescriptorTypeIpv4 = "IPV4"
	WafIPSetDescriptorTypeIpv6 = "IPV6"

	// MatchFieldType values
	WafMatchFieldTypeUri            = "URI"
	WafMatchFieldTypeQueryString    = "QUERY_STRING"
	WafMatchFieldTypeHeader         = "HEADER"
	WafMatchFieldTypeMethod         = "METHOD"
	WafMatchFieldTypeBody           = "BODY"
	WafMatchFieldTypeSingleQueryArg = "SINGLE_QUERY_ARG"
	WafMatchFieldTypeAllQueryArgs   = "ALL_QUERY_ARGS"

	// MigrationErrorType values
	WafMigrationErrorTypeEntityNotSupported    = "ENTITY_NOT_SUPPORTED"
	WafMigrationErrorTypeEntityNotFound        = "ENTITY_NOT_FOUND"
	WafMigrationErrorTypeS3BucketNoPermission  = "S3_BUCKET_NO_PERMISSION"
	WafMigrationErrorTypeS3BucketNotAccessible = "S3_BUCKET_NOT_ACCESSIBLE"
	WafMigrationErrorTypeS3BucketNotFound      = "S3_BUCKET_NOT_FOUND"
	WafMigrationErrorTypeS3BucketInvalidRegion = "S3_BUCKET_INVALID_REGION"
	WafMigrationErrorTypeS3InternalError       = "S3_INTERNAL_ERROR"

	// ParameterExceptionField values
	WafParameterExceptionFieldChangeAction                     = "CHANGE_ACTION"
	WafParameterExceptionFieldWafAction                        = "WAF_ACTION"
	WafParameterExceptionFieldWafOverrideAction                = "WAF_OVERRIDE_ACTION"
	WafParameterExceptionFieldPredicateType                    = "PREDICATE_TYPE"
	WafParameterExceptionFieldIpsetType                        = "IPSET_TYPE"
	WafParameterExceptionFieldByteMatchFieldType               = "BYTE_MATCH_FIELD_TYPE"
	WafParameterExceptionFieldSqlInjectionMatchFieldType       = "SQL_INJECTION_MATCH_FIELD_TYPE"
	WafParameterExceptionFieldByteMatchTextTransformation      = "BYTE_MATCH_TEXT_TRANSFORMATION"
	WafParameterExceptionFieldByteMatchPositionalConstraint    = "BYTE_MATCH_POSITIONAL_CONSTRAINT"
	WafParameterExceptionFieldSizeConstraintComparisonOperator = "SIZE_CONSTRAINT_COMPARISON_OPERATOR"
	WafParameterExceptionFieldGeoMatchLocationType             = "GEO_MATCH_LOCATION_TYPE"
	WafParameterExceptionFieldGeoMatchLocationValue            = "GEO_MATCH_LOCATION_VALUE"
	WafParameterExceptionFieldRateKey                          = "RATE_KEY"
	WafParameterExceptionFieldRuleType                         = "RULE_TYPE"
	WafParameterExceptionFieldNextMarker                       = "NEXT_MARKER"
	WafParameterExceptionFieldResourceArn                      = "RESOURCE_ARN"
	WafParameterExceptionFieldTags                             = "TAGS"
	WafParameterExceptionFieldTagKeys                          = "TAG_KEYS"

	// ParameterExceptionReason values
	WafParameterExceptionReasonInvalidOption      = "INVALID_OPTION"
	WafParameterExceptionReasonIllegalCombination = "ILLEGAL_COMBINATION"
	WafParameterExceptionReasonIllegalArgument    = "ILLEGAL_ARGUMENT"
	WafParameterExceptionReasonInvalidTagKey      = "INVALID_TAG_KEY"

	// PositionalConstraint values
	WafPositionalConstraintExactly      = "EXACTLY"
	WafPositionalConstraintStartsWith   = "STARTS_WITH"
	WafPositionalConstraintEndsWith     = "ENDS_WITH"
	WafPositionalConstraintContains     = "CONTAINS"
	WafPositionalConstraintContainsWord = "CONTAINS_WORD"

	// PredicateType values
	WafPredicateTypeIpmatch           = "IPMatch"
	WafPredicateTypeBytematch         = "ByteMatch"
	WafPredicateTypeSqlinjectionmatch = "SqlInjectionMatch"
	WafPredicateTypeGeomatch          = "GeoMatch"
	WafPredicateTypeSizeconstraint    = "SizeConstraint"
	WafPredicateTypeXssmatch          = "XssMatch"
	WafPredicateTypeRegexmatch        = "RegexMatch"

	// RateKey values
	WafRateKeyIp = "IP"

	// TextTransformation values
	WafTextTransformationNone               = "NONE"
	WafTextTransformationCompressWhiteSpace = "COMPRESS_WHITE_SPACE"
	WafTextTransformationHtmlEntityDecode   = "HTML_ENTITY_DECODE"
	WafTextTransformationLowercase          = "LOWERCASE"
	WafTextTransformationCmdLine            = "CMD_LINE"
	WafTextTransformationUrlDecode          = "URL_DECODE"

	// WafActionType values
	WafWafActionTypeBlock = "BLOCK"
	WafWafActionTypeAllow = "ALLOW"
	WafWafActionTypeCount = "COUNT"

	// WafOverrideActionType values
	WafWafOverrideActionTypeNone  = "NONE"
	WafWafOverrideActionTypeCount = "COUNT"

	// WafRuleType values
	WafWafRuleTypeRegular   = "REGULAR"
	WafWafRuleTypeRateBased = "RATE_BASED"
	WafWafRuleTypeGroup     = "GROUP"
)

var wafChangeActionValues = []string{
	"INSERT",
	"DELETE",
}

var wafChangeTokenStatusValues = []string{
	"PROVISIONED",
	"PENDING",
	"INSYNC",
}

var wafComparisonOperatorValues = []string{
	"EQ",
	"NE",
	"LE",
	"LT",
	"GE",
	"GT",
}

var wafGeoMatchConstraintTypeValues = []string{
	"Country",
}

var wafGeoMatchConstraintValueValues = []string{
	"AF",
	"AX",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BQ",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"KH",
	"CM",
	"CA",
	"CV",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CG",
	"CD",
	"CK",
	"CR",
	"CI",
	"HR",
	"CU",
	"CW",
	"CY",
	"CZ",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KP",
	"KR",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MK",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"MP",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RE",
	"RO",
	"RU",
	"RW",
	"BL",
	"SH",
	"KN",
	"LC",
	"MF",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SX",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"SS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SZ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TR",
	"TM",
	"TC",
	"TV",
	"UG",
	"UA",
	"AE",
	"GB",
	"US",
	"UM",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"ZM",
	"ZW",
}

var wafIPSetDescriptorTypeValues = []string{
	"IPV4",
	"IPV6",
}

var wafMatchFieldTypeValues = []string{
	"URI",
	"QUERY_STRING",
	"HEADER",
	"METHOD",
	"BODY",
	"SINGLE_QUERY_ARG",
	"ALL_QUERY_ARGS",
}

var wafMigrationErrorTypeValues = []string{
	"ENTITY_NOT_SUPPORTED",
	"ENTITY_NOT_FOUND",
	"S3_BUCKET_NO_PERMISSION",
	"S3_BUCKET_NOT_ACCESSIBLE",
	"S3_BUCKET_NOT_FOUND",
	"S3_BUCKET_INVALID_REGION",
	"S3_INTERNAL_ERROR",
}

var wafParameterExceptionFieldValues = []string{
	"CHANGE_ACTION",
	"WAF_ACTION",
	"WAF_OVERRIDE_ACTION",
	"PREDICATE_TYPE",
	"IPSET_TYPE",
	"BYTE_MATCH_FIELD_TYPE",
	"SQL_INJECTION_MATCH_FIELD_TYPE",
	"BYTE_MATCH_TEXT_TRANSFORMATION",
	"BYTE_MATCH_POSITIONAL_CONSTRAINT",
	"SIZE_CONSTRAINT_COMPARISON_OPERATOR",
	"GEO_MATCH_LOCATION_TYPE",
	"GEO_MATCH_LOCATION_VALUE",
	"RATE_KEY",
	"RULE_TYPE",
	"NEXT_MARKER",
	"RESOURCE_ARN",
	"TAGS",
	"TAG_KEYS",
}

var wafParameterExceptionReasonValues = []string{
	"INVALID_OPTION",
	"ILLEGAL_COMBINATION",
	"ILLEGAL_ARGUMENT",
	"INVALID_TAG_KEY",
}

var wafPositionalConstraintValues = []string{
	"EXACTLY",
	"STARTS_WITH",
	"ENDS_WITH",
	"CONTAINS",
	"CONTAINS_WORD",
}

var wafPredicateTypeValues = []string{
	"IPMatch",
	"ByteMatch",
	"SqlInjectionMatch",
	"GeoMatch",
	"SizeConstraint",
	"XssMatch",
	"RegexMatch",
}

var wafRateKeyValues = []string{
	"IP",
}

var wafTextTransformationValues = []string{
	"NONE",
	"COMPRESS_WHITE_SPACE",
	"HTML_ENTITY_DECODE",
	"LOWERCASE",
	"CMD_LINE",
	"URL_DECODE",
}

var wafWafActionTypeValues = []string{
	"BLOCK",
	"ALLOW",
	"COUNT",
}

var wafWafOverrideActionTypeValues = []string{
	"NONE",
	"COUNT",
}

var wafWafRuleTypeValues = []string{
	"REGULAR",
	"RATE_BASED",
	"GROUP",
}

func getWafEnum(name string) []string {
	switch name {
	case "ChangeAction":
		return wafChangeActionValues
	case "ChangeTokenStatus":
		return wafChangeTokenStatusValues
	case "ComparisonOperator":
		return wafComparisonOperatorValues
	case "GeoMatchConstraintType":
		return wafGeoMatchConstraintTypeValues
	case "GeoMatchConstraintValue":
		return wafGeoMatchConstraintValueValues
	case "IPSetDescriptorType":
		return wafIPSetDescriptorTypeValues
	case "MatchFieldType":
		return wafMatchFieldTypeValues
	case "MigrationErrorType":
		return wafMigrationErrorTypeValues
	case "ParameterExceptionField":
		return wafParameterExceptionFieldValues
	case "ParameterExceptionReason":
		return wafParameterExceptionReasonValues
	case "PositionalConstraint":
		return wafPositionalConstraintValues
	case "PredicateType":
		return wafPredicateTypeValues
	case "RateKey":
		return wafRateKeyValues
	case "TextTransformation":
		return wafTextTransformationValues
	case "WafActionType":
		return wafWafActionTypeValues
	case "WafOverrideActionType":
		return wafWafOverrideActionTypeValues
	case "WafRuleType":
		return wafWafRuleTypeValues
	}
	return nil
}

func getWafEnumNames() []string {
	return []string{
		"ChangeAction",
		"ChangeTokenStatus",
		"ComparisonOperator",
		"GeoMatchConstraintType",
		"GeoMatchConstraintValue",
		"IPSetDescriptorType",
		"MatchFieldType",
		"MigrationErrorType",
		"ParameterExceptionField",
		"ParameterExceptionReason",
		"PositionalConstraint",
		"PredicateType",
		"RateKey",
		"TextTransformation",
		"WafActionType",
		"WafOverrideActionType",
		"WafRuleType",
	}
}
