// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// Workspaces enum constants
const (
	// AGAModeForDirectoryEnum values
	WorkspacesAGAModeForDirectoryEnumEnabledAuto = "ENABLED_AUTO"
	WorkspacesAGAModeForDirectoryEnumDisabled    = "DISABLED"

	// AGAModeForWorkSpaceEnum values
	WorkspacesAGAModeForWorkSpaceEnumEnabledAuto = "ENABLED_AUTO"
	WorkspacesAGAModeForWorkSpaceEnumDisabled    = "DISABLED"
	WorkspacesAGAModeForWorkSpaceEnumInherited   = "INHERITED"

	// AGAPreferredProtocolForDirectory values
	WorkspacesAGAPreferredProtocolForDirectoryTcp  = "TCP"
	WorkspacesAGAPreferredProtocolForDirectoryNone = "NONE"

	// AGAPreferredProtocolForWorkSpace values
	WorkspacesAGAPreferredProtocolForWorkSpaceTcp       = "TCP"
	WorkspacesAGAPreferredProtocolForWorkSpaceNone      = "NONE"
	WorkspacesAGAPreferredProtocolForWorkSpaceInherited = "INHERITED"

	// AccessEndpointType values
	WorkspacesAccessEndpointTypeStreamingWsp = "STREAMING_WSP"

	// AccessPropertyValue values
	WorkspacesAccessPropertyValueAllow = "ALLOW"
	WorkspacesAccessPropertyValueDeny  = "DENY"

	// AccountLinkStatusEnum values
	WorkspacesAccountLinkStatusEnumLinked                           = "LINKED"
	WorkspacesAccountLinkStatusEnumLinkingFailed                    = "LINKING_FAILED"
	WorkspacesAccountLinkStatusEnumLinkNotFound                     = "LINK_NOT_FOUND"
	WorkspacesAccountLinkStatusEnumPendingAcceptanceByTargetAccount = "PENDING_ACCEPTANCE_BY_TARGET_ACCOUNT"
	WorkspacesAccountLinkStatusEnumRejected                         = "REJECTED"

	// Application values
	WorkspacesApplicationMicrosoftOffice2016 = "Microsoft_Office_2016"
	WorkspacesApplicationMicrosoftOffice2019 = "Microsoft_Office_2019"

	// ApplicationAssociatedResourceType values
	WorkspacesApplicationAssociatedResourceTypeWorkspace = "WORKSPACE"
	WorkspacesApplicationAssociatedResourceTypeBundle    = "BUNDLE"
	WorkspacesApplicationAssociatedResourceTypeImage     = "IMAGE"

	// ApplicationSettingsStatusEnum values
	WorkspacesApplicationSettingsStatusEnumDisabled = "DISABLED"
	WorkspacesApplicationSettingsStatusEnumEnabled  = "ENABLED"

	// AssociationErrorCode values
	WorkspacesAssociationErrorCodeValidationerrorInsufficientdiskspace      = "ValidationError.InsufficientDiskSpace"
	WorkspacesAssociationErrorCodeValidationerrorInsufficientmemory         = "ValidationError.InsufficientMemory"
	WorkspacesAssociationErrorCodeValidationerrorUnsupportedoperatingsystem = "ValidationError.UnsupportedOperatingSystem"
	WorkspacesAssociationErrorCodeDeploymenterrorInternalservererror        = "DeploymentError.InternalServerError"
	WorkspacesAssociationErrorCodeDeploymenterrorWorkspaceunreachable       = "DeploymentError.WorkspaceUnreachable"

	// AssociationState values
	WorkspacesAssociationStatePendingInstall             = "PENDING_INSTALL"
	WorkspacesAssociationStatePendingInstallDeployment   = "PENDING_INSTALL_DEPLOYMENT"
	WorkspacesAssociationStatePendingUninstall           = "PENDING_UNINSTALL"
	WorkspacesAssociationStatePendingUninstallDeployment = "PENDING_UNINSTALL_DEPLOYMENT"
	WorkspacesAssociationStateInstalling                 = "INSTALLING"
	WorkspacesAssociationStateUninstalling               = "UNINSTALLING"
	WorkspacesAssociationStateError                      = "ERROR"
	WorkspacesAssociationStateCompleted                  = "COMPLETED"
	WorkspacesAssociationStateRemoved                    = "REMOVED"

	// AssociationStatus values
	WorkspacesAssociationStatusNotAssociated               = "NOT_ASSOCIATED"
	WorkspacesAssociationStatusAssociatedWithOwnerAccount  = "ASSOCIATED_WITH_OWNER_ACCOUNT"
	WorkspacesAssociationStatusAssociatedWithSharedAccount = "ASSOCIATED_WITH_SHARED_ACCOUNT"
	WorkspacesAssociationStatusPendingAssociation          = "PENDING_ASSOCIATION"
	WorkspacesAssociationStatusPendingDisassociation       = "PENDING_DISASSOCIATION"

	// AuthenticationType values
	WorkspacesAuthenticationTypeSaml = "SAML"

	// BundleAssociatedResourceType values
	WorkspacesBundleAssociatedResourceTypeApplication = "APPLICATION"

	// BundleType values
	WorkspacesBundleTypeRegular = "REGULAR"
	WorkspacesBundleTypeStandby = "STANDBY"

	// CertificateBasedAuthStatusEnum values
	WorkspacesCertificateBasedAuthStatusEnumDisabled = "DISABLED"
	WorkspacesCertificateBasedAuthStatusEnumEnabled  = "ENABLED"

	// ClientDeviceType values
	WorkspacesClientDeviceTypeDevicetypewindows = "DeviceTypeWindows"
	WorkspacesClientDeviceTypeDevicetypeosx     = "DeviceTypeOsx"
	WorkspacesClientDeviceTypeDevicetypeandroid = "DeviceTypeAndroid"
	WorkspacesClientDeviceTypeDevicetypeios     = "DeviceTypeIos"
	WorkspacesClientDeviceTypeDevicetypelinux   = "DeviceTypeLinux"
	WorkspacesClientDeviceTypeDevicetypeweb     = "DeviceTypeWeb"

	// Compute values
	WorkspacesComputeValue                 = "VALUE"
	WorkspacesComputeStandard              = "STANDARD"
	WorkspacesComputePerformance           = "PERFORMANCE"
	WorkspacesComputePower                 = "POWER"
	WorkspacesComputeGraphics              = "GRAPHICS"
	WorkspacesComputePowerpro              = "POWERPRO"
	WorkspacesComputeGeneralpurpose4xlarge = "GENERALPURPOSE_4XLARGE"
	WorkspacesComputeGeneralpurpose8xlarge = "GENERALPURPOSE_8XLARGE"
	WorkspacesComputeGraphicspro           = "GRAPHICSPRO"
	WorkspacesComputeGraphicsG4dn          = "GRAPHICS_G4DN"
	WorkspacesComputeGraphicsproG4dn       = "GRAPHICSPRO_G4DN"

	// ConnectionAliasState values
	WorkspacesConnectionAliasStateCreating = "CREATING"
	WorkspacesConnectionAliasStateCreated  = "CREATED"
	WorkspacesConnectionAliasStateDeleting = "DELETING"

	// ConnectionState values
	WorkspacesConnectionStateConnected    = "CONNECTED"
	WorkspacesConnectionStateDisconnected = "DISCONNECTED"
	WorkspacesConnectionStateUnknown      = "UNKNOWN"

	// CustomImageProtocol values
	WorkspacesCustomImageProtocolPcoip = "PCOIP"
	WorkspacesCustomImageProtocolDcv   = "DCV"
	WorkspacesCustomImageProtocolByop  = "BYOP"

	// CustomWorkspaceImageImportState values
	WorkspacesCustomWorkspaceImageImportStatePending    = "PENDING"
	WorkspacesCustomWorkspaceImageImportStateInProgress = "IN_PROGRESS"
	WorkspacesCustomWorkspaceImageImportStateCompleted  = "COMPLETED"
	WorkspacesCustomWorkspaceImageImportStateError      = "ERROR"

	// DataReplication values
	WorkspacesDataReplicationNoReplication   = "NO_REPLICATION"
	WorkspacesDataReplicationPrimaryAsSource = "PRIMARY_AS_SOURCE"

	// DedicatedTenancyAccountType values
	WorkspacesDedicatedTenancyAccountTypeSourceAccount = "SOURCE_ACCOUNT"
	WorkspacesDedicatedTenancyAccountTypeTargetAccount = "TARGET_ACCOUNT"

	// DedicatedTenancyModificationStateEnum values
	WorkspacesDedicatedTenancyModificationStateEnumPending   = "PENDING"
	WorkspacesDedicatedTenancyModificationStateEnumCompleted = "COMPLETED"
	WorkspacesDedicatedTenancyModificationStateEnumFailed    = "FAILED"

	// DedicatedTenancySupportEnum values
	WorkspacesDedicatedTenancySupportEnumEnabled = "ENABLED"

	// DedicatedTenancySupportResultEnum values
	WorkspacesDedicatedTenancySupportResultEnumEnabled  = "ENABLED"
	WorkspacesDedicatedTenancySupportResultEnumDisabled = "DISABLED"

	// DeletableCertificateBasedAuthProperty values
	WorkspacesDeletableCertificateBasedAuthPropertyCertificateBasedAuthPropertiesCertificateAuthorityArn = "CERTIFICATE_BASED_AUTH_PROPERTIES_CERTIFICATE_AUTHORITY_ARN"

	// DeletableSamlProperty values
	WorkspacesDeletableSamlPropertySamlPropertiesUserAccessUrl           = "SAML_PROPERTIES_USER_ACCESS_URL"
	WorkspacesDeletableSamlPropertySamlPropertiesRelayStateParameterName = "SAML_PROPERTIES_RELAY_STATE_PARAMETER_NAME"

	// DescribeWorkspaceDirectoriesFilterName values
	WorkspacesDescribeWorkspaceDirectoriesFilterNameUserIdentityType = "USER_IDENTITY_TYPE"
	WorkspacesDescribeWorkspaceDirectoriesFilterNameWorkspaceType    = "WORKSPACE_TYPE"

	// DescribeWorkspacesPoolsFilterName values
	WorkspacesDescribeWorkspacesPoolsFilterNamePoolname = "PoolName"

	// DescribeWorkspacesPoolsFilterOperator values
	WorkspacesDescribeWorkspacesPoolsFilterOperatorEquals      = "EQUALS"
	WorkspacesDescribeWorkspacesPoolsFilterOperatorNotequals   = "NOTEQUALS"
	WorkspacesDescribeWorkspacesPoolsFilterOperatorContains    = "CONTAINS"
	WorkspacesDescribeWorkspacesPoolsFilterOperatorNotcontains = "NOTCONTAINS"

	// EndpointEncryptionMode values
	WorkspacesEndpointEncryptionModeStandardTls   = "STANDARD_TLS"
	WorkspacesEndpointEncryptionModeFipsValidated = "FIPS_VALIDATED"

	// ImageAssociatedResourceType values
	WorkspacesImageAssociatedResourceTypeApplication = "APPLICATION"

	// ImageComputeType values
	WorkspacesImageComputeTypeBase         = "BASE"
	WorkspacesImageComputeTypeGraphicsG4dn = "GRAPHICS_G4DN"

	// ImageType values
	WorkspacesImageTypeOwned  = "OWNED"
	WorkspacesImageTypeShared = "SHARED"

	// InternetFallbackProtocol values
	WorkspacesInternetFallbackProtocolPcoip = "PCOIP"

	// LogUploadEnum values
	WorkspacesLogUploadEnumEnabled  = "ENABLED"
	WorkspacesLogUploadEnumDisabled = "DISABLED"

	// ModificationResourceEnum values
	WorkspacesModificationResourceEnumRootVolume  = "ROOT_VOLUME"
	WorkspacesModificationResourceEnumUserVolume  = "USER_VOLUME"
	WorkspacesModificationResourceEnumComputeType = "COMPUTE_TYPE"

	// ModificationStateEnum values
	WorkspacesModificationStateEnumUpdateInitiated  = "UPDATE_INITIATED"
	WorkspacesModificationStateEnumUpdateInProgress = "UPDATE_IN_PROGRESS"

	// OSVersion values
	WorkspacesOSVersionWindows10 = "Windows_10"
	WorkspacesOSVersionWindows11 = "Windows_11"

	// OperatingSystemName values
	WorkspacesOperatingSystemNameAmazonLinux2      = "AMAZON_LINUX_2"
	WorkspacesOperatingSystemNameUbuntu1804        = "UBUNTU_18_04"
	WorkspacesOperatingSystemNameUbuntu2004        = "UBUNTU_20_04"
	WorkspacesOperatingSystemNameUbuntu2204        = "UBUNTU_22_04"
	WorkspacesOperatingSystemNameUnknown           = "UNKNOWN"
	WorkspacesOperatingSystemNameWindows10         = "WINDOWS_10"
	WorkspacesOperatingSystemNameWindows11         = "WINDOWS_11"
	WorkspacesOperatingSystemNameWindows7          = "WINDOWS_7"
	WorkspacesOperatingSystemNameWindowsServer2016 = "WINDOWS_SERVER_2016"
	WorkspacesOperatingSystemNameWindowsServer2019 = "WINDOWS_SERVER_2019"
	WorkspacesOperatingSystemNameWindowsServer2022 = "WINDOWS_SERVER_2022"
	WorkspacesOperatingSystemNameRhel8             = "RHEL_8"
	WorkspacesOperatingSystemNameRocky8            = "ROCKY_8"

	// OperatingSystemType values
	WorkspacesOperatingSystemTypeWindows = "WINDOWS"
	WorkspacesOperatingSystemTypeLinux   = "LINUX"

	// Platform values
	WorkspacesPlatformWindows = "WINDOWS"

	// PoolsRunningMode values
	WorkspacesPoolsRunningModeAutoStop = "AUTO_STOP"
	WorkspacesPoolsRunningModeAlwaysOn = "ALWAYS_ON"

	// Protocol values
	WorkspacesProtocolPcoip = "PCOIP"
	WorkspacesProtocolWsp   = "WSP"

	// ReconnectEnum values
	WorkspacesReconnectEnumEnabled  = "ENABLED"
	WorkspacesReconnectEnumDisabled = "DISABLED"

	// RunningMode values
	WorkspacesRunningModeAutoStop = "AUTO_STOP"
	WorkspacesRunningModeAlwaysOn = "ALWAYS_ON"
	WorkspacesRunningModeManual   = "MANUAL"

	// SamlStatusEnum values
	WorkspacesSamlStatusEnumDisabled                          = "DISABLED"
	WorkspacesSamlStatusEnumEnabled                           = "ENABLED"
	WorkspacesSamlStatusEnumEnabledWithDirectoryLoginFallback = "ENABLED_WITH_DIRECTORY_LOGIN_FALLBACK"

	// SessionConnectionState values
	WorkspacesSessionConnectionStateConnected    = "CONNECTED"
	WorkspacesSessionConnectionStateNotConnected = "NOT_CONNECTED"

	// StandbyWorkspaceRelationshipType values
	WorkspacesStandbyWorkspaceRelationshipTypePrimary = "PRIMARY"
	WorkspacesStandbyWorkspaceRelationshipTypeStandby = "STANDBY"

	// StorageConnectorStatusEnum values
	WorkspacesStorageConnectorStatusEnumEnabled  = "ENABLED"
	WorkspacesStorageConnectorStatusEnumDisabled = "DISABLED"

	// StorageConnectorTypeEnum values
	WorkspacesStorageConnectorTypeEnumHomeFolder = "HOME_FOLDER"

	// StreamingExperiencePreferredProtocolEnum values
	WorkspacesStreamingExperiencePreferredProtocolEnumTcp = "TCP"
	WorkspacesStreamingExperiencePreferredProtocolEnumUdp = "UDP"

	// TargetWorkspaceState values
	WorkspacesTargetWorkspaceStateAvailable        = "AVAILABLE"
	WorkspacesTargetWorkspaceStateAdminMaintenance = "ADMIN_MAINTENANCE"

	// Tenancy values
	WorkspacesTenancyDedicated = "DEDICATED"
	WorkspacesTenancyShared    = "SHARED"

	// UserIdentityType values
	WorkspacesUserIdentityTypeCustomerManaged      = "CUSTOMER_MANAGED"
	WorkspacesUserIdentityTypeAwsDirectoryService  = "AWS_DIRECTORY_SERVICE"
	WorkspacesUserIdentityTypeAwsIamIdentityCenter = "AWS_IAM_IDENTITY_CENTER"

	// UserSettingActionEnum values
	WorkspacesUserSettingActionEnumClipboardCopyFromLocalDevice = "CLIPBOARD_COPY_FROM_LOCAL_DEVICE"
	WorkspacesUserSettingActionEnumClipboardCopyToLocalDevice   = "CLIPBOARD_COPY_TO_LOCAL_DEVICE"
	WorkspacesUserSettingActionEnumPrintingToLocalDevice        = "PRINTING_TO_LOCAL_DEVICE"
	WorkspacesUserSettingActionEnumSmartCard                    = "SMART_CARD"

	// UserSettingPermissionEnum values
	WorkspacesUserSettingPermissionEnumEnabled  = "ENABLED"
	WorkspacesUserSettingPermissionEnumDisabled = "DISABLED"

	// WorkSpaceApplicationLicenseType values
	WorkspacesWorkSpaceApplicationLicenseTypeLicensed   = "LICENSED"
	WorkspacesWorkSpaceApplicationLicenseTypeUnlicensed = "UNLICENSED"

	// WorkSpaceApplicationState values
	WorkspacesWorkSpaceApplicationStatePending       = "PENDING"
	WorkspacesWorkSpaceApplicationStateError         = "ERROR"
	WorkspacesWorkSpaceApplicationStateAvailable     = "AVAILABLE"
	WorkspacesWorkSpaceApplicationStateUninstallOnly = "UNINSTALL_ONLY"

	// WorkSpaceAssociatedResourceType values
	WorkspacesWorkSpaceAssociatedResourceTypeApplication = "APPLICATION"

	// WorkspaceBundleState values
	WorkspacesWorkspaceBundleStateAvailable = "AVAILABLE"
	WorkspacesWorkspaceBundleStatePending   = "PENDING"
	WorkspacesWorkspaceBundleStateError     = "ERROR"

	// WorkspaceDirectoryState values
	WorkspacesWorkspaceDirectoryStateRegistering   = "REGISTERING"
	WorkspacesWorkspaceDirectoryStateRegistered    = "REGISTERED"
	WorkspacesWorkspaceDirectoryStateDeregistering = "DEREGISTERING"
	WorkspacesWorkspaceDirectoryStateDeregistered  = "DEREGISTERED"
	WorkspacesWorkspaceDirectoryStateError         = "ERROR"

	// WorkspaceDirectoryType values
	WorkspacesWorkspaceDirectoryTypeSimpleAd             = "SIMPLE_AD"
	WorkspacesWorkspaceDirectoryTypeAdConnector          = "AD_CONNECTOR"
	WorkspacesWorkspaceDirectoryTypeCustomerManaged      = "CUSTOMER_MANAGED"
	WorkspacesWorkspaceDirectoryTypeAwsIamIdentityCenter = "AWS_IAM_IDENTITY_CENTER"

	// WorkspaceImageErrorDetailCode values
	WorkspacesWorkspaceImageErrorDetailCodeOutdatedpowershellversion              = "OutdatedPowershellVersion"
	WorkspacesWorkspaceImageErrorDetailCodeOfficeinstalled                        = "OfficeInstalled"
	WorkspacesWorkspaceImageErrorDetailCodePcoipagentinstalled                    = "PCoIPAgentInstalled"
	WorkspacesWorkspaceImageErrorDetailCodeWindowsupdatesenabled                  = "WindowsUpdatesEnabled"
	WorkspacesWorkspaceImageErrorDetailCodeAutomountdisabled                      = "AutoMountDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeWorkspacesbyolaccountnotfound          = "WorkspacesBYOLAccountNotFound"
	WorkspacesWorkspaceImageErrorDetailCodeWorkspacesbyolaccountdisabled          = "WorkspacesBYOLAccountDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeDhcpdisabled                           = "DHCPDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeDiskfreespace                          = "DiskFreeSpace"
	WorkspacesWorkspaceImageErrorDetailCodeAdditionaldrivesattached               = "AdditionalDrivesAttached"
	WorkspacesWorkspaceImageErrorDetailCodeOsnotsupported                         = "OSNotSupported"
	WorkspacesWorkspaceImageErrorDetailCodeDomainjoined                           = "DomainJoined"
	WorkspacesWorkspaceImageErrorDetailCodeAzuredomainjoined                      = "AzureDomainJoined"
	WorkspacesWorkspaceImageErrorDetailCodeFirewallenabled                        = "FirewallEnabled"
	WorkspacesWorkspaceImageErrorDetailCodeVmwaretoolsinstalled                   = "VMWareToolsInstalled"
	WorkspacesWorkspaceImageErrorDetailCodeDisksizeexceeded                       = "DiskSizeExceeded"
	WorkspacesWorkspaceImageErrorDetailCodeIncompatiblepartitioning               = "IncompatiblePartitioning"
	WorkspacesWorkspaceImageErrorDetailCodePendingreboot                          = "PendingReboot"
	WorkspacesWorkspaceImageErrorDetailCodeAutologonenabled                       = "AutoLogonEnabled"
	WorkspacesWorkspaceImageErrorDetailCodeRealtimeuniversaldisabled              = "RealTimeUniversalDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeMultiplebootpartition                  = "MultipleBootPartition"
	WorkspacesWorkspaceImageErrorDetailCodeRequires64bitos                        = "Requires64BitOS"
	WorkspacesWorkspaceImageErrorDetailCodeZerorearmcount                         = "ZeroRearmCount"
	WorkspacesWorkspaceImageErrorDetailCodeInplaceupgrade                         = "InPlaceUpgrade"
	WorkspacesWorkspaceImageErrorDetailCodeAntivirusinstalled                     = "AntiVirusInstalled"
	WorkspacesWorkspaceImageErrorDetailCodeUefinotsupported                       = "UEFINotSupported"
	WorkspacesWorkspaceImageErrorDetailCodeUnknownerror                           = "UnknownError"
	WorkspacesWorkspaceImageErrorDetailCodeAppxpackagesinstalled                  = "AppXPackagesInstalled"
	WorkspacesWorkspaceImageErrorDetailCodeReservedstorageinuse                   = "ReservedStorageInUse"
	WorkspacesWorkspaceImageErrorDetailCodeAdditionaldrivespresent                = "AdditionalDrivesPresent"
	WorkspacesWorkspaceImageErrorDetailCodeWindowsupdatesrequired                 = "WindowsUpdatesRequired"
	WorkspacesWorkspaceImageErrorDetailCodeSysprepfilemissing                     = "SysPrepFileMissing"
	WorkspacesWorkspaceImageErrorDetailCodeUserprofilemissing                     = "UserProfileMissing"
	WorkspacesWorkspaceImageErrorDetailCodeInsufficientdiskspace                  = "InsufficientDiskSpace"
	WorkspacesWorkspaceImageErrorDetailCodeEnvironmentvariablespathmissingentries = "EnvironmentVariablesPathMissingEntries"
	WorkspacesWorkspaceImageErrorDetailCodeDomainaccountservicesfound             = "DomainAccountServicesFound"
	WorkspacesWorkspaceImageErrorDetailCodeInvalidip                              = "InvalidIp"
	WorkspacesWorkspaceImageErrorDetailCodeRemotedesktopservicesdisabled          = "RemoteDesktopServicesDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeWindowsmodulesinstallerdisabled        = "WindowsModulesInstallerDisabled"
	WorkspacesWorkspaceImageErrorDetailCodeAmazonssmagentenabled                  = "AmazonSsmAgentEnabled"
	WorkspacesWorkspaceImageErrorDetailCodeUnsupportedsecurityprotocol            = "UnsupportedSecurityProtocol"
	WorkspacesWorkspaceImageErrorDetailCodeMultipleuserprofiles                   = "MultipleUserProfiles"
	WorkspacesWorkspaceImageErrorDetailCodeStagedappxpackage                      = "StagedAppxPackage"
	WorkspacesWorkspaceImageErrorDetailCodeUnsupportedosupgrade                   = "UnsupportedOsUpgrade"
	WorkspacesWorkspaceImageErrorDetailCodeInsufficientrearmcount                 = "InsufficientRearmCount"
	WorkspacesWorkspaceImageErrorDetailCodeProtocolosincompatibility              = "ProtocolOSIncompatibility"
	WorkspacesWorkspaceImageErrorDetailCodeMemoryintegrityincompatibility         = "MemoryIntegrityIncompatibility"
	WorkspacesWorkspaceImageErrorDetailCodeRestricteddriveletterinuse             = "RestrictedDriveLetterInUse"

	// WorkspaceImageIngestionProcess values
	WorkspacesWorkspaceImageIngestionProcessByolRegular          = "BYOL_REGULAR"
	WorkspacesWorkspaceImageIngestionProcessByolGraphics         = "BYOL_GRAPHICS"
	WorkspacesWorkspaceImageIngestionProcessByolGraphicspro      = "BYOL_GRAPHICSPRO"
	WorkspacesWorkspaceImageIngestionProcessByolGraphicsG4dn     = "BYOL_GRAPHICS_G4DN"
	WorkspacesWorkspaceImageIngestionProcessByolRegularWsp       = "BYOL_REGULAR_WSP"
	WorkspacesWorkspaceImageIngestionProcessByolGraphicsG4dnWsp  = "BYOL_GRAPHICS_G4DN_WSP"
	WorkspacesWorkspaceImageIngestionProcessByolRegularByop      = "BYOL_REGULAR_BYOP"
	WorkspacesWorkspaceImageIngestionProcessByolGraphicsG4dnByop = "BYOL_GRAPHICS_G4DN_BYOP"

	// WorkspaceImageRequiredTenancy values
	WorkspacesWorkspaceImageRequiredTenancyDefault   = "DEFAULT"
	WorkspacesWorkspaceImageRequiredTenancyDedicated = "DEDICATED"

	// WorkspaceImageState values
	WorkspacesWorkspaceImageStateAvailable = "AVAILABLE"
	WorkspacesWorkspaceImageStatePending   = "PENDING"
	WorkspacesWorkspaceImageStateError     = "ERROR"

	// WorkspaceState values
	WorkspacesWorkspaceStatePending          = "PENDING"
	WorkspacesWorkspaceStateAvailable        = "AVAILABLE"
	WorkspacesWorkspaceStateImpaired         = "IMPAIRED"
	WorkspacesWorkspaceStateUnhealthy        = "UNHEALTHY"
	WorkspacesWorkspaceStateRebooting        = "REBOOTING"
	WorkspacesWorkspaceStateStarting         = "STARTING"
	WorkspacesWorkspaceStateRebuilding       = "REBUILDING"
	WorkspacesWorkspaceStateRestoring        = "RESTORING"
	WorkspacesWorkspaceStateMaintenance      = "MAINTENANCE"
	WorkspacesWorkspaceStateAdminMaintenance = "ADMIN_MAINTENANCE"
	WorkspacesWorkspaceStateTerminating      = "TERMINATING"
	WorkspacesWorkspaceStateTerminated       = "TERMINATED"
	WorkspacesWorkspaceStateSuspended        = "SUSPENDED"
	WorkspacesWorkspaceStateUpdating         = "UPDATING"
	WorkspacesWorkspaceStateStopping         = "STOPPING"
	WorkspacesWorkspaceStateStopped          = "STOPPED"
	WorkspacesWorkspaceStateError            = "ERROR"

	// WorkspaceType values
	WorkspacesWorkspaceTypePersonal = "PERSONAL"
	WorkspacesWorkspaceTypePools    = "POOLS"

	// WorkspacesPoolErrorCode values
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleIsMissing                           = "IAM_SERVICE_ROLE_IS_MISSING"
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleMissingEniDescribeAction            = "IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION"
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleMissingEniCreateAction              = "IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION"
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleMissingEniDeleteAction              = "IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION"
	WorkspacesWorkspacesPoolErrorCodeNetworkInterfaceLimitExceeded                     = "NETWORK_INTERFACE_LIMIT_EXCEEDED"
	WorkspacesWorkspacesPoolErrorCodeInternalServiceError                              = "INTERNAL_SERVICE_ERROR"
	WorkspacesWorkspacesPoolErrorCodeMachineRoleIsMissing                              = "MACHINE_ROLE_IS_MISSING"
	WorkspacesWorkspacesPoolErrorCodeStsDisabledInRegion                               = "STS_DISABLED_IN_REGION"
	WorkspacesWorkspacesPoolErrorCodeSubnetHasInsufficientIpAddresses                  = "SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES"
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleMissingDescribeSubnetAction         = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION"
	WorkspacesWorkspacesPoolErrorCodeSubnetNotFound                                    = "SUBNET_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeImageNotFound                                     = "IMAGE_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeInvalidSubnetConfiguration                        = "INVALID_SUBNET_CONFIGURATION"
	WorkspacesWorkspacesPoolErrorCodeSecurityGroupsNotFound                            = "SECURITY_GROUPS_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeIgwNotAttached                                    = "IGW_NOT_ATTACHED"
	WorkspacesWorkspacesPoolErrorCodeIamServiceRoleMissingDescribeSecurityGroupsAction = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION"
	WorkspacesWorkspacesPoolErrorCodeWorkspacesPoolStopped                             = "WORKSPACES_POOL_STOPPED"
	WorkspacesWorkspacesPoolErrorCodeWorkspacesPoolInstanceProvisioningFailure         = "WORKSPACES_POOL_INSTANCE_PROVISIONING_FAILURE"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorFileNotFound                       = "DOMAIN_JOIN_ERROR_FILE_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorAccessDenied                       = "DOMAIN_JOIN_ERROR_ACCESS_DENIED"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorLogonFailure                       = "DOMAIN_JOIN_ERROR_LOGON_FAILURE"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorInvalidParameter                   = "DOMAIN_JOIN_ERROR_INVALID_PARAMETER"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorMoreData                           = "DOMAIN_JOIN_ERROR_MORE_DATA"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorNoSuchDomain                       = "DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorNotSupported                       = "DOMAIN_JOIN_ERROR_NOT_SUPPORTED"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinNerrInvalidWorkgroupName                = "DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinNerrWorkstationNotStarted               = "DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorDsMachineAccountQuotaExceeded      = "DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinNerrPasswordExpired                     = "DOMAIN_JOIN_NERR_PASSWORD_EXPIRED"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinInternalServiceError                    = "DOMAIN_JOIN_INTERNAL_SERVICE_ERROR"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretActionPermissionIsMissing    = "DOMAIN_JOIN_ERROR_SECRET_ACTION_PERMISSION_IS_MISSING"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretDecryptionFailure            = "DOMAIN_JOIN_ERROR_SECRET_DECRYPTION_FAILURE"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretStateInvalid                 = "DOMAIN_JOIN_ERROR_SECRET_STATE_INVALID"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretNotFound                     = "DOMAIN_JOIN_ERROR_SECRET_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretValueKeyNotFound             = "DOMAIN_JOIN_ERROR_SECRET_VALUE_KEY_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeDomainJoinErrorSecretInvalid                      = "DOMAIN_JOIN_ERROR_SECRET_INVALID"
	WorkspacesWorkspacesPoolErrorCodeBundleNotFound                                    = "BUNDLE_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeDirectoryNotFound                                 = "DIRECTORY_NOT_FOUND"
	WorkspacesWorkspacesPoolErrorCodeInsufficientPermissionsError                      = "INSUFFICIENT_PERMISSIONS_ERROR"
	WorkspacesWorkspacesPoolErrorCodeDefaultOuIsMissing                                = "DEFAULT_OU_IS_MISSING"

	// WorkspacesPoolState values
	WorkspacesWorkspacesPoolStateCreating = "CREATING"
	WorkspacesWorkspacesPoolStateDeleting = "DELETING"
	WorkspacesWorkspacesPoolStateRunning  = "RUNNING"
	WorkspacesWorkspacesPoolStateStarting = "STARTING"
	WorkspacesWorkspacesPoolStateStopped  = "STOPPED"
	WorkspacesWorkspacesPoolStateStopping = "STOPPING"
	WorkspacesWorkspacesPoolStateUpdating = "UPDATING"
)

var workspacesAGAModeForDirectoryEnumValues = []string{
	"ENABLED_AUTO",
	"DISABLED",
}

var workspacesAGAModeForWorkSpaceEnumValues = []string{
	"ENABLED_AUTO",
	"DISABLED",
	"INHERITED",
}

var workspacesAGAPreferredProtocolForDirectoryValues = []string{
	"TCP",
	"NONE",
}

var workspacesAGAPreferredProtocolForWorkSpaceValues = []string{
	"TCP",
	"NONE",
	"INHERITED",
}

var workspacesAccessEndpointTypeValues = []string{
	"STREAMING_WSP",
}

var workspacesAccessPropertyValueValues = []string{
	"ALLOW",
	"DENY",
}

var workspacesAccountLinkStatusEnumValues = []string{
	"LINKED",
	"LINKING_FAILED",
	"LINK_NOT_FOUND",
	"PENDING_ACCEPTANCE_BY_TARGET_ACCOUNT",
	"REJECTED",
}

var workspacesApplicationValues = []string{
	"Microsoft_Office_2016",
	"Microsoft_Office_2019",
}

var workspacesApplicationAssociatedResourceTypeValues = []string{
	"WORKSPACE",
	"BUNDLE",
	"IMAGE",
}

var workspacesApplicationSettingsStatusEnumValues = []string{
	"DISABLED",
	"ENABLED",
}

var workspacesAssociationErrorCodeValues = []string{
	"ValidationError.InsufficientDiskSpace",
	"ValidationError.InsufficientMemory",
	"ValidationError.UnsupportedOperatingSystem",
	"DeploymentError.InternalServerError",
	"DeploymentError.WorkspaceUnreachable",
}

var workspacesAssociationStateValues = []string{
	"PENDING_INSTALL",
	"PENDING_INSTALL_DEPLOYMENT",
	"PENDING_UNINSTALL",
	"PENDING_UNINSTALL_DEPLOYMENT",
	"INSTALLING",
	"UNINSTALLING",
	"ERROR",
	"COMPLETED",
	"REMOVED",
}

var workspacesAssociationStatusValues = []string{
	"NOT_ASSOCIATED",
	"ASSOCIATED_WITH_OWNER_ACCOUNT",
	"ASSOCIATED_WITH_SHARED_ACCOUNT",
	"PENDING_ASSOCIATION",
	"PENDING_DISASSOCIATION",
}

var workspacesAuthenticationTypeValues = []string{
	"SAML",
}

var workspacesBundleAssociatedResourceTypeValues = []string{
	"APPLICATION",
}

var workspacesBundleTypeValues = []string{
	"REGULAR",
	"STANDBY",
}

var workspacesCertificateBasedAuthStatusEnumValues = []string{
	"DISABLED",
	"ENABLED",
}

var workspacesClientDeviceTypeValues = []string{
	"DeviceTypeWindows",
	"DeviceTypeOsx",
	"DeviceTypeAndroid",
	"DeviceTypeIos",
	"DeviceTypeLinux",
	"DeviceTypeWeb",
}

var workspacesComputeValues = []string{
	"VALUE",
	"STANDARD",
	"PERFORMANCE",
	"POWER",
	"GRAPHICS",
	"POWERPRO",
	"GENERALPURPOSE_4XLARGE",
	"GENERALPURPOSE_8XLARGE",
	"GRAPHICSPRO",
	"GRAPHICS_G4DN",
	"GRAPHICSPRO_G4DN",
}

var workspacesConnectionAliasStateValues = []string{
	"CREATING",
	"CREATED",
	"DELETING",
}

var workspacesConnectionStateValues = []string{
	"CONNECTED",
	"DISCONNECTED",
	"UNKNOWN",
}

var workspacesCustomImageProtocolValues = []string{
	"PCOIP",
	"DCV",
	"BYOP",
}

var workspacesCustomWorkspaceImageImportStateValues = []string{
	"PENDING",
	"IN_PROGRESS",
	"COMPLETED",
	"ERROR",
}

var workspacesDataReplicationValues = []string{
	"NO_REPLICATION",
	"PRIMARY_AS_SOURCE",
}

var workspacesDedicatedTenancyAccountTypeValues = []string{
	"SOURCE_ACCOUNT",
	"TARGET_ACCOUNT",
}

var workspacesDedicatedTenancyModificationStateEnumValues = []string{
	"PENDING",
	"COMPLETED",
	"FAILED",
}

var workspacesDedicatedTenancySupportEnumValues = []string{
	"ENABLED",
}

var workspacesDedicatedTenancySupportResultEnumValues = []string{
	"ENABLED",
	"DISABLED",
}

var workspacesDeletableCertificateBasedAuthPropertyValues = []string{
	"CERTIFICATE_BASED_AUTH_PROPERTIES_CERTIFICATE_AUTHORITY_ARN",
}

var workspacesDeletableSamlPropertyValues = []string{
	"SAML_PROPERTIES_USER_ACCESS_URL",
	"SAML_PROPERTIES_RELAY_STATE_PARAMETER_NAME",
}

var workspacesDescribeWorkspaceDirectoriesFilterNameValues = []string{
	"USER_IDENTITY_TYPE",
	"WORKSPACE_TYPE",
}

var workspacesDescribeWorkspacesPoolsFilterNameValues = []string{
	"PoolName",
}

var workspacesDescribeWorkspacesPoolsFilterOperatorValues = []string{
	"EQUALS",
	"NOTEQUALS",
	"CONTAINS",
	"NOTCONTAINS",
}

var workspacesEndpointEncryptionModeValues = []string{
	"STANDARD_TLS",
	"FIPS_VALIDATED",
}

var workspacesImageAssociatedResourceTypeValues = []string{
	"APPLICATION",
}

var workspacesImageComputeTypeValues = []string{
	"BASE",
	"GRAPHICS_G4DN",
}

var workspacesImageTypeValues = []string{
	"OWNED",
	"SHARED",
}

var workspacesInternetFallbackProtocolValues = []string{
	"PCOIP",
}

var workspacesLogUploadEnumValues = []string{
	"ENABLED",
	"DISABLED",
}

var workspacesModificationResourceEnumValues = []string{
	"ROOT_VOLUME",
	"USER_VOLUME",
	"COMPUTE_TYPE",
}

var workspacesModificationStateEnumValues = []string{
	"UPDATE_INITIATED",
	"UPDATE_IN_PROGRESS",
}

var workspacesOSVersionValues = []string{
	"Windows_10",
	"Windows_11",
}

var workspacesOperatingSystemNameValues = []string{
	"AMAZON_LINUX_2",
	"UBUNTU_18_04",
	"UBUNTU_20_04",
	"UBUNTU_22_04",
	"UNKNOWN",
	"WINDOWS_10",
	"WINDOWS_11",
	"WINDOWS_7",
	"WINDOWS_SERVER_2016",
	"WINDOWS_SERVER_2019",
	"WINDOWS_SERVER_2022",
	"RHEL_8",
	"ROCKY_8",
}

var workspacesOperatingSystemTypeValues = []string{
	"WINDOWS",
	"LINUX",
}

var workspacesPlatformValues = []string{
	"WINDOWS",
}

var workspacesPoolsRunningModeValues = []string{
	"AUTO_STOP",
	"ALWAYS_ON",
}

var workspacesProtocolValues = []string{
	"PCOIP",
	"WSP",
}

var workspacesReconnectEnumValues = []string{
	"ENABLED",
	"DISABLED",
}

var workspacesRunningModeValues = []string{
	"AUTO_STOP",
	"ALWAYS_ON",
	"MANUAL",
}

var workspacesSamlStatusEnumValues = []string{
	"DISABLED",
	"ENABLED",
	"ENABLED_WITH_DIRECTORY_LOGIN_FALLBACK",
}

var workspacesSessionConnectionStateValues = []string{
	"CONNECTED",
	"NOT_CONNECTED",
}

var workspacesStandbyWorkspaceRelationshipTypeValues = []string{
	"PRIMARY",
	"STANDBY",
}

var workspacesStorageConnectorStatusEnumValues = []string{
	"ENABLED",
	"DISABLED",
}

var workspacesStorageConnectorTypeEnumValues = []string{
	"HOME_FOLDER",
}

var workspacesStreamingExperiencePreferredProtocolEnumValues = []string{
	"TCP",
	"UDP",
}

var workspacesTargetWorkspaceStateValues = []string{
	"AVAILABLE",
	"ADMIN_MAINTENANCE",
}

var workspacesTenancyValues = []string{
	"DEDICATED",
	"SHARED",
}

var workspacesUserIdentityTypeValues = []string{
	"CUSTOMER_MANAGED",
	"AWS_DIRECTORY_SERVICE",
	"AWS_IAM_IDENTITY_CENTER",
}

var workspacesUserSettingActionEnumValues = []string{
	"CLIPBOARD_COPY_FROM_LOCAL_DEVICE",
	"CLIPBOARD_COPY_TO_LOCAL_DEVICE",
	"PRINTING_TO_LOCAL_DEVICE",
	"SMART_CARD",
}

var workspacesUserSettingPermissionEnumValues = []string{
	"ENABLED",
	"DISABLED",
}

var workspacesWorkSpaceApplicationLicenseTypeValues = []string{
	"LICENSED",
	"UNLICENSED",
}

var workspacesWorkSpaceApplicationStateValues = []string{
	"PENDING",
	"ERROR",
	"AVAILABLE",
	"UNINSTALL_ONLY",
}

var workspacesWorkSpaceAssociatedResourceTypeValues = []string{
	"APPLICATION",
}

var workspacesWorkspaceBundleStateValues = []string{
	"AVAILABLE",
	"PENDING",
	"ERROR",
}

var workspacesWorkspaceDirectoryStateValues = []string{
	"REGISTERING",
	"REGISTERED",
	"DEREGISTERING",
	"DEREGISTERED",
	"ERROR",
}

var workspacesWorkspaceDirectoryTypeValues = []string{
	"SIMPLE_AD",
	"AD_CONNECTOR",
	"CUSTOMER_MANAGED",
	"AWS_IAM_IDENTITY_CENTER",
}

var workspacesWorkspaceImageErrorDetailCodeValues = []string{
	"OutdatedPowershellVersion",
	"OfficeInstalled",
	"PCoIPAgentInstalled",
	"WindowsUpdatesEnabled",
	"AutoMountDisabled",
	"WorkspacesBYOLAccountNotFound",
	"WorkspacesBYOLAccountDisabled",
	"DHCPDisabled",
	"DiskFreeSpace",
	"AdditionalDrivesAttached",
	"OSNotSupported",
	"DomainJoined",
	"AzureDomainJoined",
	"FirewallEnabled",
	"VMWareToolsInstalled",
	"DiskSizeExceeded",
	"IncompatiblePartitioning",
	"PendingReboot",
	"AutoLogonEnabled",
	"RealTimeUniversalDisabled",
	"MultipleBootPartition",
	"Requires64BitOS",
	"ZeroRearmCount",
	"InPlaceUpgrade",
	"AntiVirusInstalled",
	"UEFINotSupported",
	"UnknownError",
	"AppXPackagesInstalled",
	"ReservedStorageInUse",
	"AdditionalDrivesPresent",
	"WindowsUpdatesRequired",
	"SysPrepFileMissing",
	"UserProfileMissing",
	"InsufficientDiskSpace",
	"EnvironmentVariablesPathMissingEntries",
	"DomainAccountServicesFound",
	"InvalidIp",
	"RemoteDesktopServicesDisabled",
	"WindowsModulesInstallerDisabled",
	"AmazonSsmAgentEnabled",
	"UnsupportedSecurityProtocol",
	"MultipleUserProfiles",
	"StagedAppxPackage",
	"UnsupportedOsUpgrade",
	"InsufficientRearmCount",
	"ProtocolOSIncompatibility",
	"MemoryIntegrityIncompatibility",
	"RestrictedDriveLetterInUse",
}

var workspacesWorkspaceImageIngestionProcessValues = []string{
	"BYOL_REGULAR",
	"BYOL_GRAPHICS",
	"BYOL_GRAPHICSPRO",
	"BYOL_GRAPHICS_G4DN",
	"BYOL_REGULAR_WSP",
	"BYOL_GRAPHICS_G4DN_WSP",
	"BYOL_REGULAR_BYOP",
	"BYOL_GRAPHICS_G4DN_BYOP",
}

var workspacesWorkspaceImageRequiredTenancyValues = []string{
	"DEFAULT",
	"DEDICATED",
}

var workspacesWorkspaceImageStateValues = []string{
	"AVAILABLE",
	"PENDING",
	"ERROR",
}

var workspacesWorkspaceStateValues = []string{
	"PENDING",
	"AVAILABLE",
	"IMPAIRED",
	"UNHEALTHY",
	"REBOOTING",
	"STARTING",
	"REBUILDING",
	"RESTORING",
	"MAINTENANCE",
	"ADMIN_MAINTENANCE",
	"TERMINATING",
	"TERMINATED",
	"SUSPENDED",
	"UPDATING",
	"STOPPING",
	"STOPPED",
	"ERROR",
}

var workspacesWorkspaceTypeValues = []string{
	"PERSONAL",
	"POOLS",
}

var workspacesWorkspacesPoolErrorCodeValues = []string{
	"IAM_SERVICE_ROLE_IS_MISSING",
	"IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION",
	"IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION",
	"IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION",
	"NETWORK_INTERFACE_LIMIT_EXCEEDED",
	"INTERNAL_SERVICE_ERROR",
	"MACHINE_ROLE_IS_MISSING",
	"STS_DISABLED_IN_REGION",
	"SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES",
	"IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION",
	"SUBNET_NOT_FOUND",
	"IMAGE_NOT_FOUND",
	"INVALID_SUBNET_CONFIGURATION",
	"SECURITY_GROUPS_NOT_FOUND",
	"IGW_NOT_ATTACHED",
	"IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION",
	"WORKSPACES_POOL_STOPPED",
	"WORKSPACES_POOL_INSTANCE_PROVISIONING_FAILURE",
	"DOMAIN_JOIN_ERROR_FILE_NOT_FOUND",
	"DOMAIN_JOIN_ERROR_ACCESS_DENIED",
	"DOMAIN_JOIN_ERROR_LOGON_FAILURE",
	"DOMAIN_JOIN_ERROR_INVALID_PARAMETER",
	"DOMAIN_JOIN_ERROR_MORE_DATA",
	"DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN",
	"DOMAIN_JOIN_ERROR_NOT_SUPPORTED",
	"DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME",
	"DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED",
	"DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED",
	"DOMAIN_JOIN_NERR_PASSWORD_EXPIRED",
	"DOMAIN_JOIN_INTERNAL_SERVICE_ERROR",
	"DOMAIN_JOIN_ERROR_SECRET_ACTION_PERMISSION_IS_MISSING",
	"DOMAIN_JOIN_ERROR_SECRET_DECRYPTION_FAILURE",
	"DOMAIN_JOIN_ERROR_SECRET_STATE_INVALID",
	"DOMAIN_JOIN_ERROR_SECRET_NOT_FOUND",
	"DOMAIN_JOIN_ERROR_SECRET_VALUE_KEY_NOT_FOUND",
	"DOMAIN_JOIN_ERROR_SECRET_INVALID",
	"BUNDLE_NOT_FOUND",
	"DIRECTORY_NOT_FOUND",
	"INSUFFICIENT_PERMISSIONS_ERROR",
	"DEFAULT_OU_IS_MISSING",
}

var workspacesWorkspacesPoolStateValues = []string{
	"CREATING",
	"DELETING",
	"RUNNING",
	"STARTING",
	"STOPPED",
	"STOPPING",
	"UPDATING",
}

func getWorkspacesEnum(name string) []string {
	switch name {
	case "AGAModeForDirectoryEnum":
		return workspacesAGAModeForDirectoryEnumValues
	case "AGAModeForWorkSpaceEnum":
		return workspacesAGAModeForWorkSpaceEnumValues
	case "AGAPreferredProtocolForDirectory":
		return workspacesAGAPreferredProtocolForDirectoryValues
	case "AGAPreferredProtocolForWorkSpace":
		return workspacesAGAPreferredProtocolForWorkSpaceValues
	case "AccessEndpointType":
		return workspacesAccessEndpointTypeValues
	case "AccessPropertyValue":
		return workspacesAccessPropertyValueValues
	case "AccountLinkStatusEnum":
		return workspacesAccountLinkStatusEnumValues
	case "Application":
		return workspacesApplicationValues
	case "ApplicationAssociatedResourceType":
		return workspacesApplicationAssociatedResourceTypeValues
	case "ApplicationSettingsStatusEnum":
		return workspacesApplicationSettingsStatusEnumValues
	case "AssociationErrorCode":
		return workspacesAssociationErrorCodeValues
	case "AssociationState":
		return workspacesAssociationStateValues
	case "AssociationStatus":
		return workspacesAssociationStatusValues
	case "AuthenticationType":
		return workspacesAuthenticationTypeValues
	case "BundleAssociatedResourceType":
		return workspacesBundleAssociatedResourceTypeValues
	case "BundleType":
		return workspacesBundleTypeValues
	case "CertificateBasedAuthStatusEnum":
		return workspacesCertificateBasedAuthStatusEnumValues
	case "ClientDeviceType":
		return workspacesClientDeviceTypeValues
	case "Compute":
		return workspacesComputeValues
	case "ConnectionAliasState":
		return workspacesConnectionAliasStateValues
	case "ConnectionState":
		return workspacesConnectionStateValues
	case "CustomImageProtocol":
		return workspacesCustomImageProtocolValues
	case "CustomWorkspaceImageImportState":
		return workspacesCustomWorkspaceImageImportStateValues
	case "DataReplication":
		return workspacesDataReplicationValues
	case "DedicatedTenancyAccountType":
		return workspacesDedicatedTenancyAccountTypeValues
	case "DedicatedTenancyModificationStateEnum":
		return workspacesDedicatedTenancyModificationStateEnumValues
	case "DedicatedTenancySupportEnum":
		return workspacesDedicatedTenancySupportEnumValues
	case "DedicatedTenancySupportResultEnum":
		return workspacesDedicatedTenancySupportResultEnumValues
	case "DeletableCertificateBasedAuthProperty":
		return workspacesDeletableCertificateBasedAuthPropertyValues
	case "DeletableSamlProperty":
		return workspacesDeletableSamlPropertyValues
	case "DescribeWorkspaceDirectoriesFilterName":
		return workspacesDescribeWorkspaceDirectoriesFilterNameValues
	case "DescribeWorkspacesPoolsFilterName":
		return workspacesDescribeWorkspacesPoolsFilterNameValues
	case "DescribeWorkspacesPoolsFilterOperator":
		return workspacesDescribeWorkspacesPoolsFilterOperatorValues
	case "EndpointEncryptionMode":
		return workspacesEndpointEncryptionModeValues
	case "ImageAssociatedResourceType":
		return workspacesImageAssociatedResourceTypeValues
	case "ImageComputeType":
		return workspacesImageComputeTypeValues
	case "ImageType":
		return workspacesImageTypeValues
	case "InternetFallbackProtocol":
		return workspacesInternetFallbackProtocolValues
	case "LogUploadEnum":
		return workspacesLogUploadEnumValues
	case "ModificationResourceEnum":
		return workspacesModificationResourceEnumValues
	case "ModificationStateEnum":
		return workspacesModificationStateEnumValues
	case "OSVersion":
		return workspacesOSVersionValues
	case "OperatingSystemName":
		return workspacesOperatingSystemNameValues
	case "OperatingSystemType":
		return workspacesOperatingSystemTypeValues
	case "Platform":
		return workspacesPlatformValues
	case "PoolsRunningMode":
		return workspacesPoolsRunningModeValues
	case "Protocol":
		return workspacesProtocolValues
	case "ReconnectEnum":
		return workspacesReconnectEnumValues
	case "RunningMode":
		return workspacesRunningModeValues
	case "SamlStatusEnum":
		return workspacesSamlStatusEnumValues
	case "SessionConnectionState":
		return workspacesSessionConnectionStateValues
	case "StandbyWorkspaceRelationshipType":
		return workspacesStandbyWorkspaceRelationshipTypeValues
	case "StorageConnectorStatusEnum":
		return workspacesStorageConnectorStatusEnumValues
	case "StorageConnectorTypeEnum":
		return workspacesStorageConnectorTypeEnumValues
	case "StreamingExperiencePreferredProtocolEnum":
		return workspacesStreamingExperiencePreferredProtocolEnumValues
	case "TargetWorkspaceState":
		return workspacesTargetWorkspaceStateValues
	case "Tenancy":
		return workspacesTenancyValues
	case "UserIdentityType":
		return workspacesUserIdentityTypeValues
	case "UserSettingActionEnum":
		return workspacesUserSettingActionEnumValues
	case "UserSettingPermissionEnum":
		return workspacesUserSettingPermissionEnumValues
	case "WorkSpaceApplicationLicenseType":
		return workspacesWorkSpaceApplicationLicenseTypeValues
	case "WorkSpaceApplicationState":
		return workspacesWorkSpaceApplicationStateValues
	case "WorkSpaceAssociatedResourceType":
		return workspacesWorkSpaceAssociatedResourceTypeValues
	case "WorkspaceBundleState":
		return workspacesWorkspaceBundleStateValues
	case "WorkspaceDirectoryState":
		return workspacesWorkspaceDirectoryStateValues
	case "WorkspaceDirectoryType":
		return workspacesWorkspaceDirectoryTypeValues
	case "WorkspaceImageErrorDetailCode":
		return workspacesWorkspaceImageErrorDetailCodeValues
	case "WorkspaceImageIngestionProcess":
		return workspacesWorkspaceImageIngestionProcessValues
	case "WorkspaceImageRequiredTenancy":
		return workspacesWorkspaceImageRequiredTenancyValues
	case "WorkspaceImageState":
		return workspacesWorkspaceImageStateValues
	case "WorkspaceState":
		return workspacesWorkspaceStateValues
	case "WorkspaceType":
		return workspacesWorkspaceTypeValues
	case "WorkspacesPoolErrorCode":
		return workspacesWorkspacesPoolErrorCodeValues
	case "WorkspacesPoolState":
		return workspacesWorkspacesPoolStateValues
	}
	return nil
}

func getWorkspacesEnumNames() []string {
	return []string{
		"AGAModeForDirectoryEnum",
		"AGAModeForWorkSpaceEnum",
		"AGAPreferredProtocolForDirectory",
		"AGAPreferredProtocolForWorkSpace",
		"AccessEndpointType",
		"AccessPropertyValue",
		"AccountLinkStatusEnum",
		"Application",
		"ApplicationAssociatedResourceType",
		"ApplicationSettingsStatusEnum",
		"AssociationErrorCode",
		"AssociationState",
		"AssociationStatus",
		"AuthenticationType",
		"BundleAssociatedResourceType",
		"BundleType",
		"CertificateBasedAuthStatusEnum",
		"ClientDeviceType",
		"Compute",
		"ConnectionAliasState",
		"ConnectionState",
		"CustomImageProtocol",
		"CustomWorkspaceImageImportState",
		"DataReplication",
		"DedicatedTenancyAccountType",
		"DedicatedTenancyModificationStateEnum",
		"DedicatedTenancySupportEnum",
		"DedicatedTenancySupportResultEnum",
		"DeletableCertificateBasedAuthProperty",
		"DeletableSamlProperty",
		"DescribeWorkspaceDirectoriesFilterName",
		"DescribeWorkspacesPoolsFilterName",
		"DescribeWorkspacesPoolsFilterOperator",
		"EndpointEncryptionMode",
		"ImageAssociatedResourceType",
		"ImageComputeType",
		"ImageType",
		"InternetFallbackProtocol",
		"LogUploadEnum",
		"ModificationResourceEnum",
		"ModificationStateEnum",
		"OSVersion",
		"OperatingSystemName",
		"OperatingSystemType",
		"Platform",
		"PoolsRunningMode",
		"Protocol",
		"ReconnectEnum",
		"RunningMode",
		"SamlStatusEnum",
		"SessionConnectionState",
		"StandbyWorkspaceRelationshipType",
		"StorageConnectorStatusEnum",
		"StorageConnectorTypeEnum",
		"StreamingExperiencePreferredProtocolEnum",
		"TargetWorkspaceState",
		"Tenancy",
		"UserIdentityType",
		"UserSettingActionEnum",
		"UserSettingPermissionEnum",
		"WorkSpaceApplicationLicenseType",
		"WorkSpaceApplicationState",
		"WorkSpaceAssociatedResourceType",
		"WorkspaceBundleState",
		"WorkspaceDirectoryState",
		"WorkspaceDirectoryType",
		"WorkspaceImageErrorDetailCode",
		"WorkspaceImageIngestionProcess",
		"WorkspaceImageRequiredTenancy",
		"WorkspaceImageState",
		"WorkspaceState",
		"WorkspaceType",
		"WorkspacesPoolErrorCode",
		"WorkspacesPoolState",
	}
}
