// Code generated by enumgen from enums.json. DO NOT EDIT.

package enums

// WorkspacesInstances enum constants
const (
	// AmdSevSnpEnum values
	WorkspacesinstancesAmdSevSnpEnumEnabled  = "enabled"
	WorkspacesinstancesAmdSevSnpEnumDisabled = "disabled"

	// AutoRecoveryEnum values
	WorkspacesinstancesAutoRecoveryEnumDisabled = "disabled"
	WorkspacesinstancesAutoRecoveryEnumDefault  = "default"

	// BandwidthWeightingEnum values
	WorkspacesinstancesBandwidthWeightingEnumDefault = "default"
	WorkspacesinstancesBandwidthWeightingEnumVpc1    = "vpc-1"
	WorkspacesinstancesBandwidthWeightingEnumEbs1    = "ebs-1"

	// CapacityReservationPreferenceEnum values
	WorkspacesinstancesCapacityReservationPreferenceEnumCapacityReservationsOnly = "capacity-reservations-only"
	WorkspacesinstancesCapacityReservationPreferenceEnumOpen                     = "open"
	WorkspacesinstancesCapacityReservationPreferenceEnumNone                     = "none"

	// CpuCreditsEnum values
	WorkspacesinstancesCpuCreditsEnumStandard  = "standard"
	WorkspacesinstancesCpuCreditsEnumUnlimited = "unlimited"

	// DisassociateModeEnum values
	WorkspacesinstancesDisassociateModeEnumForce   = "FORCE"
	WorkspacesinstancesDisassociateModeEnumNoForce = "NO_FORCE"

	// HostnameTypeEnum values
	WorkspacesinstancesHostnameTypeEnumIpName       = "ip-name"
	WorkspacesinstancesHostnameTypeEnumResourceName = "resource-name"

	// HttpEndpointEnum values
	WorkspacesinstancesHttpEndpointEnumEnabled  = "enabled"
	WorkspacesinstancesHttpEndpointEnumDisabled = "disabled"

	// HttpProtocolIpv6Enum values
	WorkspacesinstancesHttpProtocolIpv6EnumEnabled  = "enabled"
	WorkspacesinstancesHttpProtocolIpv6EnumDisabled = "disabled"

	// HttpTokensEnum values
	WorkspacesinstancesHttpTokensEnumOptional = "optional"
	WorkspacesinstancesHttpTokensEnumRequired = "required"

	// InstanceInterruptionBehaviorEnum values
	WorkspacesinstancesInstanceInterruptionBehaviorEnumHibernate = "hibernate"
	WorkspacesinstancesInstanceInterruptionBehaviorEnumStop      = "stop"

	// InstanceMetadataTagsEnum values
	WorkspacesinstancesInstanceMetadataTagsEnumEnabled  = "enabled"
	WorkspacesinstancesInstanceMetadataTagsEnumDisabled = "disabled"

	// InterfaceTypeEnum values
	WorkspacesinstancesInterfaceTypeEnumInterface = "interface"
	WorkspacesinstancesInterfaceTypeEnumEfa       = "efa"
	WorkspacesinstancesInterfaceTypeEnumEfaOnly   = "efa-only"

	// MarketTypeEnum values
	WorkspacesinstancesMarketTypeEnumSpot          = "spot"
	WorkspacesinstancesMarketTypeEnumCapacityBlock = "capacity-block"

	// ProvisionStateEnum values
	WorkspacesinstancesProvisionStateEnumAllocating        = "ALLOCATING"
	WorkspacesinstancesProvisionStateEnumAllocated         = "ALLOCATED"
	WorkspacesinstancesProvisionStateEnumDeallocating      = "DEALLOCATING"
	WorkspacesinstancesProvisionStateEnumDeallocated       = "DEALLOCATED"
	WorkspacesinstancesProvisionStateEnumErrorAllocating   = "ERROR_ALLOCATING"
	WorkspacesinstancesProvisionStateEnumErrorDeallocating = "ERROR_DEALLOCATING"

	// ResourceTypeEnum values
	WorkspacesinstancesResourceTypeEnumInstance             = "instance"
	WorkspacesinstancesResourceTypeEnumVolume               = "volume"
	WorkspacesinstancesResourceTypeEnumSpotInstancesRequest = "spot-instances-request"
	WorkspacesinstancesResourceTypeEnumNetworkInterface     = "network-interface"

	// SpotInstanceTypeEnum values
	WorkspacesinstancesSpotInstanceTypeEnumOneTime    = "one-time"
	WorkspacesinstancesSpotInstanceTypeEnumPersistent = "persistent"

	// TenancyEnum values
	WorkspacesinstancesTenancyEnumDefault   = "default"
	WorkspacesinstancesTenancyEnumDedicated = "dedicated"
	WorkspacesinstancesTenancyEnumHost      = "host"

	// ValidationExceptionReason values
	WorkspacesinstancesValidationExceptionReasonUnknownOperation      = "UNKNOWN_OPERATION"
	WorkspacesinstancesValidationExceptionReasonUnsupportedOperation  = "UNSUPPORTED_OPERATION"
	WorkspacesinstancesValidationExceptionReasonCannotParse           = "CANNOT_PARSE"
	WorkspacesinstancesValidationExceptionReasonFieldValidationFailed = "FIELD_VALIDATION_FAILED"
	WorkspacesinstancesValidationExceptionReasonDependencyFailure     = "DEPENDENCY_FAILURE"
	WorkspacesinstancesValidationExceptionReasonOther                 = "OTHER"

	// VolumeTypeEnum values
	WorkspacesinstancesVolumeTypeEnumStandard = "standard"
	WorkspacesinstancesVolumeTypeEnumIo1      = "io1"
	WorkspacesinstancesVolumeTypeEnumIo2      = "io2"
	WorkspacesinstancesVolumeTypeEnumGp2      = "gp2"
	WorkspacesinstancesVolumeTypeEnumSc1      = "sc1"
	WorkspacesinstancesVolumeTypeEnumSt1      = "st1"
	WorkspacesinstancesVolumeTypeEnumGp3      = "gp3"
)

var workspacesinstancesAmdSevSnpEnumValues = []string{
	"enabled",
	"disabled",
}

var workspacesinstancesAutoRecoveryEnumValues = []string{
	"disabled",
	"default",
}

var workspacesinstancesBandwidthWeightingEnumValues = []string{
	"default",
	"vpc-1",
	"ebs-1",
}

var workspacesinstancesCapacityReservationPreferenceEnumValues = []string{
	"capacity-reservations-only",
	"open",
	"none",
}

var workspacesinstancesCpuCreditsEnumValues = []string{
	"standard",
	"unlimited",
}

var workspacesinstancesDisassociateModeEnumValues = []string{
	"FORCE",
	"NO_FORCE",
}

var workspacesinstancesHostnameTypeEnumValues = []string{
	"ip-name",
	"resource-name",
}

var workspacesinstancesHttpEndpointEnumValues = []string{
	"enabled",
	"disabled",
}

var workspacesinstancesHttpProtocolIpv6EnumValues = []string{
	"enabled",
	"disabled",
}

var workspacesinstancesHttpTokensEnumValues = []string{
	"optional",
	"required",
}

var workspacesinstancesInstanceInterruptionBehaviorEnumValues = []string{
	"hibernate",
	"stop",
}

var workspacesinstancesInstanceMetadataTagsEnumValues = []string{
	"enabled",
	"disabled",
}

var workspacesinstancesInterfaceTypeEnumValues = []string{
	"interface",
	"efa",
	"efa-only",
}

var workspacesinstancesMarketTypeEnumValues = []string{
	"spot",
	"capacity-block",
}

var workspacesinstancesProvisionStateEnumValues = []string{
	"ALLOCATING",
	"ALLOCATED",
	"DEALLOCATING",
	"DEALLOCATED",
	"ERROR_ALLOCATING",
	"ERROR_DEALLOCATING",
}

var workspacesinstancesResourceTypeEnumValues = []string{
	"instance",
	"volume",
	"spot-instances-request",
	"network-interface",
}

var workspacesinstancesSpotInstanceTypeEnumValues = []string{
	"one-time",
	"persistent",
}

var workspacesinstancesTenancyEnumValues = []string{
	"default",
	"dedicated",
	"host",
}

var workspacesinstancesValidationExceptionReasonValues = []string{
	"UNKNOWN_OPERATION",
	"UNSUPPORTED_OPERATION",
	"CANNOT_PARSE",
	"FIELD_VALIDATION_FAILED",
	"DEPENDENCY_FAILURE",
	"OTHER",
}

var workspacesinstancesVolumeTypeEnumValues = []string{
	"standard",
	"io1",
	"io2",
	"gp2",
	"sc1",
	"st1",
	"gp3",
}

func getWorkspacesInstancesEnum(name string) []string {
	switch name {
	case "AmdSevSnpEnum":
		return workspacesinstancesAmdSevSnpEnumValues
	case "AutoRecoveryEnum":
		return workspacesinstancesAutoRecoveryEnumValues
	case "BandwidthWeightingEnum":
		return workspacesinstancesBandwidthWeightingEnumValues
	case "CapacityReservationPreferenceEnum":
		return workspacesinstancesCapacityReservationPreferenceEnumValues
	case "CpuCreditsEnum":
		return workspacesinstancesCpuCreditsEnumValues
	case "DisassociateModeEnum":
		return workspacesinstancesDisassociateModeEnumValues
	case "HostnameTypeEnum":
		return workspacesinstancesHostnameTypeEnumValues
	case "HttpEndpointEnum":
		return workspacesinstancesHttpEndpointEnumValues
	case "HttpProtocolIpv6Enum":
		return workspacesinstancesHttpProtocolIpv6EnumValues
	case "HttpTokensEnum":
		return workspacesinstancesHttpTokensEnumValues
	case "InstanceInterruptionBehaviorEnum":
		return workspacesinstancesInstanceInterruptionBehaviorEnumValues
	case "InstanceMetadataTagsEnum":
		return workspacesinstancesInstanceMetadataTagsEnumValues
	case "InterfaceTypeEnum":
		return workspacesinstancesInterfaceTypeEnumValues
	case "MarketTypeEnum":
		return workspacesinstancesMarketTypeEnumValues
	case "ProvisionStateEnum":
		return workspacesinstancesProvisionStateEnumValues
	case "ResourceTypeEnum":
		return workspacesinstancesResourceTypeEnumValues
	case "SpotInstanceTypeEnum":
		return workspacesinstancesSpotInstanceTypeEnumValues
	case "TenancyEnum":
		return workspacesinstancesTenancyEnumValues
	case "ValidationExceptionReason":
		return workspacesinstancesValidationExceptionReasonValues
	case "VolumeTypeEnum":
		return workspacesinstancesVolumeTypeEnumValues
	}
	return nil
}

func getWorkspacesInstancesEnumNames() []string {
	return []string{
		"AmdSevSnpEnum",
		"AutoRecoveryEnum",
		"BandwidthWeightingEnum",
		"CapacityReservationPreferenceEnum",
		"CpuCreditsEnum",
		"DisassociateModeEnum",
		"HostnameTypeEnum",
		"HttpEndpointEnum",
		"HttpProtocolIpv6Enum",
		"HttpTokensEnum",
		"InstanceInterruptionBehaviorEnum",
		"InstanceMetadataTagsEnum",
		"InterfaceTypeEnum",
		"MarketTypeEnum",
		"ProvisionStateEnum",
		"ResourceTypeEnum",
		"SpotInstanceTypeEnum",
		"TenancyEnum",
		"ValidationExceptionReason",
		"VolumeTypeEnum",
	}
}
