run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/lex00/cloudformation-schema-go

issues:
  exclude-rules:
    # Ignore generated files
    - path: "enums/.*\\.go"
      linters:
        - goimports
        - gofmt
      text: "Code generated"
